### PR TITLE
Set the Home directory during image build process

### LINKED ISSUE #3092: home (defined by ~/) during build results in error
## Version of Singularity:

3.1.0-rc2

### Expected behavior

Build a recipe with references to home (~/) and it goes to /root

### Actual behavior

Here is an example command that fails, no matter how you try to interact with ~/ (list, echo) it reports no such file or directory. It should be /root.

```bash
+ wget https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh -O ~/anaconda.sh
~/anaconda.sh: No such file or directory
FATAL:   post proc: exit status 1
FATAL:   While performing build: while running engine: exit status 255
```

Here is a mini version to reproduce:

```bash
Bootstrap: docker
From: alpine:latest

%post
    apk update && apk add wget
    echo $HOME
    echo $SHELL
    ls ~/
    wget https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh -O ~/anaconda.sh
    ls $HOME
```

I tried both kinds of shells (sh and bash) and this isn't the issue. I also tried (locally) setting different bash options:

```bash

set -e
set -o pipefail

ls $HOME
echo ~/
```
but those worked fine on my local machine! The issue is here https://github.com/mkijowski/container-education/issues/2 and notably, the user has a bunch of recipes that built fine on previous versions of Singularity that now fail, and he was considering rewriting all the files.

### Steps to reproduce behavior

Build the recipe above.

### PR DESCRIPTION
**Pull request by schebro**
**Description of the Pull Request (PR):**

Set the Home directory during image build process

**This fixes or addresses the following GitHub issues:**

- Fixes #3092 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/util/env/clean.go [hunk 1]
```diff
@@ -67,6 +68,17 @@ func SetContainerEnv(g *generate.Generator, env []string, cleanEnv bool, homeDes
 		}
 	}
 
+	if homeDest == "" {
```
Comment (ikaneshiro) [inline internal/pkg/util/env/clean.go]: Lets move this logic for determining `homeDest` to `internal/pkg/runtime/engines/imgbuild/process_linux.go` and feed it to this function. I think its best to not change the default behavior of setting `HOME` for this function since this is used throughout the code base.

File: internal/pkg/util/env/clean.go [hunk 2]
```diff
@@ -67,6 +68,17 @@ func SetContainerEnv(g *generate.Generator, env []string, cleanEnv bool, homeDes
...
+		// Image buid typically runs as root
```
Comment (ikaneshiro) [inline internal/pkg/util/env/clean.go]: typo here, may want to change the comment when this code is moved to a slightly different context

**Review by ikaneshiro — CHANGES_REQUESTED** [review]

**Review by ikaneshiro — APPROVED** [review]
LGTM

**Comment by vsoch** [comment]
Just pulled and testing - is there a new install dependency? (it didn't fire any warnings or errors)

```bash
$ sudo singularity build container.sif Singularity 
FATAL:   Unable to create build: unable to get conveyorpacker: no bootstrap specification found
```

**Comment by ikaneshiro** [comment]
What is your definition? looks like its not parsing the header properly

**Comment by schebro** [comment]
I tested with the same recipe listed in the issue.


Bootstrap: docker
From: alpine:latest

%post
    apk update && apk add wget
    echo $HOME
    echo $SHELL
    ls ~/
    wget https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh -O ~/anaconda.sh
    ls $HOME
~                                                                                                                                          
~            


Here is my output

vagrant@vagrant:~/sif$ sudo singularity  build test.sif test.recipe 
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:bdf0201b3a056acc4d6062cc88cd8a4ad5979983bfb640f15a145e09ed985f92
 2.63 MiB / 2.63 MiB [======================================================] 0s
Copying config sha256:0ec95f35c5f9ac6f33614b60b7dc714d7b737e537858ab6a4935c8066c32a904
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
+ apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
v3.9.3-32-g137dfb961b [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.3-32-g137dfb961b [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 9755 distinct packages available
+ apk add wget
(1/1) Installing wget (1.20.3-r0)
Executing busybox-1.29.3-r10.trigger
OK: 6 MiB in 15 packages
+ echo /root
/root
+ echo

+ ls /root/
+ wget https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh -O /root/anaconda.sh
--2019-04-23 13:47:49--  https://repo.anaconda.com/archive/Anaconda2-2018.12-Linux-x86_64.sh
Resolving repo.anaconda.com... 2606:4700::6810:8203, 2606:4700::6810:8303, 104.16.131.3, ...
Connecting to repo.anaconda.com|2606:4700::6810:8203|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 658699654 (628M) [application/x-sh]
Saving to: '/root/anaconda.sh'

/root/anaconda.sh                  100%[===============================================================>] 628.18M  12.2MB/s    in 54s     

2019-04-23 13:48:43 (11.6 MB/s) - '/root/anaconda.sh' saved [658699654/658699654]

+ ls /root
anaconda.sh
INFO:    Creating SIF file...
INFO:    Build complete: test.sif

**Comment by vsoch** [comment]
“It works for me” is not a resolution to the issue.

**Comment by schebro** [comment]
Agreed.

Checking to see what the failure case is so that I can see why.

-Satish

**Comment by vsoch** [comment]
The recipe is one used in the original issue:

```
From: busybox
Bootstrap: docker
%post
echo $HOME && ls ~/
```

**Comment by vsoch** [comment]
https://github.com/sylabs/singularity/blob/master/internal/pkg/build/build.go#L116

Let me know what you'd like me to test.

**Comment by schebro** [comment]
Thanks. I am running into same issue with this recipe.

Will investigate why.

-Satish

**Comment by ikaneshiro** [comment]
@vsoch this will work if you flip around the header to have `Bootstrap:` first, with the changes for multistage in 3.2 `Bootstrap` now needs to be the first parameter of the header

**Comment by vsoch** [comment]
Oh geez, won't that break a lot of people's recipes?

**Comment by vsoch** [comment]
Okay, can confirm works with flipping the header.

Should this be better discussed with the community? It's a change that breaks a lot of things.

**Comment by ikaneshiro** [comment]
I wouldn't anticipate it breaking many given all documentation I've found related to recipes and examples from others I've seen indicate to me that formats that don't start with `Bootstrap` aren't common, I could be wrong though. This is definitely something that will be mentioned in the userdocs for 3.2 but those are still a work in progress given all the new features coming in. I'm happy to open this up to further discussion in another issue

**Comment by vsoch** [comment]
I can't speak for others, but I use them fairly interchangeably. I would just be ready for the issue to pop up for some number of users that might do this.
