### PR TITLE
Key export command

### LINKED ISSUE #2866: PGP Key Export Command
Splitting #2516 into two issues as #2781 is only handling PGP Import functionality. Quoting from #2516:

Currently, the only way to get a public/private PGP key pair in Singularity is to use the `singularity keys newpair` command. While this works, it has some pretty major limitations:

* It doesn't allow folks to use their pre-existing PGP keys.
* It doesn't allow folks to move their PGP keys to another system.

_Technically_, this can be achieved with some hacking around with the `~/.singularity/sypgp/pgp-public` file. But this is terribly unfriendly.

I propose we create a couple of new commands:

* ~`singularity keys import` to import a key pair into Singularity~
* `singularity keys export` to export a key pair from Singularity

### LINKED ISSUE #3252: 'key export --secret' Should Export a Encrypted Key
## Version of Singularity:

```
3.1.1-683.ga2b07deb6.dirty
```

### Expected behavior

When exporting a secret key, that key should be encrypted. So the next time someone imports that key, they will need a password.

```bash
# Importing a secret key that was exported by singularity:
$ singularity key import ./bar 
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
Enter the old password for this key: **the_old_password**
Enter a new password for this key : **the_new_password**
Retype your passphrase : **the_new_password**
Key with fingerprint 454391CB130DD92BF01FBE8D5393E28237807646 succesfully added to the keyring
```

*Notice its asking for your old password. This is what you expect when you import an exported private key for gpg.*

<br>

### Actual behavior

```bash
$ singularity key import ./bar 
WARNING: sylabs-token files are deprecated. Use 'singularity remote' to manage remote endpoints and tokens.
Enter a new password for this key : 
Retype your passphrase : 
Key with fingerprint 454391CB130DD92BF01FBE8D5393E28237807646 succesfully added to the keyring
```

*Notice its not asking for your old password.*

<br>

### Steps to reproduce behavior

Look ⬆️⬆️⬆️

### LINKED ISSUE #3253: 'key import/export' Should use binary keys by Default
## Version of Singularity:

```
3.1.1-683.ga2b07deb6.dirty
```

<br>

### Expected behavior

```bash
$ singularity key export -s ./exported-key
[...]
Private key with fingerprint 454391CB130DD92BF01FBE8D5393E28237807646 correctly exported to file: ./exported-key

$ file exported-key
exported-key: PGP\011Secret Key - 3072b created on Fri Apr  5 12:10:25 2019 - RSA (Encrypt or Sign) e=65537 hashed AES with 128-bit key Salted&Iterated S2K SHA-1
```
<br>

### Actual behavior

```bash
$ singularity key export -s ./exported-key
[...]
Private key with fingerprint 454391CB130DD92BF01FBE8D5393E28237807646 correctly exported to file: ./exported-key

$ file exported-key
exported-key: ASCII text
```

<br>

### Steps to reproduce behavior

:eyes:  :up:

### PR DESCRIPTION
**Pull request by jchavezlavalle**
**Description of the Pull Request (PR):**

Exporting a key either public or private from the local keystore. 

**This fixes or addresses the following GitHub issues:**

- Fixes #2866 
- Fixes #3252 
- Fixes #3253 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/key_export.go [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+	var fetchPath string
+	var keyString string
+
+	if secretExport {
+		fetchPath = sypgp.SecretPath()
+	} else {
+		fetchPath = sypgp.PublicPath()
+	}
+
+	f, err := os.OpenFile(fetchPath, os.O_RDONLY|os.O_CREATE, 0600)
```
Comment (mem) [inline cmd/internal/cli/key_export.go]: why do you need os.O_CREATE here?

File: cmd/internal/cli/key_export.go [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+		defer file.Close()
+		fmt.Printf("Public key with fingerprint %s correctly exported to file: %s\n", fingerprint, path)
+	}
+
+	return nil
+}
+
+func exportRun(cmd *cobra.Command, args []string) {
+
+	if err := doKeyExportCmd(secretExport, args[0], args[1]); err != nil {
```
Comment (mem) [inline cmd/internal/cli/key_export.go]: if you pass an io.Writer instead of args[1] here, you can open the file for creation here, and handle the closing. If you don't want to create the file in case of failure, you can still pass an io.Writer (in the form of a bytes.Buffer) that you can later io.Copy into the destination file.

The advantage of this is that you can test the function by passing a bytes.Buffer and comparing the result with the expected result.

File: cmd/internal/cli/key_export.go [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+	DisableFlagsInUseLine: true,
+	PreRun:                sylabsToken,
+	Run:                   exportRun,
+	Use:                   docs.KeyExportUse,
+	Short:                 docs.KeyExportShort,
+	Long:                  docs.KeyExportLong,
+	Example:               docs.KeyExportExample,
+}
+
+func doKeyExportCmd(secretExport bool, fingerprint string, path string) error {
```
Comment (mem) [inline cmd/internal/cli/key_export.go]: I think `path string` should be `w io.Writer` instead, please see below.

File: cmd/internal/cli/key_export.go [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+
+			fmt.Printf("%0X\n", localEntity.PrivateKey.PublicKey.Fingerprint)
+			if fmt.Sprintf("%X", localEntity.PrivateKey.PublicKey.Fingerprint) == fingerprint {
+				foundKey = true
+				entityToSave = localEntity
+				break
+			}
+
+		}
+
```
Comment (mem) [inline cmd/internal/cli/key_export.go]: I'm guessing somewhere around here you should have a `if !foundKey` to abort if the key is not found.

Up to this point, I would expect the logic to be still shared with the public key path.

File: cmd/internal/cli/key_export.go [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+		pass, err := sypgp.AskQuestionNoEcho("Enter key passphrase: ")
+		if err != nil {
+			return err
+		}
+
+		fmt.Println(entityToSave.PrivateKey)
+		if entityToSave.PrivateKey != nil && entityToSave.PrivateKey.Encrypted {
+			err := entityToSave.PrivateKey.Decrypt([]byte(pass))
```
Comment (mem) [inline cmd/internal/cli/key_export.go]: I'm not 100% sure, but I'm guessing you could postpone asking for the passphrase until this point.

Also, if you use the public keyring, is PrivateKey populated here? I'm trying to figure out if the code path can be shared or not. Could you turn the question of whether you are accessing the public or private keyring into a question of whether the key you retrieved is encrypted or not?

File: docs/content.go [hunk 6]
```diff
@@ -230,6 +230,31 @@ Enterprise Performance Computing (EPC)`
 	KeyImportExample string = `
   $ singularity key import $HOME/key.asc
   $ singularity keys import $HOME/key.asc
+  `
+
+	// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+	// key export
+	// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+	KeyExportUse   string = `export [export options...] <key-fingerprint> <full-path-to-key-file>`
```
Comment (mem) [inline docs/content.go]: the last argument should be described as "output file" to make it clear that this is the file that will be written.

File: docs/content.go [hunk 7]
```diff
@@ -230,6 +230,31 @@ Enterprise Performance Computing (EPC)`
...
+	KeyExportShort string = `Export a public or private key into a specific folder location`
+	KeyExportLong  string = `
+  The 'key export' command allows you to export a key (either private or public) and save it on a local folder`
+	KeyExportExample string = `
+  Exporting a private key:
+  
+  $ singularity key export --secret <fingerprint_id> <file_folder_path>
```
Comment (mem) [inline docs/content.go]: same here

File: docs/content.go [hunk 8]
```diff
@@ -230,6 +230,31 @@ Enterprise Performance Computing (EPC)`
...
+
+  For example:
+
+  $ singularity key export --secret 9B19CCFCA7B8DDE324E03753D144FCB921E59147 $HOME/mysecretkey.asc
+  
+  Exporting a public key:
+  
+  $ singularity key export <fingerprint_id> <file_folder_path>
```
Comment (mem) [inline docs/content.go]: same here

**Review by mem — CHANGES_REQUESTED** [review]

**Review by ikaneshiro — APPROVED** [review]
LGTM

**Review by mem — APPROVED** [review]
