### PR TITLE
Check SIF squashfs/ext3 partitions at load time

### LINKED ISSUE #3996: singularity inspect returns "FATAL:   exit status 255: "
## Version of Singularity:

singularity version 3.2.1-1.el7a

### Expected behavior

Output of container metadata or meaningfull error message

### Actual behavior

Singularity prints `FATAL:   exit status 255: `, nothing more

### Steps to reproduce behavior

Run `singularity inspect <myimage.sif>` on a container.

Happens only for some containers build by users on our HPC cluster. On the same image I get `FATAL:   container creation failed: mount /proc/self/fd/12->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/12: failed to mount squashfs filesystem: invalid argument` so it might be a faulty image. But the non-existing inspect output makes it impossible to help them

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Actually SIF squashfs/ext3 partitions are not checked, this PR add checks for both squashfs/ext3 system/data partitions

**This fixes or addresses the following GitHub issues:**

- Related to #3996 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: pkg/image/sif.go [hunk 1]
```diff
@@ -130,8 +143,20 @@ func (f *sifFormat) initializer(img *Image, fileinfo os.FileInfo) error {
 			switch fstype {
```
Comment (Flamefire) [inline pkg/image/sif.go]: Can't this code be merged with the above? Some function returning the FS type or an error?

Comment (cclerget) [reply pkg/image/sif.go]: Yes it could, just for now does it work as expected for you ?

Comment (Flamefire) [reply pkg/image/sif.go]: No. I still get the same indeterminate error on inspect and mount failure on shell/run/exec

Comment (cclerget) [reply pkg/image/sif.go]: Well it's weird that the cluster kernel doesn't support the default compression which is gzip, when image is compressed with another compression algorithm you get an info message like `squashfs image was compressed with <comp>, if it failed to run, please contact image's author`.

I think squashfs filesystem is supported by your kernel (just in case check with `grep squashfs /proc/filesystems`), otherwise you should get a `no such device` error if it was the case.

From `mount` man, the only corresponding error for this issue is `EINVAL source had an invalid superblock`

File: pkg/image/sif.go [hunk 2]
```diff
@@ -127,14 +152,16 @@ func (f *sifFormat) initializer(img *Image, fileinfo os.FileInfo) error {
...
-			case sif.FsExt3:
-				partition.Type = EXT3
-			default:
-				partition.Type = uint32(fstype)
+
+			htype, err := checkPartitionType(img, fstype, desc.Fileoff)
+			if err != nil && err != ErrUnknownFsType {
+				return fmt.Errorf("while checking data partition header: %s", err)
+			} else if err == ErrUnknownFsType {
+				img.Partitions[0].Type = uint32(fstype)
```
Comment (Flamefire) [inline pkg/image/sif.go]: I know this was here before but it strikes me as sketchy. Doesn't this assume the constants of https://github.com/sylabs/singularity/blob/c5e243fc45fc5b55f315f7e39255cb95201d4f17/pkg/image/image.go#L21 and https://github.com/sylabs/sif/blob/640d2f2a0ef5219f0066d277e465b6c18a046fc8/pkg/sif/sif.go#L147 are kept in sync? Is this ensured at another place?

Comment (cclerget) [reply pkg/image/sif.go]: We can't really sync those constants with the SIF ones because the image code is generic and must handle different format like sandbox, ext3 only, squashfs only, SIF (which can contain ext3/squashfs image), so it doesn't hurt to have different values there.

Comment (Flamefire) [reply pkg/image/sif.go]: But this code basically says: We have an unknown file system type, just assume that the incoming type id (type is `Fstype` from SIF package) is a valid Type here (like `SQUASHFS`) even though we may not even know it.

This works for e.g. `fstype==FsEncryptedSquashfs` because it happens to hold `uint32(FsEncryptedSquashfs) == ENCRYPTSQUASHFS`, but what if the enums(?) go out of sync?

Comment (cclerget) [reply pkg/image/sif.go]: I initially thought to keep the entry for a possible use by the caller as it's a public package but as it's only for overlay partition, we could probably just ignore those unknow fstype entries to avoid confusion, thoughts ?

Comment (Flamefire) [reply pkg/image/sif.go]: Not sure if I understand correctly but IMO an unknown fs type is an error and should be reported as such. So I'd remove lines 159&160 and the check for `err != ErrUnknownFsType ` from 157

File: pkg/image/sif.go [hunk 3]
```diff
@@ -82,24 +107,26 @@ func (f *sifFormat) initializer(img *Image, fileinfo os.FileInfo) error {
 			continue
 		}
 
+		// checks if the partition length is greater that the file
+		// size which may reveal a corrupted image (see issue #3996)
+		if fimg.Filesize < desc.Filelen {
```
Comment (Flamefire) [inline pkg/image/sif.go]: Shouldn't this be `desc.Filelen + desc.Fileoff` or is that already included?

Comment (cclerget) [reply pkg/image/sif.go]: Yes and thanks for the review and for spotting my stupid mistakes, now it's time for me to end this work day :)

Comment (Flamefire) [reply pkg/image/sif.go]: Sure :)
May I suggest adding tests that running `singularity inspect` or `singularity shell/exec` on an incomplete image returns a meaningful error message? I guess there are already tests for running those commands on correct images. To create an incomplete image I'd take a normal one and chop of the last byte. Maybe additionally tests where you destroy the squashfs header. just to make sure this code is correctly triggered and to avoid regressions.

Comment (cclerget) [reply pkg/image/sif.go]: I will add missing unit tests for SIF images in a first time in this PR, and create another PR for e2e tests

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 4]
```diff
@@ -614,8 +614,24 @@ func (c *container) mountImage(mnt *mount.Point) error {
 		mountType = "squashfs"
 	}
 	err = c.rpcOps.Mount(path, mnt.Destination, mountType, flags, optsString)
-	if err != nil {
-		return fmt.Errorf("failed to mount %s filesystem: %s", mountType, err)
+	switch err {
+	case syscall.EINVAL:
+		switch mountType {
+		case "squashfs":
```
Comment (sashayakovtseva) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: No need for switch here, can be simplified to 
```
if mountType == "squashfs" {
  return ....
}
return ....
```

**Comment by Flamefire** [comment]
Update on my example corrupted image:

- Using `inspect` still results in `Unable to process command: exit status 255: `
- Using `shell` results in `FATAL:   image format not recognized`
- Adding `-d` to `shell`:

```
VERBOSE [U=1000,P=14703]   init()                        Spawn stage 1
DEBUG   [U=1000,P=14703]   startup()                     singularity runtime engine selected
VERBOSE [U=1000,P=14703]   startup()                     Execute stage 1
DEBUG   [U=1000,P=14703]   StageOne()                    Entering stage 1
DEBUG   [U=1000,P=14703]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=14703]   Init()                        Check for image format sif
DEBUG   [U=1000,P=14703]   Init()                        sif format initializer returned: SIF image /home/tmp.sif is corrupted: wrong partition size
DEBUG   [U=1000,P=14703]   Init()                        Check for image format sandbox
DEBUG   [U=1000,P=14703]   Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1000,P=14703]   Init()                        Check for image format squashfs
DEBUG   [U=1000,P=14703]   Init()                        squashfs format initializer returned: while parsing squashfs super block: not a valid squashfs image
DEBUG   [U=1000,P=14703]   Init()                        Check for image format ext3
DEBUG   [U=1000,P=14703]   Init()                        ext3 format initializer returned: file is not a valid ext3 image
FATAL   [U=1000,P=14703]   StageOne()                    image format not recognized
VERBOSE [U=1000,P=14695]   wait_child()                  stage 1 exited with status 255
```

So yes it works better, although the error message is still not that helpful unless one uses `-d`. Still better :+1: BTW: See the typo at   `Entering image format intializer`?

**Review by sashayakovtseva — APPROVED** [review]
