### PR TITLE
Cherry pick #4737 to release-3.5

### LINKED ISSUE #4560: docker-daemon:// builder does not clean up all of its tempfiles.
### Version of Singularity:

What version of Singularity are you using? 
```
$ singularity version
3.4.0-1
```

```
$docker version
docker version
Password: 
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.12.9
 Git commit:        039a7df
 Built:             Tue Sep 24 13:23:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       039a7df
  Built:            Tue Sep 24 13:23:15 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
### Expected behavior

What did you expect to see when you do...?

When you build an image using the `docker-daemon://` builder it should at a minimum temp files created by this process should be cleaned up by `singularity cache clean` or a similar command, but I can't seem to find one.  Preferably it would just get cleaned up when the build finishes without an additional command

### Actual behavior

What actually happend? Why was it incorrect?

`singularity build $img docker-daemon://$docker_container_name` leave a potentially large file(s) in `/var/tmp/docker-tar-${some_hash}` 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

build any container using the `docker-daemon://` builder

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

### How did you install Singularity

Installed from source using an [ebuild that I wrote](https://bugs.gentoo.org/694048) since the upstream one hasn't been updated in a while.  I'm trying to get it merged.

### PR DESCRIPTION
**Pull request by dtrudg**
Cherry pick #4737 to release-3.5 for 3.5.1

Fixes #4560

When building a singularity .sif from a docker archive, singularity would
create a temporary file named docker-tarXXX in /var/tmp, and never clean it up.
This adds a line to calculateRefHash (which was creating the file via
NewImageSource()) to close the image source it created, cleaning up the
temporary file.

### CODE REVIEW

**Review by EmmEff — APPROVED** [review]
lgtm

File: internal/pkg/client/oci/oci.go [hunk 1]
```diff
@@ -114,17 +115,22 @@ func ImageSHA(ctx context.Context, uri string, sys *types.SystemContext) (string
...
 }
 
-func calculateRefHash(ctx context.Context, ref types.ImageReference, sys *types.SystemContext) (string, error) {
+func calculateRefHash(ctx context.Context, ref types.ImageReference, sys *types.SystemContext) (hash string, err error) {
 	source, err := ref.NewImageSource(ctx, sys)
 	if err != nil {
 		return "", err
 	}
+	defer func() {
+		if closeErr := source.Close(); closeErr != nil {
```
Comment (mem) [inline internal/pkg/client/oci/oci.go:124]: I'm going to approve this because it's a cherry pick, but this construction is really strange.

In principle the idea with errors.Wrapf is that you have an error that you wish you annotate with additional information (like what was happening when the error occurred). Here you are annotating the original error err with an additional error. The wrapping should have been done on line ~ 120.

Also note that you have a variable error on the function's signature and on line 119 you have a short variable declaration, except that the only variable being declared is "source", not "err". This makes for hard-to-read code, as quickly glancing at the code might look like the anonymous function on line 123 is a closure on the variable from line 119.

File: internal/pkg/client/oci/oci.go [hunk 2]
```diff
@@ -114,17 +115,22 @@ func ImageSHA(ctx context.Context, uri string, sys *types.SystemContext) (string
...
+			err = errors.Wrapf(err, " (src: %v)", closeErr)
```
Comment (mem) [inline internal/pkg/client/oci/oci.go:125]: I'm trying to picture this from the point of view of the user. The user will see:

    Something something something (src: something something): something something

The extra space before ` (src: %v)` is something that the upper layers should be dealing with (as part of the leading "Something something something"). The additional ": something something" is the result of calling Error() on this new error (and the "soemthing something" will be the from the error returned by `ref.NewImageSource`.

**Review by mem — APPROVED** [review]
