### PR TITLE
Fix CLI command root user check for unprivileged installation

### LINKED ISSUE #4962: Allow Singularity config global and plugin commands for unpriv installation
For unprivileged installation those CLI commands should be allowed :

- `singularity config global`
- `singularity plugin install`
- `singularity plugin disable`
- `singularity plugin enable`
- `singularity plugin uninstall`

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Disable root check for unprivilege installation with commands `config global` and `plugin install/enable/disable/uninstall`

### This fixes or addresses the following GitHub issues:

 - Fixes #4962 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/singularity.go [hunk 1]
```diff
@@ -580,3 +580,18 @@ func singularityExec(image string, args []string) (string, error) {
...
+// CheckRoot ensures that a command is executed with root privileges.
+func CheckRoot(cmd *cobra.Command, args []string) {
+	if os.Geteuid() != 0 {
+		sylog.Fatalf("%q command requires root privileges", cmd.CommandPath())
+	}
+}
+
+// CheckRootAndInstall ensures that a command is executed with root
+// privileges or that Singularity is installed unprivileged.
+func CheckRootAndInstall(cmd *cobra.Command, args []string) {
```
Comment (dtrudg) [inline cmd/internal/cli/singularity.go]: `CheckRootAndInstall` is a bit unclear to me, until I look at this comment on the `func` def. 

What about `CheckRootOrUnpriv` - as that suggests more that we are checking if we are root _or_ singularity is installed unpriv?

**Review by dtrudg — CHANGES_REQUESTED** [review]

File: cmd/internal/cli/singularity.go (hunk 1 above)
Comment (cclerget) [reply cmd/internal/cli/singularity.go]: Yes that's better, thanks @dctrud :)

**Review by dtrudg — APPROVED** [review]
