### PR TITLE
Honor the umask when building a SIF

### LINKED ISSUE #4521: Build command does not honer umask
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.4.1-316.g5f86ee51e.dirty
```

### Expected behavior

The `build` command should honer the umask, like:

```
$ umask 
0077
$ touch foobar
$ ls -l foobar 
-rw------- 1 westleyk westleyk 0 Sep 25 13:31 foobar

$ singularity build foo.sif library://alpine
INFO:    Starting build...
INFO:    Creating SIF file...
INFO:    Build complete: foo.sif

$ ls -l foo.sif 
-rwx------ 1 westleyk westleyk 2719744 Sep 25 13:31 foo.sif
```

### Actual behavior

Build does not care about the umask:

```
$ umask 
0077
$ touch foobar
$ ls -l foobar 
-rw------- 1 westleyk westleyk 0 Sep 25 13:31 foobar

$ singularity build foo.sif library://alpine
INFO:    Starting build...
INFO:    Creating SIF file...
INFO:    Build complete: foo.sif

$ ls -l foo.sif 
-rwxr-xr-x 1 westleyk westleyk 2719744 Sep 25 13:31 foo.sif
```

### Steps to reproduce this behavior

Build a container, and check the permission.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Source.

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

This PR make sure the `build` command honors the umask when creating the
output container.

~As of now, the images in `~/.singularity/cache` do not honor the umask,
this is _(maybe)_ still a issue, that will be fixed in another PR.~ _Fixed in this PR._

### This fixes or addresses the following GitHub issues:

 - Fixes #4521

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — CHANGES_REQUESTED** [review]
I don't think this is a great way to accomplish this. As the comment.. `// remove anything that may exist at the build destination at last moment` suggests, if we are overwriting a SIF we want to leave the original in place for as long as possible. There are many points at which an error can occur during build, before SIF creation, and it's reasonable for a user to expect the existing image to remain untouched if any of these errors happen.

File: cmd/internal/cli/build.go [hunk 1]
```diff
@@ -297,9 +297,29 @@ func checkBuildTarget(path string) error {
...
+			}
+		}
 	} else if os.IsNotExist(err) && update && sandbox {
 		return fmt.Errorf("could not update sandbox %s: doesn't exist", path)
 	}
+
+	if !sandbox && !update {
+		// Create the new image now, before any building, (and umask changes).
+		sylog.Debugf("Creating output image: %s", path)
+		fp, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_RDWR, 0755)
```
Comment (cclerget) [inline cmd/internal/cli/build.go]: `0755` is the perm before umask and works because it's not impacted by build umask `0002`, the quickest fix would be to just change https://github.com/sylabs/singularity/blob/master/internal/pkg/build/build.go#L78 to :

```
oldumask := syscall.Umask(0002)
defer syscall.Umask(oldumask)
```

Regarding umask for cache, I think it would also be fixed with above change

**Review by cclerget — CHANGES_REQUESTED** [review]

File: cmd/internal/cli/build.go (hunk 1 above)
Comment (WestleyK) [reply cmd/internal/cli/build.go]: Yup, that worked! much more simpler then I was trying to make it :smile:

**Comment by WestleyK** [comment]
@dctrud, I agree, I changed it to what @cclerget suggests. I was first trying to replicate how the `pull` command handles this, by removing the image at the cli level. But @cclerget's suggestion is a lot simpler.

_Maybe at one point we should update the `pull` command also..._

_EDIT:_ Actually I opened a issue, should be fixed sooner rather then later https://github.com/sylabs/singularity/issues/4561.

**Review by cclerget — APPROVED** [review]
LGTM, thanks !

**Review by dtrudg — APPROVED** [review]
Nice. :+1:
