### PR TITLE
Change the interface to create a new image cache handle 

### LINKED ISSUE #4213: Command pull --disable-cache still creates a cache.
## Version of Singularity:

master

### Expected behavior

When running `singularity pull --disable-cache`, the cache should be entirely bypassed. This is for instance required when the location for the cache (default location or specified by user) is not writable (grid environment and such). Otherwise the command will fail.

### Actual behavior

The command will still create the directories related to the cache:
```
$ cd /tmp/e2e-imgcache-905650874/cache
$ tree
.
├── library
├── net
├── oci
├── oci-tmp
├── oras
└── shub
```

### Steps to reproduce behavior

Create a temporary directory, set the cache location to that temporary directory and run `singularity pull --disable-cache test.sif library://alpine:latest`.

### PR DESCRIPTION
**Pull request by gvallee**
**Description of the Pull Request (PR):**

This PR changes the interface to create a new image cache handle to use a context (extensible structure) instead of a single string for the specification of the base directory. This is required because we now have various ways to impact the cache, namely environment variables (e.g., `SINGULARITY_CACHE_DIR`, `SINGULARITY_DISABLE_CACHE`) and command options (e.g., `singularity pull --disable-cache`). As a result, we need to be able to capture the context in which a new image cache handle is created.

This PR only changes the interface for the creation of a cache handle, in order to ease the its review. The goal here is to only introduce a new struct `Context` that can be used to capture the context in which a cache is created, as well as the changes to the interface to support the context, as well as all the changes necessary.

Extension to the `Context` structure to address #4213 and #4192 will be introduced in future PRs.

**This fixes or addresses the following GitHub issues:**

- Addresses #4213 
- Addresses #4192 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/client/cache/dir.go [hunk 1]
```diff
@@ -38,6 +38,13 @@ const (
 	CacheDir = "cache"
 )
 
+// Context describes the context in which a new handle is created, as defined
+// by the user through command flags and environment variables.
+type Context struct {
```
Comment (ikaneshiro) [inline internal/pkg/client/cache/dir.go]: I have a knee-jerk reaction to the name of this struct just because of the prevalence of the https://golang.org/pkg/context/ package to manage go routine lifetimes. What are your thoughts on renaming this to `Config`?

**Review by ikaneshiro — APPROVED** [review]
This LGTM, only one suggestion that isnt a blocker

**Review by ikaneshiro — APPROVED** [review]
