### PR TITLE
Sign all signable partitions

### LINKED ISSUE #4425: Sign should default to sign all sign-able partitions
## Version of Singularity:

```
v3.4
```

### Expected behavior

When you run `singularity sign foo.sif`, it should sign all sign-able partitions on that sif.

### Actual behavior

Only signed the system partition.

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

This PR changes the `sign` behavior to sign all singable partitions, (non-signature partitions).

I know that there will be some disusing about default `verify` and `sign` behavior, so if the default `sign` behavior is to sign all singable partitions, then `verify` should also verify all signable partitions.

### This fixes or addresses the following GitHub issues:

 - Fixes #4425

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: pkg/signing/signing.go [hunk 1]
```diff
@@ -89,15 +87,64 @@ func sifAddSignature(fimg *sif.FileImage, groupid, link uint32, fingerprint [20]
 	return nil
 }
 
+// Copy-paste from sylabs/sif
+// datatypeStr returns a string representation of a datatype.
+func datatypeStr(dtype sif.Datatype) string {
```
Comment (mem) [inline pkg/signing/signing.go:92]: this is usually done by defining a `String()` method on the type, `sif.Datatype` in this case.

The copy/paste comment makes me guess this is already there?

File: pkg/signing/signing.go [hunk 2]
```diff
@@ -89,15 +87,64 @@ func sifAddSignature(fimg *sif.FileImage, groupid, link uint32, fingerprint [20]
...
+		return "JSON.Generic"
+	case sif.DataGeneric:
+		return "Generic/Raw"
+	}
+	return "Unknown data-type"
+}
+
+func getDataPartitionToSign(fimg *sif.FileImage, dataType sif.Datatype) ([]*sif.Descriptor, error) {
+	sylog.Debugf("Looking for: %s partition to sign...", datatypeStr(dataType))
+	data, _, err := fimg.GetLinkedDescrsByType(uint32(0), dataType)
```
Comment (mem) [inline pkg/signing/signing.go:116]: could you please add a comment here explaning the logic behind the first argument?

It's looking for descriptors linking to ID 0 with a specific data type, so much is clear, but why 0? That's the bit that needs documenting so that other people don't get stuck on this.

File: pkg/signing/signing.go [hunk 3]
```diff
@@ -89,15 +87,64 @@ func sifAddSignature(fimg *sif.FileImage, groupid, link uint32, fingerprint [20]
...
+	var err error
 
 	if id == 0 {
 		descr[0], _, err = fimg.GetPartPrimSys()
 		if err != nil {
 			return nil, fmt.Errorf("no primary partition found")
 		}
+
+		// signablePartitions is a list of all the signable datatypes.
+		signablePartitions := []sif.Datatype{
```
Comment (mem) [inline pkg/signing/signing.go]: nit picking: it might be more clear to call this "signableDatatypes" and call the loop variable "datatype" instead of s?

File: pkg/signing/signing.go [hunk 4]
```diff
@@ -122,16 +169,16 @@ func descrToSign(fimg *sif.FileImage, id uint32, isGroup bool) (descr []*sif.Des
 func Sign(cpath string, id uint32, isGroup bool, keyIdx int) error {
 	keyring := sypgp.NewHandle("")
 
+	// Generate a private key usable for signing
```
Comment (mem) [inline pkg/signing/signing.go]: is it "generating" or "loading"?

**Review by mem — COMMENTED** [review]
Some minor issues, otherwise it looks good

File: pkg/signing/signing.go (hunk 1 above)
Comment (WestleyK) [reply pkg/signing/signing.go:92]: This function already exists here https://github.com/sylabs/sif/blob/master/pkg/sif/fmt.go#L61, since that non-exported (for now...) I just copy-paste here.

Since this function is not _that_ importent (it only generates a name for `sylog.Debugf()`), I can leave it out until we have the `String()` method for `Datatype`. I'm fine either way.

File: pkg/signing/signing.go (hunk 4 above)
Comment (WestleyK) [reply pkg/signing/signing.go]: It should be `Load a private key...`

File: pkg/signing/signing.go (hunk 1 above)
Comment (ikaneshiro) [reply pkg/signing/signing.go:92]: I think this is OK for now. I think it makes sense to support a `String()` method for data types within the SIF package. Lets open an issue for that in the SIF repo and integrate it the next time we cut a SIF release

**Review by ikaneshiro — APPROVED** [review]
lgtm

File: pkg/signing/signing.go (hunk 1 above)
Comment (WestleyK) [reply pkg/signing/signing.go:92]: Issue opened -> https://github.com/sylabs/sif/issues/67
