### PR TITLE
Development 3.0: Provide debug output for instance and information status

### LINKED ISSUE #2014: singularity instance start does not work, provides no error
## Version of Singularity:

$ singularity --version
singularity version 3.0.0-alpha.1-468-gb034a40-dirty

### Expected behavior

$ singularity instance start Default.sif www
$ echo $?
0
$ singularity instance list
INSTANCE NAME    PID      IMAGE
<instance info shown here>

### Actual behavior

$ singularity instance start Default.sif www
$ echo $?
1
$ singularity instance list
INSTANCE NAME    PID      IMAGE
$ singularity --verbose instance start Default.sif www
$ echo $?
1

### Steps to reproduce behavior

$ sudo singularity build Default.sif examples/busybox/Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
$ singularity instance start Default.sif www
$ echo $?
1
$ singularity instance list
INSTANCE NAME    PID      IMAGE
$ singularity --verbose instance start Default.sif www
$ echo $?
1

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR provides full debug output when starting instance and provides information status in case of success/failure

**This fixes or addresses the following GitHub issues:**

- Fixes #2014

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

File: src/cmd/singularity/cli/actions.go [hunk 1]
```diff
@@ -466,7 +464,56 @@ func execStarter(cobraCmd *cobra.Command, image string, args []string, name stri
...
+		if err != nil {
+			sylog.Fatalf("failed to create instance log files: %s", err)
+		}
+
+		pipefd, err := exec.SetPipe(configData)
+		if err != nil {
+			sylog.Fatalf("failed to set pipe communication: %s", err)
+		}
+
+		cmd := osexec.Command(starter, "")
```
Comment (bauerm97) [inline src/cmd/singularity/cli/actions.go]: Maybe rebase on master, then check out the new function `src/pkg/util/exec/pipe.go:PipeCommand()`, and see if that fits your use case here

**Review by bauerm97 — CHANGES_REQUESTED** [review]

File: src/cmd/singularity/cli/actions.go (hunk 1 above)
Comment (cclerget) [reply src/cmd/singularity/cli/actions.go]: Unfortunately that won't fit here, need to redirect stdout/stderr for command file logging

Comment (bauerm97) [reply src/cmd/singularity/cli/actions.go]: Hmm, I think it will still work here. Look at function signature of `PipeCommand()`:

`func PipeCommand(command string, args []string, env []string, data []byte) (*exec.Cmd, error)`

`PipeCommand()` returns `*exec.Cmd` type, which is same type as `cmd` you're using here. So I think you can do this:

```
cmd, err := exec.PipeCommand(starter, "", Env, configData)
if err != nil {
    //fatal
}

// do stderr.Seek...

cmd.Stdout = stdout
cmd.Stderr = stderr

cmdErr := cmd.Run()
```

Comment (bauerm97) [reply src/cmd/singularity/cli/actions.go]: `PipeCommand()` func will automatically set environment variable `PIPE_EXEC_FD` to the fd of the pipe file for the `exec.Cmd` type, and will also ensure that the pipe file remains open and passed to `starter` binary.

File: src/cmd/singularity/cli/actions.go [hunk 2]
```diff
@@ -466,7 +464,56 @@ func execStarter(cobraCmd *cobra.Command, image string, args []string, name stri
...
+		if err != nil {
+			sylog.Warningf("failed to get standard error stream offset: %s", err)
+		}
+
+		cmd.Stdout = stdout
+		cmd.Stderr = stderr
+		cmd.Env = append(Env, pipefd)
+		cmd.Args[0] = procname
+
+		cmdErr := cmd.Run()
```
Comment (bauerm97) [inline src/cmd/singularity/cli/actions.go:544]: Is intended to use `cmd.Run()` since `Run()` method blocks until `cmd` exits (either successfully or not-successfully)?

File: src/cmd/singularity/cli/actions.go (hunk 1 above)
Comment (cclerget) [reply src/cmd/singularity/cli/actions.go]: Ok I look too quickly, that would work. Thanks Michael !

File: src/cmd/singularity/cli/actions.go (hunk 2 above)
Comment (cclerget) [reply src/cmd/singularity/cli/actions.go:544]: Yes, instance always returns, so `cmd.Run()` will block until instance start or fail to provide information about success/failure

**Comment by cclerget** [comment]
@bauerm97 Now use `PipeCommand`. I took the opportunity to simplify code and remove some code redundancies in `src/pkg/util/exec/pipe.go`. Also fixed the hardcoded PIPE_EXEC_FD value (always set to 3) used in `PipeCommand`.

**Comment by bauerm97** [comment]
@cclerget Reason that I hardcoded `PIPE_EXEC_FD=3` is because I was passing the pipe `*os.File` to the `os/exec.Cmd` struct's `Files` field. When reading `os/exec` package I wasn't clear if open files are always passed to new process when not explicitly adding to `Files` of the `Cmd`. But it looks like this is working properly so it's ok this way

**Review by bauerm97 — APPROVED** [review]
