### PR TITLE
fix: Do not load keyring in prepare_linux if ECL not enabled

### LINKED ISSUE #5558: ECL does not handle missing /home nicely
### Version of Singularity:

```
singularity version 3.6.1-1.el7
```

### Expected behavior

Launch Singularity with ``--no-home`` option and be able to execute the container on a host
where ``$HOME`` is not mounted:

```
~$ singularity pull /tmp/python.sif docker://python:latest
~$ cd /tmp
~$ singularity --verbose exec --no-home /tmp/python.sif python --version
VERBOSE: HOME=/home/mtds                                          
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Drop root privileges
VERBOSE: Drop root privileges permanently      
VERBOSE: Spawn stage 1                          
VERBOSE: Execute stage 1                                  
VERBOSE: stage 1 exited with status 0                                                                          
VERBOSE: Get root privileges     
VERBOSE: Change filesystem uid to 1001                              
VERBOSE: Spawn master process  
VERBOSE: Create mount namespace
VERBOSE: Entering in mount namespace      
VERBOSE: Drop root privileges
VERBOSE: Create mount namespace          
VERBOSE: Spawn RPC server
VERBOSE: Execute master process
VERBOSE: Serve RPC requests                                          
VERBOSE: Default mount: /proc:/proc    
VERBOSE: Default mount: /sys:/sys
VERBOSE: Default mount: /dev:/dev
VERBOSE: Found 'bind path' = /etc/hosts, /etc/hosts
VERBOSE: Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE: Default mount: /tmp:/tmp
VERBOSE: Default mount: /var/tmp:/var/tmp
VERBOSE: Default mount: /etc/resolv.conf:/etc/resolv.conf
VERBOSE: Default mount: /tmp: to the container
VERBOSE: Checking for template passwd file: /var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE: Creating passwd content
VERBOSE: Creating template passwd file and appending user data: /var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE: Default mount: /etc/passwd:/etc/passwd
VERBOSE: Checking for template group file: /var/singularity/mnt/session/rootfs/etc/group
VERBOSE: Creating group content
VERBOSE: Default mount: /etc/group:/etc/group
VERBOSE: Skipping mount /tmp, /var/singularity/mnt/session/final/tmp/mtds already mounted
VERBOSE: rpc server exited with status 0
VERBOSE: Execute stage 2
Python 3.8.5
```
The previous command worked perfectly till version _3.5.3_.

### Actual behavior

```
~$ cd /tmp
~$ singularity --verbose exec --no-home /tmp/python.sif uname -a
VERBOSE: Setting HOME=/home/mtds
VERBOSE: Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Drop root privileges
VERBOSE: Drop root privileges permanently
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
FATAL:   while obtaining keyring for ECL: mkdir /home: permission denied
VERBOSE: stage 1 exited with status 255
```

It looks like Singularity is still looking for my home directory (set to be ``/home/mtds``) in any case, even when
the ``--no-home`` parameter is specified. This will not allow us to run containers as batch jobs on nodes which
by default do not mount the home directories of our users.

### Steps to reproduce this behavior

```bash
[root@lxdev01 ~]# singularity pull /tmp/python.sif docker://python:latest
[root@lxdev01 ~]# adduser --no-create-home foo
[root@lxdev01 ~]# su foo
bash-4.2$ ls $HOME
ls: cannot access /home/foo: No such file or directory
bash-4.2$ cd /tmp
bash-4.2$ singularity -v exec --no-home /tmp/python.sif python --version
VERBOSE: Setting HOME=/tmp
VERBOSE: Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WARNING: can't determine current working directory: stat .: permission denied
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid
VERBOSE: Drop root privileges
VERBOSE: Drop root privileges permanently
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
WARNING: can't determine current working directory
FATAL:   while obtaining keyring for ECL: mkdir /home/foo: permission denied
VERBOSE: stage 1 exited with status 255
```
Same result is obtained also when using the ``--home`` parameter and pointing it to ``/tmp``.

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
```
~$ uname -r
3.10.0-1127.13.1.el7.x86_64
```

### How did you install Singularity

We did build an RPM package from upstream directly.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Avoid attempting to load the public keyring for ECL handling when the
ECL is not enabled. Take the approach of passing through a null keyring
so ECL apply/ignore logic remains in the ECL package and is not
duplicated in the runtime code.

This is an effective fix for #5558 when ECL is not enabled.

Note: this does not address:
- Deeper issues in the way sypgp code handles paths - such as #5516. We need to fix env var handling, and ideally be able to differentiate between a non-fatal failure for certain read-only operations on a missing keyring, vs fatal failures.
- An e2e test for missing/inaccessible home dir. Because of the way the e2e framework sets up a homedir tmpfs mount in a namespace that is shared by things in each suite.Run() call it's not trivial to test home dir issues by manipulating perms / deleting the home dir etc. We need a way to do this to avoid regressions and I'll open a tech debt issue for it.

### This fixes or addresses the following GitHub issues:

 - Fixes #5558

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engine/singularity/prepare_linux.go [hunk 1]
```diff
@@ -1166,9 +1166,16 @@ func (e *EngineOperations) loadImages(starterConfig *starter.Config) error {
...
 
-			kr, err := sypgp.PublicKeyRing()
-			if err != nil {
-				return fmt.Errorf("while obtaining keyring for ECL: %s", err)
+			// Only try to load the keyring here if the ECL is active.
+			// Otherwise pass through an empty keyring rather than avoiding calling
+			// the ECL functions as this keeps the logic for applying / ignoring ECL in a
+			// single location.
+			kr := sypgp.NullKeyRing()
+			if ecl.Activated {
```
Comment (tri-adam) [inline internal/pkg/runtime/engine/singularity/prepare_linux.go:1175]: Arguably, if this is `false`, we don't need to call `ecl.ShouldRunFp` at all, and thus wouldn't need a keyring? What about something like: 

```
			if ecl.Activated {
				kr, err := sypgp.PublicKeyRing()
				if err != nil {
					return fmt.Errorf("while obtaining keyring for ECL: %s", err)
				}

				if ok, err := ecl.ShouldRunFp(img.File, kr); err != nil {
					return fmt.Errorf("while checking container image with ECL: %s", err)
				} else if !ok {
					return errors.New("image prohibited by ECL")
				}
			}
```

**Review by tri-adam — CHANGES_REQUESTED** [review]
One suggestion, thank you.

File: internal/pkg/runtime/engine/singularity/prepare_linux.go (hunk 1 above)
Comment (dtrudg) [reply internal/pkg/runtime/engine/singularity/prepare_linux.go:1175]: Now modified per discussion elsewhere,

**Review by tri-adam — APPROVED** [review]
