### PR TITLE
Fix instances test

### LINKED ISSUE #2127: [Test] TestInstance fails due parallel execution
After https://github.com/sylabs/singularity/pull/2081, the CI tests is failing
```
--- FAIL: TestInstance (0.02s)
    instance_test.go:52: Error building an image from a definition: exit status 255. Output follows.
        WARNING: Authentication token file not found : Only pulls of public images will succeed
        Build target already exists. Do you want to overwrite? [N/y] FATAL:   Error parsing input: EOF
FAIL
coverage: 50.0% of statements
FAIL	github.com/sylabs/singularity/src/cmd/singularity	470.022s
```
Posible fix:
https://github.com/sylabs/singularity/blob/master/src/cmd/singularity/instance_test.go#L16
should aff `--force` to the build arguments

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
- Fixes #2127

Signed-off-by: ArangoGutierrez <eduardo@sylabs.io>

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

File: src/cmd/singularity/instance_test.go [hunk 1]
```diff
@@ -41,33 +34,40 @@ func stopInstance(instance string) ([]byte, error) {
...
+		writable: false,
+	}
+	if b, err := imageBuild(opts, imagePath, definition); err != nil {
+		t.Log(string(b))
+		t.Fatalf("unexpected failure: %v", err)
 	}
+	imageVerify(t, imagePath, true)
+	defer os.RemoveAll(imagePath)
 
 	t.Run("StartListStop", test.WithoutPrivilege(func(t *testing.T) {
```
Comment (GodloveD) [inline src/cmd/singularity/instance_test.go:55]: Can this be run in a loop with all of the flags checked or something?

File: src/cmd/singularity/instance_test.go [hunk 2]
```diff
@@ -41,33 +34,40 @@ func stopInstance(instance string) ([]byte, error) {
...
+		if err != nil {
+			t.Fatalf("Error listing instances: %v. Output follows.\n%s", err, string(listInstanceOutput))
 		}
 
-		stopInstanceOutput, stopInstanceError := stopInstance(defaultInstance)
-		if stopInstanceError != nil {
-			t.Fatalf("Error stopping instance by name: %v. Output follows.\n%s", stopInstanceError, string(stopInstanceOutput))
+		stopInstanceOutput, err := stopInstance(defaultInstance)
+		if err != nil {
+			t.Fatalf("Error stopping instance by name: %v. Output follows.\n%s", err, string(stopInstanceOutput))
```
Comment (GodloveD) [inline src/cmd/singularity/instance_test.go:70]: Seems like `instance list` should be called again and the text output should be checked to make sure it doesn't report any running instances.

File: src/cmd/singularity/instance_test.go [hunk 3]
```diff
@@ -41,33 +34,40 @@ func stopInstance(instance string) ([]byte, error) {
...
+		startInstanceOutput, err := startInstance(imagePath, defaultInstance)
+		if err != nil {
+			t.Fatalf("Error starting instance from an image: %v. Output follows.\n%s", err, string(startInstanceOutput))
 		}
 
-		listInstanceOutput, listInstanceError := listInstance()
-		if listInstanceError != nil {
-			t.Fatalf("Error listing instances: %v. Output follows.\n%s", listInstanceError, string(listInstanceOutput))
+		listInstanceOutput, err := listInstance()
+		if err != nil {
```
Comment (GodloveD) [inline src/cmd/singularity/instance_test.go:64]: Instead of just checking the error can we also check that the std out of the command is reasonable?

**Review by GodloveD — DISMISSED** [review]
Do running instances also create and delete temporary files somewhere like they used to do in 2.x?  Can this test suite also check for the presence and absence of those files where appropriate.

**Review by GodloveD — APPROVED** [review]
Agreed that this PR should just fix existing tests and not add enhancements.  Moved request to #2129 

lgtm
