### PR TITLE
Fix configuration parser

### LINKED ISSUE #2530: Bind mounts in singularity.conf not loading
## Version of Singularity:

3.0.2

### Expected behavior

Bind mounts specified in `/etc/singularity/singularity.conf` should be bound to specified directories in the container.

### Actual behavior

They are not.

### Steps to reproduce behavior

* Add specific bind points in the `singularity.conf` file like so:

```text
bind path = /etc/localtime
bind path = /etc/hosts
bind path = /scratch
bind path = /shared
```
* Make files/directories exist in container.
* Run the container (`exec` or `shell` for simplicity).
* `ls` the directories that should be bind mounted.

This functionality has been tested and works in 3.0.1. This is a regression in the latest patch release.

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fixes a regression introduced in 3.0.2 while parsing configuration file, default value are always taken for configuration directives of string slice type.

**This fixes or addresses the following GitHub issues:**

- Fixes #2530

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engines/config/parser_test.go [hunk 1]
```diff
@@ -0,0 +1,141 @@
+// Copyright (c) 2018, Sylabs Inc. All rights reserved.
```
Comment (jmstover) [inline internal/pkg/runtime/engines/config/parser_test.go]: Can you change this to 2019 here?

**Review by jmstover — APPROVED** [review]

File: internal/pkg/runtime/engines/config/parser_test.go (hunk 1 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/config/parser_test.go]: Sure
