### PR TITLE
Set default umask during stages build

### LINKED ISSUE #4749: FATAL:   no run driver found inside container
### Version of Singularity:

```
singularity --version
singularity version 3.5.0
```

### Expected behavior

I've installed the latest version of Singularity on our cluster using the standard methods.  It works when I run it as myself.  I also expect it to work when I run it as a freshly created user.

### Actual behavior
When I run a docker container as a freshly created user, it does not work.
```
$ singularity run docker://godlovedc/lolcow
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
FATAL:   no run driver found inside container
```

The freshly created user is able to run the same command with Singularity 3.4.1.  As myself, I've deleted `~/.singularity` but I'm still able to run the docker container.  I've checked the permissions of the files within the installation directory and everything seems to be in order.  

### Steps to reproduce this behavior
Unfortunately, I'm not yet sure.   

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

source

### Debug output
```
$ singularity --debug run docker://godlovedc/lolcow
DEBUG   [U=38959,P=51533]  persistentPreRunE()           Singularity version: 3.5.0
DEBUG   [U=38959,P=51533]  handleConfDir()               /home/apptest1/.singularity already exists. Not creating.
DEBUG   [U=38959,P=51533]  getCacheBasedir()             environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/library
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/oci-tmp
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/oci
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/net
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/shub
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/oras
DEBUG   [U=38959,P=51533]  parseURI()                    Parsing docker://godlovedc/lolcow into reference
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb
DEBUG   [U=38959,P=51533]  updateCacheSubdir()           Caching directory set to /home/apptest1/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb
DEBUG   [U=38959,P=51533]  execStarter()                 Checking for encrypted system partition
DEBUG   [U=38959,P=51533]  Init()                        Image format detection
DEBUG   [U=38959,P=51533]  Init()                        Check for sandbox image format
DEBUG   [U=38959,P=51533]  Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=38959,P=51533]  Init()                        Check for sif image format
DEBUG   [U=38959,P=51533]  Init()                        sif image format detected
VERBOSE [U=38959,P=51533]  SetContainerEnv()             HOME=/home/apptest1
DEBUG   [U=38959,P=51533]  init()                        Use starter binary /usr/local/current/singularity/3.5.0/libexec/singularity/bin/starter-suid
VERBOSE [U=0,P=51533]      print()                       Set messagelevel to: 5
VERBOSE [U=0,P=51533]      init()                        Starter initialization
DEBUG   [U=0,P=51533]      load_overlay_module()         Trying to load overlay kernel module
DEBUG   [U=0,P=51533]      load_overlay_module()         Overlay seems supported by the kernel
DEBUG   [U=0,P=51533]      get_pipe_exec_fd()            PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=51533]      is_suid()                     Check if we are running as setuid
VERBOSE [U=0,P=51533]      priv_drop()                   Drop root privileges
DEBUG   [U=38959,P=51533]  init()                        Read engine configuration
DEBUG   [U=38959,P=51533]  init()                        Wait completion of stage1
VERBOSE [U=38959,P=51545]  priv_drop()                   Drop root privileges permanently
DEBUG   [U=38959,P=51545]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=38959,P=51545]  init()                        Spawn stage 1
DEBUG   [U=38959,P=51545]  startup()                     singularity runtime engine selected
VERBOSE [U=38959,P=51545]  startup()                     Execute stage 1
DEBUG   [U=38959,P=51545]  StageOne()                    Entering stage 1
DEBUG   [U=38959,P=51545]  prepareAutofs()               Found "/proc/sys/fs/binfmt_misc" as autofs mount point
DEBUG   [U=38959,P=51545]  prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=38959,P=51545]  prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=38959,P=51545]  prepareAutofs()               Could not keep file descriptor for home directory /home/apptest1: no mount point
DEBUG   [U=38959,P=51545]  prepareAutofs()               Could not keep file descriptor for current working directory /home/apptest1: no mount point
DEBUG   [U=38959,P=51545]  Init()                        Image format detection
DEBUG   [U=38959,P=51545]  Init()                        Check for sandbox image format
DEBUG   [U=38959,P=51545]  Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=38959,P=51545]  Init()                        Check for sif image format
DEBUG   [U=38959,P=51545]  Init()                        sif image format detected
DEBUG   [U=38959,P=51545]  setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=38959,P=51545]  setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
VERBOSE [U=38959,P=51533]  wait_child()                  stage 1 exited with status 0
DEBUG   [U=38959,P=51533]  cleanup_fd()                  Close file descriptor 4
DEBUG   [U=38959,P=51533]  init()                        Set child signal mask
DEBUG   [U=38959,P=51533]  init()                        Create socketpair for master communication channel
DEBUG   [U=38959,P=51533]  init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=38959,P=51533]  priv_escalate()               Get root privileges
VERBOSE [U=0,P=51533]      priv_escalate()               Change filesystem uid to 38959
VERBOSE [U=0,P=51533]      init()                        Spawn master process
DEBUG   [U=0,P=51552]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=51552]      create_namespace()            Create mount namespace
VERBOSE [U=0,P=51533]      enter_namespace()             Entering in mount namespace
DEBUG   [U=0,P=51533]      enter_namespace()             Opening namespace file ns/mnt
DEBUG   [U=0,P=51533]      setns()                       Using syscall() wrapped __NR_setns
VERBOSE [U=0,P=51533]      priv_drop()                   Drop root privileges
VERBOSE [U=0,P=51552]      create_namespace()            Create mount namespace
DEBUG   [U=0,P=51553]      set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=51553]      init()                        Spawn RPC server
DEBUG   [U=38959,P=51533]  startup()                     singularity runtime engine selected
VERBOSE [U=38959,P=51533]  startup()                     Execute master process
DEBUG   [U=0,P=51553]      startup()                     singularity runtime engine selected
VERBOSE [U=0,P=51553]      startup()                     Serve RPC requests
DEBUG   [U=38959,P=51533]  setupSessionLayout()          Using Layer system: overlay
DEBUG   [U=38959,P=51533]  setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=38959,P=51533]  addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=38959,P=51533]  addRootfsMount()              Image type is 4096
DEBUG   [U=38959,P=51533]  addRootfsMount()              Mounting block [squashfs] image: /home/apptest1/.singularity/cache/oci-tmp/a692b57abc43035b197b10390ea2c12855d21649f2ea2cc28094d18b93360eeb/lolcow_latest.sif
DEBUG   [U=38959,P=51533]  addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=38959,P=51533]  addKernelMount()              Adding proc to mount list
VERBOSE [U=38959,P=51533]  addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=38959,P=51533]  addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=38959,P=51533]  addKernelMount()              Adding sysfs to mount list
VERBOSE [U=38959,P=51533]  addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=38959,P=51533]  addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=38959,P=51533]  addDevMount()                 Adding dev to mount list
VERBOSE [U=38959,P=51533]  addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=38959,P=51533]  addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=38959,P=51533]  addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=38959,P=51533]  addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=38959,P=51533]  addHomeStagingDir()           Staging home directory (/home/apptest1) at /var/singularity/mnt/session/home/apptest1
DEBUG   [U=38959,P=51533]  addHomeMount()                Adding home directory mount [/var/singularity/mnt/session/home/apptest1:/home/apptest1] to list using layer: overlay
DEBUG   [U=38959,P=51533]  addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=38959,P=51533]  addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=38959,P=51533]  addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=38959,P=51533]  addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=38959,P=51533]  addCwdMount()                 Using /home/apptest1 as current working directory
VERBOSE [U=38959,P=51533]  addCwdMount()                 Default mount: /home/apptest1: to the container
DEBUG   [U=38959,P=51533]  addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=38959,P=51533]  addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=38959,P=51533]  addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=38959,P=51533]  addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=38959,P=51533]  addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=38959,P=51533]  create()                      Mount all
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting tmpfs to /var/singularity/mnt/session
DEBUG   [U=38959,P=51533]  mountImage()                  Mounting loop device /dev/loop0 to /var/singularity/mnt/session/rootfs of type squashfs
DEBUG   [U=38959,P=51533]  addActionsMount()             Ignoring actions mount, /var/singularity/mnt/session/rootfs/.singularity.d/actions doesn't exist
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting overlay to /var/singularity/mnt/session/final
DEBUG   [U=38959,P=51533]  setPropagationMount()         Set RPC mount propagation flag to SLAVE
VERBOSE [U=38959,P=51533]  Passwd()                      Checking for template passwd file: /var/singularity/mnt/session/rootfs/etc/passwd
WARNING [U=38959,P=51533]  addIdentityMount()            passwd file doesn't exist in container, not updating
VERBOSE [U=38959,P=51533]  Group()                       Checking for template group file: /var/singularity/mnt/session/rootfs/etc/group
WARNING [U=38959,P=51533]  addIdentityMount()            group file doesn't exist in container, not updating
DEBUG   [U=38959,P=51533]  mountGeneric()                Remounting /var/singularity/mnt/session/final
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /dev to /var/singularity/mnt/session/final/dev
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /etc/localtime to /var/singularity/mnt/session/final/etc/localtime
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /etc/hosts to /var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /proc to /var/singularity/mnt/session/final/proc
DEBUG   [U=38959,P=51533]  mountGeneric()                Remounting /var/singularity/mnt/session/final/proc
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting sysfs to /var/singularity/mnt/session/final/sys
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /home/apptest1 to /var/singularity/mnt/session/home/apptest1
DEBUG   [U=38959,P=51533]  mountGeneric()                Remounting /var/singularity/mnt/session/home/apptest1
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /var/singularity/mnt/session/home/apptest1 to /var/singularity/mnt/session/final/spin1/home/linux/apptest1
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /tmp to /var/singularity/mnt/session/final/tmp
DEBUG   [U=38959,P=51533]  mountGeneric()                Remounting /var/singularity/mnt/session/final/tmp
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /var/tmp to /var/singularity/mnt/session/final/var/tmp
DEBUG   [U=38959,P=51533]  mountGeneric()                Remounting /var/singularity/mnt/session/final/var/tmp
VERBOSE [U=38959,P=51533]  mountGeneric()                Skipping mount /home/apptest1, /var/singularity/mnt/session/final/spin1/home/linux/apptest1 already mounted
DEBUG   [U=38959,P=51533]  mountGeneric()                Mounting /var/singularity/mnt/session/etc/resolv.conf to /var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=38959,P=51533]  create()                      Chroot into /var/singularity/mnt/session/final
DEBUG   [U=0,P=51553]      Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=51553]      Chroot()                      Called pivot_root on /var/singularity/mnt/session/final
DEBUG   [U=0,P=51553]      Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=51553]      Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=51553]      Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=51553]      Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=38959,P=51533]  create()                      Chdir into / to avoid errors
VERBOSE [U=0,P=51552]      wait_child()                  rpc server exited with status 0
DEBUG   [U=0,P=51552]      apply_container_privileges()  Set user ID to 38959
DEBUG   [U=38959,P=51552]  set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=38959,P=51552]  startup()                     singularity runtime engine selected
VERBOSE [U=38959,P=51552]  startup()                     Execute stage 2
DEBUG   [U=38959,P=51552]  StageTwo()                    Entering stage 2
FATAL   [U=38959,P=51552]  StageTwo()                    no run driver found inside container
DEBUG   [U=38959,P=51533]  startContainer()              stage 2 process reported an error, waiting status
DEBUG   [U=38959,P=51533]  Master()                      Child exited with exit status 255
```

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Fix regression introduced by #4542  where the umask is reset to its old value a bit too early. We restore it just before `Assemble` step to also fix the original addressed by #4542 

### This fixes or addresses the following GitHub issues:

 - Fixes #4749 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/build/build.go [hunk 1]
```diff
@@ -257,6 +257,8 @@ func (b *Build) Full(ctx context.Context) error {
 	// clean up build normally
 	defer b.cleanUp()
 
+	oldumask := syscall.Umask(0002)
```
Comment (WestleyK) [inline internal/pkg/build/build.go:260]: Since we have this here, do we still need the umask call on line 79? For `newBuild`?

Comment (dtrudg) [reply internal/pkg/build/build.go:260]: in that function, `NewBundle` is doing some operations that will create a tmpdir etc.... I believe we do want to have the `Umask(0002)` for that, so the bundle dir is created with workable perms even if a crazy umask is in force.

**Review by dtrudg — APPROVED** [review]
This LGTM,

I verified the issue Cedric noted on the `umask 011` with a clean cache and this PR does work for me too.
