### PR TITLE
fix: wait for cryptsetup /dev/mapper device to appear

### LINKED ISSUE #5950: Race condition exists between cryptsetup and mounting of /dev/mapper/<GUID>
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.7.3-1.el7.SN.1
```

### Expected behavior

```
[tyson@gra-ccsudo1:/tmp]$ singularity run --passphrase master.sif 
Enter encryption passphrase: 
bash-4.4$ 
```

### Actual behavior

```
[tyson@gra-ccsudo1:/tmp]$ singularity -d shell --passphrase master.sif
...
DEBUG   [U=3001792,P=10345]create()                      Mount all
DEBUG   [U=3001792,P=10345]mountGeneric()                Mounting tmpfs to /opt/software/singularity-3.7.3/var/singularity/mnt/session
DEBUG   [U=3001792,P=10345]mountImage()                  Mounting loop device /dev/loop7 to /opt/software/singularity-3.7.3/var/singularity/mnt/session/rootfs of type encryptfs
DEBUG   [U=3001792,P=10372]func1()                       Using cryptsetup at "/sbin/cryptsetup"
DEBUG   [U=3001792,P=10372]Open()                        Running /sbin/cryptsetup /sbin/cryptsetup open --batch-mode --type luks2 --key-file - /dev/loop7 5c0135f8-159d-4f4c-b1e9-ace83a5b1495
DEBUG   [U=3001792,P=10372]Open()                        Successfully opened encrypted device /dev/loop7
DEBUG   [U=3001792,P=10345]umount()                      Umount /opt/software/singularity-3.7.3/var/singularity/mnt/session/final
DEBUG   [U=3001792,P=10345]umount()                      Umount /opt/software/singularity-3.7.3/var/singularity/mnt/session/rootfs
ERROR   [U=3001792,P=10345]CleanupContainer()            could not cleanup crypt: invalid argument
FATAL   [U=3001792,P=10345]Master()                      container creation failed: mount /proc/self/fd/3->/opt/software/singularity-3.7.3/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to mount squashfs filesystem: no such file or directory
[tyson@gra-ccsudo1:/tmp]$ 
```

### Steps to reproduce this behavior

It's a race condition so it may be tricky to trigger. It happens very reliably on our cluster login nodes though. Possibly because they usually sit at a load average >> 1. Or maybe because of other items. I don't know. What I do know is if you wrapper the `cryptsetup` executable with one that sleeps for 5 seconds before returning that resolves the issue.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

Custom RPM build (i.e., from source).

### PR DESCRIPTION
**Pull request by twhitehead**
## Description of the Pull Request (PR):

The device `/dev/mapper/...` does not show up before `cryptsetup` returns. This creates a race condition as, if singularity attempts to mount `/dev/mapper/...`, before it shows up, it fails.

This pull request causes singularity to wait up to 25.5s for `/dev/mapper/...` to show up, through a series of exponential back off sleeps, before continuing. If it doesn't show up in that time it will abort with an error.

### This fixes or addresses the following GitHub issues:

 - Fixes #5950

#### Before submitting a PR, make sure you have done the following:

- [X] Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [X] Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- [X] Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- [X] Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- [X] Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by twhitehead** [comment]
If you are happy with this, I can cherry pick it against the the release-3.7 branch too.

**Comment by gmkurtzer** [comment]
This looks good to me, but I'll let someone more qualified do the review. With that said, I would think that 25 seconds is probably excessive. How long are you seeing that it typically takes for `/dev/mapper` devices to show up?

**Comment by twhitehead** [comment]
I don't actually know other than in my initial debugging a 5s delay to cryptsetup was sufficient to resolve it, so probably doesn't have to be long at all. I had just figured it never showing up after `cyrptsetup` succeeds is such an unlikely error path though, that that a longer pause to be 100% certain was safe. I'm happy to force push a different amount if you have a specific number in mind.

File: pkg/util/crypt/crypt_dev.go [hunk 1]
```diff
@@ -299,6 +300,19 @@ func (crypt *Device) Open(key []byte, path string) (string, error) {
 
 			return "", fmt.Errorf("cryptsetup open failed: %s: %v", string(out), err)
 		}
+
+		for attempt := 0; true; attempt++ {
+			_, err := os.Stat("/dev/mapper/" + nextCrypt)
+			if err == nil {
```
Comment (dtrudg) [inline pkg/util/crypt/crypt_dev.go:306]: In checks for the existence of a file/directory/device, it's usual to check if `os.IsNotExist(err)` is true, and fail immediately if the err is not an IsNotExist.

File: pkg/util/crypt/crypt_dev.go [hunk 2]
```diff
@@ -299,6 +300,19 @@ func (crypt *Device) Open(key []byte, path string) (string, error) {
...
+				break
+			}
+			delay := 100 * (1 << attempt) * time.Millisecond
+			if delay > 12800*time.Millisecond {
```
Comment (dtrudg) [inline pkg/util/crypt/crypt_dev.go]: If you can make the conditionals more explicit that the max wait here is 25.5s then that would be useful for future readers skimming over the code. Some concise comments about the exponential backoff progression / max would work also.

**Review by dtrudg — CHANGES_REQUESTED** [review]
Thanks for contributing this. I have a couple of fairly minor requests.

**Comment by dtrudg** [comment]
Hi @twhitehead - given we are about 2 weeks out from an RC for 3.8 it's not clear there will be another 3.7 release, so you don't need to cherry-pick to the release-3.7 branch. If we issue one then this PR is nice and contained that we can cherry-pick easily.

File: pkg/util/crypt/crypt_dev.go (hunk 2 above)
Comment (twhitehead) [reply pkg/util/crypt/crypt_dev.go]: Good idea. I've add another variable and comment to make the total delay so far calculation clear.

File: pkg/util/crypt/crypt_dev.go (hunk 1 above)
Comment (twhitehead) [reply pkg/util/crypt/crypt_dev.go:306]: Done.

**Comment by twhitehead** [comment]
I just force pushed a new version. I'm not sure why it hasn't shown up here yet.

BTW, I'm always a bit confused about what it the best practice for integrating feedback into a pull request

- force pushing corrections based on feedback the best approach, or
- push additional correction commits

and in the last case, should you squash them squash them in the end when everyone agrees it is good?

**Comment by dtrudg** [comment]
@twhitehead - for Singularity the core developers tend to force push updated commits with corrections, but it doesn't always happen like that, and there is no hard rule here. If there are relatively small PRs like this one that have fixup commits we can do a 'squash and merge' when we merge the PR to clean the history up a bit when it's appropriate.

**Comment by twhitehead** [comment]
Thanks. As it still didn't seem to be picking up on my force push, I decided to change it over to a fixups commit for each of the requests as suggested [here](https://github.com/marketplace/actions/block-fixup-commit-merge#why) and force pushed that, which it seems to have picked up on.

From [this community discussion](https://github.community/t/merge-option-with-rebase-autosquash/2242/4) it simply sounds like there isn't currently a good way to do this in github (or at least for something more complex than this one which can just be squashed as you pointed out).

**Review by dtrudg — APPROVED** [review]

**Comment by dtrudg** [comment]
Thanks @twhitehead!

**Comment by twhitehead** [comment]
NP. Thank you for all the hard work on this project and the quick handling and feedback on the pull request. :+1:
