### PR TITLE
Bind /etc/hosts or create a default one with --contain flag

### LINKED ISSUE #1707: singularity --contain without --net stops sharing /etc/hosts
## Version of Singularity:

2.5.1

### Expected behavior

Without using --net, I expect /etc/hosts to be mapped into the container because the network is shared with the host.

### Actual behavior

Since /etc/hosts is only listed as a bind path in singularity.conf, and those are ignored with --contain (#1212), then /etc/hosts is not bind mounted into the container when --contain is used.

### Steps to reproduce behavior

Start singularity with --contain and look at /etc/hosts.

A workaround is to set the environment variable SINGULARITY_BINDPATH=/etc/hosts, but that shouldn't be necessary.

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Bind `/etc/hosts` with `--contain` flag or create a minimal staging hosts file if a network namespace is requested with `--contain`.

### This fixes or addresses the following GitHub issues:

 - Fixes #1707

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engine/singularity/container_linux.go [hunk 1]
```diff
@@ -1248,8 +1248,27 @@ func (c *container) addBindsMount(system *mount.System) error {
...
+			sylog.Debugf("Skipping bind mounts as contain was requested")
+
+			sylog.Verbosef("Binding staging /etc/hosts as contain is set")
+			if err := c.session.AddFile(hostsPath, files.DefaultHosts()); err != nil {
+				return fmt.Errorf("while adding /etc/hosts staging file: %s", err)
+			}
+			hosts, _ = c.session.GetPath(hostsPath)
+		}
+
+		system.Points.AddBind(mount.BindsTag, hosts, hostsPath, flags)
```
Comment (dtrudg) [inline internal/pkg/runtime/engine/singularity/container_linux.go]: In the loop below, you catch the error on `AddBind` is that not necessary here?

File: internal/pkg/runtime/engine/singularity/container_linux.go [hunk 2]
```diff
@@ -1267,6 +1286,7 @@ func (c *container) addBindsMount(system *mount.System) error {
 		if err != nil {
 			return fmt.Errorf("unable to add %s to mount list: %s", src, err)
 		}
+		system.Points.AddRemount(mount.BindsTag, dst, flags)
```
Comment (dtrudg) [inline internal/pkg/runtime/engine/singularity/container_linux.go]: Is the addition here fixing a separate issue?

Also, in the contain case above you are returning any error from `AddRemount`, but here it is not caught / returned. Does it need to be?

**Review by dtrudg — COMMENTED** [review]
Couple of questions.

File: internal/pkg/runtime/engine/singularity/container_linux.go (hunk 2 above)
Comment (cclerget) [reply internal/pkg/runtime/engine/singularity/container_linux.go]: Yes this is a different issue but while we are in this code part it's worth to fix it. Fixed the return.

File: internal/pkg/runtime/engine/singularity/container_linux.go (hunk 1 above)
Comment (cclerget) [reply internal/pkg/runtime/engine/singularity/container_linux.go]: Fixed

**Comment by DrDaveD** [comment]
How about also including /etc/localtime and /etc/nsswitch.conf as I suggested in #1707?  Unless of course someone had already bind mounted them another way.

**Comment by dtrudg** [comment]
Not sure about `nsswitch.conf`. Wouldn't that be quite likely to have `ldap` directory or `sss` caching stuff configured in it, which is not what we want in a `--contain`ed container which is meant to be as independent from the host as we can get?

**Comment by cclerget** [comment]
`/etc/localtime` has been added with `--contain` and `singularity.conf` note updated to mention this behavior. @DrDaveD I don't think it make sense to add `nsswitch.conf` for many reasons :
- it should be specific to container images and nss services present in container image
- with this PR if we bind it by default in all cases, singularity doesn't provide a way to remove this bind if a user want to use the image `nsswitch.conf`
- OS images like alpine/busybox doesn't use NSS because of musl

For those reasons it's preferable to be explicit and let users to choose by using `-B /etc/nsswitch` if necessary and make things easier for all.

**Review by dtrudg — APPROVED** [review]
This LGTM

**Comment by DrDaveD** [comment]
Ok on leaving out nsswitch.conf, looks good to me too.
