### PR TITLE
Reworked RPC capability handling to fix regression issue during overlay mount

### LINKED ISSUE #5455: Can't write to 777 files owned by other users in 3.6.0 with --writable-tmpfs (worked in 3.5.3)
### Version of Singularity:

3.6.0

### Expected behavior

Using this definition:
```
BootStrap: docker
From: alpine:latest

%post
        mkdir /perm_test
        touch /perm_test/root.log
        chown root:root /perm_test/root.log
        chmod 777 /perm_test/root.log

        touch /perm_test/nobody.log
        chown nobody:nobody /perm_test/nobody.log
        chmod 777 /perm_test/nobody.log
```
with 3.5.3, I get:
```
$ id
uid=10000(test) gid=10000(test) groups=10000(test) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
$ singularity --version
singularity version 3.5.3-1.1.el7
$ singularity shell --writable-tmpfs test.sif
Singularity> ls -l /perm_test/
total 1
-rwxrwxrwx    1 nobody   nobody           0 Jul 24 14:29 nobody.log
-rwxrwxrwx    1 root     root             0 Jul 24 14:29 root.log
Singularity> touch /perm_test/*
Singularity> 
```

### Actual behavior

In 3.6.0, touching (or trying to write to) these files fails with a permission error:

```
$ id
uid=10000(test) gid=10000(test) groups=10000(test) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
$ singularity --version
singularity version 3.6.0-1.el7
$ singularity shell --writable-tmpfs test.sif
Singularity> ls -l /perm_test/
total 1
-rwxrwxrwx    1 nobody   nobody           0 Jul 24 14:27 nobody.log
-rwxrwxrwx    1 root     root             0 Jul 24 14:27 root.log
Singularity> touch /perm_test/*
touch: /perm_test/nobody.log: Permission denied
touch: /perm_test/root.log: Permission denied
Singularity> 
```

### Steps to reproduce this behavior

Use the definition file and commands provided above.

### What OS/distro are you running

Distro: CentOS 7.8
Kernel: 3.10.0-1127.13.1.el7.x86_64

### How did you install Singularity

EPEL 7 RPM - singularity-3.6.0-1.el7.x86_64

### LINKED ISSUE #5461: --writable-tmpfs fails on Fedora 32 (5.7 kernel?)
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.6.1
```

### Actual behavior

On my Fedora 32 system `--writable-tmpfs` is now failing....

```
dave@piran~> singularity shell --writable-tmpfs docker://alpine
INFO:    Using cached SIF image
FATAL:   container creation failed: mount overlay->/usr/local/var/singularity/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /usr/local/var/singularity/mnt/session/final: permission denied
```

Wiping out all trace of the singularity install and starting afresh doesn't fix it - so there isn't anything strange with my session dir causing this.

It appears to be possibly kernel version related as I'm sure it worked before - and it continues to work on a different Fedora 32 machine still running a slightly older kernel.

Fails: 5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Works: 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What OS/distro are you running

```
Fedora 32
5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### How did you install Singularity

3.6.1 source

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Reworked RPC capability handling to fix regression issue during overlay mount. RPC now modifies its effective capabilities on a per method call basis and will abort execution by reporting the missing capability in a less cryptic error message.

Also fixes a regression issue during container decryption when `--ipc` is specified.

### This fixes or addresses the following GitHub issues:

 - Fixes #5455 
 - Fixes #5461 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/starter/c/starter.c [hunk 1]
```diff
@@ -353,16 +353,26 @@ static void set_rpc_privileges(void) {
...
+     * be in the permitted set:
+     * - CAP_MKNOD
+     * - CAP_SYS_CHROOT
+     * - CAP_SETGID
+     * - CAP_SETUID
+     * - CAP_FOWNER
+     * - CAP_DAC_OVERRIDE
+     * - CAP_DAC_READ_SEARCH
+     * - CAP_CHOWN
+     * - CAP_IPC_LOCK
```
Comment (dtrudg) [inline cmd/starter/c/starter.c:369]: I don't think `CAP_IPC_LOCK` is references anywhere else here now.... missing or intended?

The encrypt flow appears to just be using `CAP_SYS_PTRACE`?

**Review by dtrudg — CHANGES_REQUESTED** [review]
Question about CAP_IPC_LOCK - see above.

Otherwise this looks reasonable to me.

File: cmd/starter/c/starter.c (hunk 1 above)
Comment (cclerget) [reply cmd/starter/c/starter.c:369]: Initially it's required to be in the permitted set, I fixed that in RPC code to request it explicitly and trigger error if missing. Also fixed cryptsetup cleanup to request CAP_SYS_ADMIN during umount

**Review by dtrudg — APPROVED** [review]

**Review by dtrudg — APPROVED** [review]
