### PR TITLE
Check for cryptsetup at build time

### LINKED ISSUE #3819: Save location of cryptsetup during buildtime in config files
## Version of Singularity:

Currently cryptsetup utility is directly called with full path (/sbin/cryptsetup) as PATH variable is not set in Go runtime. We can address the problem in a similar way to mksquashfs by saving the location of cryptsetup in a configuration file during build time and using that location at runtime.

### Expected behavior

NA

### Actual behavior

NA

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by mem**
Currently the location of cryptsetup is hardcoded to /sbin/cryptsetup.
Check for the actual path at build time, and record the result in
buildcfg. At runtime, the path is retrieved from the configuration file
first, and if that's empty, it falls back to the path recorded at build
time. This gives the system administrator full control over which
cryptsetup program is used.

Fixes: #3819

Signed-off-by: Marcelo E. Magallon <marcelo@sylabs.io>

### CODE REVIEW

File: internal/pkg/util/bin/bin.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+	sync.Once
+	cryptsetup string
+	err        error
+}
+
+// Cryptsetup looks for the "cryptsetup" program returning the absolute
+// path to it. If the cryptsetup program is not available, this function
+// returns a non-nil error.
+func Cryptsetup() (string, error) {
+	cache.Do(func() {
```
Comment (schebro) [inline internal/pkg/util/bin/bin.go:37]: This is nice. Didn't know "Do" before.

File: internal/pkg/util/bin/bin.go [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+			return "", errors.New("unable to obtain path to cryptsetup program")
+		}
+
+		path = buildcfg.CRYPTSETUP_PATH
+	} else {
+		switch fi, err := os.Stat(path); {
+		case err != nil:
+			return "", errors.Wrapf(err, "unable to stat %s", path)
+
+		case fi.IsDir():
```
Comment (schebro) [inline internal/pkg/util/bin/bin.go:76]: Should we force one way or the other? Either store directory or the absolute path to the binary?

File: pkg/util/crypt/crypt_dev.go [hunk 3]
```diff
@@ -169,7 +174,7 @@ func (crypt *Device) FormatCryptDevice(path, key string) (string, string, error)
 	defer lock.Release(fd)
 
 	nextCrypt := getNextAvailableCryptDevice()
-	cmd = exec.Command("/sbin/cryptsetup", "luksOpen", loopdev, nextCrypt)
+	cmd = exec.Command(cryptsetup, "luksOpen", loopdev, nextCrypt)
 	cmd.Dir = "/dev"
```
Comment (schebro) [inline pkg/util/crypt/crypt_dev.go:178]: Running cryptsetup in "/dev" is harmless in this case I feel. But, as you noted in slack, you can delete this and pass "/dev"+loopdev I guess

File: pkg/util/crypt/crypt_dev.go [hunk 4]
```diff
@@ -260,7 +265,12 @@ retry:
...
 	}
 
-	cmd := exec.Command("/sbin/cryptsetup", "luksOpen", loopDev, nextCrypt)
+	cryptsetup, err := bin.Cryptsetup()
+	if err != nil {
+		return "", err
+	}
+
+	cmd := exec.Command(cryptsetup, "luksOpen", loopDev, nextCrypt)
 	cmd.Dir = "/dev"
```
Comment (schebro) [inline pkg/util/crypt/crypt_dev.go:274]: Same as above.

**Review by schebro — CHANGES_REQUESTED** [review]

File: internal/pkg/util/bin/bin.go (hunk 2 above)
Comment (mem) [reply internal/pkg/util/bin/bin.go:76]: I'm not happy with this but I'm following the example set by mksquashfs: in the configuration file the user can provide a directory or a filename. If it's a directory, it's the directory containing the program, just like this code does.

File: pkg/util/crypt/crypt_dev.go (hunk 3 above)
Comment (mem) [reply pkg/util/crypt/crypt_dev.go:178]: I'll fix that in a different PR.

File: pkg/util/crypt/crypt_dev.go (hunk 4 above)
Comment (mem) [reply pkg/util/crypt/crypt_dev.go:274]: ditto

File: internal/pkg/util/bin/bin.go (hunk 1 above)
Comment (mem) [reply internal/pkg/util/bin/bin.go:37]: :-)

File: mlocal/scripts/find_program [hunk 5]
```diff
@@ -0,0 +1,23 @@
+#!/bin/sh
```
Comment (jscook2345) [inline mlocal/scripts/find_program]: Is there a good reason to use this over standard programs like `which` and `command -v`?

File: mlocal/scripts/find_program [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+for dir in $2 ; do
+	fn="${dir}/$1"
+	if test -x "${fn}" ; then
+		# found
+		echo "${fn}"
+		exit 0
+	fi
+done
+
+exit 1
```
Comment (jscook2345) [inline mlocal/scripts/find_program]: This will cause a failure in the mconfig (what I'm seeing in CircleCI) if the package is not installed rather than with the correct output when it's not found.

Bad
```
checking: cryptsetup... Exited with code 1
```

Good
```
 checking: cryptsetup... no

unable to find the cryptsetup program, need package cryptsetup-bin
```

**Comment by jscook2345** [comment]
Does this package now need to be included with our RPMs and other CI services?

File: mlocal/scripts/find_program (hunk 6 above)
Comment (mem) [reply mlocal/scripts/find_program]: Fixed

File: mlocal/scripts/find_program (hunk 5 above)
Comment (mem) [reply mlocal/scripts/find_program]: When I was doing this I had something else in mind, and I ended up backtracking. So, right, the script is equivalent to command -v (except that command -v considers aliases, too, but I'll ignore that).

**Review by schebro — APPROVED** [review]
