### PR TITLE
Check overlay lower/upper filesystem compatibility for sandbox images

### LINKED ISSUE #3887: Error when using overlay on Lustre filesystem
## Version of Singularity:

singularity version 3.2.1-1.el7

### Expected behavior

Using overlay with SIF or sandbox container (shell/exec) on the Lustre filesystem.

### Actual behavior

The following error:

```
VERBOSE [U=0,P=123442]     print()                       Set messagelevel to: 5
DEBUG   [U=0,P=123442]     init()                        PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=123442]     init()                        Container runtime
VERBOSE [U=0,P=123442]     is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=123442]     init()                        Overlay seems supported by kernel
DEBUG   [U=0,P=123442]     init()                        Drop privileges
DEBUG   [U=32548259,P=123442]  init()                        Read json configuration from pipe
DEBUG   [U=32548259,P=123442]  init()                        Set child signal mask
DEBUG   [U=32548259,P=123442]  init()                        Wait completion of stage1
VERBOSE [U=32548259,P=123468]  priv_escalate()               Get root privileges
DEBUG   [U=0,P=123468]     set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=123468]     prepare_stage()               Entering in stage 1
DEBUG   [U=32548259,P=123468]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=32548259,P=123468]  init()                        Spawn stage 1
VERBOSE [U=32548259,P=123468]startup()                     Execute stage 1
DEBUG   [U=32548259,P=123468]Stage()                       Entering stage 1
DEBUG   [U=32548259,P=123468]Init()                        Entering image format intializer
DEBUG   [U=32548259,P=123468]Init()                        Check for image format sif
DEBUG   [U=32548259,P=123468]Init()                        sif format initializer returns: not a SIF file image
DEBUG   [U=32548259,P=123468]Init()                        Check for image format sandbox
DEBUG   [U=32548259,P=123442]  init()                        Create socketpair for master communication channel
DEBUG   [U=32548259,P=123442]  cleanup_fd()                  Check file descriptor /proc/self/fd/3 pointing to /data/louwers/arch.img
DEBUG   [U=32548259,P=123442]  cleanup_fd()                  Check file descriptor /proc/self/fd/4 pointing to anon_inode:[eventpoll]
DEBUG   [U=32548259,P=123442]  cleanup_fd()                  Closing /proc/self/fd/4
VERBOSE [U=32548259,P=123442]  priv_escalate()               Get root privileges
VERBOSE [U=0,P=123442]     create_namespace()            Create mount namespace
DEBUG   [U=0,P=123442]     init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=0,P=123442]     init()                        Spawn master process
DEBUG   [U=0,P=123488]     set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=123488]     create_namespace()            Create mount namespace
DEBUG   [U=0,P=123488]     set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=123488]     prepare_stage()               Entering in stage 2
VERBOSE [U=0,P=123491]     init()                        Spawn RPC server
DEBUG   [U=32548259,P=123488]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=123491]     startup()                     Serve RPC requests
VERBOSE [U=32548259,P=123442]startup()                     Execute master process
DEBUG   [U=32548259,P=123442]setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=32548259,P=123442]setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=32548259,P=123442]addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=32548259,P=123442]addRootfsMount()              Mounting directory rootfs: /data/louwers/arch.img
DEBUG   [U=32548259,P=123442]addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=32548259,P=123442]addKernelMount()              Adding proc to mount list
VERBOSE [U=32548259,P=123442]addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=32548259,P=123442]addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=32548259,P=123442]addKernelMount()              Adding sysfs to mount list
VERBOSE [U=32548259,P=123442]addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=32548259,P=123442]addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=32548259,P=123442]addDevMount()                 Adding dev to mount list
VERBOSE [U=32548259,P=123442]addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=32548259,P=123442]addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=32548259,P=123442]addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=32548259,P=123442]addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=32548259,P=123442]addHomeStagingDir()           Staging home directory (/home/louwers) at /var/singularity/mnt/session/home/louwers
DEBUG   [U=32548259,P=123442]addHomeMount()                Adding home directory mount [/var/singularity/mnt/session/home/louwers:/home/louwers] to list using layer: overlay
DEBUG   [U=32548259,P=123442]isLayerEnabled()              Using Layer system: overlay
DEBUG   [U=32548259,P=123442]addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=32548259,P=123442]addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=32548259,P=123442]addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=32548259,P=123442]addScratchMount()             Not mounting scratch directory: Not requested
VERBOSE [U=32548259,P=123442]addCwdMount()                 Default mount: /data/louwers: to the container
DEBUG   [U=32548259,P=123442]addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=32548259,P=123442]addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=32548259,P=123442]addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=32548259,P=123442]addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=32548259,P=123442]create()                      Mount all
DEBUG   [U=32548259,P=123442]mountGeneric()                Mounting tmpfs to /var/singularity/mnt/session
DEBUG   [U=32548259,P=123442]mountGeneric()                Mounting /data/louwers/arch.img to /var/singularity/mnt/session/rootfs
DEBUG   [U=32548259,P=123442]mountGeneric()                Remounting /var/singularity/mnt/session/rootfs
DEBUG   [U=32548259,P=123442]mountGeneric()                Mounting overlay to /var/singularity/mnt/session/final
DEBUG   [U=32548259,P=123442]CleanupContainer()            Cleanup container
FATAL   [U=32548259,P=123442]Master()                      container creation failed: mount overlay->/var/singularity/mnt/session/final error: can't mount overlay filesystem to /var/singularity/mnt/session/final: invalid argument
```

dmesg:

```
[3017338.358383] overlayfs: filesystem on '/var/singularity/mnt/session/rootfs' not supported
```

### Steps to reproduce behavior

1. Create container
2. Tansfer to Lustre filesystem
3. `shell exec container.img id`

### LINKED ISSUE #3977: Singularity freezes when running sandbox container
## Version of Singularity:

3.2.1 and 3.3.0rc3

### Expected behavior

I expect the command to execute

### Actual behavior

Freezes indefinitely.

### Steps to reproduce behavior

singularity exec centos-7 ls
or
singularity exec centos-7 echo 'Hello'

I tried with ubuntu and several other containers. This happens only on sandbox containers. It works fine with .sif containers. My OS is Ubuntu 16.04

### LINKED ISSUE #4035: Add checks for sandbox and overlay lowerdir compatibility
Actually some filesystems like `ecryptfs`, `Lustre` are known to not work when a sandbox image stored on those filesystems is used as an overlay `lowerdir`. It would be useful to add checks in order to advertise users and fallback to `underlay` automatically.

Related to : #3977

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Some filesystems are not compatible either with lower or upper overlay directories or both, this PR adds a package easing detection for those filesystems. This PR also adds an automatic fallback in runtime to use underlay if the sandbox image is on a filesystem incompatible with overlay.

**This fixes or addresses the following GitHub issues:**

- Fixes #4035
- Fixes #3977
- Fixes #3887

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/util/fs/overlay/overlay.go [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+	lowerDir
+	upperDir
+)
+
+type fs struct {
+	name       string
+	overlayDir dir
+}
+
+//nolint:mispell
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]:
```suggestion
//nolint:misspell
```

Comment (sashayakovtseva) [reply internal/pkg/util/fs/overlay/overlay.go]: Or maybe better add this in `.golangci.yml`

File: internal/pkg/util/fs/overlay/overlay.go [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+const (
+	nfs    int64 = 0x6969
+	fuse         = 0x65735546
+	ecrypt       = 0xF15F
+	lustre       = 0x0BD00BD0
+)
+
+//nolint:mispell
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]:
```suggestion
//nolint:misspell
```

File: internal/pkg/util/fs/overlay/overlay.go [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+func IsIncompatible(err error) bool {
+	if _, ok := err.(interface{ dummy(*errIncompatibleFs) }); ok {
+		return true
+	}
+	return false
+}
+
+// statfs is the function pointing to unix.Statfs and
+// also used for unit tests for mocking
+var statfs func(string, *unix.Statfs_t) error
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]: Minor suggestion: 
```
var statfs = unix.Statfs
```

instead of var + init

Comment (sashayakovtseva) [reply internal/pkg/util/fs/overlay/overlay.go]: Also would be cool to put this on top of the file

File: internal/pkg/util/fs/overlay/overlay.go [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+	return fmt.Sprintf(
+		"%s is located on a %s filesystem incompatible as overlay %s directory",
+		e.path, e.name, overlayDir,
+	)
+}
+
+// IsIncompatible returns if the error corresponds to
+// an incompatible filesystem error
+func IsIncompatible(err error) bool {
+	if _, ok := err.(interface{ dummy(*errIncompatibleFs) }); ok {
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]: You don't need dummy at all, this check can be performed like this: 
```
if _, ok := err.(*errIncompatibleFs); ok {
		return true
}
```

Comment (sashayakovtseva) [reply internal/pkg/util/fs/overlay/overlay.go]: Since `err` is an interface you can easily query the underlying type.

File: internal/pkg/util/fs/overlay/overlay.go [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+}
+
+type errIncompatibleFs struct {
+	path string
+	name string
+	dir  dir
+}
+
+// dummy function to distinguish this error amongst others.
+func (e *errIncompatibleFs) dummy(err *errIncompatibleFs) {}
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]: this should be removed

File: internal/pkg/util/fs/overlay/overlay.go [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+		overlayDir = "upper"
+	}
+	return fmt.Sprintf(
+		"%s is located on a %s filesystem incompatible as overlay %s directory",
+		e.path, e.name, overlayDir,
+	)
+}
+
+// IsIncompatible returns if the error corresponds to
+// an incompatible filesystem error
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]:
```suggestion
// an incompatible filesystem error.
```

File: internal/pkg/util/fs/overlay/overlay.go [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+func IsIncompatible(err error) bool {
+	if _, ok := err.(interface{ dummy(*errIncompatibleFs) }); ok {
+		return true
+	}
+	return false
+}
+
+// statfs is the function pointing to unix.Statfs and
+// also used for unit tests for mocking
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/overlay/overlay.go]:
```suggestion
// also used for unit tests for mocking.
```

**Review by sashayakovtseva — APPROVED** [review]
