### PR TITLE
Fix shared mount for %setup %files during build

### LINKED ISSUE #2707: %files is not working
### Expected behavior

Specified file is copied into the container image.

### Actual behavior

Specified file is not copied into the container image.

### Steps to reproduce behavior

```
# cat Singularity.def
BootStrap: docker
From: ubuntu:16.04

%files
    hello.c /var/tmp/hello.c

%post
    ls -l /var/tmp/hello.c

# ls -l hello.c
-rw-r--r--. 1 root root 63 Feb 13 22:49 hello.c

# singularity build hello.sif Singularity.def
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:7b722c1070cdf5188f1f9e43b8413157f8dfb2b4fe84db3c03cb492379a42fcc
Skipping fetch of repeat blob sha256:5fbf74db61f1459176d8647ba8f53f8e6cf933a2e56f73f0e8da81213117b7e9
Skipping fetch of repeat blob sha256:ed41cb72e5c918bdbd78e68f02930a3f1cf1d6079402b0a5b19de8508e67b766
Skipping fetch of repeat blob sha256:7ea47a67709ebea8efed59fbda703dbd00a0d2cae7e2808959744bfa30bfc0e9
Copying config sha256:288b5aca25f70512e5874c289a8a216b60808ecc47f687fa502fd848e5c3f875
 2.42 KiB / 2.42 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Copying hello.c to /var/tmp/hello.c
INFO:    Running post scriptlet
+ ls -l /var/tmp/hello.c
ls: cannot access '/var/tmp/hello.c': No such file or directory
FATAL:   post proc: exit status 2
FATAL:   While performing build: while running engine: exit status 255
```

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fixes regression in build engine dropping shared feature affecting `%setup` and `%files` sections during build

**This fixes or addresses the following GitHub issues:**

- Fixes #2707 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engines/imgbuild/create.go [hunk 1]
```diff
@@ -121,12 +97,69 @@ func (engine *EngineOperations) CreateContainer(pid int, rpcConn net.Conn) error
 		}
 	}
 
+	dest = filepath.Join(sessionPath, "proc")
```
Comment (ikaneshiro) [inline internal/pkg/runtime/engines/imgbuild/create.go:100]: What's the reasoning for having these mounted after `%setup` is run? My understanding of `%setup` is that its supposed to be ran after mounts are in place and just before the `chroot`

**Review by ikaneshiro — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/engines/imgbuild/create.go (hunk 1 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/imgbuild/create.go:100]: `%setup` doesn't need `/proc`, `/sys`, `hosts` and `resolv.conf` since not chrooted, but actually running setup after `hosts` and `resolv.conf` mount doesn't allow to inject a custom `/etc/hosts` in image without overriding `/etc/hosts` on system :

```
%files
custom_hosts /etc/hosts

%setup
     cat > $SINGULARITY_ROOTFS/etc/hosts <<EOF
blahblah ....
EOF
```

this patch additionally prevent accidental override, so its required to run `%setup` `%files` before `hosts` and `resolv.conf` mounts to not get a permission denied error.

Comment (ikaneshiro) [reply internal/pkg/runtime/engines/imgbuild/create.go:100]: Makes sense

**Review by ikaneshiro — APPROVED** [review]
