### PR TITLE
Always check the return of the Scan() function

### LINKED ISSUE #3714: Always check to return of `Scan()`
## Version of Singularity:

Master.

### Expected behavior

@mem pointed out that the `Scan` method returns a boolean, which should be inspected before trying to obtain the text:

```
Scan advances the Scanner to the next token, which will then be available
through the Bytes or Text method. It returns false when the scan stops,
either by reaching the end of the input or an error. After Scan returns
false, the Err method will return any error that occurred during scanning,
except that if it was io.EOF, Err will return nil. Scan panics if the split
function returns too many empty tokens without advancing the input. This is
a common error mode for scanners.
```

Our code base includes a few calls where we do not check the boolean returned by `Scan()`

### Actual behavior

Write here.

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by gvallee**
**Description of the Pull Request (PR):**

Always check the return of the Scan() function.

**This fixes or addresses the following GitHub issues:**

- Fixes #3714 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: pkg/util/fs/proc/proc.go [hunk 1]
```diff
@@ -144,7 +144,10 @@ func ReadIDMap(path string) (uint32, uint32, error) {
 	defer r.Close()
```
Comment (WestleyK) [inline pkg/util/fs/proc/proc.go:145]: This files copyright year should be `2018-2019`

**Review by WestleyK — COMMENTED** [review]
Looks almost good to me; can you change the copyright year to `2018-2019` in this file. Otherwise looks good, thanks :+1:

**Review by WestleyK — APPROVED** [review]
Looks good to me! :+1:

File: pkg/util/fs/proc/proc.go [hunk 2]
```diff
@@ -144,7 +144,10 @@ func ReadIDMap(path string) (uint32, uint32, error) {
...
 
 	scanner := bufio.NewScanner(r)
-	scanner.Scan()
+	tok := scanner.Scan()
+	if !tok {
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]: Can be simplified a bit with `if !scanner.Scan()`, since `tok` is used for this single check only

File: pkg/util/fs/proc/proc.go [hunk 3]
```diff
@@ -144,7 +144,10 @@ func ReadIDMap(path string) (uint32, uint32, error) {
...
+		return 0, 0, scanner.Err()
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]: Btw error can be nil here if the file was empty. I am not sure how that will affect further logic since it may become `0`  for uid, so better ask @cclerget.

Comment (cclerget) [reply pkg/util/fs/proc/proc.go]:
```suggestion
		return 0, 0, fmt.Errorf("scanner error: %s", scanner.Err())
```

**Review by cclerget — CHANGES_REQUESTED** [review]

File: pkg/util/fs/proc/proc.go (hunk 3 above)
Comment (sashayakovtseva) [reply pkg/util/fs/proc/proc.go]: hm, that might be confusing, `scanner error: nil`
but assuming that files are never empty...

**Review by sashayakovtseva — APPROVED** [review]

**Review by cclerget — APPROVED** [review]

**Comment by WestleyK** [comment]
Whats the status on this? Looks like it can be merged now.
