### PR TITLE
Finish the implementation of e2e tests for the cache command

### LINKED ISSUE #4081: [E2E] Improve coverage for cache command
## Version of Singularity:

All.

### Expected behavior

All commands expected to succeed should be tested.
Part of issue #4078

### Actual behavior

- [ ] singularity cache clean --dry-run
- [ ] singularity cache clean --force
- [ ] singularity cache clean --help
- [ ] singularity cache clean --name
- [ ] singularity cache clean --type
- [ ] singularity cache list --help
- [ ] singularity cache list --type
- [ ] singularity cache list --verbose

### Steps to reproduce behavior

N/A.

### PR DESCRIPTION
**Pull request by gvallee**
**Description of the Pull Request (PR):**

 Finish the implementation of e2e tests for the cache command (positive cases only). This PR only aims at improving coverage as defined in the current e2e effort.

**This fixes or addresses the following GitHub issues:**

- Fixes #4081 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: e2e/cache/cache.go [hunk 1]
```diff
@@ -18,88 +20,258 @@ type cacheTests struct {
...
+		send               string
+		exit               int
+		expectedEmptyCache bool // Is the cache supposed to be empty after the command is executed
 	}{
 		{
-			name:   "clean cache normal",
-			expect: "Do you want to continue? [N/y]",
-			send:   "y",
-			exit:   0,
+			name:               "clean normal",
```
Comment (jscook2345) [inline e2e/cache/cache.go]: Do we want to test any of the `N` options here? Just to make sure they don't do anything when completed?

**Review by jscook2345 — CHANGES_REQUESTED** [review]
See comments

File: e2e/cache/cache.go (hunk 1 above)
Comment (gvallee) [reply e2e/cache/cache.go]: I can easily add that, no problem.

File: e2e/cache/cache.go [hunk 2]
```diff
@@ -18,88 +20,290 @@ type cacheTests struct {
...
+			expect:             "Do you want to continue? [N/y]",
+			send:               "n",
+			expectedEmptyCache: false,
+			exit:               0,
+		},
+		{
+			name:               "clean dry-run confirmed",
+			options:            []string{"clean", "--dry-run"},
+			expect:             "Do you want to continue? [N/y]",
+			send:               "y",
```
Comment (WestleyK) [inline e2e/cache/cache.go:153]: Out of curiosity, why is `cache clean --dry-run` interactive? It should not be imo.

Comment (WestleyK) [reply e2e/cache/cache.go:153]: It seems like a bug -> https://github.com/sylabs/singularity/issues/4225

Comment (gvallee) [reply e2e/cache/cache.go:153]: @WestleyK I have no idea. Since I wrote the tests, I have to admit that I am even more confused than I was before. For cleaning, we now have `--dry-run`, `--force`, `--type` and `--name` and they all a different effect on the cache. A good example of something I do not understand is `--dry-run`.
```
$ singularity cache clean --dry-run
This will delete everything in your cache (containers from all sources and OCI blobs). 
Hint: You can see exactly what would be deleted by canceling and using the --dry-run option.
Do you want to continue? [N/y] y
Would remove /home/gvallee/.singularity/cache/library
Would remove /home/gvallee/.singularity/cache/oci-tmp
Would remove /home/gvallee/.singularity/cache/shub
Would remove /home/gvallee/.singularity/cache/oci
Would remove /home/gvallee/.singularity/cache/net
Would remove /home/gvallee/.singularity/cache/oras
```
which I personally do not understand how it is useful information (does not say exactly what will be removed and how much space freed). I am not saying that I think the developments we saw lately are bad, I just do not personally understand. 
What bothers me the most is that checking whether the cache is clean or not ends up being a non-trivial thing. And I believe it shows we still do not have good semantics behind these commands.

Comment (gvallee) [reply e2e/cache/cache.go:153]: @WestleyK Do you think we should open an issue? This is PR is really about e2e tests, I would like to avoid modifying anything outside of e2e.

Comment (WestleyK) [reply e2e/cache/cache.go:153]: This one? https://github.com/sylabs/singularity/issues/4225 I just opened it.

File: e2e/internal/e2e/fileutil.go [hunk 3]
```diff
@@ -82,3 +82,9 @@ func FileExists(t *testing.T, path string) bool {
 
 	return true
 }
+
+// FileExists return true if the file identified by the path exists, false otherwise.
+func FileExists(t *testing.T, path string) bool {
+	// todo: we should check if it is a file
```
Comment (WestleyK) [inline e2e/internal/e2e/fileutil.go:88]: Are you planing on fixing this in this PR?

**Review by WestleyK — APPROVED** [review]
Looks good to me, is that `todo` going to be fixed in this PR?

File: e2e/internal/e2e/fileutil.go (hunk 3 above)
Comment (gvallee) [reply e2e/internal/e2e/fileutil.go:88]: No, this is not needed here.

**Review by jscook2345 — APPROVED** [review]
