### PR TITLE
Fix user namespace bind source located on a read-only filesystem

### LINKED ISSUE #3799: Failure binding ro source when running unprivileged -- can't remount
## Version of Singularity:

3.2.1 and 3.3.0-rc.1

### Expected behavior

Should be able to bind a directory from a read-only filesystem into a container when running unprivileged. 

### Actual behavior

When binding anything from a read-only filesystem and running unprivileged there's a "can't remount" "operation not permitted" error.  This is a regression from singularity-2.6.1.

### Steps to reproduce behavior

Run the following or use any container image of your choice:
```
$ sudo mount -t tmpfs -o ro tmpfs /mnt
$ singularity shell -u -B /mnt docker://centos 
FATAL:   container creation failed: mount ->/mnt error: can't remount /mnt: operation not permitted
```

We noticed it first with cvmfs as a mount source but can reproduce it with any filesystem mounted read-only.

@cclerget

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR prevent to remount user bind source directory located on a RO filesystem when user namespace is in use to avoid failure

**This fixes or addresses the following GitHub issues:**

- Fixes #3799

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 1]
```diff
@@ -1339,13 +1341,23 @@ func (c *container) addUserbindsMount(system *mount.System) error {
 
 		sylog.Debugf("Adding %s to mount list\n", src)
 
+		if c.userNS {
+			// test if the source directory is a read-only filesystem by
+			// asking for write permission for this directory, if EROFS error
+			// is returned, we need to skip remount to avoid failure
+			if err := syscall.Access(src, 0x2); err.(syscall.Errno) == syscall.EROFS {
```
Comment (DrDaveD) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: Since it is running unprivileged, if the source directory is simply owned by root, won't this treat it as a read-only filesystem?  On the other hand, maybe it doesn't matter, because in that case it won't try to remount.  Or will it?  The remount seems to otherwise be always tried when AddBind() below returns err == nil.

For that matter, why do this check here and have a remount flag at all?  Why not do the check down below, just before the AddRemount, only when it is actually needed?

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 2]
```diff
@@ -1283,13 +1283,15 @@ func (c *container) addUserbindsMount(system *mount.System) error {
...
-	flags := uintptr(syscall.MS_BIND | c.suidFlag | syscall.MS_NODEV | syscall.MS_REC)
+	defaultFlags := uintptr(syscall.MS_BIND | c.suidFlag | syscall.MS_NODEV | syscall.MS_REC)
 
 	if len(c.engine.EngineConfig.GetBindPath()) == 0 {
 		return nil
 	}
 
 	for _, b := range c.engine.EngineConfig.GetBindPath() {
+		flags := defaultFlags
+		remount := true
```
Comment (DrDaveD) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: I suggest calling this something like "remountok" because it doesn't always result in a remount, it just allows it.

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 3]
```diff
@@ -1339,13 +1341,23 @@ func (c *container) addUserbindsMount(system *mount.System) error {
...
+		if c.userNS {
+			// test if the source directory is a read-only filesystem by
+			// asking for write permission for this directory, if EROFS error
+			// is returned, we need to skip remount to avoid failure
+			if err := syscall.Access(src, 0x2); err.(syscall.Errno) == syscall.EROFS {
+				remount = false
+			}
+		}
+
 		if err := system.Points.AddBind(mount.UserbindsTag, src, dst, flags); err != nil && err == mount.ErrMountExists {
```
Comment (DrDaveD) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: This comment is for the unchanged AddBind() line: the err != nil check is redundant, because if it is equal to mount.ErrMountExists it is obviously not nil.

**Review by DrDaveD — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/engines/singularity/container_linux.go (hunk 1 above)
Comment (DrDaveD) [reply internal/pkg/runtime/engines/singularity/container_linux.go]: In version 2.6.1, the [corresponding code](https://github.com/sylabs/singularity/blob/vault/release-2.6/src/lib/runtime/mounts/userbinds/userbinds.c#L143) only sets read_only when the user requests it and then [skips the remount with a warning](https://github.com/sylabs/singularity/blob/vault/release-2.6/src/lib/runtime/mounts/userbinds/userbinds.c#L143).  It does not, as far as I see, detect anywhere that the source filesystem is read-only and try to copy that.  How's that being detected now?  Even with this patch if the user requests read only it will fail rather than warn.

In a couple of other places in this same source file, when mounting /proc and /sys, it skips the remount whenever c.userNS is set.  Why not do it the same way?  And there are a number of other places where AddRemount is called (e.g. in addHostMount) that do not check c.userNS; won't some of them have this same problem?

File: internal/pkg/runtime/engines/singularity/container_linux.go (hunk 2 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/container_linux.go]: Should go away by moving check before `AddRremount`

File: internal/pkg/runtime/engines/singularity/container_linux.go (hunk 1 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/container_linux.go]: `EROFS` will take precedence over `EPERM`, that's why `EPERM` is ignored here because it means the directory is owned by another user and it doesn't matter in this case.

Regarding 2.6.1 behavior, it was a lazy approach, IMO when we can we should apply mount flag correctly even with user namespace enabled (users may want to bind a directory in read-only).

I will apply fix for others. Thanks !

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 4]
```diff
@@ -531,6 +531,15 @@ func (c *container) mountGeneric(mnt *mount.Point) (err error) {
 		}
 	}
 	_, err = c.rpcOps.Mount(source, dest, mnt.Type, flags, optsString)
+	// when using user namespace we always try to apply mount flags,
+	// then if we get a permission denied error, we contine execution
+	// by ignoring the error and warn user
+	if remount && err != nil && c.userNS {
+		if err.Error() == syscall.Errno(syscall.EPERM).Error() {
+			sylog.Warningf("Could not remount %s: %s", dest, err)
```
Comment (DrDaveD) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: I don't think this should be a warning; verbose should be enough (and matching the behavior of 2.6), unless perhaps the remount is because the user explicitly asked for it with a :ro in a --bind option.

Are there any reasons that err might be EPERM other than a remount failure?

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 5]
```diff
@@ -531,6 +531,15 @@ func (c *container) mountGeneric(mnt *mount.Point) (err error) {
 		}
 	}
 	_, err = c.rpcOps.Mount(source, dest, mnt.Type, flags, optsString)
+	// when using user namespace we always try to apply mount flags,
+	// then if we get a permission denied error, we contine execution
+	// by ignoring the error and warn user
+	if remount && err != nil && c.userNS {
```
Comment (DrDaveD) [inline internal/pkg/runtime/engines/singularity/container_linux.go:547]: Note that err != nil is redundant here again.

Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/container_linux.go:547]: this is required otherwise the call `err.Error` will panic when `err` is nil

File: internal/pkg/runtime/engines/singularity/container_linux.go (hunk 4 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/container_linux.go]: For `EPERM` condition, this is a pretty defensive approach instead of ignoring all error, other errors could be caused by a dev mistake or something irregular

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 6]
```diff
@@ -531,6 +531,20 @@ func (c *container) mountGeneric(mnt *mount.Point) (err error) {
 		}
 	}
 	_, err = c.rpcOps.Mount(source, dest, mnt.Type, flags, optsString)
+	// when using user namespace we always try to apply mount flags with
+	// remount, then if we get a permission denied error, we contine
```
Comment (DrDaveD) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: CI scripts are complaining about the misspelling of continue in this comment.

**Review by DrDaveD — APPROVED** [review]
Other than the complaint about the misspelled comment, this looks OK to me now.  There is now only the verbose message when bind-mounting from a read-only filesystem when running unprivileged.

There is a mystery, however: if I add the ":ro" flag to a bind mount (whether the source is a read-only filesystem or read-write filesystem), this adds the MS_RDONLY flag and then the remount does not fail (there is no warning message).  I don't understand what the remount is attempting to do without the MS_RDONLY flag then, nor why it is failing.  This suggests that there may be another way to solve this that does not cause a remount failure.

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 7]
```diff
@@ -540,6 +540,20 @@ func (c *container) mountGeneric(mnt *mount.Point) (err error) {
 		}
 	}
 	_, err = c.rpcOps.Mount(source, dest, mnt.Type, flags, optsString)
+	// when using user namespace we always try to apply mount flags with
+	// remount, then if we get a permission denied error, we continue
+	// execution by ignoring the error and warn user if the bind mount
+	// need to be mounted read-only
+	if remount && err != nil && c.userNS {
+		if err.Error() == syscall.Errno(syscall.EPERM).Error() {
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/container_linux.go:553]: this is comparing the error strings. This should be done only as a last resort...

You can type-assert err (`err.(syscall.Errno)`) and then compare that with `syscall.EPERM`.

**Review by mem — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/engines/singularity/container_linux.go (hunk 7 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/container_linux.go:553]: It's the last resort, here `err` is of type `ServerError`

**Comment by DrDaveD** [comment]
The travis failure is unrelated to the change and transient and so could just be retried.

If MS_RDONLY is false, why is singularity even attempting a remount?  Is the failure then really because the kernel thinks it is trying to remount a read-only source as read-write, and that's not allowed when unprivileged?

**Comment by cclerget** [comment]
> If MS_RDONLY is false, why is singularity even attempting a remount?

To also apply flags like MS_NOSUID, MS_NODEV ...

> Is the failure then really because the kernel thinks it is try to remount a read-only source as read-write, and that's not allowed when unprivileged?

Unprivileged you need to pass some of original flags (like MS_RDONLY) if you want to apply additional flags, so if source is read-only, you need to pass `-B /mnt:/mnt:ro` to add MS_RDONLY and if you want to also add `MS_NOSUID|MS_NODEV` with remount.

It would fail too :
```
mount -t tmpfs tmpfs -onoexec /mnt
singularity exec -u -B /mnt docker://alpine
```

**Comment by DrDaveD** [comment]
> so if source is read-only, you need to pass -B /mnt:/mnt:ro to add MS_RDONLY and if you want to also add MS_NOSUID|MS_NODEV with remount.

We can't expect users to add :ro, but should singularity be detecting if the source is mounted read-only and if so add the MS_RDONLY flag?

**Comment by cclerget** [comment]
> We can't expect users to add :ro, but should singularity be detecting if the source is mounted read-only and add the MS_RDONLY flag?

Yes we should, but definitively not in this PR, it involves too much changes and also need to handle MS_NOEXEC case

**Comment by DrDaveD** [comment]
> Yes we should, but definitively not in this PR

That makes sense.  Shall we consider this version final then for 3.3.0?

**Comment by cclerget** [comment]
> Shall we consider this version final then for 3.3.0?

Yep, re-requested review from @mem

File: internal/pkg/runtime/engines/singularity/container_linux.go (hunk 7 above)
Comment (mem) [inline internal/pkg/runtime/engines/singularity/container_linux.go:553]:
```suggestion
		// this needs to compare error strings because we are dropping
		// the original error value in the RPC call. In order to keep
		// the original error values, we would have to add them to the
		// corresponding struct passed over RPC and add the necessary
		// GOB encoding / decoding functions.
		if err.Error() == syscall.Errno(syscall.EPERM).Error() {
```

**Review by mem — APPROVED** [review]
Thanks!

**Comment by DrDaveD** [comment]
The failing test in travis appears to be intermittent, please re-run the test.
