### PR TITLE
Set apex log level to correspond with sylog log level

### LINKED ISSUE #4586: 3.4.1 warnings about xattr should be turned off
### Version of Singularity:

```
singularity version 3.4.1-1.2.el7
```
### Expected behavior

I expect singularity to be silent if I use the -s flag and to print a minor number of warning without. In 3.2.1 with -s it executes and returns
```
-bash-4.2$ /cvmfs/atlas.cern.ch/repo/containers/sw/singularity/testing/x86_64-el7/3.2.1/bin/singularity -s build --sandbox /home/aforti/docker_atlas_analysisbase/image docker://atlas/analysisbase
-bash-4.2$ 
```

### Actual behavior

when building centos images singularity prints out an enormous level of warnings about ignoring xattr on files. It is only 3 on the basic OS image (which is already annoying) but with more complex  images I have >12k warnings polluting the stdout. This should really be hidden behind debugging and even there I'm afraid it is polluting, maybe not for a dev, but certainly for an admin. 

### Steps to reproduce this behavior
```
export SINGULARITY_CACHEDIR=docker_atlas_analysisbase/cache
export SINGULARITY_TMPDIR=docker_atlas_analysisbase
export SINGULARITY_DISABLE_CACHE=true

singularity -s build --sandbox /home/aforti/docker_atlas_analysisbase/image docker://atlas/analysisbase > 3.4.1-test.sing.silent.txt
```
I've attached the output of this command
[3.4.1-test.sing.silent.txt](https://github.com/sylabs/singularity/files/3701702/3.4.1-test.sing.silent.txt)

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

rpm from epel-testing

### PR DESCRIPTION
**Pull request by DrDaveD**
## Description of the Pull Request (PR):

Make the apex log level, used by umoci, track sylog log levels.  The apex warning level is too verbose, so this only enables that when the sylog level is verbose and by default sets the level to errors only.

This PR is submitted against release-3.4 because sandbox builds on the master branch are broken (at least for docker://centos:7) at the moment, but the PR applies equally to master.

### This fixes or addresses the following GitHub issues:

 - Fixes #4586

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by dtrudg** [comment]
Thanks @DrDaveD - I'm afraid at present without further investigation I can't endorse hiding all apex warnings when we are expecting other warnings to show.

The `selinux` xattr warnings may be just noise to most, but there are other parts of the umoci code where Warn may display something important.

I agree the logelevel should be set to errors only for `--silent` though.

File: internal/pkg/sylog/sylog.go [hunk 1]
```diff
@@ -158,6 +157,14 @@ func Debugf(format string, a ...interface{}) {
 // SetLevel explicitly sets the loggerLevel
 func SetLevel(l int) {
 	loggerLevel = messageLevel(l)
+	// the apex log (for umoci) is too noisy at warn level, avoid that
+	if loggerLevel < verbose {
```
Comment (dtrudg) [inline internal/pkg/sylog/sylog.go]: I'd be happy to take this as a PR into 3.4.2 if the apex loglevel is matched to the sylog level - i.e. hide the apex warnings on `-s` but leave them otherwise. I think we'd need a lot more confidence that umoci was only ever using 'warn' for unimportant things to do what's currently in place in this PR.

**Review by dtrudg — CHANGES_REQUESTED** [review]

File: internal/pkg/sylog/sylog.go (hunk 1 above)
Comment (DrDaveD) [reply internal/pkg/sylog/sylog.go]: Alright, I'll make that change.  It will still address the request in #4578.

**Comment by DrDaveD** [comment]
The sandbox build failure I referred to in the submission is detailed in issue #4593

File: internal/pkg/sylog/sylog.go (hunk 1 above)
Comment (DrDaveD) [reply internal/pkg/sylog/sylog.go]: What about the quiet level?  There's no corresponding level in apex.  Can I have that silence apex warnings?

File: internal/pkg/sylog/sylog.go [hunk 2]
```diff
@@ -158,6 +158,17 @@ func Debugf(format string, a ...interface{}) {
 // SetLevel explicitly sets the loggerLevel
 func SetLevel(l int) {
 	loggerLevel = messageLevel(l)
+	// set the apex log level, for umoci
+	if loggerLevel <= log {
+		// quiet or silent options
```
Comment (dtrudg) [inline internal/pkg/sylog/sylog.go]: I don't think we want to do this for quiet - a warning isn't normal output.

`-q, --quiet     suppress normal output`

**Review by dtrudg — CHANGES_REQUESTED** [review]

File: internal/pkg/sylog/sylog.go (hunk 1 above)
Comment (dtrudg) [reply internal/pkg/sylog/sylog.go]: I don't think so - sorry for the delay - see below

**Review by dtrudg — APPROVED** [review]

**Comment by dtrudg** [comment]
LGTM - thanks @DrDaveD !
