### PR TITLE
Protect additional e2e tests needing UserNS, overlay with require.xxx

### LINKED ISSUE #4904: RHEL6 failure - e2e OCI test needs overlay
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.2
```

### Actual behavior

```
--- FAIL: TestE2E/PAR/OCI/basic (0.25s)
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci mount /tmp/stest.490211207/test.sif /tmp/stest.490211207/bundle-728097247"
                singularitycmd.go:653: 
                    "/usr/local/bin/singularity --debug oci mount /tmp/stest.490211207/test.sif /tmp/stest.490211207/bundle-728097247" output:
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      persistentPreRunE()           Singularity version: 3.5.2+141-g7742e82
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      handleConfDir()               /root/.singularity already exists. Not creating.
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      Init()                        Image format detection
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      Init()                        Check for sandbox image format
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      Init()                        sandbox format initializer returned: not a directory image
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      Init()                        Check for sif image format
                    ESC[0mDEBUG   ESC[0m[U=0,P=16049]      Init()                        sif image format detected
                    ESC[31mFATAL   ESC[0m[U=0,P=16049]      func39()                      failed to create overlay: failed to mount /tmp/stest.490211207/bundle-728097247/overlay: no such device
                    
                singularitycmd.go:653: got 255 as exit code and was expecting 0: exit status 255
                    waiting for command "/usr/local/bin/singularity --debug oci mount /tmp/stest.490211207/test.sif /tmp/stest.490211207/bundle-728097247"
                    github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func1
                        github.com/sylabs/singularity@/e2e/internal/e2e/singularitycmd.go:628
                    github.com/sylabs/singularity/e2e/internal/e2e.Privileged.func1
                        github.com/sylabs/singularity@/e2e/internal/e2e/priv_linux.go:53
                    github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func2
                        github.com/sylabs/singularity@/e2e/internal/e2e/singularitycmd.go:653
                    runtime.goexit
                        runtime/asm_amd64.s:1357
                oci.go:65: failed to mount OCI bundle image
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci create -b /tmp/stest.490211207/bundle-728097247 d20620e0-55fd-4557-a03e-af90bec89432"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci start d20620e0-55fd-4557-a03e-af90bec89432"
                require.go:46: cgroups disabled
                require.go:46: cgroups disabled
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci start d20620e0-55fd-4557-a03e-af90bec89432"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci exec d20620e0-55fd-4557-a03e-af90bec89432 id"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci kill -t 2 d20620e0-55fd-4557-a03e-af90bec89432 KILL"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci delete d20620e0-55fd-4557-a03e-af90bec89432"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci state d20620e0-55fd-4557-a03e-af90bec89432"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci kill d20620e0-55fd-4557-a03e-af90bec89432"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci start d20620e0-55fd-4557-a03e-af90bec89432"
                singularitycmd.go:653: Running command "/usr/local/bin/singularity --debug oci umount /tmp/stest.490211207/bundle-728097247"
```

### What OS/distro are you running

```
RHEL6
```

### LINKED ISSUE #4907: RHEL6 - e2e failing needing namespace support
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.2
```

### Actual behavior

```
                --- FAIL: TestE2E/PAR/ACTIONS/action_URI/ExecTrueDockerUserns (5.14s)
                    actions.go:648: Running command "/usr/local/bin/singularity --debug exec --userns docker://busybox:latest true"
                    actions.go:648: 
...

 --- FAIL: TestE2E/PAR/ACTIONS/action_URI/ExecTrueLibraryUserns (1.38s)
                    actions.go:648: Running command "/usr/local/bin/singularity --debug exec --userns library://busybox:latest true"
                    actions.go:648: 

...

--- FAIL: TestE2E/PAR/ACTIONS/action_URI/ExecTrueOrasUserns (0.02s)
                    actions.go:648: Running command "/usr/local/bin/singularity --debug exec --userns oras://localhost:5000/oras_test_sif:latest true"
                    actions.go:648: 

```

 --- FAIL: TestE2E/PAR/ACTIONS/action_URI/ExecFalseOrasUserns (0.02s)
                    actions.go:648: Running command "/usr/local/bin/singularity --debug exec --userns oras://localhost:5000/oras_test_sif:latest false"
                    actions.go:648: 
```

### What OS/distro are you running

```
RHEL6
```

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Protect additional e2e tests needing UserNS, overlay with require.xxx

### This fixes or addresses the following GitHub issues:

 - Fixes #4904 
 - Fixes #4907

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by ikaneshiro — APPROVED** [review]

File: e2e/actions/actions.go [hunk 1]
```diff
@@ -645,6 +645,14 @@ func (c actionTests) RunFromURI(t *testing.T) {
 	}
 
 	for _, tt := range tests {
+
+		for _, a := range tt.argv {
```
Comment (cclerget) [inline e2e/actions/actions.go]: Could you use profile instead ?

**Review by cclerget — CHANGES_REQUESTED** [review]

File: e2e/actions/actions.go (hunk 1 above)
Comment (dtrudg) [reply e2e/actions/actions.go]: Yeah - that's better - I'll do that

**Review by cclerget — APPROVED** [review]
LGTM
