### PR TITLE
Detect current PID user-namespace in overlay checks #5315

### LINKED ISSUE #5315: %test fails in a fakeroot image build
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
```
3.6.0~rc.3.1-1.el7
```

### Expected behavior
building a image file
### Actual behavior
```
INFO:    Adding environment to container
INFO:    Adding runscript
INFO:    Adding testscript
INFO:    Running testscript
FATAL:   container creation failed: mount overlay->/var/singularity/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /var/singularity/mnt/session/final: operation not permitted
FATAL:   While performing build: failed to execute %test script: exit status 255
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Use lolcow.def from the documentation and append this %test section:
```
%test
    echo "space left:"
    df -h
```
Then run ```singularity build --fakeroot lolcow.sif lolcow.def```. It works without the %test section and fails with the section.

### What OS/distro are you running

```
$ cat /etc/os-release


```
```
NAME="Scientific Linux"
VERSION="7.7 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.7"
PRETTY_NAME="Scientific Linux 7.7 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.7:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

### How did you install Singularity

rpm build from source of 3.6.0 rc.3 with the patch from pr #5313 applied.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When considering overlay support in `internal/pkg/runtime/engine/singularity/prepare_linux.go` detect whether the current process is running in a user namespace, rather than looking only at OCIConfig.

This is required with the changes in 3.6 that mean the build engine is not separate, and we are running builds, and any contained tests, under the singularity engine. Failure to do this means that `%test` blocks in a build will fail due to attempting to use overlay.

### This fixes or addresses the following GitHub issues:

 - Fixes #5315

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engine/singularity/prepare_linux.go [hunk 1]
```diff
@@ -1009,22 +1010,31 @@ func (e *EngineOperations) setSessionLayer(img *image.Image) error {
...
-				return nil
-			}
-			if !writableImage {
-				sylog.Debugf("Using underlay layer: user namespace requested")
-				e.EngineConfig.SetSessionLayer(singularityConfig.UnderlayLayer)
-				return nil
-			}
-			sylog.Debugf("Not attempting to use overlay or underlay: writable flag requested")
+			userNS = true
+			break
```
Comment (tri-adam) [inline internal/pkg/runtime/engine/singularity/prepare_linux.go]: If `userNS` is `true`, we don't need to iterate in this loop. To kill two birds with one stone, how about:

```
	for _, ns := range e.EngineConfig.OciConfig.Linux.Namespaces; !userNS {
		if ns.Type == specs.UserNamespace {
			userNS = true
		}
	}
```

**Review by tri-adam — COMMENTED** [review]
LGTM, just one suggestion to simplify the code slightly.

**Review by cclerget — APPROVED** [review]
LGTM

File: internal/pkg/runtime/engine/singularity/prepare_linux.go (hunk 1 above)
Comment (dtrudg) [reply internal/pkg/runtime/engine/singularity/prepare_linux.go]: Adding `; !userNS` isn't valid on a `for xxx := range xxx`

Will add the extra if. Didn't as the loop is going to be over one item (mount namespace) in most cases, so not much perf benefit, but I agree it shows the intent.

**Review by tri-adam — APPROVED** [review]
