### PR TITLE
Filter all unauthorized capabilities after user/group checks

### LINKED ISSUE #3790: capabilities - warning message printed even if group capability is configured
## Version of Singularity:

3.2.0 and later

### Expected behavior

No Warning message as the Capability exists via the group. 

### Actual behavior

root@ibmblade05:~# /opt/singularity-3.2.0/bin/singularity capability add --group users net_raw

root@ibmblade05:~# cat /opt/singularity-3.2.0/etc/singularity/capability.json 
{
	"groups": {
		"users": [
			"CAP_NET_RAW"
		]
	}
}

root@ibmblade05:~# su - anorrie
ibmblade05:/data/home/anorrie> /opt/singularity-3.2.0/bin/singularity run -B /cgv --add-caps net_raw /tmp/g2_singularity_test.db7
**WARNING: not authorized to add capability: CAP_NET_RAW**
anorrie@ibmblade05:~$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_req=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_req=2 ttl=64 time=0.029 ms
^C
--- localhost ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.029/0.032/0.036/0.006 ms

### Steps to reproduce behavior

Configure group capability as root/sudo:
singularity capability add --group users net_raw

Run singularity as regular user (but in group with cap) and add capability:
singularity run --add-caps net_raw ...

Warning is output, but the capability still works as it was add in the Group Capability:
WARNING: not authorized to add capability: CAP_NET_RAW

The problem file is singularity/internal/pkg/runtime/engines/singularity/prepare_linux.go
which prints the warning right after checking the User Capability but before checking the Group Capability

authorizedCaps, unauthorizedCaps := capConfig.CheckUserCaps(pw.Name, caps)
        if len(unauthorizedCaps) > 0 {
                sylog.Warningf("not authorized to add capability: %s", strings.Join(unauthorizedCaps, ","))
        }
        if len(authorizedCaps) > 0 {
                sylog.Debugf("User capabilities %s added", strings.Join(authorizedCaps, ","))
                commonCaps = authorizedCaps
        }

        groups, err := os.Getgroups()
        if err != nil {
                return err
        }

        for _, g := range groups {
                gr, err := user.GetGrGID(uint32(g))
                if err != nil {
                        sylog.Debugf("Ignoring group %d: %s", g, err)
                        continue
                }
                authorizedCaps, _ := capConfig.CheckGroupCaps(gr.Name, caps)
                if len(authorizedCaps) > 0 {
                        sylog.Debugf("%s group capabilities %s added", gr.Name, strings.Join(authorizedCaps, ","))
                        commonCaps = append(commonCaps, authorizedCaps...)
                }
        }

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fix message when warning user about unauthorized capabilities which actually reports false warning if a user has the permission to add a capability for an authorized group

**This fixes or addresses the following GitHub issues:**

- Fixes #3790

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engines/singularity/prepare_linux.go [hunk 1]
```diff
@@ -96,14 +97,31 @@ func (e *EngineOperations) prepareUserCaps() error {
...
+			commonUnauthorizedCaps = append(commonUnauthorizedCaps, unauthorizedCaps...)
+		}
 	}
 
 	commonCaps = capabilities.RemoveDuplicated(commonCaps)
+	commonUnauthorizedCaps = capabilities.RemoveDuplicated(commonUnauthorizedCaps)
+
+	// remove authorized capabilities from unauthorized capabilities list
+	// to end with the really unauthorized capabilities
+	for _, cap := range commonCaps {
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/prepare_linux.go]: "cap" is the built-in function to obtain a slice's capacity. Better use something else just to avoid confusion.

File: internal/pkg/runtime/engines/singularity/prepare_linux.go [hunk 2]
```diff
@@ -96,14 +97,31 @@ func (e *EngineOperations) prepareUserCaps() error {
...
+		for i := len(commonUnauthorizedCaps) - 1; i >= 0; i-- {
+			if commonUnauthorizedCaps[i] == cap {
+				commonUnauthorizedCaps = append(commonUnauthorizedCaps[:i], commonUnauthorizedCaps[i+1:]...)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/prepare_linux.go:119]: is there an expectation that this list contains duplicates? Because you could break out of the loop once you find one element matching the capability you are looking for.

**Review by mem — CHANGES_REQUESTED** [review]
LGTM, just a couple of minor things.

File: internal/pkg/runtime/engines/singularity/prepare_linux.go (hunk 1 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/prepare_linux.go]: will fix

File: internal/pkg/runtime/engines/singularity/prepare_linux.go (hunk 2 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/prepare_linux.go:119]: no this is a mistake

**Review by mem — APPROVED** [review]
