### PR TITLE
Tidy up conffile handling

### LINKED ISSUE #4117: Inconsistent handling of configuration file paths
## Version of Singularity:

3.3 (2a39c1fba60303bd40b5b8d3358e7290739431a8)

### Expected behavior

All the configuration files are handled in the same way.

### Actual behavior

Some paths to configuration files are recorded at build time and some are computed dynamically at runtime. Obtaining those paths is handled in different ways, too.

### Steps to reproduce behavior

Requires examining source code.

### PR DESCRIPTION
**Pull request by mem**
**Description of the Pull Request (PR):**

Make the handling of configuration file paths uniform by recording all of them at build time and accessing the values thru buildcfg.

**This fixes or addresses the following GitHub issues:**

- Fixes #4117

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by gvallee** [comment]
As per earlier discussions, everything using `buildcfg` is supposed to be in an internal package. This PR does the exact opposite and I do not understand at the moment why it is necessary to go against that rule; or even better, we should address the overall question of clarifying the rules: #3995

File: pkg/util/nvidia/paths.go [hunk 1]
```diff
@@ -60,11 +60,10 @@ func nvidiaContainerCli(args ...string) ([]string, error) {
 }
 
 // nvliblist returns libraries listed in nvliblist.conf which is located in nvidiaDir.
```
Comment (sashayakovtseva) [inline pkg/util/nvidia/paths.go]: Should you update the comment since now file path is accepted, not directory?

File: cmd/internal/cli/actions_linux.go [hunk 2]
```diff
@@ -133,7 +133,7 @@ func execStarter(cobraCmd *cobra.Command, image string, args []string, name stri
 
 	engineConfig := singularityConfig.NewConfig()
 
-	configurationFile := files.GetSysConfigFile()
+	configurationFile := syfs.GetSysConfigFile()
```
Comment (sashayakovtseva) [inline cmd/internal/cli/actions_linux.go]: Can't you use `buildcfg.SINGULARITY_CONF_FILE` here?

File: cmd/singularity/cli_test.go [hunk 3]
```diff
@@ -52,7 +52,7 @@ func run(m *testing.M) int {
 	cmdPath = path
 
 	// Ensure config is installed
-	if fi, err := os.Stat(files.GetSysConfigFile()); err != nil {
+	if fi, err := os.Stat(syfs.GetSysConfigFile()); err != nil {
```
Comment (sashayakovtseva) [inline cmd/singularity/cli_test.go]: Same here, `buildcfg.SINGULARITY_CONF_FILE` can be used.

File: cmd/singularity/security_test.go [hunk 4]
```diff
@@ -91,7 +91,7 @@ func testSecurityPriv(t *testing.T) {
 
 // testSecurityConfOwnership tests checks on config files ownerships
 func testSecurityConfOwnership(t *testing.T) {
-	configFile := files.GetSysConfigFile()
+	configFile := syfs.GetSysConfigFile()
```
Comment (sashayakovtseva) [inline cmd/singularity/security_test.go]: Same here. Don't really know if a function call is intended, but `buildcfg.SINGULARITY_CONF_FILE` can be used

File: pkg/syfs/syfs.go [hunk 5]
```diff
@@ -68,3 +69,9 @@ func ConfigDirForUsername(username string) (string, error) {
 
 	return filepath.Join(u.HomeDir, singularityDir), nil
 }
+
+// GetSysConfigFile returns the path the Singularity system
+// configuration file
```
Comment (sashayakovtseva) [inline pkg/syfs/syfs.go]: No period at the end of documentation comment.

File: pkg/syfs/syfs.go [hunk 6]
```diff
@@ -68,3 +69,9 @@ func ConfigDirForUsername(username string) (string, error) {
...
+func GetSysConfigFile() string {
```
Comment (sashayakovtseva) [inline pkg/syfs/syfs.go]: Since we have `SINGULARITY_CONF_FILE` now I wonder whether this function is useful at all.

File: cmd/singularity/security_test.go (hunk 4 above)
Comment (gvallee) [reply cmd/singularity/security_test.go]: @sashayakovtseva FYI, that was part of the initial work: the code was full of `buildcfg.SINGULARITY_CONF_FILE = "string"` and at one spot it was not correctly used at all. So a function seems more useful.

File: cmd/internal/cli/actions_linux.go (hunk 2 above)
Comment (gvallee) [reply cmd/internal/cli/actions_linux.go]: @sashayakovtseva FYI, that was part of the initial work: the code was full of buildcfg.SINGULARITY_CONF_FILE = "string" and at one spot it was not correctly used at all. So a function seems more useful.

File: pkg/syfs/syfs.go (hunk 6 above)
Comment (gvallee) [reply pkg/syfs/syfs.go]: @sashayakovtseva  Here this is the system level configuration file and as i said we found places where it was *not* used correctly.

File: cmd/internal/cli/actions_linux.go (hunk 2 above)
Comment (sashayakovtseva) [reply cmd/internal/cli/actions_linux.go]: I see there is still `buildcfg. NVIDIALIBS_FILE`, so mixing func and consts seems strange.

File: pkg/syfs/syfs.go (hunk 6 above)
Comment (sashayakovtseva) [reply pkg/syfs/syfs.go]: `SINGULARITY_CONF_FILE ` is defined during make and equals to `SINGULARITY_CONFDIR /singularity.conf`

Comment (gvallee) [reply pkg/syfs/syfs.go]: Yes i found it an updated my comment

**Comment by gvallee** [comment]
The description of the PR is misleading and this is actually 2 PRs in one:
- move the code from the `internal/pkg/util/fs/files` package to `pkg/syfs` packages meaning that with this PR, the manipulation of the system configuration file is now assumed to be exposed to other packages and users in general (it does not mean they will have the right to do on a given system but it will be exposed),
- make sure that more access to configuration data is done in a uniform manner

File: cmd/internal/cli/actions_linux.go (hunk 2 above)
Comment (gvallee) [reply cmd/internal/cli/actions_linux.go]: Good point and i do not know what was @mem intent atm

File: pkg/util/nvidia/paths.go (hunk 1 above)
Comment (mem) [reply pkg/util/nvidia/paths.go]: ah, thanks

File: cmd/internal/cli/actions_linux.go (hunk 2 above)
Comment (mem) [reply cmd/internal/cli/actions_linux.go]: > Can't you use `buildcfg.SINGULARITY_CONF_FILE` here?

I can, yes.

As noted in one of the commits in this PR: "Keep the GetSysConfigFile function just to make the code look a little cleaner." It is unusual for Go code to have identifiers which are all caps.

File: cmd/singularity/cli_test.go (hunk 3 above)
Comment (mem) [reply cmd/singularity/cli_test.go]: > Same here, `buildcfg.SINGULARITY_CONF_FILE` can be used.

it can be used everywhere, yes, because syfs.GetSysConfigFile() is simply "return buildcfg.SINGULARITY_CONF_FILE".

File: pkg/syfs/syfs.go (hunk 5 above)
Comment (mem) [reply pkg/syfs/syfs.go]: done.

File: pkg/syfs/syfs.go (hunk 6 above)
Comment (mem) [reply pkg/syfs/syfs.go]: Not sure what to do with this conversation.

I don't have a particular preference for having this function wrap buildcfg.SINGULARITY_CONF_FILE other than that's a mouthful and a little not Go-like (all caps, underscores).

Comment (mem) [reply pkg/syfs/syfs.go]: I updated the PR to do without this function. Personally I dislike the way it looks...

**Review by sashayakovtseva — APPROVED** [review]

**Comment by sashayakovtseva** [comment]
@mem LGTM
I understand your concern about ALL_CAPS, but imo that should be changed everywhere. 
Since now there are usages of ALL_CAPS, I suggest leaving it as it is now and possibly creating an issue to change ALL_CAPS to getters everywhere across the codebase.
