### PR TITLE
Fix cryptsetup hang when running from a container IPC namespace

### LINKED ISSUE #4059: Cryptsetup hangs if IPC namespace requested
## Version of Singularity:

master

### Expected behavior

Decrypt container and execute singularity command

### Actual behavior

Singularity command hangs

### Steps to reproduce behavior

`singularity shell --ipc --encryption-key <key> encrypted.sif`

Issue observed with instances as IPC namespace is automatically requested by instance.

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

For decryption step `cryptsetup` is actually run by RPC server, but the RPC server can potentially live in the container IPC namespace if `--ipc` is requested or use with instance, as `cryptsetup` requires to run in the host IPC namespace to work correctly, the execution of `cryptsetup` must be done in the host IPC namespace. This PR fixes that by joining the host IPC namespace before executing `cryptsetup` and returns to the container IPC namespace once `cryptsetup` command execution terminates.

**This fixes or addresses the following GitHub issues:**

- Fixes #4059

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by ikaneshiro — APPROVED** [review]
Lgtm

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 1]
```diff
@@ -599,7 +597,15 @@ func (c *container) mountImage(mnt *mount.Point) error {
 			return err
 		}
 
-		cryptDev, err := c.rpcOps.Decrypt(offset, path, key)
+		// pass the master processus ID only if a container IPC
```
Comment (schebro) [inline internal/pkg/runtime/engines/singularity/container_linux.go:600]: typo at "processus"
