### PR TITLE
Replace NO_SETUID_FIXUP with KEEP_CAPS

### LINKED ISSUE #4319: cant run ssh server properly inside a container
I first tried with NVIDIA's tensorflow image, then normal Ubuntu base image, and finally the SSH-enabled phusion's passenger-full image. All failed. So I would like to ask for help from singularity developers. If it helps anything, this is a email thread relating to this problem: https://groups.google.com/a/lbl.gov/d/topic/singularity/kjkPFsgd_t0/discussion

## Version of Singularity:

3.3.0

### Expected behavior
ssh server runs properly

### Actual behavior

can't login to the container. Running /usr/sbin/sshd -d reveals that i doesn't initialize authentication process:

```
/usr/sbin/sshd -d
debug1: sshd version OpenSSH_7.6, OpenSSL 1.0.2n  7 Dec 2017
debug1: private host key #0: ssh-rsa SHA256:EDWRBlyyVHfWKk/cAp2CI1GcnN1OLvxrSu8ay4jxQmM
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:mMeGj7V1XxyJSkmAKGqNsBYLqVq3C19n0fRkPnEGVpeM
debug1: private host key #2: ssh-ed25519 SHA256:lN7is7WPx95JBWUjcvj9GSsc44/dZ/X4xVTGJ5YL28M
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: inetd sockets after dupping: 3, 3
Connection from 172.19.8.14 port 51288 on 10.23.0.22 port 22 <========================= Login attempt
debug1: Client protocol version 2.0; client software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.8 pat OpenSSH* compat 0x04000000
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: permanently_set_uid: 105/65534 [preauth]
permanently_set_uid: was able to restore old [e]gid [preauth]
debug1: do_cleanup [preauth]
debug1: monitor_read_log: child log fd closed 
debug1: do_cleanup
debug1: Killing privsep child 50
debug1: audit_event: unhandled event 1
```

### Steps to reproduce behavior

#### Definition file (sshd.def):
```
Bootstrap: docker
From: phusion/passenger-full:1.0.6
# From: ubuntu:18.04
#From: nvidia/tensorflow:19.05-py3
#Registry: nvcr.io
IncludeCmd: yes

%environment
    export LANG=en_US.UTF-8

%post
    LANG=en_US.UTF-8
    echo $LANG UTF-8 > /etc/locale.gen
    apt-get install -y locales && update-locale --reset LANG=$LANG
    rm -f /etc/service/sshd/down
    # Regenerate SSH host keys. Passenger-docker does not contain any, so you
    # have to do that yourself. You may also comment out this instruction; the
    # init system will auto-generate one during boot.
    /etc/my_init.d/00_regen_ssh_host_keys.sh

%startscript
    /sbin/my_init --enable-insecure-key
```
#### Build

`singularity build --fakeroot sshd.sif sshd.def`

#### Run
```
singularity instance start -f --net --network-args="portmap=2222:22/tcp" ./sshd.sif sshd
INFO:    Convert SIF file to sandbox...
WARNING: underlay of /etc/localtime required more than 50 (129) bind mounts
*** Installing insecure SSH key for user root
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...

INFO:    instance started successfully

singularity shell instance://sshd
Singularity rootfs-938503987:/tmp> service ssh status
 * sshd is not running
Singularity rootfs-938503987:/tmp> service ssh start
 * Starting OpenBSD Secure Shell server sshd                                                                                                                                                                                                                                                                                                                                                                            [ OK ]
Singularity rootfs-938503987:/tmp> service ssh status
 * sshd is running
Singularity rootfs-938503987:tmp>
```
ssh -p 2222 -l  root localhost
Connection reset by 127.0.0.1 port 2222

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

`NO_SETUID_FIXUP` is propagated to container processes leading them to retain their capabilities when they switch to a non-zero UID/GID, it causes issues with some services like openssh server (see #4319)

### This fixes or addresses the following GitHub issues:

 - Fixes #4319 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by jmstover — APPROVED** [review]
Tested and verifed working. See #4319

File: cmd/starter/c/starter.c [hunk 1]
```diff
@@ -226,7 +226,7 @@ static int apply_container_privileges(struct privileges *privileges) {
      * and to set ambient capabilities. We can't use capset before changing uid/gid
      * because CAP_SETUID/CAP_SETGID could be already dropped
      */
-    if ( prctl(PR_SET_SECUREBITS, SECBIT_NO_SETUID_FIXUP|SECBIT_NO_SETUID_FIXUP_LOCKED) < 0 ) {
+    if ( prctl(PR_SET_SECUREBITS, SECBIT_KEEP_CAPS) < 0 ) {
```
Comment (dtrudg) [inline cmd/starter/c/starter.c:229]: Do we need KEEP_CAPS_LOCKED like we had _LOCKED for the FIXUP?

Comment (cclerget) [reply cmd/starter/c/starter.c:229]: No it was a misuse, we need to keep the bit only for the runtime stage 2 and reset it automatically after `execve`, it's only required for the switch of container UID/GID in this function to manipulate capabilities without getting a permission denied error.
