### PR TITLE
Remove the incomplete-downloaded cache if interrupted while pulling

### LINKED ISSUE #3776: cache is clocking re-downloading of images
## Version of Singularity:

3.3.0-rc1

### Expected behavior

If my previous pull was incomplete/interrupted - I should be able to pull again

### Actual behavior

INFO:    Use image from cache (Which was an incomplete download)

### Steps to reproduce behavior

```
$ singularity pull shub://michael-tn/mpi-hello-world:latest
```
While its downloading, interrupt the download
Run the pull command agian, you'll see
```
INFO:    Use image from cache
```

### LINKED ISSUE #3788: Interrupting a 'pull' will not delete the old image from cache
## Version of Singularity:

```
3.3.0-rc.1.29.g8900c2d22
```

### Expected behavior

After the interrupting the download, next time you download that image, it should restart. Not give you the half-downloaded image from cache.

### Actual behavior

```bash
$ singularity pull library://ubuntu:latest
# Press ctrl-c while downloading it

$ singularity pull library://ubuntu:latest
# and it will fail
```

<br>

Related to: #3776 

Also related to #3758, I think...

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

This PR fixes the issue when you pull a image, then interrupt the pull, then pull it again.

## This fixes or addresses the following GitHub issues:

- Fixes #3788 
- Fixes #3776 

<br>

### CODE REVIEW

File: internal/pkg/client/cache/library.go [hunk 1]
```diff
@@ -53,7 +55,7 @@ func (c *Handle) LibraryImageExists(sum, name string) (bool, error) {
 		return false, err
 	}
 	if cacheSum != sum {
-		return false, fmt.Errorf("cached file sum (%s) and expected sum (%s) does not match", cacheSum, sum)
+		return false, ErrCacheHashNotTheSame
```
Comment (ikaneshiro) [inline internal/pkg/client/cache/library.go]: Can we do the same in `oras.go` if it's returning an error for this case too

File: internal/pkg/client/cache/library.go [hunk 2]
```diff
@@ -6,13 +6,15 @@
...
 import (
-	"fmt"
+	"errors"
 	"os"
 	"path/filepath"
 
 	"github.com/sylabs/scs-library-client/client"
 )
 
+var ErrCacheHashNotTheSame = errors.New("hash does not match")
```
Comment (ikaneshiro) [inline internal/pkg/client/cache/library.go]: Maybe we should put this in `dir.go` since this error will now be part of the package API. Might also be worth calling it something like `ErrBadChecksum` so it's a little less verbose.

File: internal/app/singularity/pull.go [hunk 3]
```diff
@@ -311,6 +351,17 @@ func OciPull(imgCache *cache.Handle, name, imageURI, tmpDir string, ociAuth *oci
 	}
 	if !exists {
 		sylog.Infof("Converting OCI blobs to SIF format")
+
+		// monitor for OS signals and remove invalid file
+		c := make(chan os.Signal)
+		signal.Notify(c, os.Interrupt, syscall.SIGTERM)
+		go func(fileName string) {
```
Comment (ikaneshiro) [inline internal/app/singularity/pull.go]: Maybe we should start considering a general signal handler implementation. This is very similar to the signal handling in `build.go` and we can probably create a package to do what we want. I wouldnt let this block the PR, but make a tech debt issue if you dont want to address it in this PR

**Review by ikaneshiro — DISMISSED** [review]

File: internal/app/singularity/interrupt_cleanup.go [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+import (
+	"os"
+	"os/signal"
+	"syscall"
+
+	"github.com/sylabs/singularity/internal/pkg/sylog"
+)
+
+// InterruptCleanup will watch for a interrupt signal, if theres
```
Comment (gvallee) [inline internal/app/singularity/interrupt_cleanup.go]:
```suggestion
// InterruptCleanup will watch for a interrupt signal, if there's
```

**Review by gvallee — APPROVED** [review]
I just found a typo, otherwise LGTM. Thanks for implementing that.

File: internal/app/singularity/interrupt_cleanup.go (hunk 4 above)
Comment (mem) [inline internal/app/singularity/interrupt_cleanup.go]: please don't export unless you need it in a different package.

File: internal/app/singularity/interrupt_cleanup.go [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+// one detected, then it will remove all the specified file(s)
+func InterruptCleanup(files ...string) {
+	c := make(chan os.Signal)
```
Comment (mem) [inline internal/app/singularity/interrupt_cleanup.go]: the channel used to receive signal notifications should be buffered. A buffer size of 1 is enough in this case.

File: internal/app/singularity/pull.go [hunk 6]
```diff
@@ -68,11 +68,19 @@ func LibraryPull(imgCache *cache.Handle, name, ref, transport, fullURI, libraryU
...
+	} else if err != nil {
 		return fmt.Errorf("unable to check if %s exists: %v", imagePath, err)
 	}
+
 	if !exists {
 		sylog.Infof("Downloading library image")
+		go InterruptCleanup(imagePath)
 
 		// call library download image helper
 		if err = library.DownloadImage(context.TODO(), libraryClient, imagePath, imageRef, downloadImageCallback); err != nil {
```
Comment (mem) [inline internal/app/singularity/pull.go:85]: since this is using a context, the signal handler should use it to notify the download process that it should stop. I would expect that if the download is stopped, this functions returns an error, and you can let the normal code flow continue from here (dealing with the error).

This also hints at the signal handler being installed "too low". It should probably be installed higher in the call stack so that you can pass a context down and handle cancellation in that way, as it is likely that all clients need the same handling.

**Review by mem — DISMISSED** [review]

**Review by mem — COMMENTED** [review]
Removing my request for changes, but not approving.

**Comment by jscook2345** [comment]
@mem @gvallee 

Can we dismiss the approving review if this fix will be postponed? I don't want anyone to accidentally merge it seeing it was approved. Thanks!

File: internal/app/singularity/pull.go (hunk 6 above)
Comment (GodloveD) [reply internal/app/singularity/pull.go:85]: This is a good idea, but I think it should be added as an additional improvement (see #3899).  Since this is fixing a bug, I think it can be added as it already is, and the context can be fixed later.
