### PR TITLE
Respect definition section args

### LINKED ISSUE #2260: Allow users to specify their own shebangs in runscript and startscript
## Version of Singularity:

3.0.0

### Expected behavior

Singularity should parse the first line of a `runscript` or `startscript` to see if the first non-whitespace characters are `#!`. If this is the case, it should use that line as the shebang and not the default `#!/bin/sh`.

### Actual behavior

The default shebang, `#!/bin/sh`, is always prepended to the `runscript` or `startscript`.
```
ian@T440s:test$ singularity inspect -r test.sif

#!/bin/sh

#!/usr/bin/env python
print("Uh-oh, there's a snake in my container")
```

### Steps to reproduce behavior

Build a container with a definiton that has a runscript with a shebang like the example below.

```
ian@T440s:test$ cat shebang.def 
Bootstrap: docker
From: python:latest

%runscript
#!/usr/bin/env python
print("Uh-oh, there's a snake in my container")
```

### LINKED ISSUE #2438: sections in def files need to accept /bin/sh options
## Version of Singularity:

3.0.1
### Expected behavior

In the 2.x series you can have a def file that looks like this.

```
Bootstrap: docker
From: busybox

%runscript -x
    echo blah
``` 

And the option will be added to the runscript like this:

```
$ singularity exec test.sif cat /.singularity.d/runscript
#!/bin/sh -x

    echo blah
```

This is a pretty important feature because it allows people to do things like change the interpreter of scripts with the `-c` option.

### Actual behavior

The 3.x series silently ignores `/bin/sh` options in the def file.

### LINKED ISSUE #2656: %post section not run with bash
## Version of Singularity:

3.0.2-119.ged79a2e1

### Expected behavior

Run commands under `%post -c /bin/bash` with bash.

### Actual behavior

Commands are run in `/bin/sh`, which is `dash` for Debian, Ubuntu, and possibly others.

### Steps to reproduce behavior

    Bootstrap: library
    From: debian:9

    %post -c /bin/bash
            echo "Running post section"
            echo $0
            dpkg -S $0
            function foo { echo; }
            echo "Bashism function defined"

Then run:

    sudo singularity build testbash.{img,def}

Output:

    INFO:    Starting build...
     40.36 MiB / 40.36 MiB [============================================================================================] 100.00% 14.01 MiB/s 2s
    INFO:    Running post scriptlet
    + echo Running post section
    Running post section
    + echo /bin/sh
    /bin/sh
    + dpkg -S /bin/sh
    diversion by dash from: /bin/sh
    diversion by dash to: /bin/sh.distrib
    dash: /bin/sh
    + function foo { echo
    /bin/sh: 4: function: not found
    FATAL:   post proc: exit status 127
    FATAL:   While performing build: while running engine: exit status 255

I can't change `function foo {` to `foo() {`, it's an external script which needs to be sourced.

### Hacky workaround

```bash
%post
    if test "$0" = "/bin/sh"; then
        echo "Elevating script to bash"
        sed -n -z '$p' "/proc/$$/cmdline" | sed 's/\x00/\n/g' | /bin/bash -ve
        exit $?
    fi

    echo "Running post section"

%runscript
    if test -x /bin/bash && test "$( readlink /proc/$$/exe )" != /bin/bash; then
        sed '1{ /^#!/d }' "$( sed -n -z '$p' "/proc/$$/cmdline" | sed 's/\x00/\n/g' )" | /bin/bash
        exit $?
    fi

    function foo() { local array=( "$@" ); echo ${array[2]}; }
    foo 0 1 2 3 4
```

### PR DESCRIPTION
**Pull request by ikaneshiro**
**Description of the Pull Request (PR):**

- Parser changes to allow for shebangs within token sections, includes some behavior improvements and new unit test cases
- Handling of shebangs for `runscript` and `startscript`, note in 2.x `test` script does not respect shebang
- Handling of args next to script sections for `setup`,`post`, `test`

**This fixes or addresses the following GitHub issues:**

- Fixes #2656
- Fixes #2438 
- Fixed #2260

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by gvallee — APPROVED** [review]
LGTM

File: internal/pkg/build/metadata.go [hunk 1]
```diff
@@ -92,10 +93,33 @@ func insertEnvScript(b *types.Bundle) error {
 	return nil
 }
 
+// runscript and starscript should use this function to properly handle args and shebangs
+func handleShebangScript(s types.Script) (string, string) {
+	shebang := "#!/bin/sh"
+	script := ""
+	if strings.HasPrefix(s.Script, "#!") {
```
Comment (cclerget) [inline internal/pkg/build/metadata.go]: Maybe trim whitespaces/newlines before using `HasPrefix` otherwise it won't detect shebang when section is written like :

```
%runscript

#!/bin/bash
...
```

File: internal/pkg/runtime/engines/imgbuild/create_linux.go [hunk 2]
```diff
@@ -216,3 +207,35 @@ func (engine *EngineOperations) copyFiles() error {
...
+	cmd.Stdout = os.Stdout
+	cmd.Stderr = os.Stderr
+
+	// pipe in script
+	stdin, err := cmd.StdinPipe()
+	if err != nil {
+		sylog.Fatalf("while creating %s proc pipe: %v", name, err)
+	}
+
+	go func() {
```
Comment (cclerget) [inline internal/pkg/runtime/engines/imgbuild/create_linux.go:234]: After `Start()` ?

**Review by cclerget — CHANGES_REQUESTED** [review]

**Review by cclerget — APPROVED** [review]
