### PR TITLE
Fix e2e seccomp security tests

### LINKED ISSUE #4326: E2E security tests always fail on Ubuntu 19.04
## Version of Singularity:

master.

### Expected behavior

All e2e tests should succeed.

### Actual behavior

```
--- FAIL: TestE2E (55.03s)
    e2e.go:18: Running E2E tests for Singularity
    suite.go:134: /tmp/stest.286284893/test.sif
    --- FAIL: TestE2E/SECURITY (5.29s)
        singularitycmd.go:630: Running command "/usr/local/bin/singularity pull --force --allow-unsigned /tmp/stest.286284893/ubuntu-ping.sif library://sylabs/tests/ubuntu_ping:v1.0"
        --- FAIL: TestE2E/SECURITY/singularitySecurityUnpriv (0.22s)
            --- FAIL: TestE2E/SECURITY/singularitySecurityUnpriv/SecComp_BlackList (0.17s)
                security.go:85: Running command "/usr/local/bin/singularity exec --security seccomp:./security/testdata/seccomp-profile.json /tmp/stest.286284893/ubuntu-ping.sif mkdir /tmp/foo"
                security.go:85: 
                    "/usr/local/bin/singularity exec --security seccomp:./security/testdata/seccomp-profile.json /tmp/stest.286284893/ubuntu-ping.sif mkdir /tmp/foo" output:
                    WARNING: seccomp requested but not enabled, seccomp library is missing or too old
                    mkdir: cannot create directory '/tmp/foo': File exists
                    
                security.go:85: got 1 as exit code and was expecting 159: exit status 1
                    waiting for command "/usr/local/bin/singularity exec --security seccomp:./security/testdata/seccomp-profile.json /tmp/stest.286284893/ubuntu-ping.sif mkdir /tmp/foo"
                    github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity.func1
                    	/home/gvallee/go/src/github.com/sylabs/singularity/e2e/internal/e2e/singularitycmd.go:605
                    testing.tRunner
                    	/usr/local/go/src/testing/testing.go:827
                    runtime.goexit
                    	/usr/local/go/src/runtime/asm_amd64.s:1333
FAIL
```

### Steps to reproduce behavior

`SINGULARITY_E2E=1 make -C builddir e2e-test`.

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Skip e2e security tests relying on seccomp if seccomp library was not installed at build time.

**This fixes or addresses the following GitHub issues:**

- Fixes #4326

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by sashayakovtseva — APPROVED** [review]

**Review by gvallee — APPROVED** [review]
LGTM

File: internal/pkg/test/tool/require/require.go [hunk 1]
```diff
@@ -11,6 +11,8 @@ import (
 	"syscall"
 	"testing"
 
+	"github.com/sylabs/singularity/internal/pkg/security/seccomp"
+
```
Comment (WestleyK) [inline internal/pkg/test/tool/require/require.go]: Extra newline?

**Review by WestleyK — APPROVED** [review]
Looks good to me! Thanks for fixing this :+1: _just one comment about a extra newline, not necessary._
