### PR TITLE
Fix multiple bind issues

### LINKED ISSUE #2700: Bind mounting a non-existent folder should fail or warn consistently
## Version of Singularity:

v3.1.0-rc2

### Expected behavior

Trying to bind-mount a nonexisting path should fail; it did in 2.x:

```
# singularity shell -B /does/not/exist:/mnt ubuntu.simg
ERROR  : There was an error binding the path /does/not/exist: No such file or directory
ABORT  : Retval = 255
```

### Actual behavior

Singularity starts instead of aborting. Warnings are produced, but inconsistently.

### Steps to reproduce behavior

If the destination path exists within the container, no warning is printed at all:

```
$ singularity shell -B /does/not/exist:/mnt docker://ubuntu
Singularity ubuntu_latest.sif:~>
```

If the destination path requires an overlay, there's a warning but the container starts:

```
$ singularity shell -B /does/not/exist:/this/doesnt/either docker://ubuntu
WARNING: skipping mount of /does/not/exist: no such file or directory
Singularity ubuntu_latest.sif:~>
```

### LINKED ISSUE #3530: singularity should either fulfil user requests or fail
## Version of Singularity:

singularity version 3.0.2-1.el7.centos

### Expected behavior

When a user requests something, singularity should either fulfil the request or fail (exit quickly with an error code). This should apply in general, but specifically I have noticed this is an issue for mounts.

### Actual behavior

Specifically for mounts, some versions print a warning, some versions just silently do not mount. 

### Steps to reproduce behavior

```bash
# should not run ls, should fail with message 'cannot mount /tmp/fake_file'
singularity exec -C --bind /tmp/fake_file docker://debian ls /tmp/fake_file

# If the current empty home mount is the intended behaviour (dubious), should fail with message 'Cannot mount in previously mounted directory'. 
singularity exec -C --bind "$HOME" docker://debian ls "$HOME/.bashrc"
```

### LINKED ISSUE #3691: Add AppendLibrariesPath to EngineConfig
## Version of Singularity:

3.2.1

### Desired behavior
It would be desirable to be able to append to the EngineConfig's LibrariesPath, for instance from a plugin callback. Currently the only functions exposed set LibrariesPath outright, which may cause undesired effects when used from within a plugin.

Currently to append to the LibrariesPath:
```
paths = []string{'libfoo.so', 'libbar.so'}
paths = append(cfg.GetLibrariesPath(), paths...)
cfg.SetLibrariesPath(paths)
```

Perhaps a better interface for general plugin use would be:
```
paths = []string{'libfoo.so', 'libbar.so'}
cfg.AppendLibrariesPath(paths)
```

### LINKED ISSUE #3797: Unable to bind directory
## Version of Singularity:

v3.1.1

### Expected behavior

Mount/bind a specific directory into the container

### Actual behavior

No error is reported and the mounted/bound directory is not present

### Steps to reproduce behavior

```
░ tgal@cca002:/sps/km3net/users/tgal  py-3.6
░ 18:57:27 > mkdir foo
░ tgal@cca002:/sps/km3net/users/tgal  py-3.6
░ 18:57:29 > touch foo/bar
░ tgal@cca002:/sps/km3net/users/tgal  py-3.6
░ 18:57:31 > singularity shell -B /sps/km3net/users/tgal/foo:/foo docker://debian:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:6f2f362378c5a6fd915d96d11dda1e0223ccf213bf121ace56ae0f6616ea1dc8
Copying config sha256:1e527d5c3b7223581365607ee5727f0aadbffa6bdff8ccc572e6a2a5eb749a1c
 579 B / 579 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /pbs/home/t/tgal/.singularity/cache/oci-tmp/118cf8f3557e1ea766c02f36f05f6ac3e63628427ea8965fb861be904ec35a6f/debian_latest.sif
INFO:    Image cached as SIF at /pbs/home/t/tgal/.singularity/cache/oci-tmp/118cf8f3557e1ea766c02f36f05f6ac3e63628427ea8965fb861be904ec35a6f/debian_latest.sif
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Singularity debian_latest.sif:/> ls /foo
ls: cannot access '/foo': No such file or directory
Singularity debian_latest.sif:/> ls
bin  boot  dev	environment  etc  home	lib  lib64  media  mnt	opt  proc  root  run  sbin  singularity  srv  sys  tmp	usr  var
Singularity debian_latest.sif:/>
```

and here is the system:

```
░ tgal@cca002:/sps/km3net/users/tgal  py-3.6
░ 19:01:06 > singularity --version
singularity version 3.1.1
░ tgal@cca002:/sps/km3net/users/tgal  py-3.6
░ 19:01:08 > uname -a
Linux cca002 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I am wondering since there is no error message whatsoever.

### LINKED ISSUE #3894: Show error when using --bind with --writable
## Version of Singularity:
3.2.1

### Expected behavior

Not being able to mount a requested path should throw an error and exit.

### Actual behavior

`--bind` argument is silently ignored. Even `--verbose` does not show anything.

### Steps to reproduce behavior

run `singularity shell --bind /mypath:/foo --writable /tmp/ubuntu` on an image/sandbox with non-existing /foo folder

Note: https://sylabs.io/guides/3.2/user-guide/bind_paths_and_mounts.html#a-note-on-using-bind-with-the-writable-flag does describe the issue but current behaviour is inconsistent and user-unfriendly. If a user request a binding and it cannot be served then this is an error, not a "well, let's just ignore this silently" which the user may find out much later after trying to write expensive to create results to the folder.

### LINKED ISSUE #4133: Extra mount of working directory if autofs is used
## Version of Singularity:

3.3.0 (self-built on Debian; installed via SPACK on CentOS)

### Expected behavior

Access to `../something` from the working directory is supposed to work, it did for 2.6.1.

2.6.1 did (still does) a single mount for `$HOME` even if the working directory `singularity` is called in is below that (Debian Stretch)

```
Filesystem                           Size  Used Avail Use% Mounted on                                                                                                                                                                                                                                                                                                    
OverlayFS                            1.0M     0  1.0M   0% /                                                                                                                                                                                                                                                                                                             
udev                                 7.9G     0  7.9G   0% /dev                                                                                                                                                                                                                                                                                                          
tmpfs                                7.9G     0  7.9G   0% /dev/shm                                                                                                                                                                                                                                                                                                      
/dev/sdb2                             20G  7.7G   12G  40% /etc/hosts                                                                                                                                                                                                                                                                                                    
fileserver:/export/home/username      69T   11T   59T  15% /home/username                                                                                                                                                                                                                                                                                                
/dev/sdb8                            687G  734M  687G   1% /local                                                                                                                                                                                                                                                                                                        
beegfs_nodev                         242T  196T   47T  81% /work                                                                                                                                                                                                                                                                                                         
/dev/sdb5                             16G   49M   16G   1% /tmp                                                                                                                                                                                                                                                                                                          
/dev/sdb6                            128G  517M  128G   1% /var/tmp                                                                                                                                                                                                                                                                                                      
tmpfs                                 16M  8.0K   16M   1% /etc/group                                                                                                                                                                                                                                                                                                    
```

### Actual behavior

3.3.0 does an extra mount for the working directory if `/home` is provided via autofs (symlink to `/.auto/home` - Debian Stretch):

```
Filesystem                                Size  Used Avail Use% Mounted on                                                                                                                                                                                                                                                                 
overlay                                    16M   12K   16M   1% /                                                                                                                                                                                                                                                                          
udev                                      7.9G     0  7.9G   0% /dev                                                                                                                                                                                                                                                                       
tmpfs                                     7.9G     0  7.9G   0% /dev/shm                                                                                                                                                                                                                                                                   
/dev/sdb2                                  20G  9.2G   11G  48% /etc/hosts                                                                                                                                                                                                                                                                 
fileserver:/export/home/username           69T   11T   59T  15% /home/username                                                                                                                                                                                                                                                             
/dev/sdb5                                  64G   98M   64G   1% /tmp                                                                                                                                                                                                                                                                       
/dev/sdb6                                 128G  4.1G  124G   4% /var/tmp                                                                                                                                                                                                                                                                   
fileserver:/export/home/username/workdir   69T   11T   59T  15% /.auto/home/username/workdir
tmpfs                                      16M   12K   16M   1% /etc/group                                                                                                                                                                                                                                                                 
```
3.3.0 doesn't do this if /home is a "real" mountpoint (CentOS - different cluster):

```
Filesystem      Size  Used Avail Use% Mounted on                                                                                                                                                                                                                                                                                                                           
overlay          16M   12K   16M   1% /                                                                                                                                                                                                                                                                                                                                    
devtmpfs         32G     0   32G   0% /dev                                                                                                                                                                                                                                                                                                                                 
tmpfs            32G     0   32G   0% /dev/shm                                                                                                                                                                                                                                                                                                                             
/dev/sda2        55G  2.8G   49G   6% /tmp                                                                                                                                                                                                                                                                                                                                 
beegfs_nodev     46T  5.2T   41T  12% /home/username                                                                                                                                                                                                                                                                                                                        
tmpfs            16M   12K   16M   1% /etc/group                                                                                                                                                                                                                                                                                                                           
```
### Steps to reproduce behavior

Make `/home` a symlink to` /.auto/home` (let autofs populate `.auto/`). Run `singularity` in a subtree of user's `$HOME`. Check with `df` what's mounted.

_Update: I don't think this is the same as #4132 or #4077 although it looks similar..._

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

- Provide current tag as part of system mount method to help to take decision according to mount point being processed in order to report errors, warning or logs :
  - Fixes #3894
  - Fixes #3797
  - Fixes #3530
  - Fixes #2700

- Fix issue when dealing with symbolic link for current working directory and rework checkMounted method :
  - Fixes  #4133

- Fix bind issues by taking original mount flags from the parent mount point associated to a bind mount, user namespace was affected by the issue when mounting a read-only mount point.

- Add `singularityConfig.AppendLibrariesPath` and `singularityConfig.SetFilesPath`/`singularityConfig.AppendFilesPath`
  - Fixes #3691

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: pkg/util/fs/proc/proc.go [hunk 1]
```diff
@@ -47,52 +49,139 @@ func ParseMountInfo(path string) (map[string][]string, error) {
...
+	SuperOptions []string
+}
 
-	resolved, err := filepath.EvalSymlinks(path)
-	if err != nil {
-		return parent, err
+// ParseMountInfoLine parses a mountinfo line and return
+// a MountInfoEntry containing parsed fields associated
+// to the line.
+func ParseMountInfoLine(line string) *MountInfoEntry {
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]: Can be unexported maybe?

File: pkg/util/fs/proc/proc.go [hunk 2]
```diff
@@ -47,52 +49,139 @@ func ParseMountInfo(path string) (map[string][]string, error) {
...
+	Fields       string
+	FSType       string
+	Source       string
+	SuperOptions []string
+}
 
-	resolved, err := filepath.EvalSymlinks(path)
-	if err != nil {
-		return parent, err
+// ParseMountInfoLine parses a mountinfo line and return
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]:
```suggestion
// ParseMountInfoLine parses a mountinfo line and returns
```

File: pkg/util/fs/proc/proc_linux_test.go [hunk 3]
```diff
@@ -73,11 +73,35 @@ var mountInfoData = `22 28 0:21 / /sys rw,nosuid,nodev,noexec,relatime shared:7
...
+func TestGetMountInfo(t *testing.T) {
 	test.DropPrivilege(t)
 	defer test.ResetPrivilege(t)
 
-	if _, err := ParseMountInfo("/proc/self/fakemountinfo"); err == nil {
+	_, err := GetMountInfoEntry("/bad/path")
+	if err == nil {
+		t.Fatalf("unexpected success while parsing bad path")
+	}
+	entries, err := GetMountInfoEntry("/proc/self/mountinfo")
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc_linux_test.go]: Maybe it is worth using tmp file here as well?
And then compare with exact expected result rather than with `hasRoot`.

File: pkg/util/fs/proc/proc_linux_test.go [hunk 4]
```diff
@@ -92,7 +116,7 @@ func TestParseMountInfo(t *testing.T) {
 	if err := tmpfile.Close(); err != nil {
 		t.Fatal(err)
 	}
-	m, err := ParseMountInfo(tmpfile.Name())
+	m, err := GetMountPointMap(tmpfile.Name())
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc_linux_test.go:251]: Just a suggestion, maybe it is better to have an exact expected result, e.g.
```
expect:=map[string][]string{
  "/": ["/dev", "/proc", ....]
...
}
```

By looking at this test one can easily understand what `GetMountPointMap` actually does.

File: pkg/util/fs/proc/proc.go [hunk 5]
```diff
@@ -47,52 +49,139 @@ func ParseMountInfo(path string) (map[string][]string, error) {
...
 
-	return parent, nil
+	if entry == nil {
+		return nil, fmt.Errorf("no parent mount point found")
+	}
+
+	return entry, nil
+}
+
+// ParentMount parses mountinfo and return the path of parent
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]:
```suggestion
// ParentMount parses mountinfo and returns the path of parent
```

File: pkg/runtime/engines/singularity/config/config.go [hunk 6]
```diff
@@ -483,12 +484,33 @@ func (e *EngineConfig) SetLibrariesPath(libraries []string) {
...
 func (e *EngineConfig) GetLibrariesPath() []string {
 	return e.JSON.LibrariesPath
 }
 
+// SetFilesPath sets files to bind in container (eg: --nv).
+func (e *EngineConfig) SetFilesPath(files []string) {
+	e.JSON.FilesPath = files
+}
+
+// AppendFilesPath adds files to bind in container (eg: --nv)
```
Comment (sashayakovtseva) [inline pkg/runtime/engines/singularity/config/config.go:504]:
```suggestion
// AppendFilesPath adds files to bind in container (eg: --nv).
```

File: pkg/util/fs/proc/proc.go (hunk 1 above)
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]: Btw not much point in pointer here

File: pkg/util/fs/proc/proc.go [hunk 7]
```diff
@@ -47,52 +49,139 @@ func ParseMountInfo(path string) (map[string][]string, error) {
...
+	// super block options field
+	entry.SuperOptions = strings.Split(fields[9+shift], ",")
+
+	return entry
+}
 
-	p, err := os.Open("/proc/self/mountinfo")
+// GetMountInfoEntry parses a mountinfo file and returns all
+// parsed entries as an array of MountInfoEntry.
+func GetMountInfoEntry(path string) ([]*MountInfoEntry, error) {
```
Comment (sashayakovtseva) [inline pkg/util/fs/proc/proc.go]: IMO no need for pointer here

File: internal/pkg/runtime/engine/singularity/container_linux.go [hunk 8]
```diff
@@ -45,22 +45,28 @@ var defaultCNIConfPath = filepath.Join(buildcfg.SYSCONFDIR, "singularity", "netw
...
+	sessionFsType    string
+	sessionSize      int
+	userNS           bool
+	pidNS            bool
+	utsNS            bool
+	netNS            bool
+	ipcNS            bool
+	mountInfoPath    string
+	mountInfoEntries []*proc.MountInfoEntry
+	lastMount        *lastMount
```
Comment (sashayakovtseva) [inline internal/pkg/runtime/engine/singularity/container_linux.go]: Also no need for pointer. Just a suggestion...

File: internal/pkg/runtime/engine/singularity/container_linux.go [hunk 9]
```diff
@@ -347,51 +344,60 @@ func (c *container) checkMounted(dest string) string {
...
+				return fmt.Errorf("while getting stat for %s: %s", source, err)
+			}
+
+			// retrieve original mount flags from the parent mount point
+			// where source is located on
+			flags, err = c.getBindFlags(source, flags)
+			if err != nil {
+				return fmt.Errorf("while getting mount flags for %s: %s", source, err)
+			}
+			// same them for the remount step
```
Comment (sashayakovtseva) [inline internal/pkg/runtime/engine/singularity/container_linux.go]:
```suggestion
			// save them for the remount step
```

**Review by sashayakovtseva — APPROVED** [review]
LGTM, regardless whether provided suggestions are applied.
