### PR TITLE
Fix test coverage issue for internal/pkg/sylog

### LINKED ISSUE #3324: Improve test coverage of internal/pkg/sylog
## Version of Singularity:

Improve test coverage of interal/pkg/sylog.

### Expected behavior

Get close to 100% coverage.

### Actual behavior

`
$ go test -coverprofile=coverage.out && go tool cover -func=coverage.out
?   	github.com/sylabs/singularity/internal/pkg/sylog	[no test files]
total:	(statements)	0.0%
`

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by gvallee**
**Description of the Pull Request (PR):**

Slightly change the sylog.go code to enable better testing and add unit tests

**This fixes or addresses the following GitHub issues:**

- Fixes #3324 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/sylog/sylog_test.go [hunk 1]
```diff
@@ -0,0 +1,288 @@
...
+
+func TestGetenv(t *testing.T) {
+	str := GetEnvVar()
+	expectedResult := "SINGULARITY_MESSAGELEVEL="
+	if str[:25] != expectedResult {
+		t.Fatalf("Test returned %s instead of %s", str[:25], expectedResult)
+	}
+}
+
+func TestStderrOutput(t *testing.T) {
```
Comment (jscook2345) [inline internal/pkg/sylog/sylog_test.go:334]: Would it be possible to replace os.Stderr with an interface to a buffer or writer and capture the output for testing? 

I think you can use a pipe as well. Here is an example I found: https://play.golang.org/p/fXpK0ZhXXf

Comment (gvallee) [reply internal/pkg/sylog/sylog_test.go:334]: Great idea and done.

**Review by jscook2345 — APPROVED** [review]
LGTM ☕️
