### PR TITLE
Oras Support for Actions and Build commands

### LINKED ISSUE #3655: Unable to run an OCI registry (ORAS) image with URI oras://
## Version of Singularity:

Master branch (build: daaf5e78dd108822285a85bc3557ff88fbf4b22b).

### Expected behavior

Should be able to run an OCI registry (ORAS) image with URI oras://
Example: `singularity run oras://registry.azurecr.io/example_sif:latest`

### Actual behavior

Error when trying to run an OCI registry (ORAS) image with URI oras://
`FATAL:   Unsupported transport type: oras`

### Steps to reproduce behavior

```
$ singularity run oras://registry.azurecr.io/example_sif:latest
FATAL:   Unsupported transport type: oras
```

### PR DESCRIPTION
**Pull request by ikaneshiro**
**Description of the Pull Request (PR):**

- Adds `oras://` transport to `actions` and `build` commands
- Adds basic e2e tests for these commands
  - I did not add unit tests because I need to setup a local registry to properly test this so e2e seemed most appropriate 

**This fixes or addresses the following GitHub issues:**

- Fixes #3655 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/util/uri/uri.go [hunk 1]
```diff
@@ -19,6 +19,8 @@ const (
 	HTTP = "http"
 	// HTTPS is the keyword for https ref
 	HTTPS = "https"
+	// Oras is the keyword for an oras ref
```
Comment (rherban) [inline internal/pkg/util/uri/uri.go:22]: I realize you're following the pattern already set out, but this comment (and the others) don't add any clarity IMO.

**Review by mem — COMMENTED** [review]
LGTM

File: internal/pkg/util/uri/uri.go (hunk 1 above)
Comment (ikaneshiro) [reply internal/pkg/util/uri/uri.go:22]: I agree that it is redundant, but since the constant names don't give any insight for their use I think this is ok to state their purpose. This is also a consequence of go formatting wanting a specific comment format for each exported constant e.g. 
```
// ConstName ...
ConstName = constVal
```

**Comment by rherban** [comment]
LGTM

**Review by mem — APPROVED** [review]
