### PR TITLE
Fix missing warning when using --writable-tmpfs with underlay.

### LINKED ISSUE #5307: Incompatible use of --fakeroot and --writable-tmpfs
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.6.0-rc3
```

### Expected behavior

Get a warning message mentioning that `--writable-tmpfs` is not possible and that it fallback to read-only mode

```
singularity shell --fakeroot --writable-tmpfs ...
WARNING: Ignoring --writable-tmpfs as it requires overlay support, fallback to read-only mode
>
```

### Actual behavior

No warning and fakeroot use underlay mounted as read-only

```
singularity shell --fakeroot --writable-tmpfs ...
>
```

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity
source.

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Fix missing warning when using --writable-tmpfs with underlay.

### This fixes or addresses the following GitHub issues:

 - Fixes #5307 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engine/singularity/prepare_linux.go [hunk 1]
```diff
@@ -1115,32 +1115,34 @@ func (e *EngineOperations) loadImages(starterConfig *starter.Config) error {
...
-				sylog.Warningf("Fallback to %s layer: %s", layer, err)
-
-				if e.EngineConfig.GetWritableTmpfs() {
-					e.EngineConfig.SetWritableTmpfs(false)
-					sylog.Warningf("--writable-tmpfs disabled due to sandbox filesystem incompatibility with overlay")
+		if e.EngineConfig.GetSessionLayer() == singularityConfig.OverlayLayer {
+			if err := overlay.CheckLower(img.Path); overlay.IsIncompatible(err) {
+				layer := singularityConfig.UnderlayLayer
+				if !e.EngineConfig.File.EnableUnderlay {
+					sylog.Debugf("Could not fallback to underlay, disabled by configuration ('enable underlay = no')")
```
Comment (dtrudg) [inline internal/pkg/runtime/engine/singularity/prepare_linux.go]: While we are looking at this code - I'd generally expect this to be a warning, not a debug message? 

Where we are relying on fallback to underylay for lustre, GPFS etc. then people should probably know clearly that things aren't going to work as they might expect when underlay is disabled?

Comment (cclerget) [reply internal/pkg/runtime/engine/singularity/prepare_linux.go]: fixed

**Review by dtrudg — APPROVED** [review]
