### PR TITLE
Mark GPFS as incompatible for overlay lower and upper

### LINKED ISSUE #5274: Sandbox failure (stale NFS file handle) on GPFS
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.3 from source
```

Behaviour:

Stock 3.5.3 will not run a sandbox container from a GPFS 5.0.4.1 filesystem. This error occurs whether `enable overlay` is `on` or `off`:

```
08:10 PM $ singularity run /gpfs/fs1/dave/sandbox
FATAL:   failed to open /bin/sh for inspection: read /bin/sh: stale NFS file handle
```

The following patch allows a container to be run, but *only* with `enable overlay = off`

```diff
--- a/pkg/util/fs/proc/proc.go
+++ b/pkg/util/fs/proc/proc.go
@@ -118,7 +118,7 @@ func parseMountInfoLine(line string) MountInfoEntry {
        // different from those shown in mountinfo, to fix that
        // we need to get major/minor directly from a stat call
        // on the corresponding mount point
-       if entry.FSType == "btrfs" || entry.FSType == "overlay" || entry.FSType == "ceph" {
+       if entry.FSType == "btrfs" || entry.FSType == "overlay" || entry.FSType == "ceph" || entry.FSType == "gpfs" {
                fi, err := os.Stat(entry.Point)
                if err == nil {
                        st := fi.Sys().(*syscall.Stat_t)
```

This allows...

```
08:12 PM $ sudo /usr/local/bin/singularity config global --set "enable overlay" "no"
dave@dev-rhel7:~/singularity
08:12 PM $ singularity run /gpfs/fs1/dave/sandbox
Singularity> 
```

But turn on overlay and it still fails:

```
08:13 PM $ sudo /usr/local/bin/singularity config global --set "enable overlay" "yes"
dave@dev-rhel7:~/singularity
08:13 PM $ singularity run /gpfs/fs1/dave/sandbox
FATAL:   failed to open /bin/sh for inspection: read /bin/sh: stale NFS file handle
```

Everything looks normal in the debug output, until the last minute:

```
VERBOSE [U=1000,P=19614]   startup()                     Execute stage 2
DEBUG   [U=1000,P=19614]   StageTwo()                    Entering stage 2
FATAL   [U=1000,P=19614]   StageTwo()                    failed to open /bin/sh for inspection: read /bin/sh: stale NFS file handle
DEBUG   [U=1000,P=19597]   startContainer()              stage 2 process reported an error, waiting status
DEBUG   [U=1000,P=19597]   Master()                      Child exited with exit status 255
```

There is no error/warning in `dmesg`, nor any GPFS logs.

Host `/proc/mountinfo` line for GPFS is:

```
120 40 0:41 / /gpfs/fs1 rw,relatime shared:99 - gpfs fs1 rw,seclabel
```

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

When used as the lowerdir for an overlay in a mount namespace as we do, GPFS gives an NFS stale file handle error. It does not trigger the code in the kernel overlayfs source that gives a more specific error and directly denies overlay mount for other filesystems such as lustre.

We need to blacklist GPFS from overlay lower and upper usage, until we can confirm exactly what is intended to be supported by IBM.

### This fixes or addresses the following GitHub issues:

 - Fixes #5274

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/util/fs/overlay/overlay.go [hunk 1]
```diff
@@ -33,6 +33,7 @@ const (
 	fuse         = 0x65735546
 	ecrypt       = 0xF15F
 	lustre       = 0x0BD00BD0
+	gpfs         = 0x47504653
```
Comment (dtrudg) [inline internal/pkg/util/fs/overlay/overlay.go:36]: This is the SUPER_MAGIC for GPFS. Handy list here: https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go

**Review by EmmEff — APPROVED** [review]
LGTM
