### PR TITLE
Fix current working directory mount check

### LINKED ISSUE #4587: Current working directory can override --home flag
### Version of Singularity:

```
3.4.1+400-gda0e39beb
```

### Expected behavior

List an empty directory:

```
mkdir /tmp/home && cd $HOME && singularity exec -H /tmp/home:$HOME image ls -la
```

### Actual behavior

The above command actually bind the host home directory instead of the one provided by `-H` flag

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Add a new RPC methods to Singularity RPC server to get file status for container mount so dev/ino are checked against the host one to determine if the current working is already mounted.
Also set `PWD` environment variable in `RunSingularity` to match the one set by `WithDir` operations.

### This fixes or addresses the following GitHub issues:

 - Fixes #4587 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: e2e/actions/regressions.go [hunk 1]
```diff
@@ -6,8 +6,11 @@
 package actions
 
 import (
+	"path/filepath"
 	"testing"
 
+	"github.com/sylabs/singularity/internal/pkg/util/fs"
+
```
Comment (WestleyK) [inline e2e/actions/regressions.go]: Extra newline?

```suggestion
```

File: internal/pkg/runtime/engine/singularity/rpc/args.go [hunk 2]
```diff
@@ -7,6 +7,7 @@ package rpc
 
 import (
 	"os"
+	"syscall"
```
Comment (WestleyK) [inline internal/pkg/runtime/engine/singularity/rpc/args.go:10]: Would it make more sense to use `golang.org/x/sys/unix` instead of `syscall`? Since `syscall` is deprecated.

_From the `syscall` godoc_
>Deprecated: this package is locked down. Callers should use the corresponding package in the golang.org/x/sys repository instead. That is also where updates required by new systems or versions should be applied. See https://golang.org/s/go1.4-syscall for more information.

**Review by WestleyK — COMMENTED** [review]
Looks good to me, just a couple small suggestions...

File: internal/pkg/runtime/engine/singularity/rpc/args.go (hunk 2 above)
Comment (cclerget) [reply internal/pkg/runtime/engine/singularity/rpc/args.go:10]: Yes but not in this PR, I will open a technical debt issue for that to remove `syscall` from Singularity codebase

**Review by WestleyK — APPROVED** [review]
Looks good to me! Thanks for also adding e2e tests for this issue!
