### PR TITLE
Run setup before file insertion.

### LINKED ISSUE #2111: 3.0: %setup section not running
## Version of Singularity:
v3.0.0-beta.1-28-gbfcda15

### Expected behavior
`%setup` section runs

### Actual behavior
`%setup` section *does not* run

### Steps to reproduce behavior
Using a simple Definition file

```
Bootstrap: docker
From: alpine:latest

%setup
  mkdir -p $SINGULARITY_ROOTFS/my_dir

%files
  /my_file /my_dir/my_file
```

From @bauerm97 :
```
Look at `src/pkg/build/build.go:171`
On that line, we're attempting to insert the %files
Then we run the `%post/%setup` script on line 184
So %setup actually hasn't run yet
This is actually sort of a regression
```

### PR DESCRIPTION
**Pull request by ikaneshiro**
This PR moves file insertion into the build engine in order to allow the `%setup` script to run beforehand. This will allow for directories to be made before file copying occurs.

fixes #2111

### CODE REVIEW

File: src/pkg/build/build.go [hunk 1]
```diff
@@ -281,17 +268,21 @@ func (b *Build) insertMetadata() (err error) {
...
-		pre.Stdout = os.Stdout
-		pre.Stderr = os.Stderr
-
-		sylog.Infof("Running pre scriptlet\n")
-		if err := pre.Start(); err != nil {
-			sylog.Fatalf("failed to start %%pre proc: %v\n", err)
-		}
-		if err := pre.Wait(); err != nil {
-			sylog.Fatalf("pre proc: %v\n", err)
+		if syscall.Getuid() == 0 {
```
Comment (bauerm97) [inline src/pkg/build/build.go]:
```
if syscall.Getuid() != 0 {
    return fmt.Errorf(...)
}
...
```

File: src/pkg/build/build.go [hunk 2]
```diff
@@ -281,17 +268,21 @@ func (b *Build) insertMetadata() (err error) {
...
+
+			sylog.Infof("Running pre scriptlet\n")
+			if err := pre.Start(); err != nil {
+				sylog.Fatalf("failed to start %%pre proc: %v\n", err)
+			}
+			if err := pre.Wait(); err != nil {
+				sylog.Fatalf("pre proc: %v\n", err)
+			}
+		} else {
+			sylog.Errorf("Attempted to build with scripts as non-root user")
```
Comment (bauerm97) [inline src/pkg/build/build.go]: Not actually returning an error, just writing an error message then returning nil!!

**Review by bauerm97 — CHANGES_REQUESTED** [review]

**Review by bauerm97 — CHANGES_REQUESTED** [review]
Looks good my dude

**Review by bauerm97 — APPROVED** [review]
Looks good my dude
