### PR TITLE
Key import ascii formated keys

### LINKED ISSUE #3300: Importing keys with ascii armored format
## Version of Singularity:

`3.1.1-902.ge094ee448`

### Expected behavior

Consider a key file with armored ascii format:
```
$ singularity key import ./file
```

The key is automatically detected it is armored and then added to the local keystore.

### Actual behavior

Does not exist yet, there's no support yet for key import on armor format key files.

### Steps to reproduce behavior

```
$ singularity key import  ./file
```

### PR DESCRIPTION
**Pull request by jchavezlavalle**
**Description of the Pull Request (PR):**

Ascii armored formated keys generated with either `singularity key export --armor ` or with `gpg --export --armor` couldn't be imported in the local keystore (either private or public) this PR fixes that issue.

**This fixes or addresses the following GitHub issues:**

- Fixes #3300 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/key_export.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ func init() {
 // KeyExportCmd is `singularity key export` and exports a public or secret
 // key from local keyring.
 var KeyExportCmd = &cobra.Command{
-	Args:                  cobra.ExactArgs(1),
+	Args: cobra.ExactArgs(1),
```
Comment (WestleyK) [inline cmd/internal/cli/key_export.go]: This file needs gofmt...

File: cmd/internal/cli/key_import.go [hunk 2]
```diff
@@ -20,7 +20,7 @@ func init() {
 
 // KeyImportCmd is `singularity key (or keys) import` and imports a local key into the singularity key store.
 var KeyImportCmd = &cobra.Command{
-	Args:                  cobra.ExactArgs(1),
+	Args: cobra.ExactArgs(1),
```
Comment (WestleyK) [inline cmd/internal/cli/key_import.go]: Same here.

File: pkg/sypgp/sypgp.go [hunk 3]
```diff
@@ -741,136 +746,162 @@ func ExportPubKey(kpath string, armor bool) error {
...
+	defer f.Close()
+
+	el, err := openpgp.ReadKeyRing(f)
+	if err != nil {
+		// is armored, so need to identify each of the block types and store them
+		re := openpgp.ReformatGPGExportedFile(f)
+		block, err = armor.Decode(re)
+		types = append(types, block.Type)
+	} else {
+		// is not armored, so obtain the types from entitylist
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: >// is not armored, so obtain the types from entitylist

Do you mean *is* armored? Remove the _not_.

File: pkg/sypgp/sypgp.go [hunk 4]
```diff
@@ -741,136 +746,162 @@ func ExportPubKey(kpath string, armor bool) error {
...
+		for _, pathEntity := range el {
+			if pathEntity.PrivateKey != nil {
+				types = append(types, "PGP PRIVATE KEY BLOCK")
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: It may be better to declare `PGP PRIVATE KEY BLOCK`, and `PGP PUBLIC KEY BLOCK` as `const` at the top of the file.

**Review by WestleyK — CHANGES_REQUESTED** [review]
Looks great! Couple suggestions :+1:

**Review by mem — COMMENTED** [review]
Looks good. Just address the existing comments and I think it's good.

**Review by WestleyK — CHANGES_REQUESTED** [review]
After talking to @devprincess, there are a couple changes to address before merging...

File: pkg/sypgp/sypgp.go [hunk 5]
```diff
@@ -30,6 +31,12 @@ import (
 	"golang.org/x/crypto/ssh/terminal"
 )
 
+// PublicKeyType is the armor type for a PGP public key.
+var PublicKeyType = "PGP PUBLIC KEY BLOCK"
+
+// PrivateKeyType is the armor type for a PGP private key.
+var PrivateKeyType = "PGP PRIVATE KEY BLOCK"
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: Why is this a `var`? Can it be a `const`?

```suggestion
const PrivateKeyType = "PGP PRIVATE KEY BLOCK"
```

File: pkg/sypgp/sypgp.go [hunk 6]
```diff
@@ -741,136 +795,166 @@ func ExportPubKey(kpath string, armor bool) error {
...
+		// Check if the key is encrypted, if it is, decrypt it
+		if entity.PrivateKey != nil {
+			if entity.PrivateKey.Encrypted {
 				err = DecryptKey(newEntity, "Enter your old password : ")
 				if err != nil {
 					return err
 				}
 			}
+		} else {
+			sylog.Fatalf("Could not import the private key: wrong format")
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: This should return a error instead, like:

```suggestion
			return fmt.Errorf("corrupted key, unable to recover data")
```

File: pkg/sypgp/sypgp.go [hunk 7]
```diff
@@ -741,136 +795,166 @@ func ExportPubKey(kpath string, armor bool) error {
...
+			PrivateKey:  entity.PrivateKey,
+			Identities:  entity.Identities,
+			Revocations: entity.Revocations,
+			Subkeys:     entity.Subkeys,
+		}
+
+		// Check if the key is encrypted, if it is, decrypt it
+		if entity.PrivateKey != nil {
+			if entity.PrivateKey.Encrypted {
 				err = DecryptKey(newEntity, "Enter your old password : ")
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: Dont you need to add `:` here?

```suggestion
 				err := DecryptKey(newEntity, "Enter your old password : ")
```

File: pkg/sypgp/sypgp.go [hunk 8]
```diff
@@ -688,7 +739,10 @@ func ExportPrivateKey(kpath string, armor bool) error {
 		err = entityToExport.SerializePrivate(file, nil)
 	} else {
 		var keyText string
-		keyText, err = serializeEntity(entityToExport, openpgp.PrivateKeyType)
+		keyText, err = serializePrivateEntity(entityToExport, openpgp.PrivateKeyType)
+		if err != nil {
+			sylog.Fatalf("Failed to read private key ASCII armored format: %s\n", err)
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: Again, we should return a error, instead of exiting right here.

```suggestion
			return fmt.Errorf("failed to read ASCII key format: %s", err)
```

**Review by WestleyK — CHANGES_REQUESTED** [review]
Left a couple comments. Thanks :+1:

File: pkg/sypgp/sypgp.go [hunk 9]
```diff
@@ -741,136 +795,166 @@ func ExportPubKey(kpath string, armor bool) error {
...
+		// Check if the key is encrypted, if it is, decrypt it
+		if entity.PrivateKey != nil {
+			if entity.PrivateKey.Encrypted {
 				err = DecryptKey(newEntity, "Enter your old password : ")
 				if err != nil {
 					return err
 				}
 			}
+		} else {
+			return fmt.Errorf("Corrupted key, unable to recover data")
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]:
```suggestion
			return fmt.Errorf("corrupted key, unable to recover data")
```

File: pkg/sypgp/sypgp.go (hunk 7 above)
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: Still not necessary, but I would add a `:` here, because we are declaring a new variable (`err`) in this `if` statement.

```suggestion
 				err := DecryptKey(newEntity, "Enter your old password : ")
```

File: pkg/sypgp/sypgp.go [hunk 10]
```diff
@@ -741,136 +795,166 @@ func ExportPubKey(kpath string, armor bool) error {
...
-			err := ImportPrivateKey(kpath)
+			err := ImportPrivateKey(pathEntity)
 			if err != nil {
 				return err
 			}
-		} else {
+
+		}
+		if pathEntityTypes[i] == PublicKeyType {
 			// Hopfully its a public key :)
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: You can remove this comment :)

```suggestion
```

File: pkg/sypgp/sypgp.go [hunk 11]
```diff
@@ -741,136 +795,166 @@ func ExportPubKey(kpath string, armor bool) error {
...
+	return types
+}
+
 // ImportKey Will import a key from a file, and decied if its
 // a public, or private key.
 func ImportKey(kpath string) error {
 
 	// Load the private key as an entitylist
 	pathEntityList, err := LoadKeyringFromFile(kpath)
+	pathEntityTypes := getTypesFromEntity(kpath)
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: I would move this line right under the `if err != nil {...}`, so it will look like:


```go
	pathEntityList, err := LoadKeyringFromFile(kpath)
	if err != nil {
￼		return fmt.Errorf("unable to get entity from: %s: %v", kpath, err)
￼	}
￼
	pathEntityTypes := getTypesFromEntity(kpath)
￼

```

**Review by WestleyK — CHANGES_REQUESTED** [review]
Just a couple more, small minor changes, looking really good!

**Review by WestleyK — APPROVED** [review]
Looks good to me! :+1:

**Review by mem — APPROVED** [review]
