### PR TITLE
OCI engine

### LINKED ISSUE #2428: Long command causes "Failed to read JSON configuration from socket: Bad file descriptor" error
## Version of Singularity:
3.0.1-73.ga50b5b3.el7

### Expected behavior

the container runs the command. This particular container and Singularity works fine on our system and just fails for the example described here.

### Actual behavior

An error occurs: Failed to read JSON configuration from socket: Bad file descriptor

### Steps to reproduce behavior

I believe this issue happens because of the extremely long command. In my example, the command that fails in a reproducible manner with the error message above has over 30,000 characters (essentially a list of hundreds of file path that collectively form one command). 

The error happens here ([see here](https://github.com/sylabs/singularity/blob/master/cmd/starter/c/starter.c), line 758):
```
if ( (ret = read(fds[0].fd, json_stdin, config.jsonConfSize)) != config.jsonConfSize ) {
                singularity_message(ERROR, "Failed to read JSON configuration from socket: %s\n", strerror(errno));
                exit(1);
            }
```

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Add OCI engine

**This fixes or addresses the following GitHub issues:**

- Fixes #2428, #2517

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/singularity/cli/oci.go [hunk 1]
```diff
@@ -0,0 +1,748 @@
...
+			sylog.Fatalf("%s", err)
+		}
+	},
+	Use:     docs.OciStartUse,
+	Short:   docs.OciStartShort,
+	Long:    docs.OciStartLong,
+	Example: docs.OciStartExample,
+}
+
+// OciDeleteCmd represents oci start command
```
Comment (sashayakovtseva) [inline cmd/singularity/cli/oci.go]: represents oci delete command.

File: cmd/singularity/cli/oci.go [hunk 2]
```diff
@@ -0,0 +1,748 @@
...
+			sylog.Fatalf("%s", err)
+		}
+	},
+	Use:     docs.OciDeleteUse,
+	Short:   docs.OciDeleteShort,
+	Long:    docs.OciDeleteLong,
+	Example: docs.OciDeleteExample,
+}
+
+// OciKillCmd represents oci start command
```
Comment (sashayakovtseva) [inline cmd/singularity/cli/oci.go]: ... oci kill command.

File: cmd/singularity/cli/oci.go [hunk 3]
```diff
@@ -0,0 +1,748 @@
...
+		}
+	},
+	Use:     docs.OciKillUse,
+	Short:   docs.OciKillShort,
+	Long:    docs.OciKillLong,
+	Example: docs.OciKillExample,
+}
+
+// OciStateCmd represents oci start command
+var OciStateCmd = &cobra.Command{
```
Comment (sashayakovtseva) [inline cmd/singularity/cli/oci.go]: ... oci state command.

File: cmd/singularity/cli/oci.go [hunk 4]
```diff
@@ -0,0 +1,748 @@
...
+			sylog.Fatalf("%s", err)
+		}
+	},
+	Use:     docs.OciStateUse,
+	Short:   docs.OciStateShort,
+	Long:    docs.OciStateLong,
+	Example: docs.OciStateExample,
+}
+
+// OciAttachCmd represents oci start command
```
Comment (sashayakovtseva) [inline cmd/singularity/cli/oci.go]: invalid comment

File: cmd/singularity/cli/oci.go [hunk 5]
```diff
@@ -0,0 +1,748 @@
...
+}
+
+func ociDelete(containerID string) error {
+	engineConfig, err := getEngineConfig(containerID)
+	if err != nil {
+		return err
+	}
+
+	switch engineConfig.State.Status {
+	case "running":
```
Comment (sashayakovtseva) [inline cmd/singularity/cli/oci.go]: Should we have all statuses as a constants somewhere? E.g in `pkg/ociruntime` since it is already present

File: internal/pkg/cgroups/cgroups.go [hunk 6]
```diff
@@ -7,48 +7,68 @@ package cgroups
...
+	"path/filepath"
+	"strings"
 
 	"github.com/containerd/cgroups"
 	specs "github.com/opencontainers/runtime-spec/specs-go"
 )
 
-const singularity = "/singularity"
+const (
+	singularity = "/singularity"
```
Comment (sashayakovtseva) [inline internal/pkg/cgroups/cgroups.go]: Is it used anywhere?

File: internal/pkg/instance/instance.go [hunk 7]
```diff
@@ -207,6 +244,97 @@ func (i *File) Update() error {
...
+		return err
+	}
+
+	cmdline := string(data[:len(data)-1])
+	procName := ProcName(i.Name, i.User)
+	if cmdline != procName {
+		return fmt.Errorf("no command line match found")
+	}
+
+	nsMap := map[specs.LinuxNamespaceType]string{
```
Comment (sashayakovtseva) [inline internal/pkg/instance/instance.go]: perhaps better to make it a package variable

File: internal/pkg/instance/instance.go [hunk 8]
```diff
@@ -207,6 +244,97 @@ func (i *File) Update() error {
...
+	src := fmt.Sprintf("/proc/%d/ns", i.Pid)
+	if err := syscall.Mount(src, nspath, "", syscall.MS_BIND, ""); err != nil {
+		return fmt.Errorf("mounting %s in instance folder failed: %s", src, err)
+	}
+
+	return nil
+}
+
+// GetNamespaces fills instance namespaces path
+func (i *File) GetNamespaces(configNs []specs.LinuxNamespace) error {
```
Comment (sashayakovtseva) [inline internal/pkg/instance/instance.go]: Just a suggestion, if a method is a getter shouldn't it return `([]specs.LinuxNamepsace, error)` rather than modifying parameter?
As a style suggestion: explicit `GetXXX()` is not a go-way, simple `XXX()` is commonly used

File: internal/pkg/cgroups/cgroups.go [hunk 9]
```diff
@@ -7,48 +7,68 @@ package cgroups
...
-	parentCgroup cgroups.Cgroup
-	childCgroup  cgroups.Cgroup
+	Path   string
+	Pid    int
+	cgroup cgroups.Cgroup
+}
+
+// GetCgroupRootPath returns cgroup root path
+func (m *Manager) GetCgroupRootPath() string {
+	path := ""
```
Comment (sashayakovtseva) [inline internal/pkg/cgroups/cgroups.go]: I think this var can be omitted, it is never set, and simple `return ""` is clear enough

File: internal/pkg/instance/instance.go [hunk 10]
```diff
@@ -95,6 +99,29 @@ func getPath(privileged bool, username string) (string, error) {
...
+
+// GetDirPrivileged returns directory where instances file will be stored
+// if instance is run with privileges
+func GetDirPrivileged(name string) (string, error) {
+	return getDir(true, name)
+}
+
+// GetDirUnprivileged returns directory where instances file will be stored
+// if instance is run without privileges
+func GetDirUnprivileged(name string) (string, error) {
```
Comment (sashayakovtseva) [inline internal/pkg/instance/instance.go:131]: Is it used anywhere, or for the sake of symmetry here?

File: internal/pkg/runtime/engines/engines.go [hunk 11]
```diff
@@ -35,21 +37,32 @@ type EngineOperations interface {
...
 	MonitorContainer(int, chan os.Signal) (syscall.WaitStatus, error)
-	// CleanupContainer is called in smaster after the MontiorContainer returns. It is responsible
+	// CleanupContainer is called in master after the MontiorContainer returns. It is responsible
 	// for ensuring that the container has been properly torn down.
-	CleanupContainer() error
+	CleanupContainer(error, syscall.WaitStatus) error
+}
+
+// GetName returns the engine name set in JSON []byte configuration.
+func GetName(b []byte) string {
```
Comment (sashayakovtseva) [inline internal/pkg/runtime/engines/engines.go:58]: Perhaps, this func can be also reused in `NewEngine`

File: internal/pkg/runtime/engines/singularity/rpc/server/server.go [hunk 12]
```diff
@@ -52,7 +53,7 @@ func (t *Methods) Chroot(arguments *args.ChrootArgs, reply *int) error {
 		return fmt.Errorf("failed to change directory to %s", root)
 	}
 
-	if arguments.UsePivot {
+	if arguments.Method == "pivot" {
```
Comment (sashayakovtseva) [inline internal/pkg/runtime/engines/singularity/rpc/server/server.go]: a switch case here might look more elegant

File: internal/pkg/util/fs/mount/mount.go [hunk 13]
```diff
@@ -236,6 +293,26 @@ func GetSizeLimit(options []string) (uint64, error) {
 	return 0, fmt.Errorf("sizelimit option not found")
 }
 
+// HasRemountFlag checks if remount flag is set or not.
+func HasRemountFlag(flags uintptr) bool {
+	if flags&syscall.MS_REMOUNT == 0 {
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/mount/mount.go]: Can be simplified to `return flags&syscall.MS_REMOUNT != 0 `

File: internal/pkg/util/fs/mount/mount.go [hunk 14]
```diff
@@ -236,6 +293,26 @@ func GetSizeLimit(options []string) (uint64, error) {
...
+		return false
+	}
+	return true
+}
+
+// HasPropagationFlag checks if a propagation flag is set or not.
+func HasPropagationFlag(flags uintptr) bool {
+	if flags&getPropagationFlags() == 0 {
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/mount/mount.go]: Can be simplified to `return flags&getPropagationFlags() != 0`

File: internal/pkg/util/fs/mount/mount.go [hunk 15]
```diff
@@ -236,6 +293,26 @@ func GetSizeLimit(options []string) (uint64, error) {
...
+		return false
+	}
+	return true
+}
+
+func getPropagationFlags() uintptr {
+	return (syscall.MS_UNBINDABLE | syscall.MS_SHARED | syscall.MS_PRIVATE | syscall.MS_SLAVE)
```
Comment (sashayakovtseva) [inline internal/pkg/util/fs/mount/mount.go]: Unnecessary parentheses

File: pkg/network/network.go [hunk 16]
```diff
@@ -3,17 +3,26 @@ package network
...
 	"strconv"
 	"strings"
 
 	"github.com/containernetworking/cni/libcni"
 	"github.com/containernetworking/cni/pkg/types"
-	"github.com/sylabs/singularity/internal/pkg/buildcfg"
 	"github.com/sylabs/singularity/internal/pkg/util/env"
 )
 
+type netError string
```
Comment (sashayakovtseva) [inline pkg/network/network.go:18]: Any arguments against using standard `errors.New`? Underneath it is the same, with exception that errors would be `var`, not `const`

File: pkg/network/network.go [hunk 17]
```diff
@@ -3,17 +3,26 @@ package network
...
+
+func (e netError) Error() string { return string(e) }
+
+const (
+	// NoCniConfError corresponds to a missing CNI configuration path
+	NoCniConfError = netError("no CNI configuration path provided")
```
Comment (sashayakovtseva) [inline pkg/network/network.go]: Following naming conventions, I think `ErrNoCNIConf` is better

File: pkg/network/network.go [hunk 18]
```diff
@@ -3,17 +3,26 @@ package network
...
+	// NoCniPluginError corresponds to a missing CNI plugin path
+	NoCniPluginError = netError("no CNI plugin path provided")
```
Comment (sashayakovtseva) [inline pkg/network/network.go]: Following naming conventions, I think ErrNoCNIPlugin is better

File: cmd/singularity/cli/oci.go (hunk 5 above)
Comment (cclerget) [reply cmd/singularity/cli/oci.go]: Good idea

File: internal/pkg/cgroups/cgroups.go (hunk 6 above)
Comment (cclerget) [reply internal/pkg/cgroups/cgroups.go]: No, removed

File: internal/pkg/instance/instance.go (hunk 7 above)
Comment (cclerget) [reply internal/pkg/instance/instance.go]: Yep

File: internal/pkg/instance/instance.go (hunk 8 above)
Comment (cclerget) [reply internal/pkg/instance/instance.go]: Changed `GetNamespaces` for `UpdateNamespacesPath`

File: internal/pkg/cgroups/cgroups.go (hunk 9 above)
Comment (cclerget) [reply internal/pkg/cgroups/cgroups.go]: Done

File: internal/pkg/instance/instance.go (hunk 10 above)
Comment (cclerget) [reply internal/pkg/instance/instance.go:131]: May be required for user namespace code path

Comment (sashayakovtseva) [reply internal/pkg/instance/instance.go:131]: got it

File: internal/pkg/runtime/engines/singularity/rpc/server/server.go (hunk 12 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/rpc/server/server.go]: Done

File: pkg/network/network.go (hunk 16 above)
Comment (cclerget) [reply pkg/network/network.go:18]: Yes I want to expose error as constant not variable to avoid modification from another package

File: internal/pkg/runtime/engines/engines.go (hunk 11 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/engines.go:58]: An oversight, thanks

**Review by sashayakovtseva — APPROVED** [review]

File: internal/app/singularity/oci.go [hunk 19]
```diff
@@ -0,0 +1,865 @@
...
+	if err != nil {
+		return err
+	}
+
+	if state.State.Status != ociruntime.Running && state.State.Status != ociruntime.Created {
+		return fmt.Errorf("container %s is neither running nor created", containerID)
+	}
+
+	if fromFile == "" {
+		return fmt.Errorf("you must specify --cgroups-file")
```
Comment (sashayakovtseva) [inline internal/app/singularity/oci.go]: Is it `--from-file`?

Comment (cclerget) [reply internal/app/singularity/oci.go]: yep thanks

**Review by bauerm97 — APPROVED** [review]
