### PR TITLE
Try /sbin/ldconfig for gpu libs if $PATH ldconfig fails

### LINKED ISSUE #5002: --nv --rocm won't find correct ldconfig when run from Nix userspace
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.5.2-1.el7
```

```
$ singularity exec --nv pytorch.simg bash
WARNING: Unable to capture nv bind points: could not execute ldconfig: exit status 1
``` 
### Expected behavior

Not an error with ldconfig.

### Actual behavior

Error with ldconfig, because it takes the wrong ldconfig. 

### Explanation
I believe this is a regression from 
https://github.com/sylabs/singularity/issues/2445

when the util/nvidia/paths.go became 
https://github.com/sylabs/singularity/blob/master/pkg/util/gpu/paths.go

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

On systems with Nix/Guix type userland on top of a 'standard'
distribution there may be a non-working userland `ldconfig` on `$PATH`
that will fail to find the system installed CUDA libs. If we fail to
execute `ldconfig` on `$PATH` then fall back to trying the default
`/sbin/ldconfig` in case that works.

### This fixes or addresses the following GitHub issues:

 - Fixes #5002

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: pkg/util/gpu/paths.go [hunk 1]
```diff
@@ -168,6 +170,11 @@ func paths(gpuFileList []string) ([]string, []string, error) {
 		return nil, nil, fmt.Errorf("could not lookup ldconfig: %v", err)
 	}
 	out, err := exec.Command(ldConfig, "-p").Output()
+	// #5002 If we failed and our ldconfig is not in standard POSIX location, try that
+	if err != nil && ldConfig != systemLdconfig {
```
Comment (cclerget) [inline pkg/util/gpu/paths.go:170]: Not related to your changes but while we are here ... after looking at the code above, there is a strange path :
```
        ldConfig, err := exec.LookPath("ldconfig")
	if ee, ok := err.(*exec.Error); ok && ee.Err == exec.ErrNotFound {
		sylog.Debugf("Could not find ldconfig in PATH")
		ldConfig = "ldconfig"
	}
	if err != nil {
		return nil, nil, fmt.Errorf("could not lookup ldconfig: %v", err)
	}
```

which let think about a code artifact like :
```
        ldConfig, err := exec.LookPath("ldconfig")
	if ee, ok := err.(*exec.Error); ok && ee.Err == exec.ErrNotFound {
		sylog.Debugf("Could not find ldconfig in PATH")
		ldConfig = "ldconfig"
	} else if err != nil {
		return nil, nil, fmt.Errorf("could not lookup ldconfig: %v", err)
	}
``` 

Removing the useless statement `ldConfig = "ldconfig"` would avoid this confusion

Comment (dtrudg) [reply pkg/util/gpu/paths.go:170]: ahh - good catch, that is an odd flow there.

**Comment by dtrudg** [comment]
@cclerget - rebased and dropped the ineffective error check block. As mentioned on slack I have #5616 open as a 'refactor' task for this code, and also want to add some e2e there that will run on GPU equipped systems.

**Review by cclerget — APPROVED** [review]
LGTM
