### PR TITLE
Fix container mount destination containing symlink

### LINKED ISSUE #4702: Fatal error binding nvidia persistenced socket
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.0-rc.1+4-ga7c731b22
```

### Expected behavior

On a machine with the nvidia-persistenced running, a container starts with `--nv` correctly.

This works correctly on 3.4.2:

```
dave@ythel~> singularity run --nv docker://ubuntu
dave@ythel:~
10:27 AM $ 
```

### Actual behavior

On a machine with the nvidia-persistenced running, a container does not start with `--nv` correctly

```
dave@ythel~> singularity run --nv docker://ubuntu
...
INFO:    Creating SIF file...
FATAL:   container creation failed: mount /var/run/nvidia-persistenced/socket->/var/run/nvidia-persistenced/socket error: while mounting /var/run/nvidia-persistenced/socket: destination /var/run/nvidia-persistenced/socket doesn't exist in container
```

### Steps to reproduce this behavior

Try using `--nv` on a machine with nvidia drivers installed *and* the `nvidia-persistenced` running

### What OS/distro are you running

```
Debian 10.1
```

### How did you install Singularity

Git tree

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Fix overlay/underlay layers to resolve destination relative to the container root filesystem, `fs.EvalRelative` was reworked by replacing `filepath.EvalSymlinks` with `os.Readlink` in order to minimize false positive and follow links relatively to the root destination.

### This fixes or addresses the following GitHub issues:

 - Fixes #4702 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go [hunk 1]
```diff
@@ -143,14 +155,14 @@ func (u *Underlay) createLayer(rootFsPath string, system *mount.System) error {
 
 func (u *Underlay) duplicateDir(dir string, system *mount.System, existingPath string) error {
 	binds := 0
-	path := filepath.Clean(u.session.RootFsPath() + dir)
```
Comment (dtrudg) [inline internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go:146]: When eliminating `Clean` here, is there any impact if `dir` is e.g. `../../../../` ?

File: internal/pkg/util/fs/helper_linux_test.go [hunk 2]
```diff
@@ -311,17 +311,17 @@ func TestEvalRelative(t *testing.T) {
 	}{
 		{"/bin", "/usr/bin"},
 		{"/sbin", "/usr/sbin"},
-		{"/bin/bin", "/usr/bin"},
```
Comment (dtrudg) [inline internal/pkg/util/fs/helper_linux_test.go:314]: I'm pretty confused here. This looks like it used to resolve down to an actual directory `/usr/bin` but now the result `/bin` still includes a symlink?

**Review by dtrudg — COMMENTED** [review]
Sorry - I'm kinda confused on this one. It seems to fix the issue - but I'm honestly unclear how this function is used entirely, and why the change is generally reasonable.

Would you be able to give:

1. An example of the old behavior
2. An example of the new behavior
3. A brief explanation of how this fixes the issue, and why it doesn't affect anything else?

File: internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go (hunk 1 above)
Comment (cclerget) [reply internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go:146]: Because `filepath.Join` call `filepath.Clean` on returned result

File: internal/pkg/util/fs/helper_linux_test.go (hunk 2 above)
Comment (cclerget) [reply internal/pkg/util/fs/helper_linux_test.go:314]: Previous version was broken and resolved links outside of the relative root

File: internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go (hunk 1 above)
Comment (dtrudg) [reply internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go:146]: :+1: I was not aware of that, apologies.

File: internal/pkg/util/fs/helper_linux_test.go (hunk 2 above)
Comment (dtrudg) [reply internal/pkg/util/fs/helper_linux_test.go:314]: Sorry I'm not clear what "relative root" means? Do you mean that if the `root` contains a symlink then only symlinks in `path` that are *not* in `root` are resolved?

**Comment by cclerget** [comment]
> Sorry - I'm kinda confused on this one. It seems to fix the issue - but I'm honestly unclear how this function is used entirely, and why the change is generally reasonable.
> 
> Would you be able to give:
> 
>     1. An example of the old behavior
> 
>     2. An example of the new behavior
> 
>     3. A brief explanation of how this fixes the issue, and why it doesn't affect anything else?

1. With an image containing a smylink like `/image/var/run -> /run`, the old `fs.EvalRelative` resolved links to the host instead, path was valid as long as host contains the same symlink, the side effect was that overlay/underlay checked path and didn't create it because of presence or not on the host, basically the behavior was inconsistent depending of host FS layout and additionally of the bind path provided (eg: `/var/run/nvidia/...` VS `/run/nvidia/...`)

2. Change applied to `fs.EvalRelative` now ensure we stay and resolve links inside the provided relative root path, so we are not impacted by host FS layout and stay in the container root filesystem. Changes in overlay/underlay ensure that real destination directories/files are created correctly as mount follow symlinks and bind to the real path.

3. As explained in 1 and 2. It also affect OCI engine mount operations, overall this is better and the potential issues which could be introduced by those changes should be dependent of image FS layout with crazy symlinks in it.

File: internal/pkg/util/fs/helper_linux_test.go (hunk 2 above)
Comment (cclerget) [reply internal/pkg/util/fs/helper_linux_test.go:314]: See explanations below

File: internal/pkg/util/fs/helper.go [hunk 3]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+			d, err := os.Readlink(dest)
+			if err != nil {
+				continue
+			}
+			if filepath.IsAbs(d) {
+				dest = filepath.Join(cleanRoot, d)
+			} else {
+				dest = filepath.Join(filepath.Dir(dest), d)
+				if !strings.HasPrefix(dest, cleanRoot) {
+					dest = filepath.Join(filepath.Dir(dest), d)
```
Comment (dtrudg) [inline internal/pkg/util/fs/helper.go]: Isn't this a duplicate of line 174 that's not needed?

Comment (cclerget) [reply internal/pkg/util/fs/helper.go]: yep will fix that. Thanks !

File: internal/pkg/util/fs/helper.go [hunk 4]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
 	return p
 }
 
-// EvalRelative evaluates symlinks in path relative to root path. This
-// function doesn't return error but always returns an evaluated path.
+// EvalRelative evaluates symlinks in path relative to root path, it returns
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: After going thru the code several times, I think I understand what this means, and I'm having a hard time finding a suggestion as to how to change this so that other people can understand it.

First, path is _not_ a valid path in the host, and it looks like it _must_ be a valid path in the container. That's what I guess "relative to root path" means.

The bit about "it returns a path as if it was evaluated from chroot" means that the result of this function is a valid path rooted at rootfs (not relative to it). What I mean is that "relative to rootfs" would make me thing that the result of this function is a relative path (x/y/z, relative to /a/b/c) and in fact it's an absolute path rooted at rootfs (/x/y/z, with root being /a/b/c).

The other bit of documentation that is missing here is why this is needed, or in other words, when would I need to use this? What I mean is that if path is valid in the container, why would I need to fudge with it at all? I _suspect_ that part of the confusion comes from the name of this function...

File: internal/pkg/util/fs/helper.go [hunk 5]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
-				if err != nil {
-					break
-				}
-				if !strings.HasPrefix(target, root) {
-					rootDestPath = filepath.Join(root, target)
-					continue
+	cleanRoot := filepath.Clean(root)
+	cleanPath := filepath.Clean(path)
+
+	if cleanPath == "" {
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: trying to understand here...

filepath.Clean should not return an empty value, so I guess path was empty to start with?

File: internal/pkg/util/fs/helper.go [hunk 6]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+		return cleanRoot
```
Comment (dtrudg) [inline internal/pkg/util/fs/helper.go]: If `path=/1/2/3` and `root=/a/b/c` then we evaluate `/1/2/3` under `/a/b/c` and the return doesn't include `/a/b/c`?

If `path=""` then the return is `root` - this is a little odd compared to the above. Is something done with that `root` value? Is it some sort of safety measure?

File: internal/pkg/util/fs/helper.go [hunk 7]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+	}
+
+	sep := string(os.PathSeparator)
+	splitted := strings.Split(cleanPath, sep)
+
+	i := 1
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]:
```
i := 0
if filepath.IsAbs(cleanPath) {
    // path is absolute, skip the first empty element
    // that resulted from calling strings.Split above.
    i = 1
}
```

note that the index itself is not really important, so this is more or less equivalent to doing something like:

```
dest := cleanRoot

components := strings.Split(cleanPath, string(os.PathSeparator))
if filepath.IsAbs(cleanPath) {
    components = components[1:]
}

for _, component := range components {
}
```

File: internal/pkg/util/fs/helper.go [hunk 8]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+	}
+
+	dest := cleanRoot
+
+	for ; i < len(splitted); i++ {
+		dest = filepath.Join(dest, splitted[i])
+
+		fi, err := os.Lstat(dest)
+		if err != nil {
+			continue
```
Comment (mem) [inline internal/pkg/util/fs/helper.go:169]: this continue here needs a comment, specially this this is not checking the kind of error that it's getting back. What exactly are we skipping here and why?

File: internal/pkg/util/fs/helper.go [hunk 9]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+		}
+
+		if fi.Mode()&os.ModeSymlink != 0 {
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: just to avoid indenting the code too much, I would do:

```
if fi.Mode() & os.ModeSymlink == 0 {
    // not a symlink, continue
    continue
}
```

File: internal/pkg/util/fs/helper.go [hunk 10]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+			d, err := os.Readlink(dest)
+			if err != nil {
+				continue
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: again, what are we skipping and why?

File: internal/pkg/util/fs/helper.go [hunk 11]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+			}
+			if filepath.IsAbs(d) {
+				dest = filepath.Join(cleanRoot, d)
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: this one needs a comment as well...

We got an absolute path from the symlink, and we want to make it relative to cleanRoot. I know it's obvious now, but when reading this code I had to stop and think about what this is trying to do.

File: internal/pkg/util/fs/helper.go [hunk 12]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+			} else {
+				dest = filepath.Join(filepath.Dir(dest), d)
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: this line is really tricky and needs documentation...

Someone reading this will ask why is this chopping the last element of dest?

I removed the component that was added on line 159 in order to evaluate the relative symlink relative to the directory containing the new element, in other words, I go back to the containing directory to evaluate the symlink relative to that directory.

File: internal/pkg/util/fs/helper.go [hunk 13]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+				if !strings.HasPrefix(dest, cleanRoot) {
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: Please add a comment...

if the resulting path falls outside cleanRoot (e.g. the symlink was something like ..), then we do ... what?

At this point, my intuition says "error out", so this code must be here for some reason?

File: internal/pkg/util/fs/helper.go (hunk 3 above)
Comment (mem) [inline internal/pkg/util/fs/helper.go]: dest already had the element added on line 159 chopped off. That one I can understand.

Why is this removing another element?

File: internal/pkg/util/fs/helper.go [hunk 14]
```diff
@@ -134,34 +134,53 @@ func RootDir(path string) string {
...
+					dest = filepath.Join(cleanRoot, dest)
 				}
-				dest = strings.Replace(target, root, "", 1)
-				break
 			}
 		}
 	}
 
-	return dest
+	return strings.Replace(dest, cleanRoot, "", 1)
```
Comment (mem) [inline internal/pkg/util/fs/helper.go]: Sorry to nag, but how is this different from `dest = strings.TrimPrefix(dest, cleanRoot)`?

If there's a special case that's being covered by this, could you please add a comment?

**Review by mem — APPROVED** [review]

**Review by mem — DISMISSED** [review]
I only meant to post comments :-(

**Review by dtrudg — APPROVED** [review]
Thanks @cclerget - it's much faster to see the intention, flow here now.

**Comment by dtrudg** [comment]
NB - CI failure was a library download timeout - should be okay on re-run
