### PR TITLE
Development 3.0: Add actions script check for old formats

### LINKED ISSUE #2014: singularity instance start does not work, provides no error
## Version of Singularity:

$ singularity --version
singularity version 3.0.0-alpha.1-468-gb034a40-dirty

### Expected behavior

$ singularity instance start Default.sif www
$ echo $?
0
$ singularity instance list
INSTANCE NAME    PID      IMAGE
<instance info shown here>

### Actual behavior

$ singularity instance start Default.sif www
$ echo $?
1
$ singularity instance list
INSTANCE NAME    PID      IMAGE
$ singularity --verbose instance start Default.sif www
$ echo $?
1

### Steps to reproduce behavior

$ sudo singularity build Default.sif examples/busybox/Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
$ singularity instance start Default.sif www
$ echo $?
1
$ singularity instance list
INSTANCE NAME    PID      IMAGE
$ singularity --verbose instance start Default.sif www
$ echo $?
1

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR add actions script checks for old formats.

**This fixes or addresses the following GitHub issues:**

- Fixes #2014

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

File: src/runtime/engines/singularity/process.go [hunk 1]
```diff
@@ -28,6 +27,80 @@ import (
...
+	}()
+
+	for _, keyval := range env {
+		if strings.HasPrefix(keyval, "PATH=") {
+			os.Setenv("PATH", keyval[5:])
+			break
+		}
+	}
+
+	if _, err := exec.LookPath(args[0]); err == nil {
```
Comment (bauerm97) [inline src/runtime/engines/singularity/process.go:57]: Would add a comment here:

`// If args[0] is an absolute path, exec.LookPath() looks for this file directly instead of within PATH`

File: src/runtime/engines/singularity/process.go [hunk 2]
```diff
@@ -28,6 +27,80 @@ import (
...
+		return nil
+	}
+
+	switch args[0] {
```
Comment (bauerm97) [inline src/runtime/engines/singularity/process.go:63]: I would add a comment for clarity:
`// If args[0] isn't executable (either via PATH or absolute path), look for alternative approaches to handling it`

File: src/runtime/engines/singularity/process.go [hunk 3]
```diff
@@ -99,7 +154,7 @@ func (engine *EngineOperations) StartProcess(masterConn net.Conn) error {
 	}
 
 	// Spawn and wait container process, signal handler
-	cmd := exec.Command(args[0], args...)
+	cmd := exec.Command(args[0], args[1:]...)
```
Comment (bauerm97) [inline src/runtime/engines/singularity/process.go:167]: What's the purpose of this change here?

**Review by bauerm97 — CHANGES_REQUESTED** [review]
Other than those two comments I think we should add for clarity, I really like this change.

File: src/runtime/engines/singularity/process.go (hunk 3 above)
Comment (cclerget) [reply src/runtime/engines/singularity/process.go:167]: To avoid redundant first argument, `Command` is not `syscall.Exec` :)

**Review by bauerm97 — APPROVED** [review]
