### PR TITLE
Chown images after build with sudo

### LINKED ISSUE #2102: chown built images
## Version of Singularity:

v3.0.0-beta

when we do a `sudo singularity build...` I think we should chown to the user to avoid this:
```bash
ERROR:   signing container failed: failed to load SIF container file: opening(RDWR) container file: open demo/nginx.sif: permission denied
```
### Expected behavior

```bash
sudo singularity build my.sif DefFile
ls -lh my.sif
-rwxrwxr-x. 1 eduardo eduardo 187M Sep 21 16:54 my.sif
```
### Actual behavior
```bash
sudo singularity build my.sif DefFile
ls -lh my.sif
-rwxrwxr-x. 1 root root 187M Sep 21 16:54 my.sif
```

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
- Fixes #2102

Signed-off-by: ArangoGutierrez <eduardo@sylabs.io>

> test on RHEL7 - Go 1.11
```bash
[eduardo@rhel7 singularity]$ sudo singularity build test.sif examples/busybox/Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
<...>
[eduardo@rhel7 singularity]$ ls -lh test.sif
-rwxr-xr-x. 1 eduardo eduardo 640K Sep 27 10:46 test.sif
```
**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

File: src/pkg/build/assemblers/assembler_sif.go [hunk 1]
```diff
@@ -77,6 +79,14 @@ func createSIF(path string, definition []byte, squashfile string) (err error) {
 		return fmt.Errorf("while creating container: %s", err)
 	}
 
+	// chown the sif file to the calling user
+	if syscall.Getuid() == 0 {
+		uID, _ := strconv.Atoi(os.Getenv("SUDO_UID"))
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: We shouldn't be ignoring errors here, *especially* since this is touching security

Comment (bauerm97) [reply src/pkg/build/assemblers/assembler_sif.go]: Also, I think `uid` looks better than `uID`

File: src/pkg/build/assemblers/assembler_sif.go [hunk 2]
```diff
@@ -77,6 +79,14 @@ func createSIF(path string, definition []byte, squashfile string) (err error) {
 		return fmt.Errorf("while creating container: %s", err)
 	}
 
+	// chown the sif file to the calling user
+	if syscall.Getuid() == 0 {
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: What about the case where the calling user is root. Not running `sudo ...` but they are logged in as the root user? In this case, `$SUDO_UID` may not be set, and since we're not checking for `Atoi` errors, we can't be guaranteed of the behavior

**Review by bauerm97 — CHANGES_REQUESTED** [review]
In general, I'm not a fan of the approach of automatically calling `chown` on an image built with `uid=0`. This seems unexpected to me, especially because we're not handling the case where the user is actually logged in as root, and not just running as sudo. 

I think this feature would be better served by implementing a flag to optionally do this. Something like `--chown <uid>:<gid>` makes much more sense to me, as it means we won't have any unexpected default behavior. @gmkurtzer I'd like to hear your thoughts here since this was your idea IIRC

File: src/pkg/build/assemblers/assembler_sif.go (hunk 1 above)
Comment (ArangoGutierrez) [reply src/pkg/build/assemblers/assembler_sif.go]: ummm lint on my IDE, recommend id always should be ID.
but I agree with you

**Comment by ArangoGutierrez** [comment]
3519e2d behavior
```bash
[eduardo@rhel7 singularity]$ sudo singularity build user_with_sudo.sif examples/busybox/Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
[eduardo@rhel7 singularity]$ ls -lh user_with_sudo.sif
-rwxr-xr-x. 1 eduardo eduardo 640K Sep 27 14:17 user_with_sudo.sif
[eduardo@rhel7 singularity]$ sudo -i
[root@rhel7 ~]# cd /home/eduardo/go/src/github.com/sylabs/singularity/
[root@rhel7 singularity]# singularity build user_is_root.sif examples/busybox/Singularity
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
[root@rhel7 singularity]# ls -lh user_is_root.sif
-rwxr-xr-x. 1 root root 640K Sep 27 14:18 user_is_root.sif
```

File: src/pkg/build/assemblers/assembler_sif.go [hunk 3]
```diff
@@ -77,6 +79,14 @@ func createSIF(path string, definition []byte, squashfile string) (err error) {
 		return fmt.Errorf("while creating container: %s", err)
 	}
 
+	// chown the sif file to the calling user
+	if syscall.Getuid() == 0 && os.Getenv("USERNAME") != "root" {
```
Comment (jmstover) [inline src/pkg/build/assemblers/assembler_sif.go]: If I run `sudo` ... `$USERNAME` is set to `root`. 

Check `SUDO_USER` instead

**Review by jmstover — DISMISSED** [review]

**Review by jmstover — APPROVED** [review]
LGTM

**Comment by gmkurtzer** [comment]
I would say, if calling `sudo singularity ...`, we should automatically chown. But if calling through `sudo` with any other command, I would suggest not. 

You can check the command being called with `sudo` with the environment variable `SUDO_COMMAND`. Pattern match that for the singularity command to trigger the chown.

**Comment by ArangoGutierrez** [comment]
after af84fba
```bash
[eduardo@rhel7 sylabs]$ sudo singularity build user_call_sudo.sif singularity/examples/busybox/Singularity 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
[eduardo@rhel7 sylabs]$ ls -lh user_call_sudo.sif 
-rwxr-xr-x. 1 eduardo eduardo 640K Oct  2 13:27 user_call_sudo.sif
[eduardo@rhel7 sylabs]$ sudo su -
Last login: Sat Sep 29 11:21:14 -05 2018 on pts/1
[root@rhel7 ~]# singularity build user_is_root.sif /home/eduardo/go/src/github.com/sylabs/singularity/examples/busybox/Singularity 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
INFO:    Running post scriptlet
+ echo Hello from inside the container
Hello from inside the container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete!
[root@rhel7 ~]# ls -lh user_is_root.sif 
-rwxr-xr-x. 1 root root 640K Oct  2 13:28 user_is_root.sif
```

File: src/pkg/build/assemblers/assembler_sif.go [hunk 4]
```diff
@@ -129,3 +136,41 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
...
+
+			uid, err = strconv.Atoi(_uid)
+			if err != nil {
+				sylog.Errorf("Error while calling strconv: %v", err)
+
+				return 0, 0, false
+			}
+			gid, err = strconv.Atoi(_gid)
+			if err != nil {
+				sylog.Errorf("Error while calling strconv : %v", err)
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: I would say `Warningf` since these are not "errors" which will cause singularity to exit

Comment (bauerm97) [reply src/pkg/build/assemblers/assembler_sif.go]: Same as the other `Errorf` spots as well

File: src/pkg/build/assemblers/assembler_sif.go [hunk 5]
```diff
@@ -129,3 +136,41 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
...
+// changeOwner check the command being called with sudo with the environment
+// variable SUDO_COMMAND. Pattern match that for the singularity bin
+func changeOwner() (int, int, bool) {
+	var uid, gid int
+	var chown bool
+	var err error
+
+	r := regexp.MustCompile("(singularity)")
+	sudoCmd := os.Getenv("SUDO_COMMAND")
+	if r.MatchString(sudoCmd) {
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]:
```
if !r.MatchString(sudoCmd) {
    return 0, 0, false
}
```

File: src/pkg/build/assemblers/assembler_sif.go [hunk 6]
```diff
@@ -129,3 +136,41 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
 
 	return
 }
+
+// changeOwner check the command being called with sudo with the environment
+// variable SUDO_COMMAND. Pattern match that for the singularity bin
+func changeOwner() (int, int, bool) {
+	var uid, gid int
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: Can probably omit this here and just use `:=` syntax to declare these vars at appropriate times

File: src/pkg/build/assemblers/assembler_sif.go [hunk 7]
```diff
@@ -129,3 +136,41 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
...
+	var chown bool
+	var err error
+
+	r := regexp.MustCompile("(singularity)")
+	sudoCmd := os.Getenv("SUDO_COMMAND")
+	if r.MatchString(sudoCmd) {
+		if syscall.Getuid() == 0 && os.Getenv("SUDO_USER") != "root" {
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]:
```
if !(syscall.Getuid() == 0 && os.Getenv("SUDO_USER") != "root") {
    return 0, 0, false
}
```

**Review by bauerm97 — CHANGES_REQUESTED** [review]
In general pretty close to being ready. I think we should typically prefer the design pattern of avoiding lots of nested conditionals as it's harder to read. Also we should reserve `Errorf` for when we're actually returning an `error` type. If we're catching an error but are not worried about returning the error, we should be using `Warningf` instead.

File: src/pkg/build/assemblers/assembler_sif.go [hunk 8]
```diff
@@ -129,3 +136,41 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
...
+
+		return 0, 0, false
+	}
+	gid, err := strconv.Atoi(_gid)
+	if err != nil {
+		sylog.Warningf("Error while calling strconv : %v", err)
+
+		return 0, 0, false
+	}
+	chown := true
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: This line doesn't serve a purpose. Just `return uid, gid, true` is okay.

Comment (ArangoGutierrez) [reply src/pkg/build/assemblers/assembler_sif.go]: agree

File: src/pkg/build/assemblers/assembler_sif.go [hunk 9]
```diff
@@ -129,3 +136,40 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
...
+// changeOwner check the command being called with sudo with the environment
+// variable SUDO_COMMAND. Pattern match that for the singularity bin
+func changeOwner() (int, int, bool) {
+	r := regexp.MustCompile("(singularity)")
+	sudoCmd := os.Getenv("SUDO_COMMAND")
+	if !r.MatchString(sudoCmd) {
+		return 0, 0, false
+	}
+
+	if syscall.Getuid() == 0 && os.Getenv("SUDO_USER") == "root" {
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: This logic here is incorrect.

First of all, we want to continue only if the UID == 0. Second, if `SUDO_USER` is set to *anything* we should continue.

I think the logic should look like this:
`if os.Getenv("SUDO_USER") == "" || syscall.Getuid() != 0 {...}`

This means we *only* proceed with the function *if and only if* `SUDO_USER` is *set* and `uid==0`.

Comment (ArangoGutierrez) [reply src/pkg/build/assemblers/assembler_sif.go]: 066de5d

File: src/pkg/build/assemblers/assembler_sif.go [hunk 10]
```diff
@@ -81,6 +83,11 @@ func createSIF(path string, definition []byte, squashfile string) (err error) {
 		return fmt.Errorf("while creating container: %s", err)
 	}
 
+	// chown the sif file to the calling user
+	if uid, gid, ok := changeOwner(); ok {
+		os.Chown(path, uid, gid)
```
Comment (bauerm97) [inline src/pkg/build/assemblers/assembler_sif.go]: We should always be checking for errors from functions which return errors

**Review by bauerm97 — CHANGES_REQUESTED** [review]

File: src/pkg/build/assemblers/assembler_sif.go (hunk 10 above)
Comment (ArangoGutierrez) [reply src/pkg/build/assemblers/assembler_sif.go]: agree.
done in 
2d22e57

**Comment by ArangoGutierrez** [comment]
PING -> @bauerm97

**Review by cclerget — APPROVED** [review]
Looks good !

**Review by bauerm97 — APPROVED** [review]
