### PR TITLE
Capability command fixes

### LINKED ISSUE #3026: refactor singularity help capabilities text
## Version of Singularity:

3.1.0

* `Manage Linux capabilities on containers`

changed to: `Manage Linux capabilities for users and groups`

* Add reference to `man 7 capabilities` so they can see the list of capabilities available and what they are used for. Do this under the description.

* `Add authorized capabilities for a given user/group`

change to: `Add capabilities to a user or group`

* `Drop authorized capabilities for a given user/group`

change to: `Remove capabilities from an user or group`

* `List authorized capabilities for the given user/group.`

change to: `Show capabilities for a user or group`

Note in description that root is required to run all these commands.

### LINKED ISSUE #3029: refactor singularity help capability list text
## Version of Singularity:

3.1.0

* `List authorized capabilities for the given user/group.`

change to: `Show the Linux capabilities enabled for a user or group`

*
<pre>
Description:
  The capability list command allows you to see
  what Linux capabilities are associated with users/groups.
</pre>

change to:

<pre>
Description:
  Show the capabilities for a user or group.

  This command requires root to run.
</pre>

* `list all users and groups capabilities`

change to: `Show capabilities for each user and group`

* `list capabilities for the given group`

change to: `Show capabilities for a group`

* `list capabilities for the given user`

change to: `Show capabilities for a user`

### LINKED ISSUE #3030: Improve errors for singularity capability list
## Version of Singularity:

3.1.0

<pre>
$ sudo singularity capability list
[sudo] password for justin:
FATAL:   Unable to list capabilities: while listing capabilities: must specify user, group, or listall

$ singularity capability list --all
FATAL:   Unable to list capabilities: while listing capabilities: only root user can list capabilities
</pre>

I think these errors could be improved a bit.

### LINKED ISSUE #3031: --all should be the default for singularity capabilities list
## Version of Singularity:

3.0.1

I think `--all` would be a good default option here.

### LINKED ISSUE #3032: Invalid option in error for singularity capability list
## Version of Singularity:

3.0.1

<pre>
$ sudo singularity capability list
[sudo] password for justin:
FATAL:   Unable to list capabilities: while listing capabilities: must specify user, group, or listall
</pre>

`listall` is not a valid option

### LINKED ISSUE #3035: be verbose when no capabilities are available to list
## Version of Singularity:

3.1.0

<pre>
$ sudo singularity capability list --group nobody
$ echo $?
0
</pre>

When no capabilities are available, maybe we should be more verbose and say so.

### LINKED ISSUE #3036: Could we replace the options with arguments in singularity capability list
## Version of Singularity:

3.0.1

`singularity capability list --all` to `singularity capability list all (or singularity capability list)`

`singularity capability list --user nobody` to `singularity capability list nobody`

`--user` or `--group` would not really be needed, you could just print user or group perms if either matched (like user=nobody, group=nobody)

What do you think?

### LINKED ISSUE #3037: capability add and drop print fatal when describing a capability
## Version of Singularity:

3.0.1

<pre>
$ sudo singularity capability add --desc WAKE_ALARM
CAP_WAKE_ALARM:        CAP_WAKE_ALARM (since Linux 3.0)
        Trigger something that will wake up the system (set CLOCK_REALTIME_ALARM and CLOCK_BOOTTIME_ALARM timers).

FATAL:   Unable to add capabilities: no user or group specified

$ sudo singularity capability drop --desc WAKE_ALARM
CAP_WAKE_ALARM:        CAP_WAKE_ALARM (since Linux 3.0)
        Trigger something that will wake up the system (set CLOCK_REALTIME_ALARM and CLOCK_BOOTTIME_ALARM timers).

FATAL:   Unable to drop capabilities: no user or group specified
</pre>

I would expect these not to be fatal since you're describing something, and not actually adding or removing.

### LINKED ISSUE #3038: consider moving capabilities list and descriptions to new command
## Version of Singularity:

3.0.1

I think we could migrate the list of capabilities and the `--desc` flag to a new command: `singularity capability avail`.

Or perhaps move them just to `singularity capability` ?

I don't think they need to be in the add / drop commands.

### LINKED ISSUE #3039: discuss: singularity caps vs singularity capability
## Version of Singularity:

3.0.1

Could we shorten the `capability` command to `caps`? Or perhaps an alias? Maybe this is better done by the shell completion?

I'm misspelling capability all the time testing it ;)

### LINKED ISSUE #3040: typo when trying to add invalid capability
## Version of Singularity:

3.0.1

<pre>
$ sudo singularity capability add --group justin CAP_NEW_RAW
[sudo] password for justin:
WARNING: Ignoring unkown capabilities: [CAP_NEW_RAW]
</pre>

`unkown`

### LINKED ISSUE #3041: singularity capability list --all ignores arguments
## Version of Singularity:

3.0.1

<pre>
$ sudo singularity capability list --all bob tom
dave [user]: CAP_NET_RAW
justin [group]: CAP_NET_RAW
</pre>

I would figure it would give a help or usage statement and fail.

### LINKED ISSUE #3042: refactor singularity help capability add text
## Version of Singularity:

3.0.1

* `Add authorized capabilities for a given user/group`

change to: `Add Linux capabilities to a user or group`

* Description

change to: 

<pre>
Description:
  Add Linux capabilities to a user or group. If using the `--desc` option, instead describe those capabilities.

  The capabilities argument must be separated by commas and is not case sensitive
</pre>

Remove list of capabilities, maybe? Feels too busy. Tell user they can get them from `man 7 capabilities` or move them to another command where you can better show them.

* `See "-d" flag example for description of each capabilities`

Remove

* `print capabilities description`

change to: `Instead of adding capabilities, instead show a description for them`

* `add capabilities for the given group`

change to: `Add capabilities to a group`

* `add capabilities for the given user`

change to: `Add capabilities to a user`

* `To print capabilities description:`

change to: `Show a description for these capabilities:`

### LINKED ISSUE #3043: remove root requirement for singularity capability list
## Version of Singularity:

3.0.1

Could we remove the root requirement for `singularity capability list`? The file holding the info is `644`, so I assume it is not needed.

### LINKED ISSUE #3046: refactor singularity help capability drop text
## Version of Singularity:

3.1.0

I would apply the same changes as in #3042

### LINKED ISSUE #3094: "Sudo" to be added to help guide commands
## Version of Singularity:

3.1

### Expected behavior

The help guide commands that demonstrate `add`, `drop` capability commands should include `sudo` since all capability commands work only with sudo.

`$ sudo singularity capability add --user nobody AUDIT_READ,chown`

### Actual behavior

$ singularity capability add --user nobody AUDIT_READ,chown

### Steps to reproduce behavior

$ singularity capability add --help

### LINKED ISSUE #3096: The "-d" flag gives an unrelated error.
## Version of Singularity:

3.1

### Expected behavior

The -d flag describes the mentioned Linux capability. 

### Actual behavior

It does give a description of the capability but it also gives:
`FATAL:   Unable to add capabilities: no user or group specified`

### Steps to reproduce behavior

`sudo singularity capability add/drop -d SYSLOG`

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR address issues :
- Fixes #3096
- Fixes #3094
- Fixes #3046
- Fixes #3043
- Fixes #3042
- Fixes #3041
- Fixes #3040
- Fixes #3039
- Fixes #3038
- Fixes #3037
- Fixes #3036
- Fixes #3035
- Fixes #3032
- Fixes #3031
- Fixes #3030
- Fixes #3029
- Fixes #3026

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/app/singularity/capability_avail_linux.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+// CapAvailConfig instructs CapabilityAvail on what capability to list/describe
+type CapAvailConfig struct {
+	Caps string
+	Desc bool
+}
+
+// CapabilityAvail lists the capabilities based on the CapAvailConfig
+func CapabilityAvail(c CapAvailConfig) error {
+	caps, ign := capabilities.Split(c.Caps)
+	if len(ign) > 0 && c.Caps != "" {
```
Comment (mem) [inline internal/app/singularity/capability_avail_linux.go]: I'm trying to understand the reason behind the c.Caps != "" check and it took me a bit to figure it out... If c.Caps is "", capabilities.Split will return nil, []string{""}, so len(ign) is going to be 1. The fact that the reader has to stop and think a lot about it probably hints at something being wrong elsewhere...

Wouldn't it be better to fix capabilities.Split (or in fact, capabilities.Normalize) so that it ignores an empty string?

In the loop, at the beginning, add `if capb == "" { continue }`. Does this have an undesired side-effect I'm not seeing?

File: internal/app/singularity/capability_avail_linux.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+		return fmt.Errorf("Ignoring unknown capabilities: %s", ign)
```
Comment (mem) [inline internal/app/singularity/capability_avail_linux.go]: please note that formatting a slice like a string returns something like:

```
[a b c]
```

which might be confusing for the user. It might be better to do something like:

```
return fmt.Errorf("Ignoring unknown capabilities: %s", strings.Join(ign, ","))
```
so that it comes out in the same format as the input.

Also, this is not _ignoring_ those capabilities, it's bailing out completely without doing anything else so the wording of the message might need improving.

File: internal/app/singularity/capability_avail_linux.go [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+	}
+
+	if len(caps) > 0 && c.Caps != "" {
```
Comment (mem) [inline internal/app/singularity/capability_avail_linux.go]: same comment here regarding c.Caps != ""

File: internal/app/singularity/capability_avail_linux.go (hunk 1 above)
Comment (cclerget) [reply internal/app/singularity/capability_avail_linux.go]: Yep, will do that in `capabilities.Split` function as it's a side effect of `strings.Split`

File: internal/app/singularity/capability_avail_linux.go (hunk 2 above)
Comment (cclerget) [reply internal/app/singularity/capability_avail_linux.go]: removed `Ignoring` so `singularity capability avail chowned` end with error like `FATAL: Unable to list available capabilities: unknown capabilities found in: CAP_CHOWNED`

**Review by mem — APPROVED** [review]
Looks good! Thanks!
