### PR TITLE
fix 5211: don't mount home when --fakeroot and --contain are given

### LINKED ISSUE #5211: --fakeroot mounts home directory even if --contain is given
### Version of Singularity:

```
$ singularity version
3.5.2
```

### Expected behavior

I expect none of the content of my home directory to be available inside the container when using the `--contain` option.

### Actual behavior

When both `--fakeroot` and `--contain` are given the content of my home directory is available in `/root`

### Steps to reproduce this behavior

```
$ singularity exec --contain  library://sylabsed/examples/lolcow sh -c 'ls | wc -l'
0
$ singularity exec --fakeroot --contain  library://sylabsed/examples/lolcow sh -c 'ls | wc -l'
INFO:    Convert SIF file to sandbox...
29
INFO:    Cleaning up image...
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Source

### Additional info

If I understand correctly, it looks like the `--fakeroot` option automatically sets a custom home path to mount to `/root`.

https://github.com/sylabs/singularity/blob/4c5c507688906834799deb980a68089f57d8360c/cmd/internal/cli/actions_linux.go#L413-L416

That causes `addHomeStagingDir` to add the home directory even if `--contain` was given.
https://github.com/sylabs/singularity/blob/4c5c507688906834799deb980a68089f57d8360c/internal/pkg/runtime/engine/singularity/container_linux.go#L1582

I'm pretty sure `--fakeroot` + `--contain` mounting the home directory is a bug. The code also seems to suggest `--home` is intentionally respected even if `--contain` is given. I would have expected the opposite. I would have thought `--contain` would always take precedence, even going as far as it being an error if `--contain` and `--home` are both given.

### PR DESCRIPTION
**Pull request by sloretz**
## Description of the Pull Request (PR):

This is an attempt to fix #5211. It moves the logic mapping `host home -> /root` to avoid calling `SetCustomHome()`. It seems to fix the issue (manual testing); though, I'm unable to figure out how to run the regressions test suite. I can't say I'm confident the new regression test actually tests what it's supposed to.

### This fixes or addresses the following GitHub issues:

 - Fixes #5211

#### Before submitting a PR, make sure you have done the following:

- [x] Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
  - *Not sure it's necessary*
- [ ] Added tests to validate this PR and tested this PR locally with a `make testall`
  - *Added test, but unable to run e2e tests*. Not all tests pass running `make testall` on my machine, but I diff'd with test results on `master` to make sure no new tests failed.
- [x] Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- [x] Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

#### Run e2e tests locally?

I'm unable to run the e2e tests on my machine. Anything I need to set up beforehand?

<details><summary>e2e-test target output</summary>

```
> make -C builddir/ e2e-test
make: Entering directory '/home/sloretz/projects/singularity/builddir'
 TEST sudo go test [e2e]
=== RUN   TestE2E
    TestE2E: e2e.go:14: Running E2E tests for Singularity
    TestE2E: home_linux.go:123: failed to bind mount home directory: no such file or directory
        bind mounting source directory from "/home/sloretz/projects/singularity/installdir/var/singularity/mnt/session/root" to "/root"
        github.com/sylabs/singularity/e2e/internal/e2e.SetupHomeDirectories.func1
        	github.com/sylabs/singularity/e2e/internal/e2e/home_linux.go:122
        github.com/sylabs/singularity/e2e/internal/e2e.Privileged.func1
        	github.com/sylabs/singularity/e2e/internal/e2e/priv_linux.go:53
        github.com/sylabs/singularity/e2e/internal/e2e.SetupHomeDirectories
        	github.com/sylabs/singularity/e2e/internal/e2e/home_linux.go:143
        github.com/sylabs/singularity/e2e.Run
        	github.com/sylabs/singularity/e2e/suite.go:102
        github.com/sylabs/singularity/e2e.RunE2ETests
        	github.com/sylabs/singularity/e2e/e2e.go:15
        github.com/sylabs/singularity/e2e.TestE2E
        	github.com/sylabs/singularity/e2e/e2e_test.go:41
        testing.tRunner
        	testing/testing.go:991
        runtime.goexit
        	runtime/asm_amd64.s:1373
    TestE2E: suite.go:86: Test failed, not removing /tmp/stest.167854194
--- FAIL: TestE2E (0.00s)
FAIL
coverage: 33.8% of statements
FAIL	github.com/sylabs/singularity/e2e	0.038s
FAIL
Makefile:534: recipe for target 'e2e-test' failed
make: *** [e2e-test] Error 1
make: Leaving directory '/home/sloretz/projects/singularity/builddir'
```
</details>

### CODE REVIEW

**Review by dtrudg — COMMENTED** [review]
Hi @sloretz - thank you for the contribution. This fix looks logical to me.

Regarding the tests...

1) You will need to add a line here: 

https://github.com/sylabs/singularity/blob/2f8a931c1f81d0bcf44eee2d9f0ee4165de0d1fe/e2e/actions/actions.go#L2046

.. so that the test you have created runs. Once you do this it will run in the CircleCI flow here on the PR.

2) The error you posted in the PR comments might be due to the fact that your install directory is under the source tree. However, you said also that some tests don't run. Is the error you posted what you get, or did you have specific tests failing? The full test suite needs netcat `nc`, and docker available. What's you dev machine running distro wise?

**Comment by sloretz** [comment]
>     You will need to add a line here:

Rebased to fix merge conflict and added in 7d9bcb3.

> The error you posted in the PR comments might be due to the fact that your install directory is under the source tree. However, you said also that some tests don't run. Is the error you posted what you get, or did you have specific tests failing? The full test suite needs netcat nc, and docker available. What's you dev machine running distro wise?

I'm on an Ubuntu Bionic machine with docker, netcat, and nc commands available from the command line. I'll try installing to a prefix outside of the source directory and seeing if that resolves the issue.

The failing test using `make testall` is:

```
2310 --- FAIL: TestSecurity (6.05s)                                                                      
2311     --- PASS: TestSecurity/Security_unpriv (3.00s)                                                  
2312         --- PASS: TestSecurity/Security_unpriv/priv_Set_uid (0.48s)                                 
2313         --- PASS: TestSecurity/Security_unpriv/priv_Set_gid (0.48s)                                 
2314         --- PASS: TestSecurity/Security_unpriv/priv_SecComp_BlackList (0.62s)                       
2315         --- PASS: TestSecurity/Security_unpriv/priv_SecComp_true (0.47s)                            
2316         --- PASS: TestSecurity/Security_unpriv/priv_capabilities_keep (0.49s)                       
2317         --- PASS: TestSecurity/Security_unpriv/priv_capabilities_drop (0.46s)                       
2318     --- PASS: TestSecurity/Security_priv (2.08s)                                                    
2319         --- PASS: TestSecurity/Security_priv/unpriv_Set_uid (0.01s)                                 
2320         --- PASS: TestSecurity/Security_priv/unpriv_Set_gid (0.01s)                                 
2321         --- PASS: TestSecurity/Security_priv/unpriv_SecComp_BlackList (0.62s)                       
2322         --- PASS: TestSecurity/Security_priv/unpriv_SecComp_true (0.46s)                            
2323         --- PASS: TestSecurity/Security_priv/unpriv_capabilities_keep_true (0.02s)                  
2324         --- PASS: TestSecurity/Security_priv/unpriv_capabilities_keep-false (0.49s)                 
2325         --- PASS: TestSecurity/Security_priv/unpriv_capabilities_drop (0.47s)                       
2326     --- FAIL: TestSecurity/Security_config_ownerships (0.44s)                                       
2327         --- FAIL: TestSecurity/Security_config_ownerships/non_root_config (0.44s)                   
2328 FAIL                                                                                                
2329 coverage: 0.0% of statements                                                                        
2330 FAIL  github.com/sylabs/singularity/cmd/singularity 815.537s                                        
2331 ?     github.com/sylabs/singularity/cmd/starter [no test files]                                     
2332 ?     github.com/sylabs/singularity/cmd/starter/engines [no test files]                             
2333 ?     github.com/sylabs/singularity/docs  [no test files]                                           
2334 ?     github.com/sylabs/singularity/e2e [no test files]                                             
2335 ?     github.com/sylabs/singularity/e2e/actions [no test files]                                     
2336 ?     github.com/sylabs/singularity/e2e/buildcfg  [no test files]                                   
2337 ?     github.com/sylabs/singularity/e2e/cache [no test files]                                       
2338 ?     github.com/sylabs/singularity/e2e/cmdenvvars  [no test files]                                 
2339 ?     github.com/sylabs/singularity/e2e/config  [no test files]                                     
2340 ?     github.com/sylabs/singularity/e2e/delete  [no test files]                                     
2341 ?     github.com/sylabs/singularity/e2e/docker  [no test files]                                     
2342 ?     github.com/sylabs/singularity/e2e/env [no test files]                                         
2343 ?     github.com/sylabs/singularity/e2e/help  [no test files]                                       
2344 ?     github.com/sylabs/singularity/e2e/imgbuild  [no test files]                                   
2345 ?     github.com/sylabs/singularity/e2e/inspect [no test files]                                     
2346 ?     github.com/sylabs/singularity/e2e/instance  [no test files]                                   
2347 ?     github.com/sylabs/singularity/e2e/internal/e2e  [no test files]                               
2348 ?     github.com/sylabs/singularity/e2e/internal/e2e/init [no test files]                           
2349 ?     github.com/sylabs/singularity/e2e/internal/testhelper [no test files]                         
2350 ?     github.com/sylabs/singularity/e2e/key [no test files]                                                                                                                                                 
2351 ?     github.com/sylabs/singularity/e2e/oci [no test files]                                         
2352 ?     github.com/sylabs/singularity/e2e/plugin  [no test files]                                     
2353 ?     github.com/sylabs/singularity/e2e/pull  [no test files]                                       
2354 ?     github.com/sylabs/singularity/e2e/push  [no test files]                                       
2355 ?     github.com/sylabs/singularity/e2e/remote  [no test files]                                     
2356 ?     github.com/sylabs/singularity/e2e/run [no test files]                                         
2357 ?     github.com/sylabs/singularity/e2e/runhelp [no test files]                                     
2358 ?     github.com/sylabs/singularity/e2e/security  [no test files]                                   
2359 ?     github.com/sylabs/singularity/e2e/sign  [no test files]                                       
2360 ?     github.com/sylabs/singularity/e2e/verify  [no test files]                                     
2361 ?     github.com/sylabs/singularity/e2e/version [no test files]  
```

**Comment by sloretz** [comment]
I'm able to run the e2e tests locally after using a different install prefix, and I'm now confident the test does what it's supposed to. It passes with the fix, and fails without it.

I don't know why this other test on CI failed though. Is it a known flaky test, or did this PR definitely break it?

https://travis-ci.org/github/sylabs/singularity/jobs/677830665#L3991-L4036

**Review by dtrudg — DISMISSED** [review]
Thanks for the contribution. This looks good to me.

**Comment by dtrudg** [comment]
> I don't know why this other test on CI failed though. Is it a known flaky test, or did this PR definitely break it?
> 
> https://travis-ci.org/github/sylabs/singularity/jobs/677830665#L3991-L4036

I'm confident that this is unrelated to the change here. Unfortunately the test under Travis frequently encounter issues.

**Review by dtrudg — DISMISSED** [review]
Apologies - I failed to check something up while testing this a minute ago... then thought of it...

The value of  `$HOME` in the container doesn't get set to `/root` with this new code path....

```
dave@piran~/S/G/singularity> /usr/local/bin/singularity run --fakeroot --contain docker://alpine
INFO:    Using cached SIF image
INFO:    Convert SIF file to sandbox...
Singularity> cd
/bin/sh: cd: can't cd to /home/dave: No such file or directory
Singularity> 
```

On the `master` branch...

```
dave@piran~/S/G/singularity> /usr/local/bin/singularity run --fakeroot --contain docker://alpine
INFO:    Using cached SIF image
INFO:    Convert SIF file to sandbox...
Singularity> cd
Singularity> pwd
/root
```

**Comment by sloretz** [comment]
> Apologies - I failed to check something up while testing this a minute ago... then thought of it...

No worries. What's the deadline to get changes into the next release? It will be a few days before I'm able to return to this.

File: internal/pkg/runtime/engine/singularity/container_linux.go [hunk 1]
```diff
@@ -1560,8 +1560,12 @@ func (c *container) getHomePaths() (source string, dest string, err error) {
 	} else {
 		pw, err := user.Current()
```
Comment (cclerget) [inline internal/pkg/runtime/engine/singularity/container_linux.go]: It should also be `user.CurrentOriginal` to get the real user ID because fakeroot when used with unprivileged installation always return root as current user here since this process is running inside fakeroot user namespace

**Comment by dtrudg** [comment]
> > Apologies - I failed to check something up while testing this a minute ago... then thought of it...
> 
> No worries. What's the deadline to get changes into the next release? It will be a few days before I'm able to return to this.

We are going to issue an RC this week. Either we'll leave it out of the first RC, or we can make the changes and push to the branch. Cheers.

**Comment by dtrudg** [comment]
I'm going to start pushing some things here to get this finished. Please let me know @sloretz if you are working on it. I'm starting here by pushing a failing test for the issue that I noticed - so we can verify that a change fixes that.

**Comment by dtrudg** [comment]
The additional commits you see above this message, authored by you and committed by me, are a result of a rebase against `master`. This was needed because the is a change in one of the images in the library used by our tests, which causes a problem already fixed: #5238

**Comment by dtrudg** [comment]
Here is the output of the test case that is correctly failing now:

```
            --- FAIL: TestE2E/PAR/ACTIONS/issue_5211 (2.03s)
                singularitycmd.go:663: Running command "/usr/local/bin/singularity exec --fakeroot --contain /tmp/stest.178330210/test.sif test ! -d /root/singularity-issue5211-dir-189935690"
                singularitycmd.go:663: Running command "/usr/local/bin/singularity exec --fakeroot --contain /tmp/stest.178330210/test.sif sh -c echo $HOME"
                singularitycmd.go:663: failed to match pattern: Command "/usr/local/bin/singularity exec --fakeroot --contain /tmp/stest.178330210/test.sif sh -c echo $HOME":
                    Expect output stream exact match:
                    /root
                    Command output output:
                    /home/circleci
```

File: e2e/actions/regressions.go [hunk 2]
```diff
@@ -335,3 +335,40 @@ func (c actionTests) issue5228(t *testing.T) {
...
+
+	// Make non-hidden file in host home to check if it was mounted in container
+	canaryDir, cleanup := e2e.MakeTempDir(t, u.Dir, "singularity-issue5211-dir-", "")
+	defer cleanup(t)
+
+	canaryBasename := filepath.Base(canaryDir)
+
+	c.env.RunSingularity(
+		t,
+		e2e.WithProfile(e2e.UserProfile),
```
Comment (cclerget) [inline e2e/actions/regressions.go]: You can use `e2e.FakerootProfile` instead to skip test automatically on system not supporting user namespaces or not configured for fakeroot

File: e2e/actions/regressions.go [hunk 3]
```diff
@@ -335,3 +335,40 @@ func (c actionTests) issue5228(t *testing.T) {
...
+		e2e.WithDir(u.Dir),
+		e2e.WithCommand("exec"),
+		e2e.WithArgs("--fakeroot", "--contain", c.env.ImagePath, "test", "!", "-d", filepath.Join("/root", canaryBasename)),
+		e2e.ExpectExit(0),
+	)
+
+	// Check we preserve `$HOME` as /root even when we `--contain` with `--fakeroot`
+	c.env.RunSingularity(
+		t,
+		e2e.WithProfile(e2e.UserProfile),
```
Comment (cclerget) [inline e2e/actions/regressions.go]: Same

File: e2e/actions/regressions.go [hunk 4]
```diff
@@ -335,3 +335,40 @@ func (c actionTests) issue5228(t *testing.T) {
...
+	defer cleanup(t)
+
+	canaryBasename := filepath.Base(canaryDir)
+
+	c.env.RunSingularity(
+		t,
+		e2e.WithProfile(e2e.UserProfile),
+		e2e.WithDir(u.Dir),
+		e2e.WithCommand("exec"),
+		e2e.WithArgs("--fakeroot", "--contain", c.env.ImagePath, "test", "!", "-d", filepath.Join("/root", canaryBasename)),
```
Comment (cclerget) [inline e2e/actions/regressions.go]: So you could remove `--fakeroot` option

File: e2e/actions/regressions.go [hunk 5]
```diff
@@ -335,3 +335,40 @@ func (c actionTests) issue5228(t *testing.T) {
...
+		e2e.ExpectExit(0),
+	)
+
+	// Check we preserve `$HOME` as /root even when we `--contain` with `--fakeroot`
+	c.env.RunSingularity(
+		t,
+		e2e.WithProfile(e2e.UserProfile),
+		e2e.WithDir(u.Dir),
+		e2e.WithCommand("exec"),
+		e2e.WithArgs("--fakeroot", "--contain", c.env.ImagePath, "sh", "-c", "echo $HOME"),
```
Comment (cclerget) [inline e2e/actions/regressions.go]: Idem for `--fakeroot` removal with `e2e.FakerootProfile`

**Review by cclerget — CHANGES_REQUESTED** [review]
LGTM after fixing e2e test to use `e2e.FakerootProfile`

**Review by tri-adam — APPROVED** [review]
LGTM

**Review by cclerget — APPROVED** [review]

**Comment by dtrudg** [comment]
Test failure observed in CircleCI is in unrelated OCI tests. Not reproducible and recorded here: #5258

**Comment by dtrudg** [comment]
Thanks @sloretz for you contribution. Merging this!

**Comment by sloretz** [comment]
Thank you @dctrud for finishing this! :rocket: :tada: Sorry I disappeared.

**Comment by dtrudg** [comment]
@sloretz - No problem! Thanks for your contribution! Cheers.
