### PR TITLE
Fix integer overflow on 32 bits system in fakeroot package

### LINKED ISSUE #4005: 32 bit compilation failed
## Version of Singularity:

Master and 3.3.0-rc3

### Expected behavior

Compile Singularity successfully

### Actual behavior

```
build flag -mod=vendor only valid when using modules
build flag -mod=vendor only valid when using modules
 GO singularity
    [+] GO_TAGS "containers_image_openpgp sylog imgbuild_engine oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
 GEN etc/bash_completion.d/singularity
 GEN singularity.conf from /usr/local/etc/singularity/singularity.conf
 GO clean -cache
 GO cmd/starter/c/starter
# github.com/sylabs/singularity/internal/pkg/fakeroot
../internal/pkg/fakeroot/fakeroot.go:209:8: constant 4294901760 overflows int
Makefile:231: recipe for target 'cmd/starter/c/starter' failed
make: *** [cmd/starter/c/starter] Error 2
```

### Steps to reproduce behavior

Compile Singularity on a 32 bit system

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Fix constant variable typed `int` instead of `uint32`

**This fixes or addresses the following GitHub issues:**

- Fixes #4005

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by WestleyK — APPROVED** [review]
Compiles fine on a 32bit system, and I can build a container with `--fakeroot` :+1:

**Comment by cclerget** [comment]
Thanks for testing/review :+1:

**Review by ikaneshiro — APPROVED** [review]

File: internal/pkg/fakeroot/fakeroot.go [hunk 1]
```diff
@@ -25,11 +25,11 @@ const (
 	// SubGIDFile is the default path to the subgid file.
 	SubGIDFile = "/etc/subgid"
 	// validRangeCount is the valid fakeroot range count.
-	validRangeCount = 65536
+	validRangeCount = uint32(65536)
 	// StartMax is the maximum possible range start.
-	startMax = 4294967296 - validRangeCount
+	startMax = uint32(4294901760)
```
Comment (mem) [inline internal/pkg/fakeroot/fakeroot.go]: I would suggest you keep the arithmetic from before just to make it a little clear where the number is coming from.

I would even suggest writing this as:

```
validRangeCount = uint32(1 << 16)
startMax = uint32(1 << 32) - validRangeCount
```

**Review by mem — DISMISSED** [review]
hit the wrong button

File: internal/pkg/fakeroot/fakeroot.go (hunk 1 above)
Comment (mem) [reply internal/pkg/fakeroot/fakeroot.go]: sorry, that doesn't work, as 1 << 32 will overflow uint32.

There's the very awkward `uint32(1 << 32 - 1) - validRangeCount + 1` or the other option of `^uint32(0) - validRangeCount + 1`.

Comment (cclerget) [reply internal/pkg/fakeroot/fakeroot.go]: Are you training for a code obfuscation contest ?
