### PR TITLE
Remove master socket file descriptor from Go netpoll in stage 2 (#5946)

### LINKED ISSUE #5946: Singularity fails when large environment is sourced
### Version of Singularity:

```
> singularity --version
singularity version 3.7.3-1

```

### Expected behavior

```
> repeat 100 singularity exec sles12sp5.sif uptime
16:22pm  up 58 days 16:19,  0 users,  load average: 49.79, 49.44, 49.30
16:22pm  up 58 days 16:19,  0 users,  load average: 50.92, 49.71, 49.39
```

### Actual behavior
```
> repeat 100 singularity exec sles12sp5.sif uptime

runtime: netpoll: break fd ready for 16
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x555c126b9e27, 0x39)
        runtime/panic.go:1116 +0x74
runtime.netpoll(0x0, 0x0)
        runtime/netpoll_epoll.go:149 +0x2ee
runtime.sysmon()
        runtime/proc.go:4714 +0x34f
runtime.mstart1()
        runtime/proc.go:1172 +0xca
runtime.mstart()
        runtime/proc.go:1137 +0x6f

goroutine 1 [runnable, locked to thread]:
github.com/sylabs/singularity/internal/pkg/util/shell/interpreter.GetEnv.func1(0xc000179950, 0x2d, 0x1000100, 0xc00017997e, 0x60, 0x0, 0x0, 0x0, 0x0, 0x1)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/util/shell/interpreter/interpreter.go:93 +0x50
mvdan.cc/sh/v3/expand.listEnviron.Each(0xc00038a000, 0xaac, 0xc00, 0xc000228970)
        mvdan.cc/sh/v3@v3.2.1/expand/environ.go:206 +0x15d
mvdan.cc/sh/v3/interp.overlayEnviron.Each(0x555c12a7a6c0, 0xc000322180, 0xc000133920, 0xc000228970)
        mvdan.cc/sh/v3@v3.2.1/interp/vars.go:33 +0x5b
github.com/sylabs/singularity/internal/pkg/util/shell/interpreter.GetEnv(0x555c12a7a740, 0xc000322800, 0xc00019ab40, 0x14, 0x555c12a73e60, 0xc0001b0000, 0x555c12a72ec0, 0xc0001eb430, 0x555c12a73ea0, 0xc0001b0010, ...)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/util/shell/interpreter/interpreter.go:92 +0x96
github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity.getAllEnvBuiltin.func1(0x555c12a80fc0, 0xc000133950, 0xc000228920, 0x0, 0x0, 0x1, 0x0)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/runtime/engine/singularity/process_linux.go:716 +0x17c
github.com/sylabs/singularity/internal/pkg/util/shell/interpreter.(*Shell).internalExecHandler.func1(0x555c12a80fc0, 0xc000133950, 0xc000228920, 0x1, 0x1, 0xc000228920, 0x555c1264d21e)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/util/shell/interpreter/interpreter.go:153 +0x37f
mvdan.cc/sh/v3/interp.(*Runner).exec(0xc000110400, 0x555c12a80f40, 0xc00019c008, 0xc000228920, 0x1, 0x1)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:753 +0x8a
mvdan.cc/sh/v3/interp.(*Runner).call(0xc000110400, 0x555c12a80f40, 0xc00019c008, 0x1f000300000029, 0xc000228920, 0x1, 0x1)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:749 +0x405
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc000110400, 0x555c12a80f40, 0xc00019c008, 0x555c12a7edc0, 0xc000396a80)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:345 +0x14c8
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc000110400, 0x555c12a80f40, 0xc00019c008, 0xc000398058)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:285 +0x312
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc000110400, 0x555c12a80f40, 0xc00019c008, 0xc000398058)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:266 +0x1e7
mvdan.cc/sh/v3/interp.(*Runner).stmts(0xc000110400, 0x555c12a80f40, 0xc00019c008, 0xc00039e000, 0x1, 0x4)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:603 +0x58
mvdan.cc/sh/v3/interp.(*Runner).fillExpandConfig.func1(0x555c12a72ec0, 0xc0001eb430, 0xc0001805a0, 0xc00020d0c8, 0x555c1264c689)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:49 +0xe6
mvdan.cc/sh/v3/expand.(*Config).cmdSubst(0xc0001eb400, 0xc0001805a0, 0x3, 0x0, 0x0, 0x0)
        mvdan.cc/sh/v3@v3.2.1/expand/expand.go:500 +0x70
mvdan.cc/sh/v3/expand.(*Config).wordField(0xc0001eb400, 0xc0000ab420, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        mvdan.cc/sh/v3@v3.2.1/expand/expand.go:471 +0x9d3
mvdan.cc/sh/v3/expand.Literal(0xc0001eb400, 0xc000224c30, 0x0, 0x0, 0x0, 0x0)
        mvdan.cc/sh/v3@v3.2.1/expand/expand.go:143 +0x7a
mvdan.cc/sh/v3/interp.(*Runner).literal(0xc000110200, 0xc000224c30, 0x10, 0x0)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:155 +0x45
mvdan.cc/sh/v3/interp.(*Runner).assignVal(0xc000110200, 0xc0001323c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        mvdan.cc/sh/v3@v3.2.1/interp/vars.go:263 +0x955
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc000110200, 0x555c12a80f40, 0xc00019c008, 0x555c12a7ef00, 0xc000322200)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:517 +0x1fd6
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc000110200, 0x555c12a80f40, 0xc00019c008, 0xc000398000)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:285 +0x312
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc000110200, 0x555c12a80f40, 0xc00019c008, 0xc000398000)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:266 +0x1e7
mvdan.cc/sh/v3/interp.(*Runner).stmts(0xc000110200, 0x555c12a80f40, 0xc00019c008, 0xc0001fe400, 0x16, 0x20)
        mvdan.cc/sh/v3@v3.2.1/interp/runner.go:603 +0x58
mvdan.cc/sh/v3/interp.(*Runner).Run(0xc000110200, 0x555c12a80f40, 0xc00019c008, 0x555c12a79a40, 0xc0000ce840, 0xc0000ce840, 0x0)
        mvdan.cc/sh/v3@v3.2.1/interp/api.go:504 +0x2ea
github.com/sylabs/singularity/internal/pkg/util/shell/interpreter.(*Shell).Run(0xc0000ce800, 0xc000132360, 0x555c12691155)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/util/shell/interpreter/interpreter.go:223 +0x145
github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity.runActionScript(0xc0001a9220, 0x17, 0x0, 0x0, 0x12, 0x0, 0x7f976e79f548, 0x8, 0x80)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/runtime/engine/singularity/process_linux.go:831 +0x775
github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity.(*EngineOperations).StartProcess(0xc000228860, 0x555c12a85c20, 0xc000010c50, 0x0, 0x0)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/runtime/engine/singularity/process_linux.go:171 +0x5ac
github.com/sylabs/singularity/internal/app/starter.StageTwo(0x4, 0xc00000e0c0)
        github.com/sylabs/singularity@v0.0.0/internal/app/starter/stage_linux.go:58 +0x15b
main.startup.func1()
        command-line-arguments/main_linux.go:64 +0x3c
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
        github.com/sylabs/singularity@v0.0.0/internal/pkg/util/mainthread/mainthread.go:21 +0x31
main.main()
        command-line-arguments/main_linux.go:106 +0x62

goroutine 5 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc000021e20)
        github.com/sylabs/singularity@v0.0.0/internal/pkg/util/mainthread/mainthread.go:24 +0xb6
main.startup()
        command-line-arguments/main_linux.go:63 +0x24f
created by main.main
        command-line-arguments/main_linux.go:102 +0x37

goroutine 6 [runnable]:
os/signal.loop()
        os/signal/signal_unix.go:21
created by os/signal.Notify.func1.1
        os/signal/signal.go:150 +0x46
```

### Steps to reproduce this behavior

Our environment has 2727 entries using 629,101 bytes. When the environment is sourced and singularity is executed, the above error is seen, but not consistently. Out of 100 executions, up to 10% see the issue only on machines with a higher load average. 

It seems that we are only able to reproduce this issue with both the large environment _and_ on a machine with a higher load average (load > cores). 

### What OS/distro are you running

We have tested and seen this error on SLES12-SP2, SLES12-SP5 and SLES15-SP2. 

### How did you install Singularity

rpmbuild -tb singularity-3.7.3.tar.gz
rpm -ivh /usr/src/packages/RPMS/x86_64/singularity-3.7.3-1.x86_64.rpm

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Based on report from #5946 the issue seems related to the masterConn socket here https://github.com/hpcng/singularity/blob/eb85a9a928a2368a610004d4ad382be9061a452b/internal/pkg/runtime/engine/singularity/process_linux.go#L58
staying open until the container process is executed or closed explicitly, this is a requirement to communicate with the parent process and can only be closed after the execution of the container process.

What happen here is that the stage2 common code create a `net.FileConn` from the master socket descriptor here https://github.com/hpcng/singularity/blob/eb85a9a928a2368a610004d4ad382be9061a452b/internal/app/starter/stage_linux.go#L46
therefore the file descriptor become part of the netpoll fds.

This PR removes master socket file descriptor from Go runtime netpoll by not using `net.FileConn`.

### This fixes or addresses the following GitHub issues:

 - Fixes #5946

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/hpcng/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/hpcng/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/hpcng/singularity/blob/master/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/runtime/engine/oci/process_linux.go [hunk 1]
```diff
@@ -57,6 +57,13 @@ func (e *EngineOperations) StartProcess(masterConn net.Conn) error {
 		return err
 	}
 
+	comm := os.NewFile(uintptr(masterConnFd), "master-socket")
```
Comment (cclerget) [inline internal/pkg/runtime/engine/oci/process_linux.go:60]: The OCI engine doesn't use the shell interpreter and globally doesn't pass large environment, so it should be less impacted by this issue, therefore I kept `net.FileConn` here to reduce the changes in this PR

**Review by DrDaveD — APPROVED** [review]
This looks very low risk in that it only moves the place where net.FileConn is run, and is a definite improvement.  It's not known yet whether or not it definitely fixes the problem, but it's a good change in any case.

**Comment by DrDaveD** [comment]
For reference, Sylabs responded to this problem with a different fix in their [pr #8](https://github.com/sylabs/singularity/pull/8)
