### PR TITLE
Use a sensible hash for http(s) source caching

### LINKED ISSUE #4823: Net cache leads to running incorrect container (not using a good hash)
### Version of Singularity:

What version of Singularity are you using? Run:

```
Reported on 3.3.0 - verified on all above
```

### Actual behavior

If you `singularity shell http://example.com/container1/v1.sif` it will be cached in `net/hash/v1.sif`.

If you then `singularity shell http://example.com/container2/v1.sif` it will run the `container1/v1.sif` cached image, not the `container2/v1.sif` image that you expect.

The net cache introduced in #2346 is basing the cache filename on the final part of the URI only.

To avoid clashes, the obvious thing that comes to mind is taking a sha256 over:

`Full URL` + `HTTP date response header`

Then the code doing the GET can compute that to check if there's something already in the cache without downloading the whole file. Some endpoints (like object stores) might have a way of getting a real content hash, or always return one in headers - but we can't assume this is the case for hosting on a standard http server... or considering all the object store protocols out there. The HTTP Date header is the closest thing I can come up with to a proxy for 'is the the same thing at this URL'.

If there's no date header available then always download again.

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

The existing caching for `http` and `https` sources uses the final part of the URL as the key for the image within the cache. This means that `http://example.com/container1/v1.sif` and `http://example.com/container2/v1.sif` result in the same cache key, and unexpected behaviour as in #4823.

We will cache using a sha256 over the URL and the date of the file that is to be
fetched, as returned by an HTTP HEAD call. If no date is available, use the current
date-time, which will effectively result in no caching.

### This fixes or addresses the following GitHub issues:

 - Fixes: #4823

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/actions.go [hunk 1]
```diff
@@ -290,11 +294,35 @@ func handleShub(imgCache *cache.Handle, u string) (string, error) {
...
-	imageName := refParts[len(refParts)-1]
-	imagePath := imgCache.NetImage("hash", imageName)
+	// We will cache using a sha256 over the URL and the date of the file that
+	// is to be fetched, as returned by an HTTP HEAD call and the Last-Modified
+	// header. If no date is available, use the current date-time, which will
+	// effectively result in no caching.
+	imageDate := time.Now().String()
 
-	exists, err := imgCache.NetImageExists("hash", imageName)
+	req, err := http.NewRequest("HEAD", u, nil)
```
Comment (cclerget) [inline cmd/internal/cli/actions.go:303]: Maybe trim `http://`, `https://` from the hash as some server allow access via http and/or redirect http to https

Comment (dtrudg) [reply cmd/internal/cli/actions.go:303]: That's true - but equally a crazy setup could serve different things on http and http(s). That would be really stupid and unlikely, but I'd rather err on the side of re-downloading an image unless you feel strongly about this?

Comment (cclerget) [reply cmd/internal/cli/actions.go:303]: Not really it was just a suggestion

File: e2e/actions/regressions.go [hunk 2]
```diff
@@ -213,3 +218,100 @@ func (c actionTests) issue4836(t *testing.T) {
...
+		{
+			name:         "http_c2v1.sif_touched_uncached",
+			urlPath:      "/c1/v1.sif",
+			touchFile:    true,
+			expectCached: false,
+		},
+		// Different URL - not cached
+		{
+			name:         "http_c2v2.sif_uncached",
+			urlPath:      "/c1/v2.sif",
```
Comment (ikaneshiro) [inline e2e/actions/regressions.go]: Should this url be `/c2/v1.sif` instead? If the cache was keyed with just the last part of the url, as it was previously, then wouldn't cause a collision if I understand the issue correctly

**Comment by dtrudg** [comment]
CI failure seems to be a network issue - rerunning:
```
Error initializing source oci:/tmp/stest.689162124/e2e-imgcache-388157803/cache/oci:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a: Error writing blob: read tcp 10.142.0.47:59836->104.18.122.25:443: read: connection reset by peer
```

**Review by ikaneshiro — COMMENTED** [review]
Caching approach lgtm

File: e2e/actions/regressions.go (hunk 2 above)
Comment (dtrudg) [reply e2e/actions/regressions.go]: Yes - you are correct. Good spot, and :man_facepalming: from me seeing as this is what the test is meant to be for

**Review by ikaneshiro — APPROVED** [review]
