### PR TITLE
Adjust container capabilities based on latest capability available

### LINKED ISSUE #5305: Regression: error building image with --fakeroot
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version

```
`3.6.0~rc.3-1.el7`

### Expected behavior
It should build an image

### Actual behavior
```
There is an error message:
% singularity build --fakeroot -s test/ sl77.def
ERROR  : Requesting capability set 0x0000003fffffffff while permitted capability set is 0x0000001fffffffff
```

### Steps to reproduce this behavior
Try to build an image from a receipt file: 

# What OS/distro are you running

```
$ cat /etc/os-release


```
```
NAME="Scientific Linux"
VERSION="7.7 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.7"
PRETTY_NAME="Scientific Linux 7.7 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.7:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

```
### How did you install Singularity
rpm built from source

This didn't produce an error in rc.2, but it regressed in rc.3.

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

This PR clear bits in all set of capabilities to match the last available capability of the system and fix regression observed in #5305. This is precaution done in C starter code but ideally capabilities should be already set correctly from Go inside runtime engines, this is a technical debt to fix for a next release as it involves a biggest PR.

### This fixes or addresses the following GitHub issues:

 - Fixes #5305 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/starter/c/starter.c [hunk 1]
```diff
@@ -214,12 +214,13 @@ static struct capabilities *get_process_capabilities() {
...
-    for ( last_cap = CAPSET_MAX; ; last_cap-- ) {
-        if ( prctl(PR_CAPBSET_READ, last_cap) > 0 || last_cap == 0 ) {
+    for ( last_cap = CAPSET_MIN; last_cap <= CAPSET_MAX; last_cap++ ) {
+        if ( prctl(PR_CAPBSET_READ, last_cap) < 0 ) {
+            /* an error means that capability is not valid, take the last valid */
             break;
         }
     }
-    return last_cap;
+    return --last_cap;
```
Comment (dtrudg) [inline cmd/starter/c/starter.c:223]: If `CAPSET_MAX=37` is the true highest cap, then shouldn't we be returning `last_cap` instead of `last_cap--` if we reach it in the loop? Or have I misunderstood? Thanks.

Comment (cclerget) [reply cmd/starter/c/starter.c:223]: When completing the loop `for ( last_cap = CAPSET_MIN; last_cap <= CAPSET_MAX; last_cap++ )` `last_cap` is 38 to match `<=` condition, if an error occurs with `last_cap = 37` during prctl call it means max is 36, so `last_cap` need to be decremented in all cases

Comment (dtrudg) [reply cmd/starter/c/starter.c:223]: yes, sorry - silly misread of the loop condition on my part. Apologies!

**Review by dtrudg — APPROVED** [review]
LGTM
