### PR TITLE
Dont Store Public Key When Verifying a Container

### LINKED ISSUE #2579: Verify Should Check for Updates to PGP Public Key
## Version of Singularity:

3.0.2

### Expected behavior

When `singularity verify` is done on a signed container, and the public key used to sign the image is not present in the local key store, it is fetched from the Key Service. A subsequent `singularity verify` that uses the same public key should check with the Key Service that the key has not been updated (or revoked), and act accordingly.

### Actual behavior

Subsequent `singularity verify` commands do not check that the key has not been updated (or revoked.)

### Steps to reproduce behavior

Generate a PGP key pair, and sign a container with the private key. Store the public key, and push it to the Key Service. Verify `singularity verify` works. Revoke the key and push an update to the Key Service. Observe that `singularity verify` still works, and that the public key stored in `~/.singularity/sypgp/pgp-public` has not been updated.

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

When you verify a container, Singularity will **not** store that public key, (if you want to store it, you need to download it `singularity key pull ...`)

<br>

## This fixes or addresses the following GitHub issues:

- Fixes #2579 

<br>

### CODE REVIEW

File: pkg/signing/signing.go [hunk 1]
```diff
@@ -311,29 +312,81 @@ func Verify(cpath, url string, id uint32, isGroup bool, authToken string, noProm
 			return fmt.Errorf("could not get the signing entity fingerprint: %s", err)
 		}
 
-		// try to verify with local OpenPGP store first
-		signer, err := openpgp.CheckDetachedSignature(elist, bytes.NewBuffer(block.Bytes), block.ArmoredSignature.Body)
+		//fmt.Printf("fingerptinyOOOOOOOOOO: %v\n", fingerprint)
+
+		// remove the local key that signed the container
+		if err := sypgp.RemovePupKey(fingerprint); err != nil {
```
Comment (mem) [inline pkg/signing/signing.go]: RemovePubKey? (instead of pup)

File: pkg/signing/signing.go [hunk 2]
```diff
@@ -311,29 +312,81 @@ func Verify(cpath, url string, id uint32, isGroup bool, authToken string, noProm
...
+			return fmt.Errorf("could not fetch public key from server: %s", err)
+		}
+		//sylog.Infof("key retrieved successfully!")
+		//fmt.Printf("netList type: %T\n", netlist)
 
-			block, _ := clearsign.Decode(data)
-			if block == nil {
-				return fmt.Errorf("failed to parse signature block")
-			}
+		block, _ = clearsign.Decode(data)
```
Comment (mem) [inline pkg/signing/signing.go]: I might be missing something here. Unless the operation on line 324 (or this one) has a side-effect, why does this need to be called in the middle of fetching and storing the public key? Is the fetch making the new public key available to openpgp somehow? If yes, I think a comment in the code would help. If not, can this be moved after the call to sypgp.StorePubKey?

File: pkg/signing/signing.go [hunk 3]
```diff
@@ -311,29 +312,81 @@ func Verify(cpath, url string, id uint32, isGroup bool, authToken string, noProm
...
+		}
+
+		// verify the container
+		signer, err := openpgp.CheckDetachedSignature(netlist, bytes.NewBuffer(block.Bytes), block.ArmoredSignature.Body)
+		if err != nil {
+			return fmt.Errorf("signature verification failed: %s", err)
+		}
 
-			if noPrompt {
+//		sylog.Infof("key missing, searching key server for KeyID: %s...", fingerprint[24:])
```
Comment (mem) [inline pkg/signing/signing.go]: Is the commented-out code needed? Can it be removed?

File: pkg/sypgp/sypgp.go [hunk 4]
```diff
@@ -349,6 +350,68 @@ func StorePubKey(e *openpgp.Entity) (err error) {
 	return
 }
 
+// compareLocalPubKey : compares a key ID with a string. return true if the
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: Usually godoc strings should read like a sentence (so that when formatting them using go doc it comes out nicely).

For example:

    // compareLocalPubKey compares a key ID with a string, returning true if the
    // key and oldToken do not match.

Also, because of the name of the function, I would expect it to return true if they do match. Please consider changing the name of the function (or inverting the sense of the return value so that it matches the name of the function).

File: pkg/sypgp/sypgp.go [hunk 5]
```diff
@@ -349,6 +350,68 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+// key / oldToken *dont* match.
+func compareLocalPubKey(e *openpgp.Entity, oldToken string) bool {
+	if fmt.Sprintf("%X", e.PrimaryKey.Fingerprint) != oldToken {
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: note that you are evaluating a boolean to return a boolean. In other words, you have this structure:

    if condition {
        return true
    }
    return false

that's equivalent to:

    return cond

File: pkg/sypgp/sypgp.go [hunk 6]
```diff
@@ -349,6 +350,68 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+		return true
+	}
+	return false
+}
+
+// RemovePupKey : will delete all keys with the ID of (toDelete string)
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: Same comment regarding godoc strings.

File: pkg/sypgp/sypgp.go [hunk 7]
```diff
@@ -349,6 +350,68 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+func RemovePupKey(toDelete string) error {
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: So... it's intentional :-)

What's a "pup key"?

File: pkg/sypgp/sypgp.go [hunk 8]
```diff
@@ -349,6 +350,68 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+	if err != nil {
+		return fmt.Errorf("unable to read keyring: %v", err)
+	}
+
+	var newKeyList []openpgp.Entity
+
+	// sort throught them, and remove any that match toDelete
+	for i := range elist {
+		// if the elist[i] dose not match toDelete, then add it to newKeyList
+		if compareLocalPubKey(elist[i], toDelete) {
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: this is what I meant before: only looking at this code, I would flag a bug, as it suggests that it's removing everything _but_ whatever matches `toDelete`.

File: pkg/sypgp/sypgp.go [hunk 9]
```diff
@@ -349,6 +350,68 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+			newKeyList = append(newKeyList, *elist[i])
+		}
+	}
+
+	// delete all the local public keys... scary :O
+	// to my knowledge, there is no other way to do this...
+	sylog.Infof("Updating local keyring: %v", PublicPath())
+	os.Remove(PublicPath())
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: Uh...

I guess this works, on Linux, at least. On Windows it definitely doesn't. I would expect it to work on Mac OS, too.

Instead of this, since you have all the keys in memory, I would close the file and open it for writing passing O_TRUNC. That saves you from having to try to preserve the permissions.

Because of line 365, I think there's an expectation that the file already exists.

**Review by mem — CHANGES_REQUESTED** [review]

File: pkg/signing/signing.go (hunk 3 above)
Comment (WestleyK) [reply pkg/signing/signing.go]: Yes, Theres a lot of commented code that can/will be removed! *(wip)*

File: pkg/sypgp/sypgp.go (hunk 4 above)
Comment (WestleyK) [reply pkg/sypgp/sypgp.go]: On it! 
And yes, I know the true/false is backwards... fixing that.

File: pkg/sypgp/sypgp.go (hunk 7 above)
Comment (WestleyK) [reply pkg/sypgp/sypgp.go]: Short for `public key`, as oppose `private key`... I think :thinking:

File: pkg/signing/signing.go (hunk 1 above)
Comment (WestleyK) [reply pkg/signing/signing.go]: Typo, good find! :+1:

File: pkg/signing/signing.go [hunk 10]
```diff
@@ -281,14 +281,12 @@ func Verify(cpath, url string, id uint32, isGroup bool, authToken string, noProm
 	// the selected data object is hashed for comparison against signature block's
 	sifhash := computeHashStr(&fimg, descr)
 
-	// load the public keys available locally from the cache
-	elist, err := sypgp.LoadPubKeyring()
-	if err != nil {
-		return fmt.Errorf("could not load public keyring: %s", err)
-	}
+	var authok string
```
Comment (jchavezlavalle) [inline pkg/signing/signing.go]: typo: authok -> author

File: pkg/sypgp/sypgp.go [hunk 11]
```diff
@@ -349,6 +349,83 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+// key and oldToken match.
+func compareLocalPubKey(e *openpgp.Entity, oldToken string) bool {
+	if fmt.Sprintf("%X", e.PrimaryKey.Fingerprint) == oldToken {
+		return true
+	}
+	return false
+}
+
+// CheckLocalPubKey : will check if we have a local public key matching ckey stirng
+// returns true if theres a match.
```
Comment (jchavezlavalle) [inline pkg/sypgp/sypgp.go]: theres -> there's

File: pkg/sypgp/sypgp.go [hunk 12]
```diff
@@ -349,6 +349,83 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+func CheckLocalPubKey(ckey string) (bool, error) {
+	//f, err := os.OpenFile(PublicPath(), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
```
Comment (jchavezlavalle) [inline pkg/sypgp/sypgp.go]: remove commented code

File: pkg/sypgp/sypgp.go [hunk 13]
```diff
@@ -349,6 +349,83 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+	// read all the local public keys
+	elist, err := openpgp.ReadKeyRing(f)
+	if err != nil {
+		return false, fmt.Errorf("unable to list local keyring: %v", err)
+	}
+
+	for i := range elist {
+		if compareLocalPubKey(elist[i], ckey) {
+			return true, nil
+		}
```
Comment (jchavezlavalle) [inline pkg/sypgp/sypgp.go:385]: lines 378 to 382 could be changed to:

```
return compareLocalPubKey(elist[i], ckey), nil
```

File: pkg/sypgp/sypgp.go [hunk 14]
```diff
@@ -349,6 +349,83 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+	for i := range elist {
+		// if the elist[i] dose not match toDelete, then add it to newKeyList
+		if !compareLocalPubKey(elist[i], toDelete) {
+			newKeyList = append(newKeyList, *elist[i])
+		}
+	}
+
+	sylog.Infof("Updating local keyring: %v", PublicPath())
+
+	// truncate all the public keys... scary :O
```
Comment (jchavezlavalle) [inline pkg/sypgp/sypgp.go]: remove this comment :smile:

File: pkg/sypgp/sypgp.go [hunk 15]
```diff
@@ -349,6 +349,83 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+	// to my knowledge, there is no other way to do this...
+	nf, err := os.OpenFile(PublicPath(), os.O_TRUNC|os.O_WRONLY, 0600)
+	if err != nil {
+		return fmt.Errorf("unable to clear, and open the file: %v", err)
+	}
+	defer nf.Close()
+
+	// loop throught a write all the other keys back
```
Comment (jchavezlavalle) [inline pkg/sypgp/sypgp.go]: throught -> through

**Review by jchavezlavalle — CHANGES_REQUESTED** [review]
Added some comments @WestleyK thanks!

File: pkg/signing/signing.go (hunk 10 above)
Comment (WestleyK) [reply pkg/signing/signing.go]: I'm not sure thats a typo... but I'll change it anyway.

Comment (mem) [reply pkg/signing/signing.go]: Westley is right, authok is meant to be read as "authorization OK". Maybe "authOk" or "authOK" to avoid confusion?

Comment (WestleyK) [reply pkg/signing/signing.go]: `authOk` sounds good! I'll change it!

Comment (mem) [reply pkg/signing/signing.go]: Nope, we are both wrong and @devprincess is right, it's author.

Comment (WestleyK) [reply pkg/signing/signing.go]: Okay, I'll hold off :+1:

**Review by mem — APPROVED** [review]

**Review by jchavezlavalle — APPROVED** [review]
looks good thanks @WestleyK

File: pkg/signing/signing.go [hunk 16]
```diff
@@ -358,10 +348,10 @@ func Verify(cpath, url string, id uint32, isGroup bool, authToken string, noProm
 			name = i.Name
 			break
 		}
-		authok += fmt.Sprintf("\t%s, KeyID %X\n", name, signer.PrimaryKey.KeyId)
+		author += fmt.Sprintf("\t%s, KeyID %X\n", name, signer.PrimaryKey.KeyId)
 	}
 	fmt.Printf("Data integrity checked, authentic and signed by:\n")
-	fmt.Print(authok)
+	fmt.Print(author)
```
Comment (bauerm97) [inline pkg/signing/signing.go]: Let's move this to previous line.

`fmt.Printf("Data integrity checked, authentic and signed by:\n%v", author)`

**Review by bauerm97 — DISMISSED** [review]

File: pkg/sypgp/sypgp.go [hunk 17]
```diff
@@ -351,6 +351,76 @@ func StorePubKey(e *openpgp.Entity) (err error) {
...
+	defer f.Close()
+
+	// read all the local public keys
+	elist, err := openpgp.ReadKeyRing(f)
+	if err != nil {
+		return false, fmt.Errorf("unable to list local keyring: %v", err)
+	}
+
+	for i := range elist {
+		return compareLocalPubKey(elist[i], ckey), nil
```
Comment (ikaneshiro) [inline pkg/sypgp/sypgp.go]: Could there be more than one key in the keyring? It looks like this loop only checks the first one and returns.

**Review by ikaneshiro — CHANGES_REQUESTED** [review]

File: pkg/sypgp/sypgp.go (hunk 17 above)
Comment (WestleyK) [reply pkg/sypgp/sypgp.go]: Cuckoo -> @WestleyK

**Review by ikaneshiro — APPROVED** [review]
