### PR TITLE
Fix USER_PATH by appending default singularity PATH

### LINKED ISSUE #2244: --nv broken in 3.0.0
## Version of Singularity:

3.0.0

### Expected behavior

I'd expect something like `singularity shell --nv docker://centos:7` to work.

### Actual behavior

```
$ singularity shell --nv docker://centos:7
FATAL:   exec /.singularity.d/actions/shell failed: no such file or directory
```

### Steps to reproduce behavior

Works:
```
$ singularity shell docker://centos:7
Singularity centos_7.sif:~> 
```

Fails:
```
$ singularity shell --nv docker://centos:7
FATAL:   exec /.singularity.d/actions/shell failed: no such file or directory
```

Configs all default except singularity.conf:
```
$ egrep -v '^#|^$' /etc/singularity/singularity.conf
allow setuid = yes
max loop devices = 256
allow pid ns = yes
config passwd = yes
config group = yes
config resolv_conf = yes
mount proc = yes
mount sys = yes
mount dev = yes
mount devpts = yes
mount home = yes
mount tmp = yes
mount hostfs = no
bind path = /etc/localtime
bind path = /etc/hosts
bind path = /fs/project
bind path = /fs/scratch
user bind control = yes
enable overlay = try
enable underlay = yes
mount slave = yes
sessiondir max size = 16
allow container squashfs = yes
allow container extfs = yes
allow container dir = yes
always use nv = no
root default capabilities = no
allow root capabilities = yes
allow user capabilities = no
memory fs type = tmpfs
```

Debug:

```
$ singularity -d shell --nv docker://centos:7
DEBUG   [U=20821,P=6831]   parseURI()                    Parsing docker://centos:7 into reference
DEBUG   [U=20821,P=6831]   updateCacheSubdir()           Caching directory set to /users/sysp/tdockendorf/.singularity/cache/oci-tmp/67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b
DEBUG   [U=20821,P=6831]   updateCacheSubdir()           Caching directory set to /users/sysp/tdockendorf/.singularity/cache/oci-tmp
DEBUG   [U=20821,P=6831]   updateCacheSubdir()           Caching directory set to /users/sysp/tdockendorf/.singularity/cache/oci-tmp/67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b
DEBUG   [U=20821,P=6831]   updateCacheSubdir()           Caching directory set to /users/sysp/tdockendorf/.singularity/cache/oci-tmp
VERBOSE [U=20821,P=6831]   GetNvidiaPath()               nvidiaContainercli returned: no nvidia-container-cli present: exec: "nvidia-container-cli": executable file not found in $PATH
VERBOSE [U=20821,P=6831]   GetNvidiaPath()               Falling back to nvliblist.conf
VERBOSE [U=0,P=6831]       singularity_message_level()               Set messagelevel to: 5
DEBUG   [U=0,P=6831]       init()                                    PIPE_EXEC_FD value: 8
VERBOSE [U=0,P=6831]       init()                                    Container runtime
VERBOSE [U=0,P=6831]       is_suid()                                 Check if we are running as setuid
DEBUG   [U=0,P=6831]       init()                                    Overlay seems supported by kernel
DEBUG   [U=0,P=6831]       init()                                    Drop privileges
DEBUG   [U=20821,P=6831]   init()                                    Read json configuration from pipe
DEBUG   [U=20821,P=6831]   init()                                    Set child signal mask
DEBUG   [U=20821,P=6831]   init()                                    Create socketpair for smaster communication channel
DEBUG   [U=20821,P=6831]   init()                                    Wait C and JSON runtime configuration from scontainer stage 1
DEBUG   [U=20821,P=6882]   set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=20821,P=6882]   init()                                    Spawn scontainer stage 1
VERBOSE [U=20821,P=6882]   priv_escalate()                           Get root privileges
DEBUG   [U=0,P=6882]       set_parent_death_signal()                 Set parent death signal to 9
DEBUG   [U=0,P=6882]       prepare_scontainer_stage()                Entering in scontainer stage 1
DEBUG   [U=20821,P=6882]   set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=20821,P=6882]   startup()                     Execute scontainer stage 1
DEBUG   [U=20821,P=6882]   SContainer()                  Entering scontainer stage 1
DEBUG   [U=20821,P=6882]   prepareUserCaps()             Ignoring group 1021: group: unknown groupid 1021
DEBUG   [U=20821,P=6882]   prepareFd()                   Open file descriptor for /fs/project
DEBUG   [U=20821,P=6882]   prepareFd()                   Open file descriptor for /fs/scratch
DEBUG   [U=20821,P=6882]   Init()                        Entering image format intializer
DEBUG   [U=20821,P=6882]   Init()                        Check for image format sif
DEBUG   [U=20821,P=6831]   init()                                    Receiving configuration from scontainer stage 1
DEBUG   [U=20821,P=6831]   init()                                    Wait completion of scontainer stage1
VERBOSE [U=20821,P=6831]   priv_escalate()                           Get root privileges
VERBOSE [U=0,P=6831]       create_namespace()                        Create mount namespace
DEBUG   [U=0,P=6831]       init()                                    Create RPC socketpair for communication between scontainer and RPC server
VERBOSE [U=0,P=6831]       init()                                    Spawn smaster process
DEBUG   [U=0,P=6894]       set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=0,P=6894]       init()                                    Spawn scontainer stage 2
VERBOSE [U=0,P=6894]       create_namespace()                        Create mount namespace
VERBOSE [U=0,P=6895]       init()                                    Spawn RPC server
VERBOSE [U=20821,P=6831]   startup()                     Execute smaster process
VERBOSE [U=0,P=6895]       startup()                     Serve RPC requests
DEBUG   [U=20821,P=6831]   setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=20821,P=6831]   setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=20821,P=6831]   addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=20821,P=6831]   addRootfsMount()              Mounting block [squashfs] image: /users/sysp/tdockendorf/.singularity/cache/oci-tmp/67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b/centos_7.sif
DEBUG   [U=20821,P=6831]   addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=20821,P=6831]   addKernelMount()              Adding proc to mount list
DEBUG   [U=20821,P=6831]   addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=20821,P=6831]   addKernelMount()              Adding sysfs to mount list
DEBUG   [U=20821,P=6831]   addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=20821,P=6831]   addDevMount()                 Adding dev to mount list
DEBUG   [U=20821,P=6831]   addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=20821,P=6831]   addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=20821,P=6831]   addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
VERBOSE [U=20821,P=6831]   addBindsMount()               Found 'bind path' = /fs/project, /fs/project
VERBOSE [U=20821,P=6831]   addBindsMount()               Found 'bind path' = /fs/scratch, /fs/scratch
DEBUG   [U=20821,P=6831]   addHomeStagingDir()           Staging home directory (/users/sysp/tdockendorf) at /var/singularity/mnt/session/users/sysp/tdockendorf
DEBUG   [U=20821,P=6831]   addHomeMount()                Adding home directory mount [/var/singularity/mnt/session/users/sysp/tdockendorf:/users/sysp/tdockendorf] to list using layer: overlay
DEBUG   [U=20821,P=6831]   isLayerEnabled()              Using Layer system: overlay
DEBUG   [U=20821,P=6831]   addUserbindsMount()           Adding /bin/nvidia-smi to mount list
DEBUG   [U=20821,P=6831]   addUserbindsMount()           Adding /bin/nvidia-debugdump to mount list
DEBUG   [U=20821,P=6831]   addUserbindsMount()           Adding /bin/nvidia-persistenced to mount list
DEBUG   [U=20821,P=6831]   addUserbindsMount()           Adding /bin/nvidia-cuda-mps-control to mount list
DEBUG   [U=20821,P=6831]   addUserbindsMount()           Adding /bin/nvidia-cuda-mps-server to mount list
DEBUG   [U=20821,P=6831]   addUserbindsMount()           Checking for 'user bind control' in configuration file
DEBUG   [U=20821,P=6831]   addTmpMount()                 Checking for 'mount tmp' in configuration file
DEBUG   [U=20821,P=6831]   addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=20821,P=6831]   addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libcuda.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libcuda.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libEGL_nvidia.so.0 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libEGL.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libEGL.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLdispatch.so.0 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLESv1_CM_nvidia.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLESv1_CM.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLESv1_CM.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLESv2_nvidia.so.2 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLESv2.so.2 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLESv2.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGL.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGL.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLX_nvidia.so.0 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLX.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libGLX.so.0 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvcuvid.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvcuvid.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-cfg.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-cfg.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-compiler.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-eglcore.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-egl-wayland.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-encode.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-encode.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-fatbinaryloader.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-fbc.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-fbc.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-glcore.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-glsi.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-gtk2.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-gtk3.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-ifr.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-ifr.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-ml.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-ml.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-opencl.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-ptxjitcompiler.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libnvidia-ptxjitcompiler.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/tls/libnvidia-tls.so.396.37 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libOpenCL.so.1 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libOpenCL.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libOpenGL.so.0 to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libOpenGL.so to mount list
DEBUG   [U=20821,P=6831]   addLibsMount()                Add library /lib64/libvdpau_nvidia.so to mount list
DEBUG   [U=20821,P=6831]   addResolvConfMount()          Adding /etc/resolv.conf to mount list
DEBUG   [U=20821,P=6831]   addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=20821,P=6831]   create()                      Mount all
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting tmpfs to /var/singularity/mnt/session
DEBUG   [U=20821,P=6831]   mountImage()                  Mounting loop device /dev/loop0 to /var/singularity/mnt/session/rootfs
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting overlay to /var/singularity/mnt/session/final
DEBUG   [U=20821,P=6831]   setSlaveMount()               Set RPC mount propagation flag to SLAVE
VERBOSE [U=20821,P=6831]   Passwd()                      Checking for template passwd file: /var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE [U=20821,P=6831]   Passwd()                      Creating passwd content
VERBOSE [U=20821,P=6831]   Passwd()                      Creating template passwd file and appending user data: /var/singularity/mnt/session/rootfs/etc/passwd
DEBUG   [U=20821,P=6831]   addIdentityMount()            Adding /etc/passwd to mount list
VERBOSE [U=20821,P=6831]   Group()                       Checking for template group file: /var/singularity/mnt/session/rootfs/etc/group
VERBOSE [U=20821,P=6831]   Group()                       Creating group content
VERBOSE [U=20821,P=6831]   Group()                       Skipping GID 1021 as group entry doesn't exist.
DEBUG   [U=20821,P=6831]   addIdentityMount()            Adding /etc/group to mount list
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /dev to /var/singularity/mnt/session/final/dev
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /etc/localtime to /var/singularity/mnt/session/final/usr/share/zoneinfo/UTC
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /etc/hosts to /var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /fs/project to /var/singularity/mnt/session/final/fs/project
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /fs/scratch to /var/singularity/mnt/session/final/fs/scratch
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /etc/singularity/actions to /var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /proc to /var/singularity/mnt/session/final/proc
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/proc
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting sysfs to /var/singularity/mnt/session/final/sys
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /users/sysp/tdockendorf to /var/singularity/mnt/session/users/sysp/tdockendorf
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/users/sysp/tdockendorf
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /var/singularity/mnt/session/users/sysp/tdockendorf to /var/singularity/mnt/session/final/users/sysp/tdockendorf
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/users/sysp/tdockendorf
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /bin/nvidia-smi to /var/singularity/mnt/session/final/bin/nvidia-smi
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/bin/nvidia-smi
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /bin/nvidia-debugdump to /var/singularity/mnt/session/final/bin/nvidia-debugdump
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/bin/nvidia-debugdump
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /bin/nvidia-persistenced to /var/singularity/mnt/session/final/bin/nvidia-persistenced
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/bin/nvidia-persistenced
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /bin/nvidia-cuda-mps-control to /var/singularity/mnt/session/final/bin/nvidia-cuda-mps-control
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/bin/nvidia-cuda-mps-control
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /bin/nvidia-cuda-mps-server to /var/singularity/mnt/session/final/bin/nvidia-cuda-mps-server
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/bin/nvidia-cuda-mps-server
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /tmp to /var/singularity/mnt/session/final/tmp
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/tmp
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /var/tmp to /var/singularity/mnt/session/final/var/tmp
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/var/tmp
DEBUG   [U=20821,P=6831]   mountGeneric()                Skipping mount /var/singularity/mnt/session/final/users/sysp/tdockendorf, /var/singularity/mnt/session/final/users/sysp/tdockendorf already mounted
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libcuda.so.1 to /var/singularity/mnt/session/libs/libcuda.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libcuda.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libcuda.so to /var/singularity/mnt/session/libs/libcuda.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libcuda.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libEGL_nvidia.so.0 to /var/singularity/mnt/session/libs/libEGL_nvidia.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libEGL_nvidia.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libEGL.so.1 to /var/singularity/mnt/session/libs/libEGL.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libEGL.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libEGL.so to /var/singularity/mnt/session/libs/libEGL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libEGL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLdispatch.so.0 to /var/singularity/mnt/session/libs/libGLdispatch.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLdispatch.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLESv1_CM_nvidia.so.1 to /var/singularity/mnt/session/libs/libGLESv1_CM_nvidia.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLESv1_CM_nvidia.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLESv1_CM.so.1 to /var/singularity/mnt/session/libs/libGLESv1_CM.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLESv1_CM.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLESv1_CM.so to /var/singularity/mnt/session/libs/libGLESv1_CM.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLESv1_CM.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLESv2_nvidia.so.2 to /var/singularity/mnt/session/libs/libGLESv2_nvidia.so.2
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLESv2_nvidia.so.2
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLESv2.so.2 to /var/singularity/mnt/session/libs/libGLESv2.so.2
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLESv2.so.2
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLESv2.so to /var/singularity/mnt/session/libs/libGLESv2.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLESv2.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGL.so.1 to /var/singularity/mnt/session/libs/libGL.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGL.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGL.so to /var/singularity/mnt/session/libs/libGL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLX_nvidia.so.0 to /var/singularity/mnt/session/libs/libGLX_nvidia.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLX_nvidia.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLX.so to /var/singularity/mnt/session/libs/libGLX.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLX.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libGLX.so.0 to /var/singularity/mnt/session/libs/libGLX.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libGLX.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvcuvid.so to /var/singularity/mnt/session/libs/libnvcuvid.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvcuvid.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvcuvid.so.1 to /var/singularity/mnt/session/libs/libnvcuvid.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvcuvid.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-cfg.so.1 to /var/singularity/mnt/session/libs/libnvidia-cfg.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-cfg.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-cfg.so to /var/singularity/mnt/session/libs/libnvidia-cfg.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-cfg.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-compiler.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-compiler.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-compiler.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-eglcore.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-eglcore.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-eglcore.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-egl-wayland.so.1 to /var/singularity/mnt/session/libs/libnvidia-egl-wayland.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-egl-wayland.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-encode.so to /var/singularity/mnt/session/libs/libnvidia-encode.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-encode.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-encode.so.1 to /var/singularity/mnt/session/libs/libnvidia-encode.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-encode.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-fatbinaryloader.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-fatbinaryloader.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-fatbinaryloader.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-fbc.so to /var/singularity/mnt/session/libs/libnvidia-fbc.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-fbc.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-fbc.so.1 to /var/singularity/mnt/session/libs/libnvidia-fbc.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-fbc.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-glcore.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-glcore.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-glcore.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-glsi.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-glsi.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-glsi.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-gtk2.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-gtk2.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-gtk2.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-gtk3.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-gtk3.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-gtk3.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-ifr.so to /var/singularity/mnt/session/libs/libnvidia-ifr.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-ifr.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-ifr.so.1 to /var/singularity/mnt/session/libs/libnvidia-ifr.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-ifr.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-ml.so.1 to /var/singularity/mnt/session/libs/libnvidia-ml.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-ml.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-ml.so to /var/singularity/mnt/session/libs/libnvidia-ml.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-ml.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-opencl.so.1 to /var/singularity/mnt/session/libs/libnvidia-opencl.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-opencl.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-ptxjitcompiler.so.1 to /var/singularity/mnt/session/libs/libnvidia-ptxjitcompiler.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-ptxjitcompiler.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libnvidia-ptxjitcompiler.so to /var/singularity/mnt/session/libs/libnvidia-ptxjitcompiler.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-ptxjitcompiler.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/tls/libnvidia-tls.so.396.37 to /var/singularity/mnt/session/libs/libnvidia-tls.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libnvidia-tls.so.396.37
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libOpenCL.so.1 to /var/singularity/mnt/session/libs/libOpenCL.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libOpenCL.so.1
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libOpenCL.so to /var/singularity/mnt/session/libs/libOpenCL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libOpenCL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libOpenGL.so.0 to /var/singularity/mnt/session/libs/libOpenGL.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libOpenGL.so.0
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libOpenGL.so to /var/singularity/mnt/session/libs/libOpenGL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libOpenGL.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /lib64/libvdpau_nvidia.so to /var/singularity/mnt/session/libs/libvdpau_nvidia.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/libs/libvdpau_nvidia.so
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /var/singularity/mnt/session/libs to /var/singularity/mnt/session/final/.singularity.d/libs
DEBUG   [U=20821,P=6831]   mountGeneric()                Remounting /var/singularity/mnt/session/final/.singularity.d/libs
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /var/singularity/mnt/session/etc/resolv.conf to /var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /var/singularity/mnt/session/etc/passwd to /var/singularity/mnt/session/final/etc/passwd
DEBUG   [U=20821,P=6831]   mountGeneric()                Mounting /var/singularity/mnt/session/etc/group to /var/singularity/mnt/session/final/etc/group
DEBUG   [U=20821,P=6831]   create()                      Chroot into /var/singularity/mnt/session/final
DEBUG   [U=0,P=6895]       Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=6895]       Chroot()                      Change current directory to /var/singularity/mnt/session/final
DEBUG   [U=0,P=6895]       Chroot()                      Called pivot_root on /var/singularity/mnt/session/final
DEBUG   [U=0,P=6895]       Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=6895]       Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=6895]       Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=6895]       Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=20821,P=6831]   create()                      Chdir into / to avoid errors
DEBUG   [U=0,P=6894]       set_parent_death_signal()                 Set parent death signal to 9
DEBUG   [U=0,P=6894]       prepare_scontainer_stage()                Entering in scontainer stage 2
DEBUG   [U=20821,P=6894]   set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=20821,P=6894]   startup()                     Execute scontainer stage 2
FATAL   [U=20821,P=6894]   SContainer()                  exec /.singularity.d/actions/shell failed: no such file or directory
DEBUG   [U=20821,P=6831]   PostStartProcess()            Post start process
DEBUG   [U=20821,P=6831]   CleanupContainer()            Cleanup container
DEBUG   [U=20821,P=6831]   SMaster()                     Child exited with exit status 255
```

### LINKED ISSUE #2252: nvidia-smi not being brought into container correctly
## Version of Singularity:

3.0.0

### Expected behavior

nvidia-smi on the host at /usr/bin/nvidia-smi. It is a symlink to /usr/lib/nvidia-384/bin/nvidia-smi. When I run a container I would expect it to be in my path since it was on the host.

Note: I have libnvidia-container-cli installed in my path

### Actual behavior

nvidia-smi is no longer in my path in the container

### Steps to reproduce behavior

```
$ singularity shell --nv docker://centos:7
$ nvidia-smi
bash: nvidia-smi: command not found
$ find / -name nvidia-smi
/usr/lib/nvidia-384/bin/nvidia-smi
/usr/local/nvidia/bin/nvidia-smi
$ /usr/lib/nvidia-384/bin/nvidia-smi
Tue Oct 16 15:27:51 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:08:00.0 Off |                  Off |
| N/A   37C    P0    25W / 250W |      0MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:09:00.0 Off |                  Off |
| N/A   34C    P0    25W / 250W |      0MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Debug:
```
$ singularity -d shell --nv docker://centos:7
DEBUG   [U=0,P=27216]      envAppend()                   Update flag Value to: [/usr/lib/nvidia-384/bin:/usr/local/nvidia/bin]
DEBUG   [U=0,P=27216]      parseURI()                    Parsing docker://centos:7 into reference
DEBUG   [U=0,P=27216]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp/67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b
DEBUG   [U=0,P=27216]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
DEBUG   [U=0,P=27216]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp/67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b
DEBUG   [U=0,P=27216]      updateCacheSubdir()           Caching directory set to /root/.singularity/cache/oci-tmp
VERBOSE [U=0,P=27216]      singularity_message_level()               Set messagelevel to: 5
DEBUG   [U=0,P=27216]      init()                                    PIPE_EXEC_FD value: 7
VERBOSE [U=0,P=27216]      init()                                    Container runtime
VERBOSE [U=0,P=27216]      is_suid()                                 Check if we are running as setuid
DEBUG   [U=0,P=27216]      init()                                    Overlay seems supported by kernel
DEBUG   [U=0,P=27216]      init()                                    Read json configuration from pipe
DEBUG   [U=0,P=27216]      init()                                    Set child signal mask
DEBUG   [U=0,P=27216]      init()                                    Create socketpair for smaster communication channel
DEBUG   [U=0,P=27216]      init()                                    Wait C and JSON runtime configuration from scontainer stage 1
DEBUG   [U=0,P=27257]      set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=0,P=27257]      init()                                    Spawn scontainer stage 1
VERBOSE [U=0,P=27257]      startup()                     Execute scontainer stage 1
DEBUG   [U=0,P=27257]      SContainer()                  Entering scontainer stage 1
DEBUG   [U=0,P=27257]      prepareRootCaps()             Root full capabilities
DEBUG   [U=0,P=27257]      prepareFd()                   Open file descriptor for /usr/lib/nvidia-384/bin
DEBUG   [U=0,P=27257]      Init()                        Entering image format intializer
DEBUG   [U=0,P=27257]      Init()                        Check for image format sif
DEBUG   [U=0,P=27216]      init()                                    Receiving configuration from scontainer stage 1
DEBUG   [U=0,P=27216]      init()                                    Wait completion of scontainer stage1
VERBOSE [U=0,P=27216]      priv_escalate()                           Get root privileges
VERBOSE [U=0,P=27216]      create_namespace()                        Create mount namespace
DEBUG   [U=0,P=27216]      init()                                    Create RPC socketpair for communication between scontainer and RPC server
VERBOSE [U=0,P=27216]      init()                                    Spawn smaster process
DEBUG   [U=0,P=27265]      set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=0,P=27265]      init()                                    Spawn scontainer stage 2
VERBOSE [U=0,P=27265]      create_namespace()                        Create mount namespace
VERBOSE [U=0,P=27266]      init()                                    Spawn RPC server
VERBOSE [U=0,P=27216]      startup()                     Execute smaster process
VERBOSE [U=0,P=27266]      startup()                     Serve RPC requests
DEBUG   [U=0,P=27216]      setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=0,P=27216]      setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=0,P=27216]      addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=0,P=27216]      addRootfsMount()              Mounting block [squashfs] image: /root/.singularity/cache/oci-tmp/67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b/centos_7.sif
DEBUG   [U=0,P=27216]      addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=0,P=27216]      addKernelMount()              Adding proc to mount list
DEBUG   [U=0,P=27216]      addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=0,P=27216]      addKernelMount()              Adding sysfs to mount list
DEBUG   [U=0,P=27216]      addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=0,P=27216]      addDevMount()                 Adding dev to mount list
DEBUG   [U=0,P=27216]      addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=0,P=27216]      addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=0,P=27216]      addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=0,P=27216]      addHomeStagingDir()           Staging home directory (/root) at /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=27216]      addHomeMount()                Adding home directory mount [/usr/local/var/singularity/mnt/session/root:/root] to list using layer: overlay
DEBUG   [U=0,P=27216]      isLayerEnabled()              Using Layer system: overlay
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /usr/lib/nvidia-384/bin to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /usr/lib/nvidia-384/bin/nvidia-smi to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /usr/lib/nvidia-384/bin/nvidia-debugdump to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /usr/lib/nvidia-384/bin/nvidia-persistenced to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /usr/lib/nvidia-384/bin/nvidia-cuda-mps-control to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /usr/lib/nvidia-384/bin/nvidia-cuda-mps-server to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Adding /run/nvidia-persistenced/socket to mount list
DEBUG   [U=0,P=27216]      addUserbindsMount()           Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=27216]      addTmpMount()                 Checking for 'mount tmp' in configuration file
DEBUG   [U=0,P=27216]      addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=0,P=27216]      addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-ml.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-ml.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-cfg.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-cfg.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/x86_64-linux-gnu/libcuda.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/x86_64-linux-gnu/libcuda.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-ptxjitcompiler.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.130 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-compiler.so.384.130 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-compiler.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/libvdpau_nvidia.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-encode.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-encode.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvcuvid.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvcuvid.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-eglcore.so.384.130 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-glcore.so.384.130 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-tls.so.384.130 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-glsi.so.384.130 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-fbc.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-fbc.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-ifr.so.1 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libnvidia-ifr.so to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libGLX_nvidia.so.0 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libEGL_nvidia.so.0 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libGLESv2_nvidia.so.2 to mount list
DEBUG   [U=0,P=27216]      addLibsMount()                Add library /usr/lib/nvidia-384/libGLESv1_CM_nvidia.so.1 to mount list
DEBUG   [U=0,P=27216]      addResolvConfMount()          Adding /etc/resolv.conf to mount list
DEBUG   [U=0,P=27216]      addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=0,P=27216]      create()                      Mount all
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting tmpfs to /usr/local/var/singularity/mnt/session
DEBUG   [U=0,P=27216]      mountImage()                  Mounting loop device /dev/loop0 to /usr/local/var/singularity/mnt/session/rootfs
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting overlay to /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=27216]      setSlaveMount()               Set RPC mount propagation flag to SLAVE
VERBOSE [U=0,P=27216]      addIdentityMount()            Not updating passwd/group files, running as root!
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /dev to /usr/local/var/singularity/mnt/session/final/dev
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /etc/localtime to /usr/local/var/singularity/mnt/session/final/usr/share/zoneinfo/UTC
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /etc/hosts to /usr/local/var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/local/etc/singularity/actions to /usr/local/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /proc to /usr/local/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/proc
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting sysfs to /usr/local/var/singularity/mnt/session/final/sys
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /root to /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/root
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/root to /usr/local/var/singularity/mnt/session/final/root
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/root
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/bin to /usr/local/var/singularity/mnt/session/final/usr/local/nvidia/bin
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/local/nvidia/bin
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/bin/nvidia-smi to /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-smi
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-smi
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/bin/nvidia-debugdump to /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-debugdump
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-debugdump
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/bin/nvidia-persistenced to /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-persistenced
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-persistenced
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/bin/nvidia-cuda-mps-control to /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-cuda-mps-control
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-cuda-mps-control
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/bin/nvidia-cuda-mps-server to /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-cuda-mps-server
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/usr/lib/nvidia-384/bin/nvidia-cuda-mps-server
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /run/nvidia-persistenced/socket to /usr/local/var/singularity/mnt/session/final/run/nvidia-persistenced/socket
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/run/nvidia-persistenced/socket
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /tmp to /usr/local/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/tmp
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /var/tmp to /usr/local/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/var/tmp
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /var/data0/sandbox/adam/qmcpack_stuff to /usr/local/var/singularity/mnt/session/final/var/data0/sandbox/adam/qmcpack_stuff
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/var/data0/sandbox/adam/qmcpack_stuff
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-ml.so to /usr/local/var/singularity/mnt/session/libs/libnvidia-ml.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-ml.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-ml.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-ml.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-ml.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-cfg.so to /usr/local/var/singularity/mnt/session/libs/libnvidia-cfg.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-cfg.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-cfg.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-cfg.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-cfg.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/x86_64-linux-gnu/libcuda.so to /usr/local/var/singularity/mnt/session/libs/libcuda.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libcuda.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/x86_64-linux-gnu/libcuda.so.1 to /usr/local/var/singularity/mnt/session/libs/libcuda.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libcuda.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-opencl.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-opencl.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-ptxjitcompiler.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-ptxjitcompiler.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-ptxjitcompiler.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.130 to /usr/local/var/singularity/mnt/session/libs/libnvidia-fatbinaryloader.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-fatbinaryloader.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-compiler.so.384.130 to /usr/local/var/singularity/mnt/session/libs/libnvidia-compiler.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-compiler.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-compiler.so to /usr/local/var/singularity/mnt/session/libs/libnvidia-compiler.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-compiler.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/libvdpau_nvidia.so to /usr/local/var/singularity/mnt/session/libs/libvdpau_nvidia.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libvdpau_nvidia.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-encode.so to /usr/local/var/singularity/mnt/session/libs/libnvidia-encode.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-encode.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-encode.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-encode.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-encode.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvcuvid.so to /usr/local/var/singularity/mnt/session/libs/libnvcuvid.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvcuvid.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvcuvid.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvcuvid.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvcuvid.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-eglcore.so.384.130 to /usr/local/var/singularity/mnt/session/libs/libnvidia-eglcore.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-eglcore.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-glcore.so.384.130 to /usr/local/var/singularity/mnt/session/libs/libnvidia-glcore.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-glcore.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-tls.so.384.130 to /usr/local/var/singularity/mnt/session/libs/libnvidia-tls.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-tls.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-glsi.so.384.130 to /usr/local/var/singularity/mnt/session/libs/libnvidia-glsi.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-glsi.so.384.130
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-fbc.so to /usr/local/var/singularity/mnt/session/libs/libnvidia-fbc.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-fbc.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-fbc.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-fbc.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-fbc.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-ifr.so.1 to /usr/local/var/singularity/mnt/session/libs/libnvidia-ifr.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-ifr.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libnvidia-ifr.so to /usr/local/var/singularity/mnt/session/libs/libnvidia-ifr.so
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libnvidia-ifr.so
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libGLX_nvidia.so.0 to /usr/local/var/singularity/mnt/session/libs/libGLX_nvidia.so.0
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libGLX_nvidia.so.0
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libEGL_nvidia.so.0 to /usr/local/var/singularity/mnt/session/libs/libEGL_nvidia.so.0
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libEGL_nvidia.so.0
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libGLESv2_nvidia.so.2 to /usr/local/var/singularity/mnt/session/libs/libGLESv2_nvidia.so.2
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libGLESv2_nvidia.so.2
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/lib/nvidia-384/libGLESv1_CM_nvidia.so.1 to /usr/local/var/singularity/mnt/session/libs/libGLESv1_CM_nvidia.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/libs/libGLESv1_CM_nvidia.so.1
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/libs to /usr/local/var/singularity/mnt/session/final/.singularity.d/libs
DEBUG   [U=0,P=27216]      mountGeneric()                Remounting /usr/local/var/singularity/mnt/session/final/.singularity.d/libs
DEBUG   [U=0,P=27216]      mountGeneric()                Mounting /usr/local/var/singularity/mnt/session/etc/resolv.conf to /usr/local/var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=0,P=27216]      create()                      Chroot into /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=27266]      Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=27266]      Chroot()                      Change current directory to /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=27266]      Chroot()                      Called pivot_root on /usr/local/var/singularity/mnt/session/final
DEBUG   [U=0,P=27266]      Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=27266]      Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=27266]      Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=27266]      Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=0,P=27216]      create()                      Chdir into / to avoid errors
DEBUG   [U=0,P=27265]      set_parent_death_signal()                 Set parent death signal to 9
DEBUG   [U=0,P=27265]      prepare_scontainer_stage()                Entering in scontainer stage 2
DEBUG   [U=0,P=27265]      set_parent_death_signal()                 Set parent death signal to 9
VERBOSE [U=0,P=27265]      startup()                     Execute scontainer stage 2
DEBUG   [U=0,P=27216]      PostStartProcess()            Post start process
```

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fixes environment variables grabbed from user environment by appending default PATH `/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin`, some distribution doesn't set /sbin in user PATH and that broke `--nv` when searching for ldconfig and nvidia binaries

**This fixes or addresses the following GitHub issues:**

- Fixes  #2252

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by jmstover — APPROVED** [review]
This fixes my issue with `ldconfig` not being found in `$PATH`

File: src/cmd/singularity/cli/singularity.go [hunk 1]
```diff
@@ -103,10 +104,13 @@ var SingularityCmd = &cobra.Command{
 // flags appropriately. This is called by main.main(). It only needs to happen
 // once to the root command (singularity).
 func ExecuteSingularity() {
+	defaultEnv := "/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
+
```
Comment (yhcote) [inline src/cmd/singularity/cli/singularity.go:108]: Is it not customary to have /usr/local in front of /bin and /usr/bin?

**Review by yhcote — CHANGES_REQUESTED** [review]
Mostly a question, but maybe something to change

File: src/cmd/singularity/cli/singularity.go (hunk 1 above)
Comment (jmstover) [reply src/cmd/singularity/cli/singularity.go:108]: That depends on where you come from. Some places want "system" locations to always win over /usr/local/bin if a binary of the same name exists. I'm from that school of thought.  *shrug*

So my default path when set like this looks generally like:
`/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin`

Comment (cclerget) [reply src/cmd/singularity/cli/singularity.go:108]: @yhcote @jmstover PATH search order fixed

Comment (yhcote) [reply src/cmd/singularity/cli/singularity.go:108]: Well the point of having /usr/local in front is that you can install software without modifying what's on the system in /bin and usr/bin and make sure "your" version is found first. Not just "extra" software what wouldn't be installed on a common system. If you feel confident I'll let it go. Just wanted to point it out.

Comment (yhcote) [reply src/cmd/singularity/cli/singularity.go:108]: @jmstover ^

**Review by yhcote — APPROVED** [review]
Looks good to me.
