### PR TITLE
Prevent build engine from mixing container and host libraries

### LINKED ISSUE #4203: Singularity cannot build some official Docker Hub Ubuntu tags
## Version of Singularity:

```
$ singularity --version
singularity version 3.3.0-1
```

### Expected behavior

The instructions for [Building containers from Singularity definition files](https://sylabs.io/guides/3.3/user-guide/build_a_container.html#building-containers-from-singularity-definition-files) should work with your average, official Ubuntu image off the Docker Hub.

### Actual behavior

Going off the list of [docker.io/ubuntu](https://hub.docker.com/_/ubuntu) top tags, there are mixed results:

| Tag    | Result   |
| ------ | -------- |
| 16.04  | Works    |
| 18.04  | Works    |
| 18.10  | Works    |
| 19.04  | **Failed** |
| 19.10  | **Failed** |
| latest | Works _(today, anyway)_    |

The failed tags result in this error before the post actions can be taken:

```
Storing signatures
singularity image-build: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
FATAL:   While performing build: while running engine: exit status 127
```

This seems very similar to the problem in #3917 but it is not clear to me how to more permanently resolve the issue.

### Steps to reproduce behavior

Using the following simple definition file:

```
Bootstrap: docker
From: ubuntu:19.10

%post
    apt update
    apt install -y python3

%environment
    export LANG=C.UTF-8
    export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

%runscript
   python3 --version
```

Run this command, editing the second line to try each tag in the table above:

```
singularity build result.sif reproduce.def

singularity run result.sif

rm -f result.sif
```

### LINKED ISSUE #4247: Build post section fails depending of image
## Version of Singularity:

3.3 versions

### Expected behavior

Build succeed

### Actual behavior

Build fail with error because the build runtime engine load NSS library from container image while mixing it with host libc :

```
sudo singularity build /tmp/test.sif /tmp/test.def 
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:4ae16bd4778367b46064f39554128dd2fda2803a5747fddeff74059f353391c9
Copying config sha256:949ef9aebb05f4354e666d1605eda6102a8db9845ead21c18a5f0186faa109c4
 579 B / 579 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
2019/08/20 10:42:08  info unpack layer: sha256:4ae16bd4778367b46064f39554128dd2fda2803a5747fddeff74059f353391c9
singularity image-build: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
FATAL:   While performing build: while running engine: exit status 127
```

### Steps to reproduce behavior

Use definition file on Ubuntu 18.04 :

```
bootstrap: docker
from: debian:buster

%post
    echo "test"
```

And build image with `sudo singularity build /tmp/test.sif /tmp/test.def`

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Remove unecessary call to `user.Current` in `cleanEnv` to prevent Go from loading and mixing NSS libraries with container image and host libc leading to error shown in #4247

**This fixes or addresses the following GitHub issues:**

- Fixes #4203 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — APPROVED** [review]
:+1: This LGTM.

Have confirmed it fixes #4203 

Also confirmed it does not result in a regression of issue #3092:

```
08:15 AM $ cat home.def 
Bootstrap: docker
From: alpine:latest

%post
    apk update && apk add wget
    whoami
    ls ~

08:15 AM $ sudo singularity build home.sif home.def
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:0503825856099e6adb39c8297af09547f69684b7016b7f3680ed801aa310baaa
Copying config sha256:4fa153a82426ad308e69dde53d77abb1bbfb9d069bdfbdd7db50f615bd92d7ae
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
2019/08/20 08:15:53  info unpack layer: sha256:0503825856099e6adb39c8297af09547f69684b7016b7f3680ed801aa310baaa
INFO:    Running post scriptlet
+ apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
v3.10.1-115-g8dcef80b96 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
v3.10.2-1-g93e3be01c5 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
OK: 10337 distinct packages available
+ apk add wget
(1/1) Installing wget (1.20.3-r0)
Executing busybox-1.30.1-r2.trigger
OK: 6 MiB in 15 packages
+ whoami
root
+ ls /root
INFO:    Creating SIF file...
INFO:    Build complete: home.sif
```

File: e2e/regressions/build.go [hunk 1]
```diff
@@ -0,0 +1,69 @@
+// Copyright (c) 2019, Sylabs Inc. All rights reserved.
```
Comment (jscook2345) [inline e2e/regressions/build.go:1]: I'm not sure this is the best place code organizational wise for this, but I'm happy to have this here for now. Thanks!

**Review by jscook2345 — APPROVED** [review]

**Comment by jscook2345** [comment]
seal-approval
