### PR TITLE
Development 3.0: Nvidia stuff rewrite and fix --nv with --writable

### LINKED ISSUE #2088: 3.0: --writable causes --nv to be ignored
## Version of Singularity:
v3.0.0-alpha.2-272-g5fb1529

### Expected behavior
$ sudo singularity shell --nv --writable ../sbox/
> ls -l /.singularity.d/libs/ | wc -l
46

### Actual behavior
$ sudo singularity shell --nv --writable ../sbox/
> ls -l /.singularity.d/libs/
total 0

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fixes issue when `--nv` is used with `--writable` flag :
- libraries are bound into a staging directory then the staging directory is bound into `/.singularity/libs`
- nvidia binaries are handled with BindPath, it's not important if they are not bound in container with `--writable`.
- fix bug during `ldconfig` parsing to avoid binding of 32 bits libraries on 64 bits (i386 vs x86_64), this PR open all ldconfig libraries to check that ELF machine match the current in use
- Honor `always use nv` configuration directive
- Add `SINGULARITY_CONTAINLIBS` support
- Enhancements to find binaries in non-standard paths

**This fixes or addresses the following GitHub issues:**

- Fixes #2088

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

File: src/pkg/util/nvidiautils/nvidiautils.go [hunk 1]
```diff
@@ -90,66 +96,86 @@ func GetNvidiaBindPath(abspath string) ([]string, error) {
...
 		}
 	}
 
 	// walk thru the ldconfig output and add entries which contain the filenames
 	// returned by nvidia-container-cli OR the nvliblist.conf file contents
-	command, err := exec.LookPath("ldconfig")
-	if err != nil {
-		sylog.Warningf("ldconfig not found: %v", err)
-		return nil, nil
-	}
```
Comment (GodloveD) [inline src/pkg/util/nvidiautils/nvidiautils.go:103]: I wonder why the check for location of `ldconfig` is removed.  `ldconfig` is not guaranteed to be on everyone's path.  Just as @jmstover .

File: src/pkg/util/nvidiautils/nvidiautils.go [hunk 2]
```diff
@@ -90,66 +96,86 @@ func GetNvidiaBindPath(abspath string) ([]string, error) {
...
-
-	cmd := exec.Command(command, "-p")
+	cmd := exec.Command("ldconfig", "-p")
 	out, err := cmd.Output()
 	if err != nil {
 		sylog.Warningf("ldconfig execution error: %v", err)
```
Comment (GodloveD) [inline src/pkg/util/nvidiautils/nvidiautils.go:117]: Will this pick up an error where the `ldconfig` command does not appear on the path?  Maybe that is the reason for removing the check above.

File: src/runtime/engines/singularity/container.go [hunk 3]
```diff
@@ -1419,7 +1419,48 @@ func (c *container) addCwdMount(system *mount.System) error {
 }
 
 func (c *container) addLibsMount(system *mount.System) error {
-	return nil
+	sylog.Debugf("Checking for 'user bind control' in configuration file")
+	if !c.engine.EngineConfig.File.UserBindControl {
+		sylog.Warningf("Ignoring libraries bind request: user bind control disabled by system administrator")
```
Comment (GodloveD) [inline src/runtime/engines/singularity/container.go:1449]: Should there also be a return or something here so that he function does not continue to bind the files?

File: src/cmd/singularity/cli/actions.go [hunk 4]
```diff
@@ -326,15 +326,23 @@ func execStarter(cobraCmd *cobra.Command, image string, args []string, name stri
...
+					sylog.Warningf("NVIDIA binaries may not be bound with --writable")
+				}
+				BindPaths = append(BindPaths, bins...)
+			}
+			if len(libs) == 0 {
 				sylog.Warningf("Could not find any NVIDIA libraries on this host!")
 				sylog.Warningf("You may need to edit %v/nvliblist.conf", buildcfg.SINGULARITY_CONFDIR)
 			} else {
-				BindPaths = append(BindPaths, NvidiaBindPaths...)
+				engineConfig.SetLibrariesPath(libs)
```
Comment (GodloveD) [inline src/cmd/singularity/cli/actions.go]: We have users that rely on the `SINGULARITY_CONTAINLIBS` environment variable to add other libraries at runtime as well.  Afaik, this includes things to get MPI running properly.  Those users could also use `SINGULARITY_BINDPATH` but of course that option will break if the container is executed with the `--writable` option.  So imho we should also allow users to specify the `SINGULARITY_CONTAINLIBS` and append its contents to `libs` here.  

@bauerm97 is concerned about doing this because he is worried this will allow a user to bind files even if an admin has specified no user bind control in the conf file.  But afaik, if the conf file is appropriate checked in `container.go` that should be a non-issue. 

However, looking at the new code in `container.go`, it seems like the conf file is being checked but is not returning if user bind is turned off.  A warning is being issued and then the function is proceeding as normal.  Am I missing something?

**Review by GodloveD — CHANGES_REQUESTED** [review]

File: src/pkg/util/nvidiautils/nvidiautils.go (hunk 1 above)
Comment (bauerm97) [reply src/pkg/util/nvidiautils/nvidiautils.go:103]: `exec.Command` does a `LookPath` under the hood

File: src/runtime/engines/singularity/container.go (hunk 3 above)
Comment (cclerget) [reply src/runtime/engines/singularity/container.go:1449]: Oh you're right ... bad copy/paste

File: src/cmd/singularity/cli/actions.go (hunk 4 above)
Comment (cclerget) [reply src/cmd/singularity/cli/actions.go]: I will include discussed fix to handle SINGULARITY_CONTAINLIBS variable

File: src/cmd/singularity/cli/actions.go [hunk 5]
```diff
@@ -326,7 +326,7 @@ func execStarter(cobraCmd *cobra.Command, image string, args []string, name stri
 		engineConfig.SetImage(abspath)
 	}
 
-	if Nvidia {
+	if Nvidia || engineConfig.File.AlwaysUseNv {
```
Comment (GodloveD) [inline src/cmd/singularity/cli/actions.go]: Oh man.  Yes I forgot about this.  And I'm very sorry that we are going down a rabbit hole now, but when I first added this to the conf file a user asked for a kill switch so that if an admin set this in the conf file they could opt out.  

Could you also add this as a hidden option and env var the way you did with the CONTAINLIBS env var?  Here is the appropriate line in 2.x
https://github.com/sylabs/singularity/blob/release-2.6/libexec/cli/action_argparser.sh#L149

File: etc/nvliblist.conf [hunk 6]
```diff
@@ -7,11 +7,11 @@
...
-/usr/bin/nvidia-smi
-/usr/bin/nvidia-debugdump
-/usr/bin/nvidia-persistenced
-/usr/bin/nvidia-cuda-mps-control
-/usr/bin/nvidia-cuda-mps-server
+nvidia-smi
+nvidia-debugdump
+nvidia-persistenced
+nvidia-cuda-mps-control
+nvidia-cuda-mps-server
```
Comment (GodloveD) [inline etc/nvliblist.conf:14]: So, I guess with this change, a user _could_ still specify the entire path if the bin was in a very obscure place right?

File: src/cmd/singularity/cli/actions.go (hunk 5 above)
Comment (cclerget) [reply src/cmd/singularity/cli/actions.go]: @GodloveD Done

**Review by GodloveD — COMMENTED** [review]
I (or somebody) should actually test these changes before approving.  Unfortunately I cannot do so right now.  Might be able to get to it this evening.

File: etc/nvliblist.conf (hunk 6 above)
Comment (cclerget) [reply etc/nvliblist.conf:14]: Yes

**Review by ArangoGutierrez — APPROVED** [review]
Tested 
```
Fri Oct  5 12:56:18 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M620         Off  | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P8    N/A /  N/A |    813MiB /  1999MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2225      G   /usr/bin/X                                   179MiB |
|    0      2811      G   /usr/bin/gnome-shell                         258MiB |
|    0      3537      G   ...-token=C40C938A7458F67291FF7FB8F969BF27    83MiB |
|    0      3721      G   ...quest-channel-token=6038370698854482961   131MiB |
|    0      4439      G   ...-token=C17417903998F2781AA2F231CDE0C214    83MiB |
|    0      5972      G   ...process --disable-features=ColorCorrect    71MiB |
+-----------------------------------------------------------------------------+
```
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
```
```
GOARCH="amd64"
GOBIN="/home/eduardo/go/bin"
GOCACHE="off"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/eduardo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build190423514=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by GodloveD** [comment]
Thanks @ArangoGutierrez .   I think the env vars and conf file options need to be exercised as well although everything looks like it should work just fine.  As long as nothing changes this will be my 1st priority following meeting today.

**Comment by ArangoGutierrez** [comment]
NP @GodloveD 
PING me if you need to re-run tests on this PR

**Comment by GodloveD** [comment]
!@#$.  It doesn't seem like the `$SINGULARITY_NV_OFF ` env var is working. I've been trying to figure out why but I'm having no luck. I know that you need to add `"no-nv": envBool,` to `flagEnvFuncs` in `singularity.go`.  But I did that and it still isn't working 🤔

**Comment by GodloveD** [comment]
It's not just `$SINGULARITY_NV_OFF` it seems like all env bools are broken.

**Comment by cclerget** [comment]
@GodloveD My bad ... I didn't include it in action flags

**Comment by cclerget** [comment]
@GodloveD Fixed, should work fine now :)

**Comment by GodloveD** [comment]
heh.  I was so tired last night I couldn't figure that silly thing out for the life of me.

**Review by GodloveD — APPROVED** [review]
lgtm

**Comment by GodloveD** [comment]
Thanks @cclerget !
