### PR TITLE
Non interactive newkey

### LINKED ISSUE #4232: 'key newpair' should have a non-interactive option
## Version of Singularity:

```
3.3
```

### Expected behavior

`singularity key newpair` should be non-interactive, we should pass all the key information as arguments. But if no arguments are passed, then it should be interactive as it is now.

### Actual behavior

Only interactive right now.

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by pisarukv**
closes https://github.com/sylabs/singularity/issues/4232

### CODE REVIEW

File: pkg/sypgp/sypgp.go [hunk 1]
```diff
@@ -471,35 +481,60 @@ func (keyring *Handle) genKeyPair(name, comment, email, passphrase string) (*ope
...
-	if err != nil {
-		return nil, err
+	if opts.Password == nil {
+		// get a password
+		p, err := interactive.GetPassphrase("Enter a passphrase : ", 3)
+		if err != nil {
+			return nil, err
+		}
+		if p == "" {
+			a, err := interactive.AskYNQuestion("n", "WARNING: if there is no password set, your key is not secure. Do you want to continue? [y/n]")
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]:
```suggestion
			a, err := interactive.AskYNQuestion("n", "WARNING: if there is no password set, your key is not secure. Do you want to continue? [y/n] ")
```

File: pkg/sypgp/sypgp.go [hunk 2]
```diff
@@ -57,6 +57,14 @@ type Handle struct {
 	path string
 }
 
+// GenKeyPairOptions parameters needed for generating new key pair.
+type GenKeyPairOptions struct {
+	Name     *string
```
Comment (WestleyK) [inline pkg/sypgp/sypgp.go]: Why are you using pointers here?

**Review by WestleyK — CHANGES_REQUESTED** [review]
Looks good, just what I was thinking about using a struct to pass the the key information. Just a couple suggestions about the workflow...

Imo, if you just specify one (or all but one) of the key requirements with the command line, it should fail. Because if a user (or script) only passes the `--name`, `--pass`, and forgets the `--email`, the script will hang. I suggest that if not all the key requirements are passed, it should fail. Heres a example:

```bash
$ singularity key newpair --name=test --password=test123
ERROR:   Missing '--email' argument
```

Another suggestion is to change your shorthand arguments to caps, like `-e` to `-E`. The reason is that some user may only use one dash (`-`) for the long argument, that will result in a unexpected output. Heres a example:

```bash
$ singularity key newpair -email=foo@sylabs.io
# will result in a email of: "mail=foo@sylabs.io"
```

By using caps as the short arguments, that can be avoided.

File: pkg/sypgp/sypgp.go (hunk 2 above)
Comment (pisarukv) [reply pkg/sypgp/sypgp.go]: Since i want to distinguish when user didn't pass a flag and when he specified empty field. For example, empty string for password field is a valid value and without reference we will not know whether to ask user input or not.

File: pkg/sypgp/sypgp.go [hunk 3]
```diff
@@ -445,17 +453,19 @@ func (keyring *Handle) RemovePubKey(toDelete string) error {
 	return keyring.storePubKeyring(newKeyList)
 }
 
-func (keyring *Handle) genKeyPair(name, comment, email, passphrase string) (*openpgp.Entity, error) {
+func (keyring *Handle) genKeyPair(opts GenKeyPairOptions) (*openpgp.Entity, error) {
 	conf := &packet.Config{RSABits: 4096, DefaultHash: crypto.SHA384}
 
-	entity, err := openpgp.NewEntity(name, comment, email, conf)
+	entity, err := openpgp.NewEntity(*opts.Name, *opts.Comment, *opts.Email, conf)
```
Comment (sashayakovtseva) [inline pkg/sypgp/sypgp.go]: Possible nil dereference?

**Comment by sashayakovtseva** [comment]
@WestleyK you are right about capital shorthands, but we already have them lowercase almost everywhere, so maybe worth sticking with lowers here as well for CLI consistency.

File: pkg/sypgp/sypgp.go (hunk 3 above)
Comment (sashayakovtseva) [reply pkg/sypgp/sypgp.go]: Nevermind.
Maybe add a comment clarifying that `opts` should not container nil values (except pswd)?

**Review by sashayakovtseva — APPROVED** [review]
LGTM!

**Comment by WestleyK** [comment]
> @WestleyK you are right about capital shorthands, but we already have them lowercase almost everywhere, so maybe worth sticking with lowers here as well for CLI consistency.

Actually, the only non-cap short option that requires a option is `-o, --overlay` for `run` (afaik). Everything else that requires a additional option is a cap, like `-B` for `--bind`, `-H`, for `--home`, `-W` for  `--workdir` and so on... Also, I think its more "standard" to use caps in short arguments that require a variable, like gcc, and many other programs. 

_I still recommend changing the shorthand arguments to caps._

**Review by WestleyK — COMMENTED** [review]
I still like the idea of failing if a argument is missing, like: 

```bash
$ singularity key newpair --name=test --password=test123
ERROR:   Missing '--email' argument
```

Thats something we can change later...

**But** something I do suggest changing, is that when you do:

```bash
$ singularity key newpair --name=test --email=foobar@hush.com -Cnull -Ppsk
Would you like to push it to the keystore? [Y,n] 
```

Theres no argument to disable this question. One option is to add another argument like `-l`, `--no-push` (-l for local) to avoid that interactive question.

_sorry its taking me a little longer to review..._

**Comment by pisarukv** [comment]
@WestleyK about push to the keystore we have --push(-U) flag. If the flag specified we will not ask the question.

**Comment by pisarukv** [comment]
About failing if an argument is missing. Not sure that it's what user are expecting while using flags. Need to think about it a bit more. Maybe we can pass all that options via config (yaml, json). I'll create an issue for that.

**Comment by WestleyK** [comment]
> @WestleyK about push to the keystore we have --push(-U) flag. If the flag specified we will not ask the question.

I saw that, but is there a flag to disable the push without a question?

**Comment by pisarukv** [comment]
Got it. My bad in documenting push flag, but it suppose to be a bool flag. So if User will pass —push=false the push will be disabled without a question.

File: cmd/internal/cli/key_newpair.go [hunk 4]
```diff
@@ -6,34 +6,194 @@
...
+	}
+
+	keyNewPairPush     bool
+	KeyNewPairPushFlag = &cmdline.Flag{
+		ID:           "KeyNewPairPushFlag",
+		Value:        &keyNewPairPush,
+		DefaultValue: false,
+		Name:         "push",
+		ShortHand:    "U",
+		Usage:        "push generated key to a keystore",
```
Comment (WestleyK) [inline cmd/internal/cli/key_newpair.go]:
```suggestion
		Usage:        "specify to push the public key to the remote keystore (default true)",
```

And make the default behavior to push/true. Because that is the default when interactively generating a newpair.

Also suggest adding a example in `docs.KeyNewPairExample` of generating a newpair non-interactively, with `--push=false`.

File: cmd/internal/cli/key_newpair.go [hunk 5]
```diff
@@ -6,34 +6,194 @@
...
-			os.Exit(2)
+var (
+	keyNewPairName     string
+	KeyNewPairNameFlag = &cmdline.Flag{
+		ID:           "KeyNewPairNameFlag",
+		Value:        &keyNewPairName,
+		DefaultValue: "",
+		Name:         "name",
+		ShortHand:    "N",
+		Usage:        "keys owner name",
```
Comment (WestleyK) [inline cmd/internal/cli/key_newpair.go]:
```suggestion
		Usage:        "key owner name",
```

Although, `keys` (with the `s`) would be correct, because theres two keys. But `key` sounds better imo.

File: cmd/internal/cli/key_newpair.go [hunk 6]
```diff
@@ -6,34 +6,194 @@
...
+	}
+
+	keyNewPairEmail     string
+	KeyNewPairEmailFlag = &cmdline.Flag{
+		ID:           "KeyNewPairEmailFlag",
+		Value:        &keyNewPairEmail,
+		DefaultValue: "",
+		Name:         "email",
+		ShortHand:    "E",
+		Usage:        "keys owner email",
```
Comment (WestleyK) [inline cmd/internal/cli/key_newpair.go]: Same here:

```suggestion
		Usage:        "key owner email",
```

File: cmd/internal/cli/key_newpair.go [hunk 7]
```diff
@@ -6,34 +6,194 @@
...
+	}
+
+	keyNewPairComment     string
+	KeyNewPairCommentFlag = &cmdline.Flag{
+		ID:           "KeyNewPairCommentFlag",
+		Value:        &keyNewPairComment,
+		DefaultValue: "",
+		Name:         "comment",
+		ShortHand:    "C",
+		Usage:        "keys comment",
```
Comment (WestleyK) [inline cmd/internal/cli/key_newpair.go]: Same here

```suggestion
		Usage:        "key comment",
```

File: cmd/internal/cli/key_newpair.go [hunk 8]
```diff
@@ -6,34 +6,194 @@
...
+	}
+
+	keyNewPairPassword     string
+	KeyNewPairPasswordFlag = &cmdline.Flag{
+		ID:           "KeyNewPairPasswordFlag",
+		Value:        &keyNewPairPassword,
+		DefaultValue: "",
+		Name:         "password",
+		ShortHand:    "P",
+		Usage:        "keys password",
```
Comment (WestleyK) [inline cmd/internal/cli/key_newpair.go]: And here

```suggestion
		Usage:        "key password",
```

**Review by WestleyK — COMMENTED** [review]
Yes, now I understand the `--push` flag. I just have a couple more suggestions. After that, it looks good :+1:

**Comment by pisarukv** [comment]
@Westley Thanks for your fixes!

**Review by WestleyK — COMMENTED** [review]
This looks good. Can you just add this example to the key newpair help?

```go
Examples:
  $ singularity key newpair --password=psk --name=your-name --comment="key comment" --email=mail@email.com --push=false
```

After that, this looks good to go!

**Review by WestleyK — APPROVED** [review]
Looks good to me :+1: Thanks for fixing this up.

File: go.mod [hunk 9]
```diff
@@ -100,7 +100,7 @@ require (
 	google.golang.org/grpc v1.20.0 // indirect
 	gopkg.in/cheggaaa/pb.v1 v1.0.28
 	gopkg.in/yaml.v2 v2.2.2
-	gotest.tools v2.2.0+incompatible // indirect
+	gotest.tools v2.2.0+incompatible
```
Comment (mem) [inline go.mod]: please don't add this, change the code to use gotest.tools/v3

**Review by mem — CHANGES_REQUESTED** [review]

**Review by mem — APPROVED** [review]
