### PR TITLE
Set the HOME environment variable when setting different privileges during testing

### LINKED ISSUE #1969: Docker tests failing with JSON errors on openSuSE
## Version of Singularity:

singularity version 3.0.0-alpha.1-217-g41c253f6-dirty

### Expected behavior

Docker tests pass.

### Actual behavior

All the tests that use `singularity --build docker://` seem to fail on openSuSE. They pass without issue on CentOS.

=== RUN   TestDockerPermissions
--- FAIL: TestDockerPermissions (0.01s)
    docker_test.go:96: ^[[33mWARNING:^[[0m Authentication token file not found : Only pulls of public images will succeed
        2018/09/12 06:18:38 Error initializing source docker://dctrud/docker-singularity-userperms:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input

docker_test.go:97: unexpected failure: exit status 1

---

=== RUN   TestDockerWhiteoutSymlink
--- FAIL: TestDockerWhiteoutSymlink (0.01s)
    docker_test.go:148: ^[[33mWARNING:^[[0m Authentication token file not found : Only pulls of public images will succeed
        2018/09/12 06:39:44 Error initializing source docker://dctrud/docker-singularity-linkwh:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input

docker_test.go:149: unexpected failure: exit status 1

---

=== RUN   TestSandboxAssemblerDocker
^[[0mDEBUG   ^[[0m[U=1000,P=20289]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-oci-011090937
2018/09/12 06:44:44 Error initializing source docker://alpine:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input
FAIL    github.com/singularityware/singularity/src/pkg/build/assemblers 0.038s

---

=== RUN   TestOCIConveyorDocker
^[[0mDEBUG   ^[[0m[U=1000,P=20318]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-oci-390489775
2018/09/12 06:44:48 Error initializing source docker://alpine:latest: error getting username and password: error reading JSON file "/root/.docker/config.json": error unmarshaling JSON at "/root/.docker/config.json": unexpected end of JSON input
FAIL    github.com/singularityware/singularity/src/pkg/build/sources    1.859s

---

### Steps to reproduce behavior

Run `make test` after building on openSuSE. Probably has the same issues on SLE, but did not verify.

### PR DESCRIPTION
**Pull request by jscook2345**
**Description of the Pull Request (PR):**

Make sure to set the environment variable `HOME` to the correct value for whatever uid you are changing privileges to during testing.

**This fixes or addresses the following GitHub issues:**

- Fixes #1969 

**Checkoff for all PRs:**

- [ ] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [X] I have tested this PR locally with a `make test`
- [X] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [X] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

File: src/pkg/test/privilege.go [hunk 1]
```diff
@@ -123,5 +133,20 @@ func getUnprivIDs(pid int) (uid int, gid int) {
 func init() {
 	origUID = os.Getuid()
 	origGID = os.Getgid()
+	origUser, err := user.LookupId(fmt.Sprintf("%d", origUID))
```
Comment (tri-adam) [inline src/pkg/test/privilege.go]: Nitpick: `strconv. Itoa(origUID)` in place of `fmt.Sprintf()`.

File: src/pkg/test/privilege.go [hunk 2]
```diff
@@ -123,5 +133,20 @@ func getUnprivIDs(pid int) (uid int, gid int) {
...
+
+	if err != nil {
+		log.Fatalf("err: %s", err)
+	}
+
+	origHome = origUser.HomeDir
+
 	unprivUID, unprivGID = getUnprivIDs(os.Getpid())
+	unprivUser, err := user.LookupId(fmt.Sprintf("%d", unprivUID))
```
Comment (tri-adam) [inline src/pkg/test/privilege.go]: Nitpick: `strconv. Itoa(origUID)` in place of `fmt.Sprintf()`.

**Review by tri-adam — CHANGES_REQUESTED** [review]
Looks good, just one tiny comment in two places.

**Review by tri-adam — APPROVED** [review]
