### PR TITLE
Wrap inspect command around singularity exec

### LINKED ISSUE #3779: Problem with inspect command with singularity `--without-suid` installation
## Version of Singularity:

v3.2.1
v3.3.0-rc.1

### Expected behavior

I do run the command
```
singularity inspect test.sif 
```

### Actual behavior
I got the message:

```
FATAL:   Unable to prossess command: fork/exec /home/alazzaro/Work/containers/singularity/singularity_install_v3.3.0-rc.1/libexec/singularity/bin/starter-suid: no such file or directory: 
```

### Steps to reproduce behavior

- Install on Ubuntu 19.04
- Install singularity rootless: `./mconfig --without-suid --prefix=${SINGULARITY} -c "gcc" -x "g++"`

### LINKED ISSUE #4724: Figure out what inspect means in a workflow without setuid
### Version of Singularity:

All.

### Expected behavior

We should have a way to access the metadata of an image even in the context of a workflow without setuid.

### Actual behavior

```
$ singularity inspect ./lolcow_latest.sif 
WARNING: No metadata partition, searching in container...
FATAL:   Unable to process command: while running /home/gvallee/install/singularity_master/libexec/singularity/bin/starter-suid: exit status 1: ERROR  : Failed to set effective UID to 0
```

### Steps to reproduce this behavior

In a context of a workflow without setuid, create an image with metadata and try to use the `inspect` command on the image. It will return an unclear error message.

### What OS/distro are you running

All.

### How did you install Singularity

Any method

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

`inspect` command is now wrapped around `singularity exec` to address issue for unprivileged installation unable to inspect image. It also avoid to duplicate code.

### This fixes or addresses the following GitHub issues:

- Fixes #4724
- Fixes #3779

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/inspect_linux.go [hunk 1]
```diff
@@ -425,34 +422,26 @@ var InspectCmd = &cobra.Command{
...
+
+	cmd := exec.Command(singularityCmd, cmdArgs...)
+	cmd.Stdout = &stdout
+	cmd.Stderr = &stderr
+	// move to the root to not bind the current working directory
+	// while inspecting the image
+	cmd.Dir = "/"
+
+	if err := cmd.Run(); err != nil {
+		sylog.Fatalf("Unable to process command: %s: error output:\n%s", err, stderr.String())
```
Comment (WestleyK) [inline cmd/internal/cli/inspect_linux.go]: Do we want to return the error instead of exiting?

```suggestion
		return "", fmt.Errorf("unable to process command: %s: error output:%s", err, stderr.String())
```

**Review by WestleyK — COMMENTED** [review]
This looks good, only one suggestion about error returning.

**Comment by gvallee** [comment]
FYI, I tested it with my workflow and it works

File: cmd/internal/cli/inspect_linux.go (hunk 1 above)
Comment (cclerget) [reply cmd/internal/cli/inspect_linux.go]: Fixed, thanks !

File: cmd/internal/cli/inspect_linux.go [hunk 2]
```diff
@@ -425,34 +422,26 @@ var InspectCmd = &cobra.Command{
...
+
+	cmd := exec.Command(singularityCmd, cmdArgs...)
+	cmd.Stdout = &stdout
+	cmd.Stderr = &stderr
+	// move to the root to not bind the current working directory
+	// while inspecting the image
+	cmd.Dir = "/"
+
+	if err := cmd.Run(); err != nil {
+		return "", fmt.Errorf("Unable to process command: %s: error output:\n%s", err, stderr.String())
```
Comment (WestleyK) [inline cmd/internal/cli/inspect_linux.go]: This should be un-capitalized (but not required)

```suggestion
		return "", fmt.Errorf("unable to process command: %s: error output:\n%s", err, stderr.String())
```

**Review by WestleyK — APPROVED** [review]
Looks good, only minor suggestion about the error message (not necessary, will be fine as is).

**Review by gvallee — APPROVED** [review]
lgtm
