### PR TITLE
Better handle the path to the Singularity system configuration file

### LINKED ISSUE #3976: Better handle path to the Singularity config file
## Version of Singularity:

All.

### Expected behavior

Paths should be built using `filepath.Join()` or something similar instead of `"/a/path"+"/a/subdir".

### Actual behavior

The code has a lot of `buildcfg.SYSCONFDIR + "/singularity/singularity.conf"`.

### Steps to reproduce behavior

N/A.

### PR DESCRIPTION
**Pull request by gvallee**
**Description of the Pull Request (PR):**

Better handle the path to the Singularity system configuration file by calling a specific API instead of the creation of a string (which did not even use `filepath.Join()`).

**This fixes or addresses the following GitHub issues:**

- Fixes #3976 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/actions_linux.go [hunk 1]
```diff
@@ -129,7 +130,7 @@ func execStarter(cobraCmd *cobra.Command, image string, args []string, name stri
 
 	engineConfig := singularityConfig.NewConfig()
 
-	configurationFile := buildcfg.SYSCONFDIR + "/singularity/singularity.conf"
+	configurationFile := files.GetSysConfigFile()
```
Comment (mem) [inline cmd/internal/cli/actions_linux.go:136]: there's the `syfs` package in `pkg/syfs`. I think that's a better place for this code.

**Review by mem — CHANGES_REQUESTED** [review]

File: cmd/internal/cli/actions_linux.go (hunk 1 above)
Comment (gvallee) [reply cmd/internal/cli/actions_linux.go:136]: I put it there because it is not user-facing but internal; what is in `syfs` is related to the user-level file system details (e.g., user-level config files). Here we deal with the system-level Singularity configuration file.

**Review by jscook2345 — APPROVED** [review]
Approve pending agreement on filesystem location.

File: cmd/internal/cli/actions_linux.go (hunk 1 above)
Comment (mem) [reply cmd/internal/cli/actions_linux.go:136]: Having two packages that deal with the layout of the singularity files is confusing. There's some pending clean up that needs to happen in terms of what's available to other packages (if that's what you mean by "user facing") but I would rather have one problem pending of a fix and not two.

Comment (gvallee) [reply cmd/internal/cli/actions_linux.go:136]: Well, issues are there for that. I would prefer to do the right thing here, i.e., put the package in the right place. I guess we need to see if we can find consensus about this because on who review my PRs, it is once one way, once the other way and this is not good to change code based on what appears to me to be personal preferences. In other words, let's set some guidelines.

Comment (cclerget) [reply cmd/internal/cli/actions_linux.go:136]: The rule is pretty simple here, if the package use `buildcfg` constants, it's an internal package because it would be unusable as public package otherwise.

An other approach could be to add some get accessor in `buildcfg` package to have things like `buildcfg.GetSingularityConfigFile()`

Comment (gvallee) [reply cmd/internal/cli/actions_linux.go:136]: I think there is agreement that the current location is adequate. We also have issue #3995 to finalize the discussion and agree on the potential next steps.

Comment (mem) [reply cmd/internal/cli/actions_linux.go:136]: Agreement is something else.

I hadn't realized that you sneaked the change into a different unrelated code review. You could have said so.

**Review by mem — APPROVED** [review]
The part where the changes were requested was merged using a different PR.

**Review by WestleyK — APPROVED** [review]
Looks good to me! Thanks :+1:

**Review by jmstover — APPROVED** [review]
