### PR TITLE
Fix fakeroot image cleanup permission denied and rework starter execution util

### LINKED ISSUE #4263: singularity shell --fakeroot leaves file permission problem
This is rather an inherent problem of fakeroot, but I hope Singularity can do something smart about this. 

## Version of Singularity:

singularity version 3.3.0

### Expected behavior
ownership of files and directories should be mapped back to the USER who starts the container

### Actual behavior
```
INFO:    Cleaning up image...
ERROR:   failed to delete container image /tmp/rootfs-569592909: unlinkat /tmp/rootfs-569592909/home/testsub/.bash_logout: permission denied
```

### Steps to reproduce behavior

- start a container in shell mode with fake root: `singularity shell --fakeroot library://ubuntu`
- create a new user, say with username `testsub` inside the container with useradd command. 
- create a test directory, say `testdir` under fakeroot's home, and set permission: `chmod 777 testdir`. This is to ensure it is writetable to user `testsub`.
- switch to `testsub` user and cd into `testdir`. 
- create some test file there, for example `touch testfilebytestsub`.
- exit the container
- observe two things: `testfilebytestsub` under `testdir`  has user id and group id that are different from the current users; and files under `/home/testsub` which is actually under container's temporary directory also have the same ownerships as `testfilebytessub`. That means the HOSTUSER can't cleanup files without sudo/admin right.

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Move internal/pkg/util/exec/pipe* to internal/pkg/util/starter and code to execute starter was refactored to remove some code redundancies disseminate in CLI and internal packages.

Also fix issue during image cleanup when using fakeroot with SUID workflow, because CleanupContainer method is called by master process when fakeroot+SUID workflow are in use this method is executed outside of the fakeroot context which means that under some circumstances the image removal may fail with a permission denied error. To fix the issue the fakeroot engine is called in order to execute /bin/rm command.

**This fixes or addresses the following GitHub issues:**

- Fixes #4263

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/util/starter/starter.go [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+type Command struct {
+	path   string
+	env    []string
+	stdin  io.Reader
+	stdout io.Writer
+	stderr io.Writer
+}
+
+// Exec executes the starter binary in place of the caller if
+// there is no error. This function never return on success.
```
Comment (sashayakovtseva) [inline internal/pkg/util/starter/starter.go]:
```suggestion
// there is no error. This function never returns on success.
```

**Review by sashayakovtseva — APPROVED** [review]
