### PR TITLE
Information / option to fix restrictive sandbox permissions

### LINKED ISSUE #4628: Warn user about sandboxes that need chmod to rm
We are now building sandboxes to their final destination, and respecting permissions in the OCI/docker layers properly (via change to umoci). If we don't go back to mangling permissions for 3.5 then we should have some kind of warning to people creating sandboxes that they may need a `chmod` before they can `rm` etc.

### Version of Singularity:

What version of Singularity are you using? Run:

```
master
```

### Expected behavior

```
singularity build --sandbox mysandbox docker://centos:7
...
Info: Singularity now closely replicates permissions in docker/oci images for better compatibility.
Warning: This sandbox contains files/directories that cannot be removed until permissions are modified: `chmod -R u+rwX mysandbox`
```

### Actual behavior

```
singularity build -s mysandbox docker://centos:7
...
rm -rf mysandbox/
rm: cannot remove 'mysandbox/root/.bash_profile': Permission denied
rm: cannot remove 'mysandbox/root/.bash_logout': Permission denied
...
```

### PR DESCRIPTION
**Pull request by dtrudg**
For discussion of the changes introduced here, please go to: #4671 

-----
## Description of the Pull Request (PR):

With umoci unpacking, 3.5 will honor the permissions in OCI/docker
layers when extracting them. This can result in a sandbox build
containing files/dirs that cannot be 'rm'd without modifying the
permissions. To make things easier for users, and provide a way to use
the 3.4 behavior in a transition period:

- Add a `--fix-perms` option that will modify the permissions on
oci/docker layer extraction like 3.4 and earlier did.
- Warn the user about future removal of the `--fix-perms` option, and
provide a link to the discussion issue.
- When `--fix-perms` is not used, scan the result of OCI/docker extraction
to warn the user if any files in there will not be easily removable,
directing them to `chmod -R u+rwX` and the `--fixperms` option.

#### How this looks...

*Built an ubuntu sandbox (no permission issues)*

```
dave@piran~/permcheck> singularity  build -s mysandbox docker://ubuntu
INFO:    Starting build...
Getting image source signatures
Copying blob 22e816666fd6 skipped: already exists
Copying blob 079b6d2a1e53 skipped: already exists
Copying blob 11048ebae908 skipped: already exists
Copying blob c58094023a2e skipped: already exists
Copying config 6cd71496ca done
Writing manifest to image destination
Storing signatures
2019/10/25 10:41:31  info unpack layer: sha256:22e816666fd6516bccd19765947232debc14a5baf2418b2202fd67b3807b6b91
2019/10/25 10:41:32  info unpack layer: sha256:079b6d2a1e53c648abc48222c63809de745146c2ee8322a1b9e93703318290d6
2019/10/25 10:41:32  info unpack layer: sha256:11048ebae90883c19c9b20f003d5dd2f5bbf5b48556dabf06c8ea5c871c8debe
2019/10/25 10:41:32  info unpack layer: sha256:c58094023a2e61ef9388e283026c5d6a4b6ff6d10d4f626e866d38f061e79bb9
INFO:    Creating sandbox directory...
INFO:    Build complete: mysandbox

```

*Build a centos:7 sandbox*
```
dave@piran~/permcheck> singularity  build -s mysandbox docker://centos:7
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
Getting image source signatures
Copying blob d8d02d457314 skipped: already exists
Copying config acab94af64 done
Writing manifest to image destination
Storing signatures
2019/10/25 10:31:54  info unpack layer: sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
2019/10/25 10:31:55  warn rootless{usr/bin/ping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/10/25 10:31:56  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/10/25 10:31:56  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
WARNING: Permission handling has changed in Singularity 3.5 for improved OCI compatibility
WARNING: The sandbox will contain files/dirs that cannot be removed until permissions are modified
WARNING: Use 'chmod -R u+rwX' to set permissions that allow removal
WARNING: Use the '--fix-perms' option to 'singularity build' to modify permissions at build time
INFO:    Creating sandbox directory...
INFO:    Build complete: mysandbox
```

*Build a centos:7 sandbox with `--fix-perms`*
```
dave@piran~/permcheck> singularity  build --fix-perms -s mysandbox docker://centos:7
INFO:    Starting build...
Getting image source signatures
Copying blob d8d02d457314 skipped: already exists
Copying config acab94af64 done
Writing manifest to image destination
Storing signatures
2019/10/25 10:40:39  info unpack layer: sha256:d8d02d45731499028db01b6fa35475f91d230628b4e25fab8e3c015594dc3261
2019/10/25 10:40:39  warn rootless{usr/bin/ping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/10/25 10:40:40  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
2019/10/25 10:40:41  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
WARNING: The --fix-perms option modifies the filesystem permissions on the resulting container and will be removed in a future release.
WARNING: You can provide feedback about this change at https://github.com/sylabs/singularity/issues/4671
INFO:    Creating sandbox directory...
INFO:    Build complete: mysandbox
```

### This fixes or addresses the following GitHub issues:

 - Fixes #4628

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by vsoch** [comment]
I think the message line:

```
Use the '--fixperms' option to 'singularity build'...
```
Should have `--fix-perms` instead?

File: pkg/build/types/bundle.go [hunk 1]
```diff
@@ -46,6 +46,8 @@ type Options struct {
 	// encryption if applicable.
 	// A nil value indicates encryption should not occur.
 	EncryptionKeyInfo *crypt.KeyInfo
+	// ImgCache stores a pointer to the image cache to use.
```
Comment (dtrudg) [inline pkg/build/types/bundle.go:49]: Note - this change in order of the struct was needed to satisfy the `malign` linter - so that `bool` are not split by a pointer which creates a memory alignment issue padding required.

**Comment by vsoch** [comment]
I think there is still some confusion between the code / messages, and it's because the flag is `fixperms` as a variable, but the actual flag for the user `fix-perms` so the message should reference `--fix-perms`. It's fixed in the code now, but you might want to tweak the example output above (still has fixperms) along with this line with the now fixed --fixperms https://github.com/sylabs/singularity/pull/4672/files#diff-3e3822122223bf0c8d3ad19220a16191R79

**Comment by dtrudg** [comment]
Thanks @vsoch - example at the top has been modified, and I did find 3 incorrect ones in the code comments fixed in 64eef3b too.

**Comment by vsoch** [comment]
btw you've done a really good job bringing this up, discussing with the community on the list and slack. Just wanted to say :)

**Review by ikaneshiro — APPROVED** [review]
lgtm

**Comment by dtrudg** [comment]
> btw you've done a really good job bringing this up, discussing with the community on the list and slack. Just wanted to say :)

Appreciate the feedback. Thanks!
