### PR TITLE
Fix docker pull overwrite

### LINKED ISSUE #2939: Pull from Docker Overwrites Destination
## Version of Singularity:

`3.1.0`

### Expected behavior

Pulling from `docker://` should not overwrite an image file if it already exists, unless `-F`/`--force` options are passed.

### Actual behavior

Pulling from `docker://` overwrites an image file, even when `-F`/`--force` options are not passed.

### Steps to reproduce behavior

Pull a container from the Library twice, observe it works as expected. The first pull succeeds, and the second won't overwrite an image file that already exists:

```sh
[adam@ip-172-31-94-96 ~]$ singularity pull library://alpine
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Downloading library image
 2.59 MiB / 2.59 MiB [======================================================================================================================================================================] 100.00% 39.42 MiB/s 0s
[adam@ip-172-31-94-96 ~]$ singularity pull library://alpine
WARNING: Authentication token file not found : Only pulls of public images will succeed
```

SHUB also works properly:

```sh
$ singularity pull shub://GodloveD/lolcow
WARNING: Authentication token file not found : Only pulls of public images will succeed
 87.57 MiB / 87.57 MiB [====================================================================================================================================================================] 100.00% 41.59 MiB/s 2s
$ md5sum lolcow_latest.sif 
ee4aae1ea378ad7c0299b308c703187a  lolcow_latest.sif
$ singularity pull shub://GodloveD/lolcow
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   image file already exists - will not overwrite
```

Pull a container from `docker://`, observe the file changes:

```sh
$ singularity pull docker://alpine
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c
Copying config sha256:ff8df268d29ccbe81cdf0a173076dcfbbea4bb2b6df1dd26766a73cb7b4ae6f7
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: alpine_latest.sif
$ md5sum alpine_latest.sif 
d9feb495c462f2753d1229b6fc0b19d3  alpine_latest.sif
$ singularity pull docker://alpine
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c
Copying config sha256:ff8df268d29ccbe81cdf0a173076dcfbbea4bb2b6df1dd26766a73cb7b4ae6f7
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: alpine_latest.sif
$ md5sum alpine_latest.sif 
d0b3647836f4b28bbc7656011f82a277  alpine_latest.sif
```

### PR DESCRIPTION
**Pull request by ikaneshiro**
**Description of the Pull Request (PR):**

Checks for an existing file before building a container to that location. Force option circumvents this check and a build will overwrite the location.

**This fixes or addresses the following GitHub issues:**

- Fixes #2939 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: cmd/internal/cli/pull.go [hunk 1]
```diff
@@ -174,6 +174,12 @@ func pullRun(cmd *cobra.Command, args []string) {
 	case HTTPProtocol, HTTPSProtocol:
 		libexec.PullNetImage(name, args[i], force)
 	default:
+		if !force {
```
Comment (bauerm97) [inline cmd/internal/cli/pull.go:177]: So, I think as a fix for this issue this PR is fine. But at the same time, the way we're handling `--force` looks like complete and utter spaghetti code across the board. We're replicating this code block 2 times, but passing `force` to `PullShubImage` and `PullNetImage`. Not to mention that `libexec` as a package is meaningless and should *really* just be removed altogether. Those functions (and the rest of the code in this switch statement) should seriously only live in `internal/app/singularity`

**Review by bauerm97 — APPROVED** [review]

File: cmd/internal/cli/pull.go (hunk 1 above)
Comment (ikaneshiro) [reply cmd/internal/cli/pull.go:177]: Agreed, should be something to be refactored in the future
