### PR TITLE
Documentation for Key Search with Fingerprint 

### LINKED ISSUE #2708: Improve Key Search Documentation
## Version of Singularity

`3.0.3`

### Expected behavior

A user who wishes to search for a key by ID or fingerprint should find it simple to do so based on our documentation. In particular, a key ID or fingerprint must be prefixed with `0x` like so:

```sh
$ singularity keys search 0x7828feaed94b06a2cba6c9bf46c37f670809dd2e
Search results for '0x7828feaed94b06a2cba6c9bf46c37f670809dd2e'

Type bits/keyID     Date       User ID
--------------------------------------------------------------------------------
pub  4096R/0809DD2E 2018-09-17 Adam Hughes (testing) <adam@sylabs.io>
--------------------------------------------------------------------------------
```

### Actual behavior

The documentation doesn't mention anything about how to search for a key by ID or fingerprint:

```sh
$ singularity keys search -h
Search for keys matching string argument

Usage:
  singularity keys search [search options...] <search_string>

Description:
  The 'keys search' command allows you to connect to a key server and look for 
  public keys matching the string argument passed to the command line.

Options:
  -h, --help         help for search
  -u, --url string   specify the key server URL (default
                     "https://keys.sylabs.io")


Examples:
  $ singularity keys search sylabs.io


For additional help or support, please visit https://www.sylabs.io/docs/
```

### Steps to reproduce behavior

N/A

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

This PR will add some documentation for searching key with a fingerprint/key ID.

## This fixes or addresses the following GitHub issues:

- Fixes #2708

### CODE REVIEW

File: docs/content.go [hunk 1]
```diff
@@ -249,10 +249,18 @@ Enterprise Performance Computing (EPC)`
 	KeySearchUse   string = `search [search options...] <search_string>`
 	KeySearchShort string = `Search for keys matching string argument`
 	KeySearchLong  string = `
-  The 'key search' command allows you to connect to a key server and look for 
-  public keys matching the string argument passed to the command line.`
+  The 'key search' command allows you to connect to a key server and look for
+  public keys matching the string argument passed to the command line. You can
```
Comment (mem) [inline docs/content.go]:
```suggestion
  public keys matching the argument passed to the command line. You can
```

File: docs/content.go [hunk 2]
```diff
@@ -249,10 +249,18 @@ Enterprise Performance Computing (EPC)`
...
+  also search for a key by the fingerprint, (or key ID) by adding '0x' before the
```
Comment (mem) [inline docs/content.go]:
```suggestion
  also search for a key by fingerprint or key ID by adding '0x' before the
```

File: docs/content.go [hunk 3]
```diff
@@ -249,10 +249,18 @@ Enterprise Performance Computing (EPC)`
...
+  fingerprint.`
 	KeySearchExample string = `
-  $ singularity key search sylabs.io`
+  $ singularity key search sylabs.io
+
+  # note the '0x' before the fingerprint:
+  $ singularity key search 0x1CEC42121A994A3FBFAAF6CC51BE5020C508C7E9
+
+  # search with the sort ID: (again, theres '0x' before the ID)
```
Comment (mem) [inline docs/content.go]:
```suggestion
  # search by key ID: (again, there's '0x' before the ID)
```

**Review by mem — CHANGES_REQUESTED** [review]

**Review by mem — APPROVED** [review]
