### PR TITLE
Converted the remote command status code to readable string

### LINKED ISSUE #3000: Remote login with bad token gives uninformative error
## Version of Singularity:

3.1.0

### Expected behavior

$ singularity remote login sylabs
Generate an API Key at https://cloud.sylabs.io/auth/tokens, and paste here:
API Key:
FATAL:   while verifying token: error response from server: Invalid Token

### Actual behavior

$ singularity remote login sylabs
Generate an API Key at https://cloud.sylabs.io/auth/tokens, and paste here:
API Key:
FATAL:   while verifying token: error response from server: 404

### Steps to reproduce behavior

Try to log into a remote endpoint with an invalid token.

### PR DESCRIPTION
**Pull request by schebro**
**Description of the Pull Request (PR):**

Converted the remote command status code to readable string

Output:
---------
vagrant@vagrant:~/go/src/github.com/sylabs/singularity$ singularity remote login sylabs
Generate an API Key at https://cloud.sylabs.io/auth/tokens, and paste here:
API Key: 
FATAL:   while verifying token: error response from server: Invalid Token

**This fixes or addresses the following GitHub issues:**

- Fixes #3000 

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/remote/remote.go [hunk 1]
```diff
@@ -24,6 +24,10 @@ var (
 	ErrNoDefault = errors.New("no default remote")
 )
 
+var errorCodeMap = map[int]string{
+	404: "Invalid Token",
```
Comment (ikaneshiro) [inline internal/pkg/remote/remote.go:28]: Lets also include 500: "Internal Server Error"

File: internal/pkg/remote/remote.go [hunk 2]
```diff
@@ -212,7 +216,11 @@ func (e *EndPoint) VerifyToken() error {
 	defer res.Body.Close()
 
 	if res.StatusCode != http.StatusOK {
-		return fmt.Errorf("error response from server: %v", res.StatusCode)
+		convStatus := errorCodeMap[res.StatusCode]
```
Comment (ikaneshiro) [inline internal/pkg/remote/remote.go]: Go maps have a way to check the existence of a key like so:
```
convStatus, ok := errorCodeMap[res.StatusCode]
if !ok {
    ...
}
```

**Review by ikaneshiro — CHANGES_REQUESTED** [review]
Looks good, two nitpicks

**Review by ikaneshiro — APPROVED** [review]
