### PR TITLE
Ensure build destination path is not empty

### LINKED ISSUE #5435: Singularity build overwrites CWD when an empty string is passed as destination
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.6.0-rc.4+70-gb15629c3d
```

### Expected behavior

Passing an empty string through the CLI as a build destination should result in a fatal error.

### Actual behavior

Passing an empty string through the CLI as a build destination caused the CWD to be used at the build destination, overwriting data that exists at that location.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
NOTE: Please be careful when replicating as you're current working directory will be removed when the supplied `singularity` command is executed.
```
$ mkdir testdir/
$ touch testdir/file
$ ls -ld testdir/
drwxrwxr-x 2 ian ian 4096 Jul 16 23:00 testdir/
$ cd testdir/
$ ls -l
total 0
-rw-rw-r-- 1 ian ian 0 Jul 16 23:03 file
$ singularity build "" ""
INFO:    Starting build...
INFO:    Creating SIF file...
INFO:    Architecture not recognized, use native
INFO:    Build complete: 
$ ls -l
total 0
$ cd ..
$ ls -l testdir 
-rwxr-xr-x 1 ian ian 40960 Jul 16 23:01 testdir
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### How did you install Singularity

From source.

### PR DESCRIPTION
**Pull request by ikaneshiro**
- Add fs helper to catch empty paths when resolving abs paths
- Update image package to use this new helper
- Add regression test

Signed-off-by: Ian Kaneshiro <iankane@umich.edu>

### This fixes or addresses the following GitHub issues:

 - Fixes #5435 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: e2e/imgbuild/regressions.go [hunk 1]
```diff
@@ -393,3 +393,24 @@ func (c *imgBuildTests) issue5315(t *testing.T) {
...
+		e2e.WithProfile(e2e.UserProfile),
+		e2e.WithCommand("build"),
+		e2e.WithArgs("", ""),
+		e2e.WithDir(cwd),
+		e2e.PostRun(func(t *testing.T) {
+			if !t.Failed() {
+				cleanup(t)
+			}
+		}),
+		e2e.ExpectExit(255),
```
Comment (dtrudg) [inline e2e/imgbuild/regressions.go:429]: I would suggest testing to see that the `cwd` still exists here, or confirm the error message relates to *not* removing the existing directory, and not just rely on the exit code.

It is possible that we could delete a directory, but fail with a 255 error later on for a different reason.

**Review by dtrudg — CHANGES_REQUESTED** [review]
LGTM in general - minor point on the test, where I think given the nature of the bug it'd be nice to check the outcome of exiting with an error is correct... not just that we can an error code.

File: e2e/imgbuild/regressions.go (hunk 1 above)
Comment (ikaneshiro) [reply e2e/imgbuild/regressions.go:429]: Tested against master to make sure it's properly checking the CWD
```
=== RUN   TestE2E/PAR/BUILD/issue_5435
=== PAUSE TestE2E/PAR/BUILD/issue_5435
=== CONT  TestE2E/PAR/BUILD/issue_5435
    TestE2E/PAR/BUILD/issue_5435: singularitycmd.go:663: Running command "/usr/local/bin/singularity build  "
    TestE2E/PAR/BUILD/issue_5435: singularitycmd.go:663: 
        "/usr/local/bin/singularity build  " output:
        INFO:    Starting build...
        INFO:    Creating SIF file...
        INFO:    Architecture not recognized, use native
        INFO:    Build complete: 
        
    TestE2E/PAR/BUILD/issue_5435: singularitycmd.go:663: unexpected success while executing "/usr/local/bin/singularity build  "
    TestE2E/PAR/BUILD/issue_5435: regressions.go:426: cwd overwritten
```

**Review by dtrudg — APPROVED** [review]
:+1:

**Review by cclerget — APPROVED** [review]
LGTM, just wondering if that would make sense to also have an additional check for: CWD == image destination ?

**Review by tri-adam — APPROVED** [review]
LGTM

**Comment by ikaneshiro** [comment]
@cclerget I don't think that's quite necessary as now a user will need to explicitly feed the path of their CWD as the destination and will be prompted to use the `--force` flag if that directory doesn't have the sub-directories associated with a sandbox.

I'm going to go ahead and merge, but if this needs a follow up issue to provide a better warning I am happy to implement that.
