### PR TITLE
Encrypted File System inside SIF

### LINKED ISSUE #3285: Encrypting SIF images
## Version of Singularity:

3.3.0
### Expected behavior

Currently SIFs are not encrypted. Idea here is the encrypt the squashfs portion of SIF while building and decrypting that portion via a loopback device at runtime.

### Actual behavior
Encryption is not currently supported.

### Steps to reproduce behavior

None

### LINKED ISSUE #3517: encrypt the squashfs partition of a SIF image
In order to mount and run encrypted SIF images, one must first be able to simply encrypt the file system.  This is the first little step toward that greater goal.  

This doesn't even really need to be integrated into the Singularity CLI or anything yet.  Just carried out as a POC.

### LINKED ISSUE #3518: mount an encrypted SIF container to the loop device
This is one step in the overall process of encrypting and running encrypted containers.  Don't know if it will be a simple thing to do or if it will require multiple sub-issues.  Once the POC is carried out, will need to integrate into Singularity runtime code as well.

### LINKED ISSUE #3519: Read the contents of an encrypted and mounted SIF image
This is one more POC step to implementing encrypted containers.  After the container is mounted it must be demonstrated that the contents can be accessed.

### LINKED ISSUE #3605: Add command line support for encrypted filesystem
## Version of Singularity:

3.5

### Expected behavior

Add singularity command support to specify if the filesystem needs to be encrypted.
Subsequently read the password during encryption and decryption phases.

### Actual behavior

Not implemented

### Steps to reproduce behavior

NA

### LINKED ISSUE #3662: Add a command line argument to encrypt file system
### Expected behavior

sudo singularity build -e test.sif test.recipe

Enter password to encrypt filesystem: 

### Actual behavior

Not supported yet

### LINKED ISSUE #3664: Root privilege during cleanup
### Expected behavior

During cleanup (exiting the container), "cryptsetup luksClose <dev>" needs to be executed so that we don't end up with stale encrypted devices and loopback devices. CleanupContainer() is run for the regular runtime to perform cleanup operations but it doesn't have root privileges to perform the above operation. 

### Actual behavior

NA

### Steps to reproduce behavior

NA

### PR DESCRIPTION
**Pull request by schebro**
Description of the Pull Request (PR):

Implemented review feedback

Locking /dev/mapper before creating crypt devices to avoid races

Deleted encryptfs.go, which is not necessary

Generate random number for crypt device

Ext3->Squashfs for encrypted FS

This fixes or addresses the following GitHub issues:

Fixes #3605
Fixes #3662
Fixes #3664
Fixes #3285
Fixes #3517
Fixes #3518
Fixes #3519
NOTE: CI tests are still failing. I am resolving the failures now. Pushing the code to get feedback on the latest changes while I resolve other issues.

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 1]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
 		return file.Delete()
 	}
 
+	if engine.EngineConfig.CryptMount != "" {
+		// Elevate the privilege to unmount and delete the crypt device
+		uid := os.Getuid()
+		err := syscall.Setresuid(uid, 0, uid)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: You need to lock os thread with `runtime.LockOSThread()` before escalating privileges and call `runtime.UnlockOSThread()` after privileges drop, otherwise runtime scheduler can execute routine on this thread which could lead to potential side effects

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 2]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+		if err != nil {
+			sylog.Debugf("Err setting suid")
+			return err
+		}
+
+		err = syscall.Unmount("/usr/local/var/singularity/mnt/session/final", syscall.MNT_DETACH)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: You can use `filepath.Join(buildcfg.SESSIONDIR, "final")` to match user custom installation

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 3]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+		if err != nil {
+			syscall.Setresuid(uid, uid, 0)
+			sylog.Debugf("Error while unmounting overlay FS: %s", err)
+			return err
+		}
+
+		err = syscall.Unmount("/usr/local/var/singularity/mnt/session/rootfs", syscall.MNT_DETACH)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: same with `filepath.Join(buildcfg.SESSIONDIR, "rootfs")`

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 4]
```diff
@@ -612,11 +628,16 @@ func (c *container) addRootfsMount(system *mount.System) error {
 	offset := imageObject.Partitions[0].Offset
 	size := imageObject.Partitions[0].Size
 
+	sylog.Debugf("Image type is %v", imageObject.Partitions[0].Name)
+
 	switch imageObject.Partitions[0].Type {
 	case image.SQUASHFS:
 		mountType = "squashfs"
+		sylog.Debugf("Mount type is squashfs")
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: you can remove this debug, it's redundant with line 631

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 5]
```diff
@@ -855,6 +876,7 @@ func (c *container) addKernelMount(system *mount.System) error {
 	} else {
 		sylog.Verbosef("Skipping /sys mount")
 	}
+	err = system.Points.AddBind(mount.KernelTag, "/sbin", "/sbin", bindFlags)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: Need to be removed

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 6]
```diff
@@ -33,6 +38,52 @@ func (t *Methods) Mount(arguments *args.MountArgs, reply *int) (err error) {
...
 
+// Crypt decrypts the loop device
+func (t *Methods) Decrypt(arguments *args.CryptArgs, reply *string) (err error) {
+
+	sylog.Debugf("In Crypt RPC")
+	sylog.Debugf("Crypt RPC running in PID %d", os.Getpid())
+	sylog.Debugf("Loop device is %s", arguments.Loopdev)
+
+	fmt.Print("Enter the password to decrypt File System: ")
+	password, err := terminal.ReadPassword(int(syscall.Stdin))
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: I would rather ask password from master process and pass it as argument in https://github.com/sylabs/singularity/pull/3729/files#diff-784d2c712e51a05593054a6d797ab51bR39

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 7]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+		if err != nil {
+			syscall.Setresuid(uid, uid, 0)
+			sylog.Debugf("Error while unmounting Rootfs: %s", err)
+			return err
+		}
+
+		cmd := exec.Command("/sbin/cryptsetup", "luksClose", engine.EngineConfig.CryptMount)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: Maybe use `exec.LookPath` instead of hardcoded `/sbin/cryptsetup`

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 8]
```diff
@@ -33,6 +38,52 @@ func (t *Methods) Mount(arguments *args.MountArgs, reply *int) (err error) {
...
+
+	crypt_dev := &crypt.Device{
+		MaxDevices: 256,
+	}
+
+	cdev_str, err := crypt_dev.GetCryptDevice()
+
+	sylog.Debugf("Crypt device is %s\n", cdev_str)
+
+	cmd := exec.Command("/sbin/cryptsetup", "luksOpen", arguments.Loopdev, cdev_str, "-v", "--debug")
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: Maybe use `exec.LookPath` instead of hardcoded `/sbin/cryptsetup`

File: internal/pkg/util/fs/mount/mount_linux.go [hunk 9]
```diff
@@ -581,6 +584,7 @@ func (p *Points) AddImage(tag AuthorizedTag, source string, dest string, fstype
 	if flags&(syscall.MS_BIND|syscall.MS_REMOUNT|syscall.MS_REC) != 0 {
 		return fmt.Errorf("MS_BIND, MS_REC or MS_REMOUNT are not valid flags for image mount points")
 	}
+	sylog.Debugf("FStype is %s", fstype)
```
Comment (cclerget) [inline internal/pkg/util/fs/mount/mount_linux.go]: Can also be removed

File: pkg/build/types/bundle.go [hunk 10]
```diff
@@ -64,8 +76,25 @@ type Options struct {
 	NoCleanUp bool `json:"noCleanUp"`
 }
 
+func createLoop(file *os.File, offset, size uint64) (string, error) {
+	loopDev := &loop.Device{
+		MaxLoopDevices: 256,
+		Shared:         true,
```
Comment (cclerget) [inline pkg/build/types/bundle.go]: `Shared` is meaningful when images are open in read-only mode, so it's not required here

File: pkg/build/types/bundle.go [hunk 11]
```diff
@@ -83,10 +112,116 @@ func NewBundle(bundleDir, bundlePrefix string) (b *Bundle, err error) {
...
+		}
+
+		// Create a sparse file in tmp dir
+		f, err := os.Create(b.Path + "/sparse_fs.loop")
+		if err != nil {
+			return nil, err
+		}
+
+		// Create a 500MB sparse file
+		err = f.Truncate(5 * 1e8)
```
Comment (cclerget) [inline pkg/build/types/bundle.go]: We will really need to determine final size dynamically

File: pkg/runtime/engines/singularity/config/config_linux.go [hunk 12]
```diff
@@ -13,9 +13,10 @@ import (
...
-	OciConfig *oci.Config      `json:"ociConfig"`
-	File      *FileConfig      `json:"-"`
-	Network   *network.Setup   `json:"-"`
-	Cgroups   *cgroups.Manager `json:"-"`
+	JSON       *JSONConfig      `json:"jsonConfig"`
+	OciConfig  *oci.Config      `json:"ociConfig"`
+	File       *FileConfig      `json:"-"`
+	Network    *network.Setup   `json:"-"`
+	Cgroups    *cgroups.Manager `json:"-"`
+	CryptMount string           `json:"_"`
```
Comment (cclerget) [inline pkg/runtime/engines/singularity/config/config_linux.go]:
```suggestion
	CryptMount string           `json:"-"`
```

File: vendor/github.com/sylabs/sif/pkg/sif/fmt.go [hunk 13]
```diff
@@ -89,6 +89,8 @@ func fstypeStr(ftype Fstype) string {
 		return "Archive"
 	case FsRaw:
 		return "Raw"
+	case FsEncrypt:
```
Comment (cclerget) [inline vendor/github.com/sylabs/sif/pkg/sif/fmt.go]: This change requires a PR in https://github.com/sylabs/sif repository. We don't touch vendor

File: vendor/github.com/sylabs/sif/pkg/sif/sif.go [hunk 14]
```diff
@@ -148,6 +148,7 @@ const (
 	FsExt3                      // EXT3 file system, RDWR (deprecated)
 	FsImmuObj                   // immutable data object archive
 	FsRaw                       // raw data
+	FsEncrypt                   // Encrypted File System
```
Comment (cclerget) [inline vendor/github.com/sylabs/sif/pkg/sif/sif.go]: same

File: vendor/github.com/sylabs/sif/pkg/sif/sif.go [hunk 15]
```diff
@@ -299,6 +300,7 @@ type DescriptorInput struct {
 	Link      uint32   // link to be set for new descriptor
 	Size      int64    // size of the data object for the new descriptor
 	Alignment int      // Align requirement for data object
+	Encrypt   bool
```
Comment (cclerget) [inline vendor/github.com/sylabs/sif/pkg/sif/sif.go]: same

File: pkg/build/types/bundle.go [hunk 16]
```diff
@@ -83,10 +112,116 @@ func NewBundle(bundleDir, bundlePrefix string) (b *Bundle, err error) {
...
+		}()
+
+		out, err = cmd.CombinedOutput()
+		if err != nil {
+			sylog.Verbosef("Out is %s, err is %s", out, err)
+			return nil, err
+		}
+
+		// Create an EXT3 FS in the mapped device
+		cmd = exec.Command("mkfs.ext3", cdevStr)
```
Comment (cclerget) [inline pkg/build/types/bundle.go]: Disable journal ?

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 17]
```diff
@@ -33,6 +38,52 @@ func (t *Methods) Mount(arguments *args.MountArgs, reply *int) (err error) {
 	return err
 }
 
+// Crypt decrypts the loop device
+func (t *Methods) Decrypt(arguments *args.CryptArgs, reply *string) (err error) {
+
+	sylog.Debugf("In Crypt RPC")
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: The whole code could be wrapped in a package function in `pkg/util/crypt/`

File: pkg/image/encryptfs.go [hunk 18]
```diff
@@ -0,0 +1,49 @@
+package image
```
Comment (cclerget) [inline pkg/image/encryptfs.go]: Looks like this file is not required ?

File: cmd/singularity/cli.go [hunk 19]
```diff
@@ -16,7 +16,6 @@ func main() {
 	// In cmd/internal/cli/singularity.go
 	cli.ExecuteSingularity()
 }
-
```
Comment (cclerget) [inline cmd/singularity/cli.go]: Need a blank line here

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 20]
```diff
@@ -139,45 +144,68 @@ func getMksquashfsPath() (string, error) {
...
+	if encrypted == true {
+		err = syscall.Unmount(b.Rootfs(), 0)
+		if err != nil {
+			return fmt.Errorf("Unable to unmount Rootfs: %s err: %s", b.Rootfs(), err)
+		}
 
-	if err := mksquashfsCmd.Start(); err != nil {
-		return fmt.Errorf("While starting mksquashfs: %v", err)
-	}
+		cmd := exec.Command("/sbin/cryptsetup", "luksClose", b.LoopPath)
```
Comment (cclerget) [inline internal/pkg/build/assemblers/assembler_sif.go]: Use `exec.LookPath`

File: internal/pkg/runtime/engines/imgbuild/create_linux.go [hunk 21]
```diff
@@ -57,7 +58,10 @@ func (engine *EngineOperations) CreateContainer(pid int, rpcConn net.Conn) error
 	// sensible mount point options to avoid accidental system settings override
 	flags := uintptr(syscall.MS_BIND | syscall.MS_NOSUID | syscall.MS_NOEXEC | syscall.MS_NODEV | syscall.MS_RDONLY)
 
-	sylog.Debugf("Mounting image directory %s\n", rootfs)
+	bpath := engine.EngineConfig.Bundle.Path
+	// Create a sparse file in /tmp
+	ioutil.TempFile(bpath, "temp_loop")
```
Comment (cclerget) [inline internal/pkg/runtime/engines/imgbuild/create_linux.go]: dead code ?

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 22]
```diff
@@ -612,11 +628,16 @@ func (c *container) addRootfsMount(system *mount.System) error {
 	offset := imageObject.Partitions[0].Offset
 	size := imageObject.Partitions[0].Size
 
+	sylog.Debugf("Image type is %v", imageObject.Partitions[0].Name)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/container_linux.go]:
```suggestion
	sylog.Debugf("Image type is %v", imageObject.Partitions[0].Type)
```

**Review by cclerget — CHANGES_REQUESTED** [review]
Overall, there is some related crypto code which could find a place in `pkg/util/crypt` package. Did you give a try with squashfs approach which seems simpler imo: https://martin.elwin.com/blog/2008/05/backups-with-squashfs-and-luks/

**Comment by schebro** [comment]
> Overall, there is some related crypto code which could find a place in `pkg/util/crypt` package. Did you give a try with squashfs approach which seems simpler imo: https://martin.elwin.com/blog/2008/05/backups-with-squashfs-and-luks/

I will go through it today. It sounds interesting. I tried this approach before but gave up when I couldn't reliably create a LUKS container to stash the squashfs.

File: pkg/image/encryptfs.go (hunk 18 above)
Comment (schebro) [reply pkg/image/encryptfs.go]: yes. forgot to remove it.

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 6 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: Any specific reason to do that instead of reading here?

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 7 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go]: Runtime doesn't seem to have PATH set. The only env variable I see in runtime is SINGULARITY_MESSAGELEVEL=5. PATH is set inside the container though.

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 6 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: Well actually this won't work when running a Singularity instance because there is no terminal available at this stage, this is also the case in master process but that could be fixed more easily for master process in the future. Additionally I'm not comfortable to let user interact with a program executed with root privileges

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 7 above)
Comment (cclerget) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go]: Runtime could set a default PATH like `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

File: vendor/github.com/sylabs/sif/pkg/sif/sif.go (hunk 14 above)
Comment (schebro) [reply vendor/github.com/sylabs/sif/pkg/sif/sif.go]: Should I make these changes separately in sif repository and push?

Comment (WestleyK) [reply vendor/github.com/sylabs/sif/pkg/sif/sif.go]: I would fork the [sif repo](https://github.com/sylabs/sif), then checkout your branch and add these changes, push to your branch and open a PR. _Thats how I would do it..._

Then you can update the vendor in this PR.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 7 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go]: We cleanup all the env variables in cleanenv() in starter.c. Wonder if it's for any specific reason. Otherwise, I can just add them back.

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 23]
```diff
@@ -90,7 +91,11 @@ func createSIF(path string, definition, ociConf []byte, squashfile string) (err
 	parinput.Fp = fp
 	parinput.Size = fi.Size()
 
-	err = parinput.SetPartExtra(sif.FsSquash, sif.PartPrimSys, sif.GetSIFArch(runtime.GOARCH))
+	if encrypted == false {
+		err = parinput.SetPartExtra(sif.FsSquash, sif.PartPrimSys, sif.GetSIFArch(runtime.GOARCH))
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go]: this is changing the first argument of the function. It would be preferred to do this:

```
if encrypted {
    sifType = sif.FsEncrypt
} else {
    sifType = sif.FsSquash
}
```

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 24]
```diff
@@ -139,45 +144,68 @@ func getMksquashfsPath() (string, error) {
...
-	defer os.Remove(squashfsPath)
+	sylog.Debugf("Encrypted loop device is %s", b.LoopPath)
 
-	args := []string{b.Rootfs(), squashfsPath, "-noappend"}
-
-	// build squashfs with all-root flag when building as a user
-	if syscall.Getuid() != 0 {
-		args = append(args, "-all-root")
+	encrypted := false
+	if b.LoopPath != "" {
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go]: `LoopPath` is too generic to signify that this bundle. The `Opts` member of `types.Bundle` seems more appropriate to contain a flag to indicate that the result should be encrypted.

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 25]
```diff
@@ -139,45 +144,68 @@ func getMksquashfsPath() (string, error) {
...
+		err = syscall.Unmount(b.Rootfs(), 0)
+		if err != nil {
+			return fmt.Errorf("Unable to unmount Rootfs: %s err: %s", b.Rootfs(), err)
+		}
 
-	if err := mksquashfsCmd.Start(); err != nil {
-		return fmt.Errorf("While starting mksquashfs: %v", err)
-	}
+		cmd := exec.Command("/sbin/cryptsetup", "luksClose", b.LoopPath)
+		cmd.Dir = "/dev/mapper"
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go]: can you please add a comment indicating why you need to execute the command in this directory?

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 26]
```diff
@@ -46,6 +46,7 @@ func createSIF(path string, definition, ociConf []byte, squashfile string) (err
 		Groupid:  sif.DescrDefaultGroup,
 		Link:     sif.DescrUnusedLink,
 		Data:     definition,
+		Encrypt:  true,
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go]: shouldn't this use the `encrypted` argument to `createSIF`?

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 27]
```diff
@@ -139,45 +144,68 @@ func getMksquashfsPath() (string, error) {
...
+	if b.LoopPath != "" {
+		encrypted = true
 	}
 
-	mksquashfsCmd := exec.Command(mksquashfs, args...)
-	stderr, err := mksquashfsCmd.StderrPipe()
-	if err != nil {
-		return fmt.Errorf("While setting up stderr pipe: %v", err)
-	}
+	if encrypted == true {
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go]: can you please move both branches of this `if` to separate functions? They seem to be doing two completely different things that need to be documented on their own.

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 28]
```diff
@@ -139,45 +144,68 @@ func getMksquashfsPath() (string, error) {
 func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go:146]: It seems to me that you have two somewhat similar but different enough functions to warrant two different types.

One would be the existing SIFAssembler, that creates unencrypted images, and the other would be SIFEncryptedAssembler that creates encrypted images.

This probably makes it easier to stack the assemblers, too. At some point in the future what you want to do is create a squashfs filesystem, push the data to it, set up an encrypted LUKS container, and push the squashfs data to it. In order to do that, you need to know how big the LUKS container needs to be, and that means you need to create the squashfs filesystem first. This is easier if you have two separate assemblers.

File: internal/pkg/runtime/engines/imgbuild/create_linux.go (hunk 21 above)
Comment (mem) [reply internal/pkg/runtime/engines/imgbuild/create_linux.go]: not quite sure how this got resolved?

Since ioutil.TempFile returns an open file handle, this doesn't seem to be doing anything with that new file (since it's not storing the variable anywhere)

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 29]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
 		return file.Delete()
 	}
 
+	if engine.EngineConfig.CryptMount != "" {
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: it seems to be this whole bit of code belongs in a separate function, possibly part of `config.Common`.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 1 above)
Comment (mem) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: looks like you want to place dropping privilege in a defer'ed function

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 30]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+
+		err = syscall.Unmount("/usr/local/var/singularity/mnt/session/rootfs", syscall.MNT_DETACH)
+		if err != nil {
+			syscall.Setresuid(uid, uid, 0)
+			sylog.Debugf("Error while unmounting Rootfs: %s", err)
+			return err
+		}
+
+		cmd := exec.Command("/sbin/cryptsetup", "luksClose", engine.EngineConfig.CryptMount)
+		cmd.Dir = "/dev/mapper"
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: also needs a comment mentioning why this needs to run in this directory.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 31]
```diff
@@ -51,5 +52,43 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+		cmd.SysProcAttr.Credential = &syscall.Credential{Uid: 0, Gid: 0}
+		_, err = cmd.CombinedOutput()
+		if err != nil {
+			sylog.Debugf("Unable to delete the crypt device %s", err)
+			syscall.Setresuid(uid, uid, 0)
+			return err
+		}
+
+		// Restore the privilege
+		err = syscall.Setresuid(uid, uid, 0)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: this is dropping this error, no?

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 32]
```diff
@@ -545,10 +544,27 @@ func (c *container) mountImage(mnt *mount.Point) error {
...
+	sylog.Debugf("Mounting loop device %s to %s of type %s\n", path, mnt.Destination, mnt.Type)
+
+	if mnt.Type == "encryptfs" {
+		sp := strings.Split(path, "/")
+		loopdev := sp[len(sp)-1]
+		dev, err := c.rpcOps.Decrypt(offset, loopdev)
+
+		sylog.Debugf("Device to be mounted is %s", dev)
+
+		_, err = c.rpcOps.Mount("/dev/mapper/"+dev, mnt.Destination, "ext3", flags, optsString)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: assuming we change the format of the encrypted data to squashfs (and this is something we have to either express in the SIF metadata or simply assume, which would require documenting), the encrypted/non-encrypted bit of info should be a boolean stored as part of mount.Point.

If that's done that way, we can call the open operation (via Decrypt, I guess?) and obtain the device. We can override path with that value we obtained from the RPC server. At that point the mount operation is the same for encrypted / non-encrypted images, so line 564 does not need to be on an else branch.

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 33]
```diff
@@ -545,10 +544,27 @@ func (c *container) mountImage(mnt *mount.Point) error {
...
-	_, err = c.rpcOps.Mount(path, mnt.Destination, mnt.Type, flags, optsString)
-	if err != nil {
-		return fmt.Errorf("failed to mount %s filesystem: %s", mnt.Type, err)
+
+	sylog.Debugf("Mounting loop device %s to %s of type %s\n", path, mnt.Destination, mnt.Type)
+
+	if mnt.Type == "encryptfs" {
+		sp := strings.Split(path, "/")
+		loopdev := sp[len(sp)-1]
+		dev, err := c.rpcOps.Decrypt(offset, loopdev)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/container_linux.go]: it's better if this receives path as argument, not "loopdev". It's also better if the call returns the full path to the device, not just the name used with device mapper.

Basically, this code can become:

```
newPath, err := c.rpcOps.Decrypt(offset, path)

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 34]
```diff
@@ -33,6 +38,52 @@ func (t *Methods) Mount(arguments *args.MountArgs, reply *int) (err error) {
...
+	if err != nil {
+		sylog.Fatalf("Error parsing input: %s", err)
+	}
+	fmt.Println()
+
+	crypt_dev := &crypt.Device{
+		MaxDevices: 256,
+	}
+
+	cdev_str, err := crypt_dev.GetCryptDevice()
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: please, no snake_case. Go uses camelCase.

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 8 above)
Comment (mem) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: let's not depend on PATH lookups inside privileged code.

If you need to resolve the path to cryptsetup, do it at build time, and introduce a configuration variable so that the admin that override that location.

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 35]
```diff
@@ -33,6 +38,52 @@ func (t *Methods) Mount(arguments *args.MountArgs, reply *int) (err error) {
...
+
+	sylog.Debugf("Crypt device is %s\n", cdev_str)
+
+	cmd := exec.Command("/sbin/cryptsetup", "luksOpen", arguments.Loopdev, cdev_str, "-v", "--debug")
+	cmd.Dir = "/dev"
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: can you please document why you need this?

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 36]
```diff
@@ -134,6 +185,7 @@ func (t *Methods) LoopDevice(arguments *args.LoopArgs, reply *int) error {
 	} else {
 		var err error
 		image, err = os.OpenFile(arguments.Image, arguments.Mode, 0600)
+		defer image.Close()
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go:153]: is this necessary? "image" is used below as an argument to loopdev.AttachFromFile, and that sets things up so that this file descriptor is closed. There's no explicit call to image.Close(), that's right. And there might be some error paths where this is not closed, too.

Did you find a case where this was needed?

File: pkg/build/types/bundle.go [hunk 37]
```diff
@@ -64,8 +76,25 @@ type Options struct {
...
+	idx := 0
+	if err := loopDev.AttachFromFile(file, os.O_RDWR, &idx); err != nil {
+		return "", fmt.Errorf("failed to attach image %s: %s", file.Name(), err)
+	}
+	return fmt.Sprintf("/dev/loop%d", idx), nil
+}
+
 // NewBundle creates a Bundle environment
-func NewBundle(bundleDir, bundlePrefix string) (b *Bundle, err error) {
+func NewBundle(encrypt bool, bundleDir, bundlePrefix string) (b *Bundle, err error) {
```
Comment (mem) [inline pkg/build/types/bundle.go]: see above

File: pkg/build/types/bundle.go [hunk 38]
```diff
@@ -83,10 +112,116 @@ func NewBundle(bundleDir, bundlePrefix string) (b *Bundle, err error) {
 		"rootfs": "fs",
 	}
 
+	var input = "Default"
+	if encrypt == true {
```
Comment (mem) [inline pkg/build/types/bundle.go]: this branch is too long. Please move it to a separate function.

I was thinking it should be possible to set up the contents of the file system as usual, create the squashfs filesystem as usual, and then create a loop device of the correct size (squashfs + ~ 16 MB overhead, exact number is 16384 for the metadata + 16744448 key slots, it might be possible to reduce the size of the key slot storage), format it and the copy the squashfs data into the encrypted volume (e.g. `dd if=squashfs.img of=/dev/mapper/luks-volume ...`).

File: pkg/util/crypt/crypt_dev.go [hunk 39]
```diff
@@ -0,0 +1,44 @@
...
+
+func (e *errCryptDeviceUnavailable) Error() string {
+	return e.message
+}
+
+// GetCryptDevice returns the next available device in /dev/mapper for encryption/decryption
+func (crypt *Device) GetCryptDevice() (string, error) {
+	// Return the next available crypt device
+	for i := 0; i < crypt.MaxDevices; i++ {
+		retStr := fmt.Sprintf("singularity_crypt_%d", i)
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go]: it might be better to use a random ID (e.g. uuid) to reduce the chance of collisions.

**Review by mem — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 35 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: The flags are unnecessary. I will delete them.

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 34 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: Sorry.. My leftover C habits. :-) Will change.

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 36 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go:153]: Didn't really find any cases that are going wrong with this image not being closed. This change has nothing to do with the overall change. I just thought image should be closed before we exit this function.

File: internal/pkg/build/assemblers/assembler_sif.go (hunk 28 above)
Comment (schebro) [reply internal/pkg/build/assemblers/assembler_sif.go:146]: In the new code, I am using squashfs image to create an encrypted one.

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 40]
```diff
@@ -139,19 +147,19 @@ func getMksquashfsPath() (string, error) {
...
 	sylog.Infof("Creating SIF file...")
 
+	var fsPath string
+
 	mksquashfs, err := getMksquashfsPath()
 	if err != nil {
 		return fmt.Errorf("While searching for mksquashfs: %v", err)
 	}
-
 	f, err := ioutil.TempFile(b.Path, "squashfs-")
```
Comment (mem) [inline internal/pkg/build/assemblers/assembler_sif.go:155]: I missed this before.

The idea of using ioutil.TempFile is that you get a file handle for a file that did not exist before, and that you can use to create a new file without worrying about races. Simplest case is that you want to create an image, and _always_ use the name "/tmp/new_image" for the temporary file. Someone can create a symlink from "/tmp/new_image" to an interesting file so that your process clobbers it. So to mitigate that, you remove "/tmp/new_image" before opening it for writing. Now you have a race: there's a window of time between removing the file and creating the file that the attacker can use to create the symlink again. To mitigate that, you use a non-fixed filename, e.g. "/tmp/new_image_123". You still have a race: the attacker can try creating _all_ the possible filenames.

ioutil.TempFile deals with all of that: it repeatedly calls open with O_CREATE|O_EXCL so that it knows that the file did not exist before it created it. By _removing_ the file before creating it again (line 159), this code is opening up the window for the race again. By using a different filename than the one ioutil.TempFile returned (line 157) it's opening the window again. Just use whatever ioutil.TempFile returns, do _not_ remove the file and pass `-noappend` to mksquashfs (this will cause it to truncate the file, which is fine, because the file is empty anyways). After you are done, call `os.Rename` to rename the file to its final name if needed.

File: pkg/util/crypt/crypt_dev.go [hunk 41]
```diff
@@ -0,0 +1,306 @@
...
+	}
+
+	return nil
+}
+
+// FormatCryptDevice allocates a loop device, encrypts, and returns the loop device name, and encrypted device name
+func (crypt *Device) FormatCryptDevice(path string) (string, string, error) {
+
+	// Read the password from terminal
+	fmt.Print("Enter the password to encrypt the filesystem: ")
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go]: before we can merge this, can you please remove the interactive prompts from here and simply pass the secret as an argument to this function?

File: pkg/util/crypt/crypt_dev.go [hunk 42]
```diff
@@ -0,0 +1,306 @@
...
+		sylog.Fatalf("Error parsing the password: %s", err)
+	}
+	input2 := string(password2)
+	fmt.Println()
+
+	if input != input2 {
+		return "", "", errors.New("Passwords don't match")
+	}
+
+	squashF, err := os.Stat(path)
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go]: there's nothing in this that is specific to squashfs.

File: pkg/util/crypt/crypt_dev.go [hunk 43]
```diff
@@ -0,0 +1,306 @@
...
+	// NOTE: This routine runs with root privileges. It's not necessary
+	// to explicitly set cmd's uid or gid here
+	cmd := exec.Command("/sbin/cryptsetup", "luksFormat", cryptF.Name())
+	stdin, err := cmd.StdinPipe()
+
+	if err != nil {
+		return "", "", err
+	}
+
+	go func() {
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go:147]: you don't need a goroutine for this. You can call cmd.Start(), which does not block.

File: pkg/util/crypt/crypt_dev.go [hunk 44]
```diff
@@ -0,0 +1,306 @@
...
+
+	err = os.Truncate(cryptF.Name(), size)
+	if err != nil {
+		sylog.Debugf("Unable to truncate crypt file to size %d", size)
+		return "", "", err
+	}
+
+	// NOTE: This routine runs with root privileges. It's not necessary
+	// to explicitly set cmd's uid or gid here
+	cmd := exec.Command("/sbin/cryptsetup", "luksFormat", cryptF.Name())
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go:140]: it's probably a good idea to pass --key-file, to not rely on the interactive prompting. The file passed can be "-" so that it still reads from stdin.

File: pkg/util/crypt/crypt_dev.go [hunk 45]
```diff
@@ -0,0 +1,306 @@
...
+		return "", "", err
+	}
+
+	// Associate the temporary crypt file with a loop device
+	loop, err := createLoop(cryptF, 0, uint64(size))
+	if err != nil {
+		return "", "", err
+	}
+
+	sp := strings.Split(loop, "/")
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go]: guessing the bit of code to obtain a name for the dm device should be its own function.

File: pkg/util/crypt/crypt_dev.go [hunk 46]
```diff
@@ -0,0 +1,306 @@
...
+	}
+	nextCrypt := getNextAvailableCryptDevice()
+	cmd = exec.Command("/sbin/cryptsetup", "luksOpen", loopdev, nextCrypt)
+	cmd.Dir = "/dev"
+	stdin, err = cmd.StdinPipe()
+	if err != nil {
+		return "", "", err
+	}
+
+	go func() {
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go:179]: same here

File: pkg/util/crypt/crypt_dev.go [hunk 47]
```diff
@@ -0,0 +1,306 @@
...
+	sp := strings.Split(loop, "/")
+	loopdev := sp[len(sp)-1]
+
+	fd, err := lock.Exclusive("/dev/mapper")
+	if err != nil {
+		sylog.Debugf("Unable to acquire lock on /dev/mapper")
+		return "", "", err
+	}
+	nextCrypt := getNextAvailableCryptDevice()
+	cmd = exec.Command("/sbin/cryptsetup", "luksOpen", loopdev, nextCrypt)
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go:172]: --key-file here, too

File: pkg/util/crypt/crypt_dev.go [hunk 48]
```diff
@@ -0,0 +1,306 @@
...
+	copyDeviceContents("/dev/"+loopdev, loopF.Name(), size)
+
+	return loopF.Name(), nextCrypt, err
+}
+
+// copyDeviceContents copies the contents of source to destination.
+// source and dest can either be a file or a block device
+func copyDeviceContents(source string, dest string, size int64) error {
+
+	squashFd, err := syscall.Open(source, syscall.O_RDWR, 0777)
```
Comment (mem) [inline pkg/util/crypt/crypt_dev.go]: why do you need to use the system calls directly? Open the two files and use io.Copy?

**Review by mem — CHANGES_REQUESTED** [review]
about halfway thru

File: pkg/util/crypt/crypt_dev.go (hunk 48 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go]: I tried that first. io.Copy doesn't work with block devices. Will try once more.

File: pkg/util/crypt/crypt_dev.go (hunk 47 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go:172]: Ok. What you are suggesting is to take our the interactive password entry and replace with a keyfile, right?

File: pkg/util/crypt/crypt_dev.go (hunk 43 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go:147]: This go func is providing the password from stdin to the command. But if I use keyfile, these go away.

File: pkg/util/crypt/crypt_dev.go (hunk 42 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go]: Right. "path" here belongs to squashfs. That's why I named it as such. Will change.

File: internal/pkg/runtime/engines/imgbuild/create_linux.go [hunk 49]
```diff
@@ -60,7 +60,6 @@ func (engine *EngineOperations) CreateContainer(pid int, rpcConn net.Conn) error
 		flags = uintptr(syscall.MS_BIND | syscall.MS_REC)
 	}
 
-	sylog.Debugf("Mounting image directory %s\n", rootfs)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/imgbuild/create_linux.go]: Why is it removed ?

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 50]
```diff
@@ -58,5 +63,47 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+	return nil
+}
+
+func cleanupCrypt(path string) error {
+
+	// Elevate the privilege to unmount and delete the crypt device
+	runtime.LockOSThread()
+	uid := os.Getuid()
+	err := syscall.Setresuid(uid, 0, uid)
+	defer syscall.Setresuid(uid, uid, 0)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: I didn't notice during first review, but `defer syscall.Setresuid(uid, uid, 0)` defer call must be after `defer runtime.UnlockOSThread()`, `UnlockOSThread` call need to be the last (the first defer call is the last executed in the stack) and I believe `syscall` functions trigger a scheduler yield, so `syscall.Setresuid(uid, uid, 0)` could be scheduled on a different thread and drop privileges for a different OS thread leaving privileges for the previously locked thread

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 51]
```diff
@@ -58,5 +63,47 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+	defer runtime.UnlockOSThread()
+	if err != nil {
+		sylog.Debugf("Err setting suid")
+		return err
+	}
+
+	err = syscall.Unmount(filepath.Join(buildcfg.SESSIONDIR, "final"), syscall.MNT_DETACH)
+	if err != nil {
+		sylog.Debugf("Error while unmounting overlay FS: %s", err)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]:
```suggestion
		sylog.Debugf("Error while unmounting final session directory: %s", err)
```

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 52]
```diff
@@ -58,5 +63,47 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+		return err
+	}
+
+	err = syscall.Unmount(filepath.Join(buildcfg.SESSIONDIR, "rootfs"), syscall.MNT_DETACH)
+	if err != nil {
+		sylog.Debugf("Error while unmounting Rootfs: %s", err)
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]:
```suggestion
		sylog.Debugf("Error while unmounting rootfs session directory: %s", err)
```

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 53]
```diff
@@ -58,5 +63,47 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+		return err
+	}
+
+	sp := strings.Split(path, "/")
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: you can use `devName := filepath.Base(path)` and drop line 99

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 54]
```diff
@@ -571,10 +570,29 @@ func (c *container) mountImage(mnt *mount.Point) error {
...
 
 	path := fmt.Sprintf("/dev/loop%d", number)
-	sylog.Debugf("Mounting loop device %s to %s\n", path, mnt.Destination)
-	_, err = c.rpcOps.Mount(path, mnt.Destination, mnt.Type, flags, optsString)
+
+	sylog.Debugf("Mounting loop device %s to %s of type %s\n", path, mnt.Destination, mnt.Type)
+
+	mountType := mnt.Type
+
+	if mnt.Type == "encryptfs" {
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/container_linux.go]:
```suggestion
	if mountType == "encryptfs" {
```

File: internal/pkg/runtime/engines/singularity/rpc/client/client.go [hunk 55]
```diff
@@ -33,6 +34,21 @@ func (t *RPC) Mount(source string, target string, filesystem string, flags uintp
 	return reply, err
 }
 
+// Decrypt calls the DeCrypt RPC using the supplied arguments.
+func (t *RPC) Decrypt(offset uint64, path string) (string, error) {
+	sp := strings.Split(path, "/")
```
Comment (cclerget) [inline internal/pkg/runtime/engines/singularity/rpc/client/client.go]: same `loopdev := filepath.Base(path)`

File: pkg/build/types/bundle.go [hunk 56]
```diff
@@ -88,13 +90,28 @@ func NewBundle(bundleDir, bundlePrefix string) (b *Bundle, err error) {
 		"rootfs": "fs",
 	}
 
+	if encrypted {
```
Comment (cclerget) [inline pkg/build/types/bundle.go]: `b.Opts.Encrypted = encrypted` ?

File: pkg/util/crypt/crypt_dev.go [hunk 57]
```diff
@@ -0,0 +1,306 @@
...
+func (crypt *Device) CloseCryptDevice(path string) error {
+
+	cmd := exec.Command("/sbin/cryptsetup", "luksClose", path)
+	cmd.SysProcAttr = &syscall.SysProcAttr{}
+	cmd.SysProcAttr.Credential = &syscall.Credential{Uid: 0, Gid: 0}
+	fd, err := lock.Exclusive("/dev/mapper")
+	if err != nil {
+		return err
+	}
+	err = cmd.Run()
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go:59]: just before this line, I would call `defer lock.Release(fd)` in order to release lock if an error occur during `cmd.Run()`

File: pkg/util/crypt/crypt_dev.go [hunk 58]
```diff
@@ -0,0 +1,306 @@
...
+	if err != nil {
+		sylog.Debugf("Unable to delete the crypt device %s", err)
+		return err
+	}
+	err = lock.Release(fd)
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go]: previous comment

File: pkg/util/crypt/crypt_dev.go [hunk 59]
```diff
@@ -0,0 +1,306 @@
...
+
+	sp := strings.Split(loop, "/")
+	loopdev := sp[len(sp)-1]
+
+	fd, err := lock.Exclusive("/dev/mapper")
+	if err != nil {
+		sylog.Debugf("Unable to acquire lock on /dev/mapper")
+		return "", "", err
+	}
+	nextCrypt := getNextAvailableCryptDevice()
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go:171]: call `defer lock.Release(fd)` here

File: pkg/util/crypt/crypt_dev.go (hunk 45 above)
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go]: `loopdev := filepath.Base(loop)`

File: pkg/util/crypt/crypt_dev.go [hunk 60]
```diff
@@ -0,0 +1,306 @@
...
+	b := make([]byte, n)
+	if _, err := rand.Read(b); err != nil {
+		sylog.Debugf("Something went wrong while generating random string")
+		return ""
+	}
+	return fmt.Sprintf("%x", b)
+}
+
+func getNextAvailableCryptDevice() string {
+	return getRandomString(15)
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go]: or you can import `github.com/satori/go.uuid` and use `uuid.NewV4()`

File: pkg/util/crypt/crypt_dev.go [hunk 61]
```diff
@@ -0,0 +1,306 @@
...
+		return "", "", err
+	}
+
+	err = lock.Release(fd)
+	if err != nil {
+		sylog.Debugf("Unable to release lock on /dev/mapper")
+		return "", "", err
+	}
+
+	copyDeviceContents(path, "/dev/mapper/"+nextCrypt, squashFsSize)
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go]: eligible for `filepath.Join("/dev/mapper", nextCrypt)`

File: pkg/util/crypt/crypt_dev.go [hunk 62]
```diff
@@ -0,0 +1,306 @@
...
+
+	// Open a new Temp file to stash the loop contents
+	loopF, err := ioutil.TempFile("", "loop-")
+	if err != nil {
+		sylog.Debugf("Error creating temporary crypt file")
+		return "", "", err
+	}
+
+	copyDeviceContents("/dev/"+loopdev, loopF.Name(), size)
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go]: eligible for `filepath.Join("/dev", loopdev)`

File: vendor/github.com/sylabs/sif/pkg/sif/fmt.go (hunk 13 above)
Comment (cclerget) [inline vendor/github.com/sylabs/sif/pkg/sif/fmt.go]: need to revert this change

File: vendor/github.com/sylabs/sif/pkg/sif/sif.go (hunk 14 above)
Comment (cclerget) [inline vendor/github.com/sylabs/sif/pkg/sif/sif.go]: same

File: vendor/github.com/sylabs/sif/pkg/sif/sif.go (hunk 15 above)
Comment (cclerget) [inline vendor/github.com/sylabs/sif/pkg/sif/sif.go]: same

File: pkg/util/crypt/crypt_dev.go [hunk 63]
```diff
@@ -0,0 +1,306 @@
...
+	}
+
+	go func() {
+		defer stdin.Close()
+		io.WriteString(stdin, string(password))
+	}()
+
+	out, err := cmd.CombinedOutput()
+	if err != nil {
+		if strings.Contains(string(out), "No key available") {
```
Comment (cclerget) [inline pkg/util/crypt/crypt_dev.go:279]: Just a question, is cryptsetup return different exit code which could help to determine the error ? Relying on error output could have side effects between cryptsetup version, `LANG` environment variable can alter error output and return error message in another language, ok it's not actually the case because this function is only called by RPC server which run with only one environment variable, but if this function is called directly by build command or something else, that's something to consider.

**Review by cclerget — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/engines/imgbuild/create_linux.go (hunk 49 above)
Comment (schebro) [reply internal/pkg/runtime/engines/imgbuild/create_linux.go]: Oops. Thought I added that. I should have checked the final diff. Will restore.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 50 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go]: Will fix that. Thanks for pointing out. I didn't know the order of defers.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 53 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go]: Cool. Will fix.

File: vendor/github.com/sylabs/sif/pkg/sif/fmt.go (hunk 13 above)
Comment (schebro) [reply vendor/github.com/sylabs/sif/pkg/sif/fmt.go]: Yes. I will revert the vendor changes once the PR in SIF repo is merged.

File: pkg/util/crypt/crypt_dev.go (hunk 63 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go:279]: cryptsetup error codes are not as descriptive as the output. That's why I was checking for the output to know what exactly the error is. Here are cryptsetup error codes.

0 - success, otherwise fail
1 - wrong parameters
2 - no permission
3 - out of memory
4 - wrong device specified
5 - device already exists or device is busy

If the password is wrong or for any other wrong parameter, the error code would be 1. For the latter case where the device exists, the code would be 5. I can replace the second string compare by checking the error code for 5 but error code 1 is not very descriptive.

File: cmd/internal/cli/build_linux.go [hunk 64]
```diff
@@ -23,6 +23,7 @@ import (
 )
 
 func run(cmd *cobra.Command, args []string) {
+
```
Comment (WestleyK) [inline cmd/internal/cli/build_linux.go]: Why the extra newline?

```suggestion
```

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 65]
```diff
@@ -25,13 +25,15 @@ import (
...
+	"github.com/sylabs/singularity/pkg/util/crypt"
 )
 
 // SIFAssembler doesnt store anything
 type SIFAssembler struct {
 }
 
-func createSIF(path string, definition, ociConf []byte, squashfile string) (err error) {
+func createSIF(path string, definition, ociConf []byte, squashfile string, encrypted bool) (err error) {
+
```
Comment (WestleyK) [inline internal/pkg/build/assemblers/assembler_sif.go]: Extra newline here too?

```suggestion
```

File: internal/pkg/build/assemblers/assembler_sif.go [hunk 66]
```diff
@@ -177,7 +185,28 @@ func (a *SIFAssembler) Assemble(b *types.Bundle, path string) (err error) {
 		return fmt.Errorf("While running mksquashfs: %v: %s", err, strings.Replace(string(errOut), "\n", " ", -1))
 	}
 
-	err = createSIF(path, b.Recipe.Raw, b.JSONObjects["oci-config"], squashfsPath)
+	if b.Opts.Encrypted {
+
```
Comment (WestleyK) [inline internal/pkg/build/assemblers/assembler_sif.go]: And here? Are these necessary?

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 67]
```diff
@@ -58,5 +63,47 @@ func (engine *EngineOperations) CleanupContainer(fatal error, status syscall.Wai
...
+
+	// Elevate the privilege to unmount and delete the crypt device
+	runtime.LockOSThread()
+	uid := os.Getuid()
+	err := syscall.Setresuid(uid, 0, uid)
+	defer syscall.Setresuid(uid, uid, 0)
+	defer runtime.UnlockOSThread()
+	if err != nil {
+		sylog.Debugf("Err setting suid")
+		return err
```
Comment (WestleyK) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go]: I think it would also be good to add more debugging in the error message:

```suggestion
		return fmt.Errorf("unable to setup suid: %v", err)
```

_Or something like that..._

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 51 above)
Comment (WestleyK) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go]: Should that message also be returned in the `error`? Like:

```go
return fmt.Errorf("failed unmounting final session directory: %s", err)
```

File: internal/pkg/runtime/engines/singularity/container_linux.go [hunk 68]
```diff
@@ -571,10 +570,29 @@ func (c *container) mountImage(mnt *mount.Point) error {
...
+		cryptDev, err := c.rpcOps.Decrypt(offset, path)
+
+		if err != nil {
+			return fmt.Errorf("Unable to decrypt the file system: %s", err)
```
Comment (WestleyK) [inline internal/pkg/runtime/engines/singularity/container_linux.go:611]: Its better to not use caps in error messages

```suggestion
			return fmt.Errorf("unable to decrypt the file system: %s", err)
```

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 69]
```diff
@@ -13,6 +13,8 @@ import (
 	"strings"
 	"syscall"
 
+	"github.com/sylabs/singularity/pkg/util/crypt"
+
```
Comment (WestleyK) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: Extra newline here

```suggestion
```

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go [hunk 70]
```diff
@@ -33,6 +35,18 @@ func (t *Methods) Mount(arguments *args.MountArgs, reply *int) (err error) {
 	return err
 }
 
+// DeCrypt decrypts the loop device by using dm-crypt interface
+func (t *Methods) Decrypt(arguments *args.CryptArgs, reply *string) (err error) {
+
```
Comment (WestleyK) [inline internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: Extra newline here too

```suggestion
```

File: pkg/util/crypt/crypt_dev.go [hunk 71]
```diff
@@ -0,0 +1,306 @@
...
+	"strings"
+	"syscall"
+
+	"github.com/sylabs/singularity/internal/pkg/sylog"
+	"github.com/sylabs/singularity/pkg/util/fs/lock"
+	"github.com/sylabs/singularity/pkg/util/loop"
+	"golang.org/x/crypto/ssh/terminal"
+)
+
+// Device is
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: Device is what? Is there more that needs to go here?

File: pkg/util/crypt/crypt_dev.go [hunk 72]
```diff
@@ -0,0 +1,306 @@
...
+	fmt.Println()
+
+	if input != input2 {
+		return "", "", errors.New("Passwords don't match")
+	}
+
+	squashF, err := os.Stat(path)
+	if err != nil {
+		sylog.Debugf("Error acquiring size of %s", path)
+		return "", "", err
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: I think this should also return some debugging like the above line

```suggestion
		return "", "", fmt.Errorf("failed getting size of: %s: ", path, err)
```

File: pkg/util/crypt/crypt_dev.go [hunk 73]
```diff
@@ -0,0 +1,306 @@
...
+
+	go func() {
+		defer stdin.Close()
+		io.WriteString(stdin, input)
+	}()
+
+	err = cmd.Run()
+	if err != nil {
+		sylog.Verbosef("Unable to format crypt device")
+		return "", "", err
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: Should also return some debugging to?

File: pkg/util/crypt/crypt_dev.go [hunk 74]
```diff
@@ -0,0 +1,306 @@
...
+
+	copyDeviceContents("/dev/"+loopdev, loopF.Name(), size)
+
+	return loopF.Name(), nextCrypt, err
+}
+
+// copyDeviceContents copies the contents of source to destination.
+// source and dest can either be a file or a block device
+func copyDeviceContents(source string, dest string, size int64) error {
+
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: Extra newline

File: pkg/util/crypt/crypt_dev.go [hunk 75]
```diff
@@ -0,0 +1,306 @@
...
+	}
+
+	copyDeviceContents("/dev/"+loopdev, loopF.Name(), size)
+
+	return loopF.Name(), nextCrypt, err
+}
+
+// copyDeviceContents copies the contents of source to destination.
+// source and dest can either be a file or a block device
+func copyDeviceContents(source string, dest string, size int64) error {
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: Not necessary, but may look nicer...

```suggestion
func copyDeviceContents(source, dest string, size int64) error {
```

File: pkg/util/crypt/crypt_dev.go [hunk 76]
```diff
@@ -0,0 +1,306 @@
...
+
+	squashFd, err := syscall.Open(source, syscall.O_RDWR, 0777)
+	if err != nil {
+		sylog.Debugf("Unable to open the file %s", source)
+		return err
+	}
+	defer syscall.Close(squashFd)
+
+	cryptFd, err := syscall.Open(dest, syscall.O_RDWR, 0777)
+
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go:212]: Extra newline?

File: pkg/util/crypt/crypt_dev.go [hunk 77]
```diff
@@ -0,0 +1,306 @@
...
+	if err != nil {
+		sylog.Debugf("Unable to open the file: %s", dest)
+		return err
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: Again, this should probably return some debugging with the error message:

```suggestion
		return fmt.Errorf("unable to open file: %s: %v", dest, err)
```

File: pkg/util/crypt/crypt_dev.go [hunk 78]
```diff
@@ -0,0 +1,306 @@
...
+}
+
+func getNextAvailableCryptDevice() string {
+	return getRandomString(15)
+}
+
+// GetCryptDevice returns the next available device in /dev/mapper for encryption/decryption
+func (crypt *Device) GetCryptDevice(loopDev string) (string, error) {
+
+	fmt.Print("Enter the password to decrypt the File System: ")
```
Comment (WestleyK) [inline pkg/util/crypt/crypt_dev.go]: Maybe there should also be a argument to pass the password?

**Review by WestleyK — COMMENTED** [review]
Looks good, just a couple suggestion that may help :+1:

File: cmd/internal/cli/build_linux.go (hunk 64 above)
Comment (schebro) [reply cmd/internal/cli/build_linux.go]: Sorry. Not intentional. I was relying on vscode to format the extra lines but apparently it doesn't. Will clean up. Thanks for pointing out.

Comment (WestleyK) [reply cmd/internal/cli/build_linux.go]: Sure! No problem :+1:

**Comment by GodloveD** [comment]
Wow!  113 comments and counting!!

Let's really try to get this merged as a top priority so that we can use it as the basis for more work toward that goal.

**Comment by schebro** [comment]
Most of these are already addressed in the latest version. I am going to
open a separate issue for keyfile support. I don't want it to delay
existing changes. Will push other changes tomorrow. Let's get it merged.

File: pkg/util/crypt/crypt_dev.go (hunk 44 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go:140]: I will change this behavior as part of a separate issue. There need to be some changes both on the encryption and decryption side w.r.t providing extra arguments(key-file) to the command.

File: pkg/util/crypt/crypt_dev.go (hunk 45 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go]: Changed this to filepath.Base

File: internal/pkg/build/assemblers/assembler_sif.go (hunk 66 above)
Comment (schebro) [reply internal/pkg/build/assemblers/assembler_sif.go]: Not necessary. Coming from C background, I am used to use new lines liberally for readability. Will remove

File: internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go (hunk 6 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go]: I created #3851 to supply encryption keys non-interactively.

File: pkg/util/crypt/crypt_dev.go (hunk 41 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go]: Created #3851 to address it. Passing secret as argument requires some changes in encryption and decryption path such as supplying a --key-file from the command line. Instead of holding this PR up, I prefer to address it as a separate issue if that's fine.

File: pkg/util/crypt/crypt_dev.go (hunk 44 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go:140]: #3851

File: pkg/util/crypt/crypt_dev.go (hunk 60 above)
Comment (schebro) [reply pkg/util/crypt/crypt_dev.go]: Used that instead

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go [hunk 79]
```diff
@@ -6,12 +6,17 @@
 package singularity
```
Comment (WestleyK) [inline internal/pkg/runtime/engines/singularity/cleanup_linux.go:6]: Missing copyright thing?

```
// Copyright (c) 2019, Sylabs Inc. All rights reserved.
// This software is licensed under a 3-clause BSD license. Please consult the
// LICENSE.md file distributed with the sources of this project regarding your
// rights to use or distribute this software.

package singularity
```

_EDIT: not necessary, it already exist. my bad_

**Review by WestleyK — COMMENTED** [review]
Have one more suggestion, not necessary, we can fix this in a followup PR.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 79 above)
Comment (WestleyK) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go:6]: Sorry, my bad. There already one, but it should be `2018-2019`. (not `2018`)

**Review by cclerget — APPROVED** [review]

**Review by mem — CHANGES_REQUESTED** [review]
I still think the reading of the passphrase is happening too late and too deep in the code (this is related to but not the same as not reading the passphrase interactively). I also think this would be better done in two steps: create the unencrypted SIF file and later creating a second SIF that's encrypted. That would allow us to introduce an "encrypt" operation for existing SIF files. The more important consequence of that is that you can split the encryption code from the squashfs creation code. An issue should be opened for that.

Given the above, before merging this, let's do one last thing: all the opened issues have a counterpart in this review (e.g. reading the passphrase from the terminal is happening in a couple specific locations).

I would strongly prefer to annotate the _source code_ with the corresponding issue numbers. For example:

```
// TODO(schebro): fix issue #3818 
// We expect the cryptsetup utility to be installed in the host.
// We need to add checks in mconfig for that purpose and we need
// to provide a configuration variable for the sysadmin to specify
// its location.
```

In order words, please add internal documentation that documents what the issue is, both as a reference to the existing issue and with enough description for someone else to understand what the problem is. This will allow us to split the effort if necessary, and not miss any changes related to those issues.

**Comment by schebro** [comment]
> I still think the reading of the passphrase is happening too late and too deep in the code (this is related to but not the same as not reading the passphrase interactively). I also think this would be better done in two steps: create the unencrypted SIF file and later creating a second SIF that's encrypted. That would allow us to introduce an "encrypt" operation for existing SIF files. The more important consequence of that is that you can split the encryption code from the squashfs creation code. An issue should be opened for that.
> 
> Given the above, before merging this, let's do one last thing: all the opened issues have a counterpart in this review (e.g. reading the passphrase from the terminal is happening in a couple specific locations).
> 
> I would strongly prefer to annotate the _source code_ with the corresponding issue numbers. For example:
> 
> ```
> // TODO(schebro): fix issue #3818 
> // We expect the cryptsetup utility to be installed in the host.
> // We need to add checks in mconfig for that purpose and we need
> // to provide a configuration variable for the sysadmin to specify
> // its location.
> ```
> 
> In order words, please add internal documentation that documents what the issue is, both as a reference to the existing issue and with enough description for someone else to understand what the problem is. This will allow us to split the effort if necessary, and not miss any changes related to those issues.

I will annotate the code with necessary comments and issues. I agree that the key reading can happen much earlier. The method of key reading is going to change in the coming weeks anyway. I will address it then.

File: internal/pkg/runtime/engines/singularity/cleanup_linux.go (hunk 79 above)
Comment (schebro) [reply internal/pkg/runtime/engines/singularity/cleanup_linux.go:6]: Fixed

**Review by mem — APPROVED** [review]
thanks, let's go with this.
