### PR TITLE
Fix error when using sandbox path with slash at the end

### LINKED ISSUE #4407: Build sandbox failure with path containing a trailing slash
## Version of Singularity:

Master branch

### Expected behavior

Build succeed

### Actual behavior

```
singularity build -s /tmp/sand/ docker://alpine
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:9d48c3bd43c520dc2784e868a780e976b207cbf493eaff8c6596eb871cbd9609
Copying config sha256:1f97f0559cbddbff6c872039e93f18c1abdc279cbe82e0eb40258c28f4c30bfd
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
2019/09/09 18:10:45  info unpack layer: sha256:9d48c3bd43c520dc2784e868a780e976b207cbf493eaff8c6596eb871cbd9609
INFO:    Creating sandbox directory...
FATAL:   While performing build: sandbox assemble failed: rename /tmp/sand/rootfs-5f236710-d31c-11e9-a585-bcaec52cd0df /tmp/sand/: no such file or directory
```

### Steps to reproduce behavior

```
singularity build -s /tmp/sand/ docker://alpine
```

### PR DESCRIPTION
**Pull request by sashayakovtseva**
**Description of the Pull Request (PR):**

- clean build destination path to avoid bugs (e.g. `singularity build -s /tmp/sand/ docker://alpine` doesn't work now because of slash in the end)
- format tests so they are more readable, run build tests as subtests to avoid skipping of all test cases
- use string concatenation instead of `filepath.Join` in build tests to check the case with slash at the end (`filepath.Join` calls clean under the hood)

**This fixes or addresses the following GitHub issues:**

- Fixes #4407

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: e2e/imgbuild/imgbuild.go [hunk 1]
```diff
@@ -27,60 +27,105 @@ type imgBuildTests struct {
...
-		{"DockerURI", "", "docker://busybox", true},
-		{"DockerDefFile", "", "../examples/docker/Singularity", true},
+		{
+			name:      "BusyBox",
+			dest:      c.env.TestDir + "/container",
+			buildSpec: "../examples/busybox/Singularity",
+		},
+		{
+			name:       "Debootstrap",
+			dest:       c.env.TestDir + "/container/",
```
Comment (cclerget) [inline e2e/imgbuild/imgbuild.go:47]: Maybe put a mention about the intention of letting the trailing slash ?

**Review by cclerget — APPROVED** [review]
LGTM ! Just left a suggestion about adding a comment for the trailing slash
