### PR TITLE
Confirm Key Generate Password

### LINKED ISSUE #2238: Add "passphrase confirm" feature
## Version of Singularity:

v3.0.0

### Expected behavior

singularity keys newpair should ask to confirm key encryption passphrase

### Actual behavior

It doesn't

### Steps to reproduce behavior

singularity keys newpair

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

When generating a new key, you will now be ask to retype your password.

***NOTE:** Will will need to update the [signNverify](https://www.sylabs.io/guides/3.0/user-guide/signNverify.html) examples for 3.2.*

## This fixes or addresses the following GitHub issues:

- Fixes #2238 

<br>

### CODE REVIEW

File: pkg/sypgp/sypgp.go [hunk 1]
```diff
@@ -393,6 +393,14 @@ func GenKeyPair() (entity *openpgp.Entity, err error) {
 	if err != nil {
 		return
 	}
+	passRetype, err := AskQuestionNoEcho("Retype your passphrase : ")
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: Would you like to offer the user the chance to type the passphrase again if they don't match? For example, try three times? Otherwise the user has to enter all the information again (name, email, comment), and usually this leads to frustrated users.

Comment (WestleyK) [reply pkg/sypgp/sypgp.go]: Good thinking! :+1:

**Review by jchavezlavalle — APPROVED** [review]

**Comment by jchavezlavalle** [comment]
looks good @WestleyK might be good idea to refer to passphrases either as "passphrases" or as "passwords" in all the warning messages

**Review by ikaneshiro — APPROVED** [review]
LGTM

File: pkg/sypgp/sypgp.go [hunk 2]
```diff
@@ -372,18 +372,37 @@ func GenKeyPair() (entity *openpgp.Entity, err error) {
 		return
 	}
 
-	fmt.Print("Generating Entity and OpenPGP Key Pair... ")
-	entity, err = openpgp.NewEntity(name, comment, email, conf)
+	pass, err := AskQuestionNoEcho("Enter encryption passphrase : ")
+	if err != nil {
+		return
+	}
+	passRetype, err := AskQuestionNoEcho("Retype your passphrase : ")
```
Comment (mem) [inline pkg/sypgp/sypgp.go]: Can you please look at the comment I left in the other review?

Comment (WestleyK) [reply pkg/sypgp/sypgp.go]: :+1:

**Review by mem — APPROVED** [review]
