### PR TITLE
Lock ext3 image partitions and prevent them from concurrent writes

### LINKED ISSUE #4048: Overlay image corruption with multiple writable instances on same SIF
## Version of Singularity:

3.3.0-rc4

### Expected behavior

Some sort of diagnostic or safeguard around mounting images multiple times.

### Actual behavior

I put an ext3 overlay filesystem into a `.sif` file and started two writable instances with `shell` and `exec`. I installed some software as root in one while the other one was active, `dmesg` spews warnings about deleted inodes and the filesystem is pretty much busted.

I'm guessing that it might be technically safe if all mounts are read-only.

### Steps to reproduce behavior

Reproduction steps approximate, reconstructing from history.

I'm not sure if this is how one is supposed to make an persistent overlay image at all, as it's quite underdocumented but this approach got it appearing to work for single instances.

Build image:
```bash
singularity pull docker://fedora:30
truncate -s 150G data.ext3
mkfs.ext3 data.ext3
singularity sif add --datatype 4 --groupid 1 --partarch 2 --partfs 2 --parttype 4 fedora_30.sif data.ext3
```

Concurrently - launch two instance and install a bunch of software from repos in the superuser one while building software in the other one.
```bash
singularity shell -e -w fedora_30.sif
sudo singularity shell -e -w fedora_30.sif
```

`blkid` on the host sees two loop devices, both appearing to be the image:
```
/dev/loop2: TYPE="squashfs"
/dev/loop3: UUID="0c055153-8bd5-4896-a96d-395289e91883" TYPE="ext3"
/dev/loop4: TYPE="squashfs"
/dev/loop5: UUID="0c055153-8bd5-4896-a96d-395289e91883" TYPE="ext3"
```

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Lock EXT3 image partitions to prevent from concurrent writes

**This fixes or addresses the following GitHub issues:**

- Fixes #4048 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/runtime/engines/singularity/prepare_linux.go [hunk 1]
```diff
@@ -911,6 +910,23 @@ func (e *EngineOperations) loadImages(starterConfig *starter.Config) error {
 				return err
 			}
 		}
+		// lock overlay ext3 partitions if any to prevent concurrent writes
+		if len(img.Partitions) > 1 {
+			for _, part := range img.Partitions[1:] {
+				if part.Type == image.EXT3 {
+					if err := img.LockSection(part); err != nil {
+						return fmt.Errorf("error while loading ext3 overlay partition from %s: %s", img.Path, err)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/prepare_linux.go]: "while locking", no?

File: internal/pkg/runtime/engines/singularity/prepare_linux.go [hunk 2]
```diff
@@ -911,6 +910,23 @@ func (e *EngineOperations) loadImages(starterConfig *starter.Config) error {
...
+					}
+				}
+			}
+		}
+	} else if img.Type == image.EXT3 {
+		// lock ext3 system partition if we opened it for writing
+		// or check if the image is not already opened for writing
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/prepare_linux.go]: not sure where the "or" part of this comment is...

Is `LockSection` doing something more than just locking?

File: internal/pkg/runtime/engines/singularity/prepare_linux.go [hunk 3]
```diff
@@ -911,6 +910,23 @@ func (e *EngineOperations) loadImages(starterConfig *starter.Config) error {
...
+		// by another process in case of read-only use
+		if err := img.LockSection(img.Partitions[0]); err != nil {
+			return fmt.Errorf("error while loading ext3 system partition from %s: %s", img.Path, err)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/prepare_linux.go]: "while locking"?

File: internal/pkg/runtime/engines/singularity/prepare_linux.go [hunk 4]
```diff
@@ -934,6 +950,12 @@ func (e *EngineOperations) loadImages(starterConfig *starter.Config) error {
 		if err != nil {
 			return fmt.Errorf("failed to open overlay image %s: %s", splitted[0], err)
 		}
+		// lock overlay ext3 images to prevent concurrent writes
+		if img.Type == image.EXT3 && img.HasRootFs() {
+			if err := img.LockSection(img.Partitions[0]); err != nil {
+				return fmt.Errorf("error while loading ext3 overlay image %s: %s", img.Path, err)
```
Comment (mem) [inline internal/pkg/runtime/engines/singularity/prepare_linux.go]: "while locking"?

File: pkg/image/image.go [hunk 5]
```diff
@@ -161,6 +162,39 @@ func (i *Image) HasRootFs() bool {
 	return false
 }
 
+// LockSection put a file byte-range lock on a section to prevent
```
Comment (mem) [inline pkg/image/image.go]: "LockSection puts ..."

File: pkg/image/image.go [hunk 6]
```diff
@@ -161,6 +162,39 @@ func (i *Image) HasRootFs() bool {
...
+	ltype := lock.ReadLock
+	if i.Writable {
+		ltype = lock.WriteLock
+	}
+	if err := br.Acquire(ltype); err == lock.ErrByteRangeAcquired {
+		if i.Writable {
+			return fmt.Errorf("can't open %s for writing, currently in use by another process", i.Path)
+		}
+		return fmt.Errorf("can't open %s for reading, currently in use for writing by another process", i.Path)
+	} else if err != nil {
```
Comment (mem) [inline pkg/image/image.go]: Not sure what to do with this...

The function is supposed to acquire a lock, fails to do so and no error is reported. I understand the need to support filesystems where locking is not available, but I don't think dropping all errors is the right way to go about it.

Ideally it should not be necessary to dig into the implementation details to understand the logic. I suspect this handling of errors is tightly related to implementation details.

File: pkg/image/image.go [hunk 7]
```diff
@@ -161,6 +162,39 @@ func (i *Image) HasRootFs() bool {
...
+	fd := int(i.Fd)
+	start := int64(section.Offset)
+	size := int64(section.Size)
+
+	br := lock.NewByteRange(fd, start, size)
+	ltype := lock.ReadLock
+	if i.Writable {
+		ltype = lock.WriteLock
+	}
+	if err := br.Acquire(ltype); err == lock.ErrByteRangeAcquired {
```
Comment (mem) [inline pkg/image/image.go]: as a general comment, looking at the implementation of these functions (Acquire, etc), I think the client code would be easier to read if you had a different API. Instead of having a parameter specifying the type of lock, something more like:

```
func (ByteRange) RLock()
func (ByteRange) Lock()
func (ByteRange) Unlock()
```

If you look at the sync package, you'll see that read vs read-write is handled at the type level: you create a read lock, you create a rw lock.

File: pkg/util/fs/lock/lock.go [hunk 8]
```diff
@@ -1,34 +1,105 @@
...
-	if err := syscall.Flock(fd, syscall.LOCK_UN); err != nil {
+	defer unix.Close(fd)
+	if err := unix.Flock(fd, unix.LOCK_UN); err != nil {
+		return err
+	}
+	return nil
+}
+
+// Type defines the type of a lock
+type Type uint8
```
Comment (mem) [inline pkg/util/fs/lock/lock.go]: this type and the corresponding constants are mimicking the underlying flock API. I don't think these are necessary (or at least, I don't think it's necessary to export these; obviously it's necessary with the current implementation).

File: pkg/util/fs/lock/lock.go [hunk 9]
```diff
@@ -1,34 +1,105 @@
...
+	// UnLock corresponds to a released lock
+	UnLock
+)
+
+// ErrByteRangeAcquired correponds to the error returned
+// when a file byte-range is already acquired
+var ErrByteRangeAcquired = errors.New("file byte-range lock is already acquired")
+
+// ByteRange defines a file byte-range lock.
+type ByteRange struct {
```
Comment (mem) [inline pkg/util/fs/lock/lock.go:48]: `ByteRangeLock` maybe? I don't really like it because it stutters with the package name (lock.ByteRangeLock). The standard library side-stepped this problem by calling the somewhat equivalent package `sync`, so it results in `sync.Mutex`, etc.

Within the package the problem I see with `ByteRange` is that it sounds like it's something else (something representing a byte range, not a lock on a byte range).

File: pkg/image/image.go (hunk 6 above)
Comment (cclerget) [reply pkg/image/image.go]: Will just ignore `ENOLCK` error and will see if it block users

File: pkg/image/image.go (hunk 7 above)
Comment (cclerget) [reply pkg/image/image.go]: will do, thanks !

File: pkg/util/fs/lock/lock.go (hunk 9 above)
Comment (cclerget) [reply pkg/util/fs/lock/lock.go:48]: Well we are in package `lock` and get `lock.ByteRange`, that's explicit enough at least for me and there is many package with this kind of "shortcuted" name

File: pkg/util/fs/lock/lock.go [hunk 10]
```diff
@@ -1,34 +1,85 @@
...
-	defer syscall.Close(fd)
-	if err := syscall.Flock(fd, syscall.LOCK_UN); err != nil {
+	defer unix.Close(fd)
+	if err := unix.Flock(fd, unix.LOCK_UN); err != nil {
 		return err
 	}
 	return nil
 }
+
+// ErrByteRangeAcquired correponds to the error returned
```
Comment (sashayakovtseva) [inline pkg/util/fs/lock/lock.go]:
```suggestion
// ErrByteRangeAcquired corresponds to the error returned
```

File: pkg/util/fs/lock/lock.go [hunk 11]
```diff
@@ -1,34 +1,85 @@
...
+// when a file byte-range is already acquired
```
Comment (sashayakovtseva) [inline pkg/util/fs/lock/lock.go]:
```suggestion
// when a file byte-range is already acquired.
```

**Review by sashayakovtseva — CHANGES_REQUESTED** [review]
lgtm
as discussed offline a couple things to address:
- ErrLockNotSupported
- lock partition[0] of SIF if it is ext3 (even though it is a rare case)
- F_SETLK64 is equal to F_SETLK in linux, so probably no need to separate const and const_linux

**Review by sashayakovtseva — APPROVED** [review]
lgtm
