### PR TITLE
Show correct web URL for detached builds

### LINKED ISSUE #5782: Detached remote build shows invalid URL
### Version of Singularity:

3.7.0

### Expected behavior

1. `singularity pull` command should not include obsolete `--library` argument (though the library host is correctly represented there)
2. browser URL does not reflect the currently configured remote

### Actual behavior

```sh
$ singularity build --remote --detached ubuntu-test-detach.sif ubuntu.def
Build submitted! Once it is complete, the image can be retrieved by running:
        singularity pull --library https://library.mydomain.com library://myuser/remote-builds/rb-5fe5b3609d4b6974c4fa0c99:latest

Alternatively, you can access it from a browser at:
        https://cloud.sylabs.io/library/myuser/remote-builds/rb-5fe5b3609d4b6974c4fa0c99:latest
INFO:    Build complete: ubuntu-test-detach.sif
```

### Steps to reproduce this behavior

Configure a non-default remote and run the following command:

```sh
singularity build --remote --detached ...
```

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

Replace the hard coded cloud URI link for detached builds to a URI
derived from the current remote.

If the user specifies custom service URIs (--library/--cloud) there is
no easy and reliable method to get the corresponing web frontend URI, so
do not show the web link.

### This fixes or addresses the following GitHub issues:

 - Fixes: #5782

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: internal/pkg/build/remotebuilder/remotebuilder.go [hunk 1]
```diff
@@ -107,7 +106,9 @@ func (rb *RemoteBuilder) Build(ctx context.Context) (err error) {
 	if rb.IsDetached {
 		fmt.Printf("Build submitted! Once it is complete, the image can be retrieved by running:\n")
 		fmt.Printf("\tsingularity pull --library %s library://%s\n\n", bi.LibraryURL, libraryRefRaw)
```
Comment (EmmEff) [inline internal/pkg/build/remotebuilder/remotebuilder.go:108]:
```suggestion
		fmt.Printf("\tsingularity pull library://%s\n\n", bi.LibraryURL, libraryRefRaw)
```

Shouldn't the use of the `--library` argument be deprecated since the advent of `singularity remote`?

**Review by EmmEff — CHANGES_REQUESTED** [review]
Question about the need for the `--library` argument

File: internal/pkg/build/remotebuilder/remotebuilder.go (hunk 1 above)
Comment (dtrudg) [reply internal/pkg/build/remotebuilder/remotebuilder.go:108]: You can still specify a custom `--library` flag, and this far down in the code we can't tell whether the library URI came from the remote config, or a custom flag.

We can get rid of it, which is neater and correct for 99.9% of cases where it should be the remote defined library.... or we can leave it in case.

**Review by EmmEff — APPROVED** [review]
