### PR TITLE
Do remote build when builder flag is set

### LINKED ISSUE #2985: build flag builder should default flag remote
## Version of Singularity:

3.1

### Expected behavior

when the `--builder` flag is used, we should use the `--remote` under the hood, to avoid 
` --remote --builder <url>` 

### Actual behavior

```
-bash-3.2$ singularity build --builder https://cloud.staging.sylabs.io/library builder3_apline-3.6.sif docker://alpine:3.6
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:5a3ea8efae5d0abb93d2a04be0a4870087042b8ecab8001f613cdc2a9440616a
Copying config sha256:8186e170383f46da698e9a1dd3e1384e2c86a75c2ebdef62843a23cb8899955b
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: builder3_apline-3.6.sif
```
a local build

### Steps to reproduce behavior

```
singularity build --builder https://cloud.staging.sylabs.io/library builder3_apline-3.6.sif docker://alpine:3.6
```

### PR DESCRIPTION
**Pull request by ikaneshiro**
**Description of the Pull Request (PR):**

Title

**This fixes or addresses the following GitHub issues:**

- Fixes #2985 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
Keep it simple, I like it

File: cmd/internal/cli/build_darwin.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ func run(cmd *cobra.Command, args []string) {
 		os.Exit(1)
 	}
 
-	if !remote {
+	if !remote && !cmd.Flags().Lookup("builder").Changed {
```
Comment (mem) [inline cmd/internal/cli/build_darwin.go]: I see what you are doing here: either the use set remote explicitly or they specified builder and therefore set remote implicitly.

In order to reduce maintaining costs and avoid having to check the two things continuously, I think it might be easier to check for builder Changed once, and *set* remote if that's the case. Maybe take preRun out of build_linux.go and build_darwin.go (since it's the same in both) and move it to build.go, and perform this check there:

```
func preRun(...) {
    ...
    if cmd.Flags().Lookup("builder").Changed {
        cmd.Flags().Lookup("remote").Value.Set("true")
    }
}
```

in this way, in the rest of the code you can continue checking only remote, as it is now and you don't have to introduce the explicit handling of the dependency everywhere.

It's also a good idea to update the documentation for the builder flag and add something like "(implies --remote)".

File: cmd/internal/cli/build_linux.go [hunk 2]
```diff
@@ -36,7 +36,7 @@ func run(cmd *cobra.Command, args []string) {
 		os.Exit(1)
 	}
 
-	if remote {
+	if remote || cmd.Flags().Lookup("builder").Changed {
```
Comment (mem) [inline cmd/internal/cli/build_linux.go]: I can see that this is the change the issue is asking for: setting builder implies --remote.

**Review by mem — CHANGES_REQUESTED** [review]

**Review by mem — APPROVED** [review]
Thanks!
