### PR TITLE
Fix --contain issues. Fix bind destination creation

### LINKED ISSUE #3949: "can't remount" under "cleaned up" /home and /tmp in -c mode
## Version of Singularity:
<details><summary>
Initially ran into a failure with 2.6.1 where failing behavior varies (might be related to #3530)
</summary>

```shell
/tmp/d > mkdir -p {~,/tmp}/d; touch {~,/tmp}/d/file;  for d in /etc /etc/apt ~ ~/d /tmp /tmp/d; do echo $d ; builtin cd $d; singularity exec -c -B $d /tmp/out1/containers/images/bids/bids-mriqc--0.15.0.sing ls -l $d >/dev/null; echo "exited with $?"; done                        
/etc
exited with 0
/etc/apt
exited with 0
/home/yoh
WARNING: Not mounting requested bind point (already mounted in container): /home/yoh
exited with 0
/home/yoh/d
exited with 0
/tmp
exited with 0
/tmp/d
ls: cannot access '/tmp/d': No such file or directory
exited with 2
```
</details>

and then replicated with 3.1.1 (debian system both times)

### Expected behavior

leading subdirectories will be provided within cleaned up environment, similar to how it is done to any other directory (overlays?)

### Actual behavior

Just fails to bind mount a directory under /home or /tmp whenever running with `-c` flag:
```shell
/tmp/d > mkdir -p {~,/tmp}/d; touch {~,/tmp}/d/file; for d in /etc /etc/apt /data/famface/ ~ ~/d /tmp /tmp/d; do echo $d ; builtin cd $d; singularity exec -c -B $d /tmp/out1/containers/images/bids/bids-mriqc--0.15.0.sing ls -l $d | head -n 1; done
/etc
total 2868
/etc/apt
total 72
/data/famface/
total 16
/home/yoh
total 1317320
/home/yoh/d
FATAL:   container creation failed: mount ->/home/yoh/d error: can't remount /home/yoh/d: no such file or directory
/tmp
total 172088
/tmp/d
FATAL:   container creation failed: mount ->/tmp/d error: can't remount /tmp/d: no such file or directory
```
in above - /data/famface is not in the container, everything works out just fine.  ~/d and /tmp/d -- fail to bind mount

Interestingly, if I provide `-W` path where I will have those /tmp/d and /home/yoh/d precreated -- seems to "work" for /tmp but not for home:
```shell
/tmp/d > mkdir -p {~,/tmp}/d; touch {~,/tmp}/d/file; for d in ~/d /tmp/d; do echo $d ; builtin cd $d; singularity exec -c -W /home/yoh/.tmp/singtmp.HUk5El -B $d /tmp/out1/containers/images/bids/bids-mriqc--0.15.0.sing ls -l $d | head -n 1; done                                               
/home/yoh/d
FATAL:   container creation failed: mount ->/home/yoh/d error: can't remount /home/yoh/d: no such file or directory
/tmp/d
total 0
```
but you can mention that actually `/tmp/d` lists no files (total 0) so it doesn't bind mount /tmp/d from outside which has a `file` in it

PS removed `E: could not determine git repository root` in the above dumps which were coming from my prompt setup and shouldn't be relevant here

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

- Fix --contain issue with both overlay/underlay and writable flags.
- Introduces overrideDir in session manager to simulate a bind mount during directories/files/symlinks creation, it should address many issues related to binding giving error like "no such file directory" during mount call.
- Nested binds are already allowed, with `overrideDir` destination directories will be automatically created.
- Fix RPC mount error type to now return `syscall.Errno` type

**This fixes or addresses the following GitHub issues:**

- Fixes #3949

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by gvallee — APPROVED** [review]
LGTM

File: internal/pkg/util/fs/layout/manager.go [hunk 1]
```diff
@@ -152,6 +159,20 @@ func (m *Manager) AddSymlink(path string, target string) error {
...
+func (m *Manager) overrideDir(path string, realpath string) {
+	m.ovDirs[path] = realpath
+}
+
+// GetOverridePath returns the real path for the session path
+func (m *Manager) GetOverridePath(path string) (string, error) {
+	if p, ok := m.ovDirs[path]; !ok {
+		return p, nil
+	}
+	return "", fmt.Errorf("no override directory %s", path)
```
Comment (WestleyK) [inline internal/pkg/util/fs/layout/manager.go:173]:
```suggestion
	return "", fmt.Errorf("no override directory: %s", path)
```

~All~ **most** of the error returns have the `:` right before a variable, for consistency maybe better to add it

File: internal/pkg/util/fs/layout/session_linux.go [hunk 2]
```diff
@@ -75,12 +78,74 @@ func (s *Session) FinalPath() string {
...
+			flags, _ := mount.ConvertOptions(point.Options)
+
+			// ignore anything which is not a bind mount point
+			if flags&syscall.MS_BIND == 0 {
+				continue
+			}
+
+			// check if the bind source exists
+			if err := syscall.Stat(point.Source, st); err != nil {
+				sylog.Warningf("skipping mount of %s: %s", point.Source, err)
```
Comment (WestleyK) [inline internal/pkg/util/fs/layout/session_linux.go]: Same here...

```suggestion
				sylog.Warningf("skipping mount of: %s: %s", point.Source, err)
```

**Review by WestleyK — APPROVED** [review]
Looks good to me, just two optional suggestions :+1:

File: internal/pkg/util/fs/layout/manager.go (hunk 1 above)
Comment (mem) [reply internal/pkg/util/fs/layout/manager.go:173]: I don't think the result would be understandable in this case: `no override directory: /foo/bar`, it's better without the colon.

Comment (WestleyK) [reply internal/pkg/util/fs/layout/manager.go:173]: @mem, I agree, it does sound a bit better in this case.

**Review by WestleyK — APPROVED** [review]
Looks good to me! Thanks :+1:
