### PR TITLE
Show unsquashfs command failure output

### LINKED ISSUE #3996: singularity inspect returns "FATAL:   exit status 255: "
## Version of Singularity:

singularity version 3.2.1-1.el7a

### Expected behavior

Output of container metadata or meaningfull error message

### Actual behavior

Singularity prints `FATAL:   exit status 255: `, nothing more

### Steps to reproduce behavior

Run `singularity inspect <myimage.sif>` on a container.

Happens only for some containers build by users on our HPC cluster. On the same image I get `FATAL:   container creation failed: mount /proc/self/fd/12->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/12: failed to mount squashfs filesystem: invalid argument` so it might be a faulty image. But the non-existing inspect output makes it impossible to help them

### LINKED ISSUE #4012: Give unsquashfs failure output
## Version of Singularity:

>= 3.2

### Expected behavior

Give error output of `unsquashfs` command

### Actual behavior

```
$ singularity -d build -s /tmp/sandbox ~/tmp.sif 
DEBUG   [U=1000,P=23130]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=23130]   Init()                        Check for image format sif
DEBUG   [U=1000,P=23130]   NewBundle()                   Created temporary directory for bundle /tmp/sbuild-543796861
INFO    [U=1000,P=23130]   Full()                        Starting build...
DEBUG   [U=1000,P=23130]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=23130]   Init()                        Check for image format sif
DEBUG   [U=1000,P=23130]   GetLocalPacker()              Packing from SIF
DEBUG   [U=1000,P=23130]   Init()                        Entering image format intializer
DEBUG   [U=1000,P=23130]   Init()                        Check for image format sif
ERROR   [U=1000,P=23130]   Pack()                        unpackSIF Failed: root filesystem extraction failed: extract command failed: exit status 1
DEBUG   [U=1000,P=23130]   cleanUp()                     Build bundle(s) cleaned: [/tmp/sbuild-543796861]
FATAL   [U=1000,P=23130]   run()                         While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: exit status 1
```

### Steps to reproduce behavior

corrupted squashfs filesystem and run `singularity -d build -s /tmp/sandbox ~/tmp.sif`

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Actually during extraction only the exit status is reported which doesn't give any useful hints to end user, this PR now show combined output when the extraction failed.

**This fixes or addresses the following GitHub issues:**

- Fixes #4012
- Fixes #3996

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

File: pkg/image/unpacker/squashfs.go [hunk 1]
```diff
@@ -64,8 +64,8 @@ func (s *Squashfs) extract(files []string, reader io.Reader, dest string) error
 	if stdin {
 		cmd.Stdin = reader
 	}
-	if err := cmd.Run(); err != nil {
-		return fmt.Errorf("extract command failed: %s", err)
+	if o, err := cmd.CombinedOutput(); err != nil {
+		return fmt.Errorf("extract command failed: %s\nCommand output: %s", err, string(o))
```
Comment (WestleyK) [inline pkg/image/unpacker/squashfs.go]: Is there a way to do this without using a newline? Maybe like:

```suggestion
		return fmt.Errorf("extract command failed: %s: %s", string(o), err)
```

**Review by WestleyK — APPROVED** [review]
Looks good to me! Thanks :+1:
